### ISSUE TITLE
GUI: random walk with real-time updates

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#10]
visualization of trust buildup for virtual identities.
Key issues: rendering, smoothing and node placement as nodes get added and pruned.

Depends: #20 

initial prototype:
![web-of-trust-in-Tribler-GUI](https://f.cloud.github.com/assets/325224/232079/405969b4-8723-11e2-9812-29685446631d.png)

**Comment by synctext** [comment]
BarterCast III crawl from [2018](https://github.com/Tribler/tribler/issues/3508#issuecomment-404537909) (now named Trustchain)

![c1d7634c1869dc6d025767399eedeb30](https://user-images.githubusercontent.com/1707075/42640533-ccf22b26-85f2-11e8-8f8c-3db8302cc939.png)

**Comment by devos50** [comment]
Real-time render of TrustChain interaction graph: http://explorer.tribler.org/visualization

**Comment by synctext** [comment]
Examples:
![image](https://user-images.githubusercontent.com/325224/52204797-6dcdcf80-2875-11e9-93ea-3a2d212f8a28.png)

**Comment by cuileri** [comment]
**Initial stuff**
I've started with exploring Alexander's code, and decided to code from scratch because:
- His graph was considering only 2 hops. I think knowing about distant agents with high trustability is important.
- Given a directed graph where each edge shows the direction of download-upload traffic, his graph was considering only the outgoing neighbors as 'neighbors'. I think the agents who download from me are also my neighbor.
- To animate the walk, we need more control over the walk, for drawing the graph frame by frame.

**Current state of the code**
- Works with randomly generated directed graph
- Firstly, performs a bfs traversal on the undirected graph, to see neighborhood. Draws the neighborhood as a tree. I used [this](https://stackoverflow.com/a/29597209) code for laying out the nodes.
- Performs and animates random walks. Size of the nodes represent the number of times the node is visited.
- For graphics, I used [matplotlib](https://matplotlib.org/).

**Issues**
- Fake and static data
- Non-modular code

**Next sprint** (upon discussed with Johan)
- Connect to the live trustchain network
- Starting from no-knowledge, each node discovers 5 nodes per second continuously, which turns out to be 5-25 Trustchain data per second.
- Plot its k-hop neighborhood in real time. The neighborhood expands or shrinks over time.
- Perform 100-1000 random walk on the snapshot of the network and determine Trust Level per node. (Possibly with real time animation)
- No DB storage, just live and standalone!
- Automated decrease of Trust Levels over time, if a node is not visited that frequently.

**Comment by alexander-stannat** [comment]
The GUI looks very nice!

It might be worth having a discussion about the second point you mentioned. If one wants to take into account the nodes that have downloaded from the seed node as well as the nodes that have uploaded to it then a good way of doing this is by considering bidirectional edges, instead of our current unidirectional ones. This would enable us to evaluate peers, not just based on their up-to download ratio, but also on absolute values. 

Also, we should think about somehow combining the BFS with the actual random walks to reduce complexity. Otherwise random walks might not be really necessary any more (as was discussed this week).

**Comment by cuileri** [comment]
I totally agree with Alexander that we need a different implementation of edge weights (or directions). I discussed it also with Johan, giving the following extreme case as an example: Consider two nodes which download and upload a huge amount of data from/to each other. At the end, the weight of the edge between them will not reflect the amount of traffic. Moreover, if they upload/download the same amount of data from each other, the weight of the edge will become zero.

I think we will come up with it a clever strategy over time.

**Comment by cuileri** [comment]
**The current state of the [code](https://github.com/Tribler/real_time_random_walk):**

- I implemented a Transaction Discovery module. At this stage it either generates fake data or listens to the tribler crawler to feed Random Walk module.

- Current state of random walk module:

  - Before each batch of random walk, the node takes as an input a list of 3-tuples (from_node, to_node, edge_weight) and updates its own transaction graph (rooted at itself).

  - These new transactions update the existing graph proportionally, so that if no transaction is done on an existing edge, it is subject to be removed as the time goes by.

  - Edge weights show the amount of one-way traffic between nodes and are significant for the determination of the next step of a walk.

  - Having updated the graph w.r.t. new transactions, the node then performs random walks, and the procedure repeats.

  - Random walks determine the other nodes' importance observed by 'the node'. 

  - A node which was discovered through 'transaction discovery' but not visited frequently during random walks are subject to be removed from the graph in order to control the size of the graph.

- The code is now modular (Transaction Discovery, Local Vision, Random Walk, Graph Positioning)

- In addition to the random walks, the update of local vision of the node w.r.t. the discovered transactions is also animated now.

![anim](https://user-images.githubusercontent.com/22027137/53251013-efb65900-36bb-11e9-8d6f-ff01d4829a48.gif)



**Next sprint**
- I have already started focusing more on research than on coding.
- Research for finding/offering a function to calculate trust values of nodes (may be the title of a new issue)
- Some interesting studies that will help us: 
  - Inferring binary trust relationships in Web-based social networks. ([link](http://portal.acm.org/citation.cfm?doid=1183463.1183470))
  - Personalized reputation management in P2P networks. ([link](http://www.l3s.de/~chirita/publications/chirita04personalized.pdf))
  - A survey on Trust modeling ([link](http://dl.acm.org/citation.cfm?doid=2830539.2815595)).
  - Using Centrality Measures to Predict Helpfulness-Based Reputation in Trust Networks ([link](http://dl.acm.org/citation.cfm?doid=3036639.2981545))

- We agreed with Bulat that we will use 16GB of tribler transaction history to make tests for our algorithms. He will prepare the interface which will feed my code with real data. We decided to spare a small portion of the data for determining the initial "the most trustable peers" list.

**Comment by synctext** [comment]
Easy bootstrap and visualisation idea to take "mathematics-of-trust into production usage. Show the user and include a first version of our trust formula. Possible goal for end of March: genesis trust swarm.
- crawl Trustchain network
- extract 25 MByte of most trustworthy, oldest, and central nodes (1 metric)
- Create Bittorrent swarm with 25 x 1 MByte .mblob records (**Genesis Trust Swarm**)
- Each Tribler client hard-coded downloads this data upon install
- With each completed .mblob we both have a trustchain record of the agent that helped us and Trustchain data.
- Possible: Ask these agents to produce records linking them directly to the genesis trust swarm. Thus creating a single connected component.
- real-time animation for exactly 20 second while downloading in the genesis trust swarm.
- show random walk animation to give them a feeling that this is not just another Bittorrent client. It's a new trustworthy protocol and leaderless ecosystem.

**Comment by cuileri** [comment]
Detected a problem with both Alexander's and my implementation of random walks. Presented [here](https://github.com/Tribler/tribler/issues/2805#issuecomment-470940011).

**Comment by synctext** [comment]
New Attacker model: majority is malicious, however majority of evil nodes are overseas.

Brainstorm, combine [latency-restricted communication](https://github.com/Tribler/tribler/issues/2541) #2541 with  the 25MByte boostrap concept ([oldest mention](https://github.com/Tribler/tribler/issues/3690#issuecomment-465652950)):
- new approach all agents self-organise into latency-based **genesis trust swarms**.
- Each **genesis trust swarms** independently determines the trust consensus of 25MByte.
- Discovery of various genesis trust swarms, at different network distance
- join various genesis swarms and determine their peers
- determine in which community the closest by peers reside
- bootstrap from this genesis trust swarm
- at regular intervals the contents of the genesis trust swarm is updated
- only members within acceptable short network latency are eligible voting members

**Comment by synctext** [comment]
PR #4488 ![image](https://user-images.githubusercontent.com/325224/58094896-02b0ca80-7bd2-11e9-8349-80dfef97143b.png)

**Comment by synctext** [comment]
Epic progress tracking issue, largely historic, moving to #31.
- (CLOSED) trustworthy gossip: [integrating gossip mechanisms with trust calculations #3690](https://github.com/Tribler/tribler/issues/3690) has lots of historical and insightful comments (such as ```Trustworthy_Gossip(suppress,delete,store,collect,spread)```)
- (OPEN) [strongest possible reputation system #31](https://github.com/Tribler/tribler/issues/31) The other historic issue since 2013.
