### ISSUE TITLE
option to close to tray

### ISSUE THREAD

**Issue by winkbrace** [Tribler/tribler#1054]
As a user I expect Tribler to close to tray (just like uTorrent). I would like to have this option available in the GUI. Currently it is only possible to minimize to tray, which feels unnatural to me (after all these years). I don't ever want to close the application of course. I just want it to work in the background.

**Comment by whirm** [comment]
@LipuFei could you check this one?

**Comment by whirm** [comment]
And assign it to 6.5 if it's feasible to do it for then.

**Comment by adamjimenez** [comment]
minimise to tray makes more sense than close to tray. need to break those old habits.

**Comment by tukkek** [comment]
Just want to say I strongly second this: there is no way most users are going to let Tribler stay idle on the background unless there is a tray icon they can minimize to and still be able to access it easily to monitor whatever downloads they have, etc. The alternative would be to allow the app to close its window but stay running in the backgorund (daemon/service-like) but I think this is verging on "malware' practices - the user should always be able to easily and immediately tell if the app is running, not to mention that requiring the user to run the command again (or from a launcher icon) is awkward and, again, gives off the idea that the program is only "starting" at that point. Trays are the established design around this.

As a Linux user, I have many more options than most users in ways to "hide" an open window: I can use virtual desktops, virtual activities or even per-application window manager settings - all of which come with KDE by default. Even then, I already have uses for all these things and I won't be running Tribler habitually until it offers a tray icon as I don't want to get into it if it means messing with my current workflows. I love the idea and concepts behind the project, but I can wait.

> minimise to tray makes more sense

No it doesn't. Minimize always has been and always will be minimizing *to the task bar*. Tray applications shouldn't close for good when you hit close, which is why 100% of all major applications use close as "close to tray". 

If you use minimize to "close to tray", you block the user's ability to minimize to the task bar, which is a legitimate use case in any operating system, while closing to tray still allows the user to close the application for good, either by showing a dialog, menu option, tray context menu or user preferences options. On the other hand, offering a minimize action in any such a way would be ridiculous. The first rule of user interface design is to follow established patterns and Tribler absolutely shouldn't be looking to be the only application that works differently from standard UI, especially considering the first thing people will think of are other torrent applications (as @winkbrace aptly mentions), which work as I described.

**Comment by SeinopSys** [comment]
> there is no way most users are going to let Tribler stay idle on the background unless there is a tray icon they can minimize to and still be able to access it easily

I came here to say this. Since @devos50 closed the other issue which was in a milestone looks like this was left unattended to but IMO it's one of the most critical points for software you are meant to be running constantly.
