### ISSUE TITLE
Automatic updater

### ISSUE THREAD

**Issue by Lehmax** [Tribler/tribler#1218]
Tribler will get many updates in the near future, but it still has no automatic updater (or at least an update-checker) that assures users are running the latest version.

**Comment by whirm** [comment]
We have some rusty code sitting there but it's not in a good shape:

 * It uses http (instead of https)
 * It doesn't do any kind of cryptographic check.

An unattended update system would be great, like the one Firefox or Chrome use.

We would gladly accept contributions on this. Otherwise we will have to do it ourselves rather sooner than later.

**Comment by YakovL** [comment]
@whirm May be for update-checking (not updating itself) http is good enough?

Also, as you're looking for volunteers, may be it's be better to share the rusty code as starting somewhere (not in vacuum) is more engaging?

**Comment by xur86x** [comment]
Yeah, I'd really like to try this one. I'm not sure if I could do it, but I'd need to try to know.

**Comment by whirm** [comment]
@xur86x: This is the module that takes care of it:
https://github.com/Tribler/tribler/blob/devel/Tribler/Main/Utility/version_check.py
It should be changed to use https and check the latest release published on github for starters.

Also, the next release will come with a pgp signed sha1sum file, so a validity check with a hardcoded public key would also be great to have in the future.

Thanks!
