### ISSUE TITLE
Adding a newly created torrent to Tribler does not work, will result in 'downloading 0.0%'

### ISSUE THREAD

**Issue by rjruigrok** [Tribler/tribler#1486]
Creating a new torrent is possible in Channel > My Channel. But after creating the torrent, and adding the .torrent to the Downloads list, it will get download-status "Downloading 0.0%". 
I was expecting to see state "Seeding 100.0%". I already put the file to be seeded to the directory Tribler Downloads, but no matter how: it always stays on downloading state. 

Is this a bug, or am I just doing it the wrong way?

**Comment by rjruigrok** [comment]
Found out that when I create the torrent manually with ctorrent on terminal, seeding works like a charm. So there's something going wrong in the torrent creation.

**Comment by synctext** [comment]
to clarify.. from My Channel, you goto torrent manager, you have a local file, create a .torrent, gets added to your channel OK, gets shown OK in downloads, and then Tribler should start to seed it...

**Comment by LipuFei** [comment]
@rjruigrok I tried the steps. I can see the download but it's always building circuits.

**Comment by rjruigrok** [comment]
That's correct. But after circuits are built (you can speed this up finding
candidates by running the 'rjruigrok-hiddenservices-seeding' job in jenkins.

When the circuits are built, it should start seeding.

Op donderdag 18 juni 2015 heeft Lipu Fei <notifications@github.com> het
volgende geschreven:

**Comment by LipuFei** [comment]
@rjruigrok I just did a few tests using ubuntu-15.04-desktop-amd64.iso torrent:

1. Adding a download NOT through MyChannel: I first put the iso file into TriblerDownloads and then started the download. After the circuits were built, it checked the file and started seeding.
2. Adding a download NOT through MyChannel: I first started the download. After the circuits were built, it was showing "Downloading 0.0%" because I didn't put the complete file there. Then I shutdown Tribler, put the file into TriblerDownloads, and started Tribler again. After the circuits were built, It still showed "Downloading 0.0%", and it didn't check the file I put there. But if I do a "force recheck", it will work.

So far I haven't dug deeper, but I guess the download logic might not be correct: it probably doesn't check if a file has been manually changed externally or not.

**Comment by LipuFei** [comment]
@rjruigrok I think the result will be the same if I add a download through MyChannel.

**Comment by rjruigrok** [comment]
@LipuFei It works fine for all torrents, but to clarify where it goes wrong: for torrents created within Tribler itself (there is a button in mychannel to generate a torrent file by adding some files to it, specify a name, and it's afterwards saved somewhere on your disk. After creating this - let's call it tribler-generated' torrent, it will be 'downloading 0.0%' even when the file contained in the torrent is already in TriblerDownloads.

**Comment by LipuFei** [comment]
@rjruigrok I loaded the created torrent file with transmission and it showed 0.0% even if I rechecked the the local file. So the torrent file that Tribler creates may be incorrect.

**Comment by LipuFei** [comment]
@rjruigrok #1491 will fix the torrent creation problem.

**Comment by whirm** [comment]
@LipuFei I think we should have a test for this.

**Comment by LipuFei** [comment]
@whirm I will have a look. The create torrent thing is coupled with the GUI, so it might not be easy to separate them.

**Comment by LipuFei** [comment]
@rjruigrok #1491 has been merged.

**Comment by LipuFei** [comment]
@rjruigrok Shall we close this one?

**Comment by rjruigrok** [comment]
Yep. :-) works perfectly.

Op woensdag 1 juli 2015 heeft Lipu Fei <notifications@github.com> het
volgende geschreven:
