### ISSUE TITLE
test_anon_download_exitnode_changeofmind failing

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1629]
http://jenkins.tribler.org//job/GH_Tribler_pull-request-tester_devel/4907/testReport/junit/Tribler.Test.test_tunnel_community_negative/TestTunnelCommunityNegative/test_anon_download_exitnode_changeofmind/

**Comment by rjruigrok** [comment]
The idea behind this test, is that it should never reach 100% download progress because halfway it disables the exit node functionality. This can be checked by looking for messages like `Dropping data packets, refusing to be an exit node for data`. 

There are a lot of them, and while some exit nodes look like they block data, it looks like there are exitnodes around that should not be there in the test... Are we sure that this test is run isolated? Looks like it happens incidentally?

**Comment by whirm** [comment]
@rjruigrok nope, this was a normal test run.

**Comment by devos50** [comment]
This issue is not relevant anymore.
