### ISSUE TITLE
Crashes at start when resuming/checking many torrents [RC5]

### ISSUE THREAD

**Issue by colin1497** [Tribler/tribler#1682]
Somewhere above 60 torrents seeding, anonymously, where all torrents are already downloaded, but because tribler is updating to a new version (6.5 from 6.4) it is checking each torrent at startup, tribler crashes with no log file while "building circuits."

Since I eventually got through this, I don't currently have a setup in the state to reproduce this bug, so it may be a little tough to check fixes.

Lots of information provided in #1605, splitting this issue out for tracking purposes.

This may actually be considered to be two bugs?

1) The crash itself
2) The lack of a log file

**Comment by whirm** [comment]
If there's a segfault (as in the error doesn't happen in python space) it's expected that no log entries will be written. Not much to do about that except for installing a debugger so the process state can be inspected when it happens.

**Comment by whirm** [comment]
I've just tested a migration from 6.4.3 to 6.5RC5+ with 233 downloads (most of them in seeding state) and the upgrade went smoothly.

A bunch of bugs have been fixed since RC5, maybe you where hitting one of them?

I'll close this, but if somebody manages to get the same behavior with a >RC5 version, please reopen it.

@colin1497: I'll post RC6 shortly in case you are interested in further testing.
