### ISSUE TITLE
After downloading completed, it still shows falling "Download speed"

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1707]
Probably due to some averaging. This looks misleading.

**Comment by whirm** [comment]
Yeah, I agree it looks weird.

**Comment by vi** [comment]
Still an issue even with the new GUI.

**Comment by ichorid** [comment]
This is Libtorrent's fault, as some experiments with `client_test` show. Won't fix it in Tribler, at least in the foreseeable future.

**Comment by devos50** [comment]
This is also noticeable in the libtorrent validation experiments. We could fix it in the GUI by always displaying a download speed of 0 when the torrent is completed though.

If I remember correctly, Utorrent also shows the decay in download speed after the torrent has been finished.

**Comment by synctext** [comment]
Or it could be accurate (defending Libtorrent here).
Speculating that pieces are requested from multiple sources in end-game mode, when 99% done. The useless info or downloaded. or simple 10-second averaging window.

**Comment by ichorid** [comment]
Checked it out. It is about averaging. The thing still shows gradually falling speed even when removing network connectivity completely.
This should be addressed by Libtorrent, not us. Fetching and showing the status data directly from Libtorrent is precious to us because it gives us a clear insight into what happens there.
