### ISSUE TITLE
[enhancement] Command line

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#1711]
headless rtorrent like XMLRPC would make tribler usable when flexible scheduling and torrent management is required.

**Comment by 0vermind** [comment]
I don't get why this feature is still missing after years of project.

**Comment by whirm** [comment]
Well, we are severely understaffed and we have to chose our battles. 
The issue is that we still have some download code tangled with the GUI code that needs to get refactored so we can offer this feature.

It seems that a couple of master students will be working on this during this semester, so maybe we will get this feature in the not so distant future.

We would also love to have collaborators though :)

**Comment by devos50** [comment]
I am going to spend some time on it over the next weeks but as @whirm said, the core logic has to be separated from the GUI code first. Collaborators are indeed very welcome :+1:

**Comment by whirm** [comment]
@devos50  I'll assign that to you once you accept the team invitation.

Also, let's talk about how the command line iface should look before doing any serious work on this aspect ok?

**Comment by synctext** [comment]
It's now operational. REST api in devel.

**Comment by Dmole** [comment]
Thanks, is that available in (Pre-release) v6.6.0-exp1 or can you link to a build for testing?

**Comment by synctext** [comment]
https://jenkins.tribler.org/job/pers/job/Build-Tribler7_OSX/
Still very much under construction. Within a few weeks it should be stable and documented. But it's coming....
