### ISSUE TITLE
Feature request: portable version / save settings to local folder [Windows]

### ISSUE THREAD

**Issue by vatterspun** [Tribler/tribler#1761]
**Current behavior**: settings are written to the ".Tribler" folder in AppData

**Requested capability**: settings written to the local folder.

**Why?**  One additional layer of security/convenience is the ability to run the client via a USB drive or over cloud services.  Right now, if the program is run from anywhere but the same computer, you will have to re-enter the settings, which can become a chore.  This approach also simplifies backup/restore and synchronization between machines.

Notably this can make updating the client more complicated as you have to know to update some files and not others, so it is recommended as an optional setting or separate version.

**Comment by whirm** [comment]
Maybe a TRIBLER_HOME env. var could be added so that Tribler will use that instead of the default state dir path. On Linux this can already be done by calling Tribler like this: `HOME=/media/usb_drive/my_tribler_dir tribler`

We won't give a lot of priorty to this, but we will welcome a pull request for that.

Thanks for the report!

**Comment by ichorid** [comment]
Related to #3904

**Comment by vatterspun** [comment]
So did this get resolved?  I didn't see a clear bath to settings portability in the #3904 thread.  Thanks.

**Comment by devos50** [comment]
@vatterspun not yet, but I think #3904 covers this issue sufficiently well. We will try to prioritize this after the 7.5 release.
