### ISSUE TITLE
OSX and windows installers should show the same license file

### ISSUE THREAD

**Issue by whirm** [Tribler/tribler#1864]

**Comment by lfdversluis** [comment]
Just looked into this, I see this line in the mac builder script `eulagise --license $LIBRARYNAME/LICENSE.txt --target dist/$APPNAME.dmg` and this line in the windows builder script `type Tribler\LICENSE.txt Tribler\binary-LICENSE-postfix.txt > Tribler\binary-LICENSE.txt`

Looks like they target the same `LICENSE.txt`. The postfix differs though, because ffmpeg is added to it (from what I saw, didn't diff with a tool)

**Comment by whirm** [comment]
Nice!
