### ISSUE TITLE
Webseeds aren't working on Tribler. (Was: Are webseeds supported?)

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#2002]
Are webseeds supported?
https://en.wikipedia.org/wiki/BitTorrent#Web_seeding

**Comment by whirm** [comment]
We use rasterbar's libtorrent, so if the .torrent contains webseeds, it should work:
http://www.rasterbar.com/products/libtorrent/manual.html#http-seeding

**Comment by Dmole** [comment]
Well for whatever reason I can't get it to work on 6.5.0-rc7

echo "test" > test.txt
mktorrent -a udp://tracker.openbittorrent.com:80 -w http://some.domain.tld/ test.txt
adding the torrent to Tribler results in it never contacting the server (so said the server logs) and never getting past 0%.

**Comment by whirm** [comment]
We will have a look at it then :)

Thanks for the report! 

Also, 6.5 got released a while back, so you may want to upgrade.

**Comment by Dmole** [comment]
Thanks for updating the main OS X download to one that works! :)

**Comment by whirm** [comment]
@Dmole yeah, 6.4.X was too old to run on recent versions of OSX...

**Comment by devos50** [comment]
@Dmole it turns out that the web seeds URLs created with `mktorrent` were never imported in libtorrent since they were stripped out by our torrent validation method. I changed to logic slightly to support web seeds created with `mktorrent`. The upcoming 6.6 alpha should have PR #2079 integrated which contains the fix.

**Comment by Dmole** [comment]
Thanks, I'll test when it's avalabe.
