### ISSUE TITLE
"no channels matching de"

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2390]
https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2336/testReport/junit/Tribler.Test.test_remote_search/TestRemoteChannelSearch/test_channel_search/

https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2336/testReport/junit/Tribler.Test.test_remote_search/TestRemoteChannelSearch/test_channel_search_2/

**Comment by devos50** [comment]
@brussee that error is very rare, I only see it in around 1/50 runs. It is already a lot better than before (when we used a more specific search term). Anyway, this error will be gone after the wx GUI is removed (since the `test_channel_search` package will be removed as well) so I don't think it 's worth to spent a lot of time on this.

Also, we should move away from being dependent on other Dispersy users in the network, like in the tests you linked.

**Comment by brussee** [comment]
Another case: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/2525/testReport/junit/Tribler.Test.test_remote_search/TestRemoteChannelSearch/test_channel_search/
