### ISSUE TITLE
6.6.0-exp1 colums gone

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#2521]
When clicking a column witin the download page, to resize that column, it disapeares and it is impossiblee to let it reappear again, even when you try to enlarge the column.
Within torrent details, ratio and other column data is not showing, so please show all colum's also within Torrent details,

**Comment by whirm** [comment]
Thanks for the report!

As this is a report on the old gui it won't be fixed. Instead it should be used as a reminder to check that the new gui behaves as expected.

**Comment by Nubro01** [comment]
Also the top search sle is loosing its focus and you can only search through the home screen.
Unable to get a cursor working within the top lefl search sle (Single Line Edit)

**Comment by lfdversluis** [comment]
@Nubro01 To get a bit more in-depth: we currently use wxgtk which is a not well maintained and a does not behave well cross-platform.

We are building a QT graphical user interface (GUI) now,  which is almost fully @devos50 work. We hope we can deploy this GUI soon. For now, we will leave the current wxgtk GUI as is because putting effort into something that will be deleted soon is a waste of time.
I am confident the QT GUI will be much better, we just need some time :)

**Comment by devos50** [comment]
This won't be fixed since it affects the old `wx` GUI.
