### ISSUE TITLE
blockchain-regulated markets

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2559]
Marketplace with blockchain based reputation system supporting bid,ask, and cancel messages.
![20160928_103741](https://cloud.githubusercontent.com/assets/325224/19196605/85d30968-8cb6-11e6-9121-015504ae3f90.jpg)

Our previous running code, needs work: http://repository.tudelft.nl/islandora/object/uuid:c1816da8-c82e-47bc-bde2-4f35b9a3e775

**Comment by synctext** [comment]
- [ ] 0) connectable ! Control of wallet! New message order-match-made
 - [ ] 1) orderbook realtime updates. Closed trades,  buy/sell bid/ask open orders
 - [ ] 2) 'place order NOW' price, amount. Either bid or ask. Calculate estimated average cost, estimate in Euro. Fixed price bid/ask may block, long unfilled state.
 - [ ] 3) Close trade, match in orderbook, fill at various price points, incremental settlement.
 - [ ] 4) bid/ask rating, filtering, and ranking. Reputation calculation. MarketOfLemmons problem. Score based on 'Temporal PageRank'. Simple threshold score filtering. Rank score to stars. This makes it a blockchain-regulated market?
 - [ ] 5) market supply bot. Always sell Delft credits against Bitcoin. Only when having supply. Machine buys computational power. run exit, sell and earn.
 - [ ] 6) market making bot. Daily fund of buying Delft coins. Try to be unpredictable for cheaters? Bug bounty program.

**Comment by synctext** [comment]
Existing literature (no code, just ideas):
 - [Beaver: A Decentralized Anonymous Marketplace with Secure Reputation](https://eprint.iacr.org/2016/464.pdf)
 - [Measuring the longitudinal evolution of the online anonymous marketplace ecosystem](https://www.usenix.org/system/files/conference/.../sec15-paper-soska-updated.pdf)
 - [TUDelft running prototype code](https://github.com/Tribler/tribler/pull/2233)

**Comment by synctext** [comment]
Economic theory foundation: https://scholar.google.nl/citations?view_op=view_citation&hl=en&user=ZEDUm5UAAAAJ&citation_for_view=ZEDUm5UAAAAJ:2osOgNQ5qMEC

**Comment by synctext** [comment]
Ongoing 15 pages of decentral markets survey .tex : https://github.com/Tribler/tribler/issues/2535

**Comment by synctext** [comment]
Related implementation on central server from 2011 [that can handle 6 million orders per second on a single thread](http://martinfowler.com/articles/lmax.html) on a 3 GHz machine.

**Comment by synctext** [comment]
Getting started with coding:
  - PyCharm or something
  - http://tribler.readthedocs.io/en/latest/
  - https://dispersy.readthedocs.io/en/devel/
  - https://github.com/jarradh/DispersyExample

**Comment by devos50** [comment]
Additional resource: https://github.com/Tribler/dispersy/pull/517

**Comment by synctext** [comment]
The decentral market is now smoothly operational in Gumby:
![transactions](https://cloud.githubusercontent.com/assets/325224/21684197/070093d8-d35d-11e6-9868-deb11e6070ba.jpg)

**Comment by devos50** [comment]
Gumby experiment link: https://jenkins.tribler.org/job/pers/job/market_experiment_devos50/

Like the AllChannel experiment, this can (should?) become a performance/health indicator for our decentralised market.

**Comment by synctext** [comment]
[Current survey draft. .pdf ](https://github.com/Tribler/tribler/files/726748/Lit_survey.3.pdf)

[Interesting related work](http://cdn.oreilly.com/oreilly/booksamplers/BuildWebRepSystems_Sampler.pdf)

**Comment by devos50** [comment]
@basvijzendoorn these tickets seems to have overlap, see https://github.com/Tribler/tribler/issues/2535#issuecomment-260346273 for another table of content.

**Comment by synctext** [comment]
- first known (distributed) accounting paper from 2002: [Policies in Accountable Contracts](http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=1011296)
  - Dated 2003 vision on building trust: [Using Trust for Secure Collaboration in Uncertain
Environments](https://pdfs.semanticscholar.org/d50b/3a504b79f91f3bd32cc4cf82259050f61bca.pdf); Please copy this picture in your report - "Figure 3: The framework for one party to a computing interaction. (Large arrows signify data flows, and thin arrows signify control flows."

**Comment by synctext** [comment]
http://www.the-blockchain.com/2017/02/26/0x-open-protocol-decentralized-exchange-ethereum-blockchain/

**Comment by synctext** [comment]
ToDo Bas, read and run the code :
- self-replicating code: http://repository.tudelft.nl/islandora/object/uuid%3Aa1b443c7-8b37-4263-ae96-d38bc8b8f397
- this seems to be the bleeding edge code: https://github.com/devos50/tribler/tree/market_community

**Comment by synctext** [comment]
THE Core economic theory of markets from 1970: https://github.com/dmvaldman/library/blob/master/economics/Akerlof%20-%20The%20Market%20for%20Lemons.pdf

**Comment by devos50** [comment]
Worked on a first very basic version of a Trustchain credits <-> BTC market in Tribler. I've integrated the Bitcoin wallet and made an API endpoint to get the balance, both confirmed and unconfirmed using the Electrum wallet. Note that the asks and bids are requested using the RESTful API. In addition, when Tribler discovers a new ask/bid, the list in the GUI is automatically updated and sorted accordingly.

<img width="1280" alt="market_screen" src="https://cloud.githubusercontent.com/assets/1707075/23568630/a4ea0496-005b-11e7-83bb-7301980efaf6.png">

TODO (GUI-related):
- make it possible to create a new ask or bid
- wallet management
- transaction history overview
- accepting trades
- cancelling trades? (tentative, requires more work in the market community)

**Comment by synctext** [comment]
good screenshot. will include it in grant submission for Tuesday.

**Comment by devos50** [comment]
I've rewritten some of the wallet logic. We now support more than one wallet and each wallet has a short identifier. The main idea is that we have various wallets that holds assets, i.e.:
- Trustchain reputation wallet
- Bitcoin wallet

More wallets can easily be added in the future.

Also, some of the API endpoints have been rewritten. One can query all the wallets available with a call to `GET /wallets`. This returns a list of identifiers of each wallet (i.e. `btc` and `mc`). Each wallet has various methods that should be implemented:
- get_identifier
- get_balance
- transfer_assets (TODO)

This allows us to get rid of the `PaymentProviders` in the current decentralised market code and use wallets that are integrated in Tribler instead.

Finally, the GUI has to be redesigned slightly to support multiple wallets and multiple assets.

**Comment by synctext** [comment]
Good progress. If now API access is hacked, wallet access is possible. Needs to be hardend.

**Comment by basvijzendoorn** [comment]
Privacy of Traders problem description
https://www.sharelatex.com/project/58c7d6390d2b81b36b2736a3

**Comment by synctext** [comment]
0) connectable ! Control of wallet! New message order-match-made

@devos50 critical above item slipped of the roadmap. We need to detect if peer is connectable. Everything assumes full connectability.

**Comment by devos50** [comment]
A small update here. Last week, I've been working on writing a big integration test that tests the decentralized market from ask/bid dissemination up to and including making transactions (with real bitcoin!). This works well and the Jenkins job can be found here: https://jenkins.tribler.org/job/pers/job/market_community_btc_credits_test/

In addition, I've spent some time improving the incremental payments system. Also, I've included a bloom filter in each introduction request so the order books are synchronized between two users. This addresses bootstrapping problems since we have no persistency of orders in our market.

Also, the timeout mechanism of asks and bids has been fixed and I've added an event so orders are dynamically removed from the GUI. This all works pretty neat.

@synctext regarding the connectability of peers, I rather implement a generic check in Tribler for this since there might be more components in the future that requires connectability. Do you agree if we just disable creating new orders and display a warning if a peer is not connectable for a first iteration?

**Comment by devos50** [comment]
Interesting related work (on the business case of blockchain markets): https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2785626

**Comment by devos50** [comment]
BTC <-> Tribler reputation can now be exchanged without problems. In addition, I've added support for trading between multiple wallets, like a real currency exchange. This means that we can also add more types of wallets later.

**Comment by devos50** [comment]
More related work:

https://media.consensys.net/introducing-swap-a-protocol-for-decentralized-peer-to-peer-trading-on-the-ethereum-blockchain-d4058f3179cf

https://www.youtube.com/watch?v=0Bzwayom_iA&feature=youtu.be

This video explains why it's hard to build order books on the blockchain. I should note that they assume a "traditional" blockchain with proof-of-work consensus which causes latency and thus possibilities for market/order manipulation.

**Comment by devos50** [comment]
Must-read related work: http://www.econinfosec.org/archive/weis2014/papers/Clark-WEIS2014.pdf

**Comment by Jaapp-** [comment]
Beta testing branch [market_community](https://github.com/devos50/tribler/tree/market_community): no tracebacks and able to do some trading.
![2017-06-09-121448_1000x1075_scrot](https://user-images.githubusercontent.com/3542526/26971463-930e7168-4d0d-11e7-90fc-5be5e11ac41c.png)

**Comment by MitchellHop** [comment]
able to create negative balance on my Tribler reputation credits. We conducted a collusion attack on the live network. We did several back and forth transactions to create an endless amount of reputation. Note the -1*10^12 reputation in the screenshot below.
![screenshot from 2017-06-09 12-16-00](https://user-images.githubusercontent.com/5709613/26971586-0f05276c-4d0e-11e7-9496-9d6420e2b01f.png)

**Comment by devos50** [comment]
Nashx: "NASHX is about enabling two untrusted parties to make safe exchanges online by putting them in a Mexican standoff. We put two untrusted parties into Nash equilibrium, through a military strategy called Mutually assured destruction so that neither party has anything to gain by scamming one another." (http://nashx.com/About)

They use a neat strategy but not decentralized. Also nice to read about http://en.wikipedia.org/wiki/Mexican_standoff and http://en.wikipedia.org/wiki/Mutually_assured_destruction :)

![hownashxworks](https://user-images.githubusercontent.com/1707075/27243618-0d91dc42-52e3-11e7-977a-bab6ef41a890.png)

**Comment by devos50** [comment]
When running some experiments on a larger scale, it turned out that there were still some errors that occurred in *very unlikely* circumstances. It took me quite some hours to hunt these down and fix them since I had to go through many MBs of log files.

The experiment now seems to function as it should and I'm ready to extract the first graphs out of it.

![transaction_graph-2](https://user-images.githubusercontent.com/1707075/27260843-1a4cd17c-5436-11e7-962a-41907176e52b.png)

**Comment by devos50** [comment]
First (very preliminary) results with an order book where the Google stock symbol is traded:

[efficiency.pdf](https://github.com/Tribler/tribler/files/1084521/efficiency.pdf)

**Comment by devos50** [comment]
TODO:
- [ ] make sure the market can handle **any** asset trading. This is slightly different from what I've implemented right now since it's not possible to define more complex matching rules (for instance, an Uber-like marketplace).
- [ ] write one page related work
- [ ] write something about the results

**Comment by devos50** [comment]
Update: first experiment with a third-party matchmaker succeeded, time to scale this up and test it better. In the image below, node 1 is the matchmaker that matches node 2 and 3 who have created an ask and bid respectively.

![transaction_graph-3](https://user-images.githubusercontent.com/1707075/27637094-bdfb73f2-5c0e-11e7-85b0-53cae15826ab.png)

**Comment by devos50** [comment]
Taxi experiment using a real-world Uber dataset up and running: https://jenkins.tribler.org/job/pers/job/taxi_experiment_devos50/.

**Comment by synctext** [comment]
Related work [bitsquare decentral market](https://github.com/Tribler/tribler/files/1152645/bitsquare.pdf):
 ```Redundant data storage (flooded to all peers)``` and
 ```Resistant against spam/flooding```
So please copy or try to understand their magical solution

**Comment by devos50** [comment]
First initial results of taxi-simulation using the market:

![bandwidth](https://user-images.githubusercontent.com/1707075/28269155-51808a3a-6b01-11e7-9a98-aec9dbc47d87.png)

![matching_efficiency](https://user-images.githubusercontent.com/1707075/28269159-5522a0ba-6b01-11e7-9aba-aabdd67e40d1.png)

![matching_latency](https://user-images.githubusercontent.com/1707075/28269160-595cd772-6b01-11e7-9326-9068738648a9.png)

**Comment by devos50** [comment]
After considerable effort, I managed to compile and run bitshares on the DAS5 (so we can compare it against our own implementation). I had to compile my own version of GCC, OpenSSL, CMake and Boost but it seems to work now.

**Comment by devos50** [comment]
After some thinking, I feel that that the we are not really using the power of (our) blockchain (TradeChain) in the market implementation. Instead of using TradeChain as a post-market ledger, I envision it to be the core component of the market, used to account all ask/bid/order cancels, transactions and payments. In this scenario, the market becomes properly blockchain-regulated (or blockchain-powered I guess).

There are various advantages of doing this, the most obvious one being that all operations in the market become tamper-proof and irrefutable (this is already a property of the decentralized exchanges I’m comparing with, i.e. Waves and Bitshares). Making TradeChain an essential component in the market helps to make a more fair comparison with other blockchain-based exchanges. Another advantages is that we can combine gossiping of the blockchain and order synchronization between peers (currently, these are two separate processes, leading to increased communication costs). Finally, it provides more transparency since all market manipulations are recorded on TradeChain.

The only problem I foresee here is that some operations recorded on the TradeChain do not involve a transaction counterparty, for instance, cancelling one of your own orders. As a consequence, the block that captures the order cancellation only contains one signature, namely your own. To ensure entanglement, I propose to use one of the matchmakers as “witness node” that verifies that you have cancelled the order.

I think we have a strong platform to sell after we make TradeChain our core component: decentralized and scalable matchmaking, irrefutable and transparent transactions, zero transaction fees and near-instant clearing and settlement.

@synctext do you agree with this?

**Comment by devos50** [comment]
Got the experiment with the Waves platform completely working: https://jenkins.tribler.org/job/pers/job/waves_experiment_devos50/57/. However, it seems that they use a centralized matchmaker server so it's not as decentralized as they claim. Transfer of value is recorded on a global blockchain however. Also, for every new buy/sell order, a small transaction fee has to be paid to the matchmaker.

**Comment by devos50** [comment]
The Bitshares market is now also fully functional within Gumby (up to the point where I can make buy and sell orders): https://jenkins.tribler.org/job/pers/job/bitshares_experiment_devos50/116/. We are now ready to compare our implementation against these markets 👍 

Next focus will be the refactoring of the market to make TradeChain our central component.

**Comment by synctext** [comment]
more related work, social markets: https://thenextweb.com/contributors/2017/08/29/can-blockchains-replace-retail-giants-like-amazon-ebay/#.tnw_tyPxx71b

**Comment by synctext** [comment]
Another ICO {scam} exchange market with low/no fees: https://bitcointalk.org/index.php?topic=2091630.0
Ready for business: 2019 :-)

**Comment by devos50** [comment]
Related work: https://ico.wcex.co/whitepaper?lang=en (centralized but low fees)

**Comment by devos50** [comment]
[On the Impossibility of Fair Exchange Without a Trusted Third Party](https://www.cs.utexas.edu/~shmat/courses/cs395t_fall04/pagnia.pdf) shows that it is impossible to facilitate a fair exchange without a TTP being involved. This is the reason why incremental payments should be used. Filecoin uses a similar philosophy, however, they consider this as future work while we have full support for incremental payments and transaction recording.

**Comment by synctext** [comment]
Bitcoin Historical Data - [Bitcoin data at 1-min intervals from select exchanges, Jan 2012 to May 2017](https://www.kaggle.com/mczielinski/bitcoin-historical-data) and other datasets at that site.

**Comment by devos50** [comment]
Now that the market is functional and the first emulation results are available, I will focus on improving the security of our platform. This includes a (basic) defense against the Sybil-attack using [Temporal Pagerank](https://repository.tudelft.nl/islandora/object/uuid%3A17adc7bd-5c82-4ad5-b1c8-a8b85b23db1f). The unique property of Temporal Pagerank is that it incorporates the notion of time. The temporal aspect is often disregarded when we consider defenses against the Sybil attack (see [Exploiting Temporal Dynamics in Sybil Defenses](https://www.princeton.edu/~pmittal/publications/temporal-ccs15.pdf)). The structure of our transaction ledger (TradeChain) is used as input for this algorithm. It has been proven that Temporal Pagerank is resistant against historical Sybil attacks. Additionally, it is computationally cheap.

At this point, the algorithm has been implemented and integrated in Tribler (PR will be opened soon) and the performance of the mechanism will be evaluated using a real-world dataset.

**Comment by devos50** [comment]
The paper [Bazaar: Strengthening user reputations in online marketplaces](https://mislove.org/publications/Bazaar-NSDI.pdf) describes a novel technique to determine transaction risks in an online marketplace. The key idea is to create `risk graph` and perform a max-flow computation on it from a specific buyer to a seller to asses whether a transaction should be flagged as `fraudulent` (or high-risk). Since max-flow computations is an expensive technique, they split up the complete graph into multiple, smaller graphs in a smart way. This provides a speedup of around 3x.

Their experiment is based on scraped eBay data, containing millions of purchases. The algorithm is driven by user-feedback where new feedback, either positive or negative, modifies the risk graph.

**Comment by devos50** [comment]
After a bit more research I realized that the problem is not about sybil _detection_ but rather about sybil _prevention_. Temporal Pagerank is not designed to detect Sybils since they are not guaranteed to be assigned a lower trust score than honest nodes, however, the effects of a Sybil attack on reputation are limited (however, not as strong as NetFlow).

Fortunately, Temporal Pagerank is an asymmetric reputation system since it's personalized (the random walk starts from the set of your own half-interactions). This is beneficial since [it has been proven that symmetric reputations mechanism cannot be Sybil-proof](http://netecon.seas.harvard.edu/P2PEcon05.html/Papers/Cheng_05.pdf). Examples of symmetric algorithms are EigenTrust and regular PageRank.

I've considered various dataset to evaluate Temporal Pagerank, however, there have been some issues:
- most datasets do not have a ground truth and a true classification of Sybils/non-Sybils. This includes almost all dataset described in Sybil-detection algorithms (mostly social network graphs).
- Temporal Pagerank needs, as the name implies, a total order on the interactions. Unfortunately, all datasets I've seen are void of temporal information (this includes the dataset with [8000 fake twitter followers](https://shkspr.mobi/blog/2015/03/this-is-what-a-graph-of-8000-fake-twitter-accounts-looks-like/)).
- it is beneficial to use a graph with weighted edges, however, only a few dataset contains this property.

While I agree that using a social network dataset is nice, it lacks some desired properties that make Temporal Pagerank work. Additionally, I don't want to derivate much from the domain I've been exploring (peer-to-peer markets) so for now, I propose that I use my own scraped dataset with eBid transactions. This dataset contains 246.181 transactions, created by 13.955 users. Each transaction has a value (so it's a weighted graph) and a timestamp (so the set of transactions is ordered).

Next step is to perform a small (local) experiment with just the reputation algorithm to see how much influence Sybils have on their ranking (similar to the method described [here](https://link.springer.com/content/pdf/10.1007/978-0-387-73655-6_18.pdf)). Next, we can emulate the market on the DAS-5, with crawling, and perform a Sybil attack to see how it works in a complete environment with nodes crawling the TradeChains of others.

**Comment by devos50** [comment]
I just realized that NetFlow will not work for computing reputations of traders. Imagine a transaction between user A and B where a total value is exchanged of 20 dollars. Now, this is represented as an edge from A -> B and with an edge from B -> A with a weight of 20. However, when performing the first step of the NetFlow algorithm, the capacities of all new edges will always be zero (since the maximum flow from A -> B is the same as the maximum flow from B -> A). In fact, NetFlow is based on inequality between consumption and contribution.

**Comment by devos50** [comment]
I've performed a few experiments with Temporal PageRank. First, I've rerun the experiment of Pim where he determined the computation time required for the algorithm. Instead of running it once, I've averaged the results over ten runs. We use the scraped data from eBid (described in one of my previous comments). The horizontal axis shows the total amount of transactions in the graph and the vertical axis the computation time. The results are shown for the preparation time of the data structure and the actual computation time for Temporal PageRank. We see that Temporal PageRank is a feasible algorithm, even for a graph with many traders and transactions.

![compute_time](https://user-images.githubusercontent.com/1707075/30961734-8bcf558e-a447-11e7-9348-839be46b8948.png)

However, a more interesting question is _how much reputation Sybil attackers are able to gain with Temporal PageRank_. To determine this, we perform an artificial Sybil attack as follows: first, we pick 100 random nodes who will become attackers. Each of these attackers introduce a varying amount of additional Sybil nodes and initiates a transaction with a value of 1.000.000 with this Sybil. [It has been proven that this gives the maximum amount of reputation to an attacker](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.450.1721&rep=rep1&type=pdf). We consider different amounts of additional Sybils introduced; 1, 2, 3, ... 10. We are interested in the average increase of PageRank score and rank by attackers when they perform a Sybil attack (this metric is used by most papers I've found that evaluate Sybil Attacks on PageRank). We consider three (related) reputation mechanisms: PageRank, Personalized PageRank and Temporal PageRank. The results of this experiment are shown in the following figures. As we see, Temporal PageRank is more resistant against Sybil attacks than the other two algorithms (yay!).

![sybil_simulation_rank](https://user-images.githubusercontent.com/1707075/30962127-eb40b28c-a448-11e7-82d3-beca0d44b3f7.png)

![sybil_simulation_score](https://user-images.githubusercontent.com/1707075/30962133-ee903e1c-a448-11e7-8397-873560e17dec.png)

**Comment by devos50** [comment]
I was thinking a bit about the current implementation of the decentralised market in Tribler. While it's working (https://jenkins.tribler.org/job/pers/job/market_experiment_devos50/732/) and contains an implementation of the Temporal Pagerank algorithm, next point of actions *can* be the following:
- global consensus on TradeChain records with CHECO. Since CHECO uses protobuf message serialisation, I argue that this, if we decide that we want to have this on top of TrustChain, should be implemented in the IPv8 library. I found out that there are some issues with CHECO if we want to implement this in a Tribler-like system (including transaction spam) but I will post these elsewhere since they are not relevant for this ticket. Note that global consensus is a must if I want to compare our market with other existing solutions like Bitshares, WAVES and/or OpenLedger, to ensure a fair comparison.
- solving transaction spam - Bitcoin and many other systems solve this with transaction fees which is undesirable for our market since it is built with the vision of having zero transaction fees. We might be able to exploit witnesses (witnesses are used to co-sign a TradeChain record that creates a new order), which are capable of refusing to sign a record that creates a new order in the market. On the other hand, users are able to simply create a new digital witness identity and use that identity to enforce a new order in the market. This might be addressed by introducing a separate reputation for witnesses?
- improve scalability with incremental Temporal Pagerank

**Comment by synctext** [comment]
ACM publication related work: [decentralized blockchain-based electronic marketplaces](https://cacm.acm.org/magazines/2018/1/223888-decentralized-blockchain-based-electronic-marketplaces/fulltext). Discussion [at YCombinator](https://news.ycombinator.com/item?id=16145451).

![image](https://user-images.githubusercontent.com/325224/34944674-d007be76-fa00-11e7-9c23-a1c2e1951083.png)

**Comment by synctext** [comment]
Related work on market for labor and tasks:
"This article will provide a theoretical compass to assist in navigating the reinvention of the company. In the same vein, the seismic movements that have fractured the firm, hence redrawing labour law’s borders will be investigated. The exploration is organized as follows. First and foremost, attention will be devoted to the doctrinal debate on the fragmentation of the firm and the decentralisation of the production cycle. "
[The Invention of the Future. Does ‘Platformisation’ Redefine the Notion of the Firm?](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3124389)

**Comment by synctext** [comment]
Really decentral related work? https://github.com/KomodoPlatform/BarterDEX

**Comment by devos50** [comment]
I've listed BarterDEX already in my related work comment. At that time, there was no code. It seems that there's a beta now available. Their technology heavily resolves around atomic swaps, a technique that requires [BIP65](https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki) implemented. While this ensures that exchange of currencies is either executed or not at all, its functionality is limited to trading of cryptocurrencies.

Browsing a bit through their documentation, I found this comparison between state-of-the-art DEX platforms (the last row is quite arbitrary chosen):

![ac557dfa614a8f6db222e26ea4b00df4](https://user-images.githubusercontent.com/1707075/38016811-7c76635e-3270-11e8-9478-d332489a1aff.png)

I will try to get some more information about their decentralized matching algorithm. Curious to know how they implemented that.

**Comment by devos50** [comment]
They haven't done any scalability experimentation at all, after reading through their whitepaper. Also, some statements they make, are fuzzy:

> With 100 full nodes, thousands of non-relay nodes can be supported, possibly tens of thousands, though that number has not been reached in practice, so we will have to wait and see what the real world limitations are.

> ... In practice, we are seeing the nearly instantaneous response when all the parameters are properly met.

**Comment by devos50** [comment]
I compiled BarterDEX and got it running on the DAS5, it's ready for some experiments 👍

**Comment by devos50** [comment]
Extracted from the IDEX whitepaper:

> Due to the competitive nature of the space we are not revealing the exact proposed method for decentralizing the orderbook at this time

Also, according to the whitepaper, their distributed order book will be live in Q3 2018.

Even more fantasy and dreaming from their main project, Aurora (https://auroradao.com/assets/Aurora-Labs-Whitepaper-V0.9.5.pdf):

> In addition to guaranteeing open access, operating the infrastructure in a distributed manner brings many additional benefits. Decentralized operations make it much harder to DDOS the Aurora infrastructure, ensuring that the network is always available. Additionally Aurora will be able to access computing power for the best rates possible. It is conceivable that Aurora will eventually incorporate machine learning algorithms operate an AI banker. Operating on a distributed network would give Aurora access to a lot of cheap computing power.

**Comment by synctext** [comment]
Epic text!

**Comment by devos50** [comment]
I might have fried the DAS5 cluster at the VU but I managed to reach over **30.000 trades/sec**.

The following graph gives the relation between the total number of traders in the network and the average global throughput in trades per second. Each trader trades with another trader at a rate of 20 trades/sec, for a period of 30 seconds. The graph is made after optimizing the code and storing all Trustchain records in memory such that lookups are _very_ efficient.

Also, the graph strongly suggests horizontal scalability.

![trades_throughput](https://user-images.githubusercontent.com/1707075/38767045-6682f62a-3fdb-11e8-8ef2-0e9367e155d3.png)

**Comment by devos50** [comment]
Repeated the OpenRide experiment, here are two rough plots (still needs some polish and I'm running it more times so I can add some error bars). During the experiment, I differ the broadcast settings, in particular, the fan-out _f_ and _TTL_. So when using _f = 10_ and _TTL=2_, each new ask/bid order reaches 10 + 10^2 = 110 nodes. As we see, lower values of _f_ and _TTL_ lead to suboptimal efficiency, in particular in the situation where _f = 5_ and _TTL = 2_. Also, note that increasing the broadcast range further doesn't really improve the matching efficiency anymore.

![openride_efficiency](https://user-images.githubusercontent.com/1707075/38782072-713d0f9c-40ee-11e8-9328-7d985a6be0b6.png)

Average bandwidth usage per network participant:

![openride_bandwidth](https://user-images.githubusercontent.com/1707075/38782073-74a26d08-40ee-11e8-9b71-f70b55091b15.png)

**Comment by zilveer** [comment]
Don't forget Bitbay #BAY (`[Bitbay.market](Bitbay.market)`) which is also a decentralized market with smart contracts.

**Comment by devos50** [comment]
I now have a trading bot running on the market testnet, which periodically (every 35) creates an order, alternating between an ask and a bid. See [here](http://explorer.tribler.org/users/4c69624e61434c504b3a1e415a2a9f24805cf25336ae80f60768ac2bceca4508b40e5072f633defc8e3fce46ac50d04e8f925ed0a8fe022500917053b2546e38379efbf0dea4205c757d) for the latest orders of this node. I will run this overnight to see whether things work as expected.

Next step: add a second node to the testnet and let these two bots trade.

**Comment by synctext** [comment]
Nice! This could be the V7.2 key feature. A testnet wallet auto-activated and instant live animation would be cool TorrentFreak promo points.
Gigachannel feature will not be fully usable and have gossip updates for 7.2.

**Comment by devos50** [comment]
After some major refactoring, matchmakers no longer reserve some quantity in their order books when matching. Instead, any conflicts should be resolved between the two trading parties.

The motivation behind this change is that I noticed during my experiments that matchmaking becomes very inefficient if assets are reserved. By avoiding the reservation of assets in the order book, the same order can be matched against multiple other orders and a `match` message will be sent to all identities behind the matched orders now. Intuitively, this should lead to better matching efficiency but I should validate this with some experiments on my order datasets.

**Comment by synctext** [comment]
Lots of related work appearing. As discussed indeed 1 common theme. We need reputation, we are not working on it, and concrete plan is lacking.
https://hackernoon.com/dharma-protocol-tokenized-debt-and-funding-through-decentralized-systems-384527f1a75d

**Comment by devos50** [comment]
Since our market is mostly accountability-oriented, I think a reputation system is a valuable and natural extension of this line of work.

**Comment by synctext** [comment]
Sorry, to clarify: common theme on these white papers: they have no reputation system, they critically need one, and are delaying work on it. Fundamental science: universal reputation system.

**Comment by synctext** [comment]
https://www.mariuszoican.org/blog/smart-settlement-on-the-blockchain

**Comment by synctext** [comment]
phd thesis outline, outcome of discussion:
- architecture of decentral marketplace and components
- matching of orders in decentral bid/ask orderbook  (under submission)
- real-time clearing and settlement ([Internet-of-Money at IFIP networking](https://doi.org/10.23919/IFIPNetworking.2018.8696786))
- accountability: using append-only individual ledgers ([trustchain Journal by Martijn with contributions from Pim, Brusee, Veldhuisen](https://pure.tudelft.nl/portal/files/47579639/paper.pdf))
- final chapter: 
  - high impact topic
  - exposure for lab?
  - experimental validation, architectural validation, deployment results, experimentation and validation?

**Comment by devos50** [comment]
After (almost) a week work, I have the following progress:
- Setup a [standalone repository](https://github.com/tribler/anydex-core) that stores all code related to the decentralised market, *AnyDex*.
- Setup some [basic CI](https://jenkins-ci.tribler.org/job/AnyDex/job/anydex_PR/) that runs when a new PR is made against the master branch.
- Merged my recent work of the last month regarding order matching into the main repository. As a result, matchmaking has superior scalability, fault tolerance and resistance against malicious matchmakers now. I consider the matchmaking algorithm finished.
- [Updated Gumby to support experiments with Python 3](https://github.com/Tribler/gumby/pull/415). Specifically, it can now build a `venv` with Python 3 and run the AnyDex validation fully with Python 3. Not sure about any improvements regarding speed so far.
- Updated the IPv8 infrastructure to support Python 3.
- Worked on a first GUI prototype, based on [HyperDEX](https://github.com/atomiclabs/hyperdex).

Next, I will focus on some fundamental issues, namely counterparty fraud detection and improved trade accountability. Hopefully, I can make some progress with the GUI next week, and setup some unit tests for the REST API.

**Comment by devos50** [comment]
I think the issues raised in this ticket have been sufficiently addressed with the deployment of [AnyDex](https://github.com/tribler/anydex-core) and our upcoming journal article 👍 .

**Comment by Beckyni** [comment]
I had lost some funds due to an airdrop scam too and it fucked me up luckily I got introduced to this hacker who helped me recover what was stolen from me hit him up on telegram::https://t.me/badestha
