### ISSUE TITLE
[PeX] Disabled, should/can i enable it?

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#2563]
##### Tribler version/branch+revision: #####
6.5.2
##### Operating system and version: #####
Windows 10
##### Expected behavior: #####
[PeX] Enabled/Working
##### Actual behavior: #####
[PeX] Disabled
-------------------------
Hello, all torrents (private/public) i added into Tribler has [PeX] Disabled when i click torrent and click torrent trackers tab.

DHT is "Working"

Is it wrong PeX is not working, if it gives any advantage, i would like to enable it, but i do not know how.

**Comment by devos50** [comment]
PeX is a peer exchange protocol that can be used to discover other peers in a libtorrent swarm, see http://www.bittorrent.org/beps/bep_0011.html. When downloading a torrent anonymously, PeX is disabled since peer discovery should be performed by our own anonymous overlay. If you download a torrent regularly (not anonymously), PeX should work as expected.
