### ISSUE TITLE
Starting Tribler fails: ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by brussee** [Tribler/tribler#2642]
On latest devel just starting Tribler fails: (nothing changed since last night when it still worked)

```ERROR:root:No JSON object could be decoded
Traceback (most recent call last):
  File "/home/paul/repos/tribler-app/TriblerGUI/tribler_request_manager.py", line 84, in on_finished
    json_result = json.loads(str(data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by brussee** [comment]
Removing appstate 'solved' it.

**Comment by devos50** [comment]
Unfortunately, this issue is too general for me since I don't have any clue on which request is going wrong. I'm working on adding info about the latests performed requests to the crash reports so I have a better idea about the state of the system when a specific crash occurred.

Do you still have the app state where Tribler crashed? If so, please mail it to me or upload it here so I can try Tribler with that state directory. For now, I will close this issue. Please reopen it if you have more information about this issue.
