### ISSUE TITLE
RuntimeError when we have a tracker URL without a port

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#2723]
Got this one in our backend:

```
Traceback (most recent call last):
File "TriblerGUI\core_manager.py", line 128, in on_received_state
RuntimeError: Unhandled Error
Traceback (most recent call last):
File "lib\multiprocessing\process.py", line 114, in run

File "TriblerGUI\core_manager.py", line 61, in start_tribler_core

File "lib\site-packages\twisted\internet\base.py", line 1195, in run

File "lib\site-packages\twisted\internet\base.py", line 1204, in mainLoop

--- <exception caught here> ---
File "lib\site-packages\twisted\internet\base.py", line 825, in runUntilCurrent

File "Tribler\Core\TorrentChecker\torrent_checker.py", line 119, in _task_select_tracker

File "Tribler\Core\TorrentChecker\torrent_checker.py", line 225, in _create_session_for_request

File "Tribler\Core\TorrentChecker\session.py", line 47, in create_tracker_session

File "Tribler\Core\Utilities\tracker_utils.py", line 110, in parse_tracker_url

exceptions.RuntimeError: No port number for UDP tracker URL.
```

Should be easy to fix by logging the error or by handling the exception properly.

**Comment by qstokkink** [comment]
Whoever fixes this should probably also look at the return value/exception when the timeout is reached for [create_tracker_session](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/TorrentChecker/session.py#L40).

**Comment by kc1212** [comment]
I'll give this one a go. What is the expected behaviour? I suspect we just assume the tracker is invalid and go to the next tracker select task. 

I'm considering to catch the error on the caller of `create_tracker_session` and then log the message. But the `RuntimeError` type is pretty general, maybe I need to create a new type or return an error value.

**Comment by devos50** [comment]
@kc1212 thanks!

The `RuntimeError` should not be thrown since this will crash the GUI. Logging it instead and going to the next tracker is a good idea. It's even better if we remove the tracker if it's invalid so it will never be selected again.

You could create a new kind of exception if you wish, something like `MalformedTrackerURLException`.

**Comment by kc1212** [comment]
I have a feeling the issue is more subtle. 

Malformed tracker URL shouldn't be added in the first place because the `_addTorrentTracker` in `TorrentDBHandler` removes them. So either there is something wrong in `get_uniformed_tracker_url` that is returning bad URLs (from my inspection it looked fine), or the trackers are added by some other function that is calling `TrackerManager:add_tracker(...)` without URL validation. I think this is the reason for the `RuntimeError`, it simply shouldn't happen.

Do you have the exact URL that caused the crash @devos50?

**Comment by kc1212** [comment]
Perhaps it's possible to inspect the database file on disk if the machine that produced this crash is available.

**Comment by devos50** [comment]
@kc1212 I don't have the URL unfortunately. The crash occurred at a random alpha tester so I don't think it's possible to ask them for the database file :/.

**Comment by qstokkink** [comment]
Quick idea:
What if [TrackerManager.initialize()](https://github.com/Tribler/tribler/blob/devel/Tribler/Core/Modules/tracker_manager.py#L28) has an unchecked tracker url?

I guess this probably could happen if (1) [LaunchManyCore.update_trackers()](https://github.com/Tribler/tribler/blob/96e4c70c775f15c606f7f25c6e3973b9d190f33f/Tribler/Core/APIImplementation/LaunchManyCore.py#L446) is called and then (2) Tribler exits before the trackers are checked. You'd have to find a way to trigger [this line](https://github.com/Tribler/tribler/blob/96e4c70c775f15c606f7f25c6e3973b9d190f33f/Tribler/Core/APIImplementation/LaunchManyCore.py#L483).

**Comment by kc1212** [comment]
If new trackers need to be added, via [`addTorrentTrackerMappingInBatch`](https://github.com/Tribler/tribler/blob/96e4c70c775f15c606f7f25c6e3973b9d190f33f/Tribler/Core/APIImplementation/LaunchManyCore.py#L483) or something else, it'll eventually call [`add_tracker`](https://github.com/Tribler/tribler/blob/96e4c70c775f15c606f7f25c6e3973b9d190f33f/Tribler/Core/Modules/tracker_manager.py#L45) which sanitises the URL.

I investigated all the code that I could find that adds trackers, they all sanitise the URL before doing anything (please let me know if there's something I missed). Also, the tracker URL is never updated or deleted. So I have two suspicions. 

1. Somehow a bad URL made it into the database, maybe from a bug in earlier versions of Tribler.
2. A corner case URL that isn't caught by our code.

Given the fact that this appears to be uncommon, I recommend the following. 

1. Sanatise the tracker URLs in `TrackerManager.initialize()`, this addresses the my first suspicion.
2. Improve logging in the `RuntimeError` so that next time it happens we know exactly which tracker caused the issue and check whether it's indeed a corner case and fix it properly, this addresses my second suspicion.

Catching the error as I've done in #2730 may not be a proper fix, I feel it's a workaround.
