### ISSUE TITLE
Tribler fails to add torrent when default download directory doesn't yet exist

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#2731]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
devel, 19ecae714f037916c8ae8a05c962d7e2914331d2

##### Operating system and version: #####
Arch Linux, kernel version 4.8.13-1

##### Expected behavior: #####
When adding a torrent, Tribler creates the default download directory if it doesn't yet exist. It then adds the torrent and starts downloading.

##### Actual behavior: #####
When the default download directory (/home/user/Downloads/TriblerDownloads) doesn't exist, Tribler gives a
```
request error:

An error occurred during the request:

Invalid destination directory specified
```
##### Steps to reproduce the behavior: #####
Remove Tribler's default download directory, (/home/user/Downloads/TriblerDownloads), but make sure the parent folder (/home/user/Downloads/) exists. Then add a torrent (from .torrent file), change no options, and click 'download'.

**Comment by devos50** [comment]
Thanks! This one should be easy to fix; just check whether the directory exists and if not, create the directories recursively.

**Comment by vandenheuvel** [comment]
Can I get this assigned?

**Comment by devos50** [comment]
I've already fixed this in a PR I will open tomorrow, together with various other fixes.

**Comment by vandenheuvel** [comment]
Alright. Could you maybe still give feedback on the direction [this](https://github.com/vandenheuvel/tribler/tree/fix_2731_create_default_dir) is taking? @MaxVanDeursen and I decided that it would be best to keep the api files strictly for parsing and came up with this solution.

**Comment by devos50** [comment]
@vandenheuvel this is how I fixed it: https://github.com/Tribler/tribler/pull/2739/commits/78a4b9d5b0214cb9f363bb4a338adf0117809398

Some remarks:
- I see that you did some cosmetic changes (i.e. changes were you don't change functionality of the code). Try to keep them to a minimum if they are not necessary since it might lead to rebase conflicts for other students. I will do an auto PEP8 soon.
- Any (uncatched) exception popping up when executing a request, is returned in the HTTP response of that request and displayed in an error dialog to the user (the text is the message of the exception). That's why I don't catch the `OSError` when recursively making the directories. This is something you probably didn't know but it's great since you don't have to worry too much about handling exceptions when executing a request.
- Libtorrent will handle the case when the target download directory is not writable for you (the status of the download will switch to `error when downloading` or something like that and the user can see the details about the error when clicking on the torrent).
- The events you've added are unnecessary. You should only add new events when you want to inform a client about an action that is not bound to a specific request.

Also, if you wish to fix another issue, please first ask me to assign you before writing the code. I will also make sure that I assign myself when I'm fixing something 👍.

**Comment by vandenheuvel** [comment]
@devos50 Thanks a lot. We indeed didn't know about the exception handling.

The event we added was actually meant to inform a client about an action that is not bound to a specific request: when WatchFolder tries to readd all torrents in the directory subtree and the default download directory isn't accessible I think this can still go wrong. Or are exceptions also handled by the caller of WatchFolder?
