### ISSUE TITLE
video-on-demand is pre-allocating GBytes of disk space

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2760]
When selecting a single video-on-demand file, other files do not appear in the GUI.
However, it seems our libtorrent settings trigger a full disk pre-allocation of the whole swarm.

this causes solid disk space usage (observed on MacOS 10.10.4).
```
$ROOT>  ls -lah .unwanted/
-rw-r--r--  1 staff  staff   727M Jan 27 14:04 34e7247a996c7ec82a64931302476b33fe435b0
-rw-r--r--  1 staff  staff   965M Jan 27 13:59 34e7247a996c7ec82a64931302476b33fe435b1
-rw-r--r--  1 staff  staff   1.1G Jan 27 16:04 34e7247a996c7ec82a64931302476b33fe435b2
-rw-r--r--  1 staff  staff   1.2G Jan 27 13:59 34e7247a996c7ec82a64931302476b33fe435b4
-rw-r--r--  1 staff  staff   1.5G Jan 27 14:07 34e7247a996c7ec82a64931302476b33fe435b6
-rw-r--r--  1 staff  staff   1.6G Jan 27 14:22 34e7247a996c7ec82a64931302476b33fe435b7
```

**Comment by devos50** [comment]
I can verify this, however, I'm sure that we are using the right allocation mode (http://www.rasterbar.com/products/libtorrent/manual-ref.html#storage-allocation and https://github.com/Tribler/tribler/blob/5ca5e067eefb4fbdfa64a0bbaefb08c3b3373970/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L294). I have to test this on Linux or Windows to see whether this is something OS X related or in libtorrent.

**Comment by devos50** [comment]
It turns out that libtorrent creates a sparse file. If you use the `ls` command, the apparent size of the file is returned which is the final size when everything is downloaded, however, if you use `ls -ls` (or `du`), the *real* size of the file is returned which is the amount of blocks that have been allocated. I've tested this and the size reported by `du` is increasing as the download makes progress. So while it might seem that space is wasted and a full allocation is used, the file system efficiently uses sparse files so it's working as expected, resolving this issue.

More info: https://en.wikipedia.org/wiki/Sparse_file
