### ISSUE TITLE
create_undo was called without having the permission to undo

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#2781]
##### Tribler version/branch+revision: #####
7.0.0-alpha2-36-g31841c7

##### Operating system and version: #####
Windows 10 64bit

Hello, i am having this Alpha version: https://jenkins.tribler.org/job/Build-Tribler_Win64_devel/347/
When i go to My Channel / Torrents and try to delete a torrent i added into my channel in Tribler v.6.x.x
then i am getting error: create_undo was called without having the permission to undo

Removing torrent which was added to the channel from within Tribler v.7 works without issue. Actually being unable to remove the torrent from my channel in Tribler 6.x was reason i installed Tribler 7.x Alpha.

Thank You

**Comment by qstokkink** [comment]
This seems like the user mid changed, while keeping old database entries for 'my channel'. This probably requires implementation of some mechanism to convert the old database entries to the new user mid.

This _might_ be due to switching member encryptions in the past (from the M2Crypto stuff to EC).

**Comment by devos50** [comment]
Okay, that might be a bit too complicated for now. I will move it to the next milestone.

**Comment by devos50** [comment]
Dispersy is end-of-life, therefore I will close this issue.

**Comment by slrslr** [comment]
@devos50 how i can delete what i have added in old Tribler versions? Or it will be possible in milestone 7.1 ?
