### ISSUE TITLE
GUI freeze/stuck after download completed

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#2876]
Latest 7.0 Beta on Ubuntu.

Background core and GUI seem to break their connection.

GUI does not freeze, there are just no updates or stats coming through from the core. Captured the last request from the GUI, the core continued further. However, the download complete never made it to the GUI. As already discovered, non-200 OK codes might be fatal in Tribler

![20170318_234335](https://cloud.githubusercontent.com/assets/325224/24100998/cd0ff8d6-0d76-11e7-9079-d369a73e22f3.jpg)

**Comment by devos50** [comment]
This is due to one single request to `/downloads` failing which blocks future updating of the GUI. I've added a timeout mechanism that cancels the current request if it takes too long and starts a new one. That should hopefully prevent situations like this from happening. It will be included in my next PR.

The next step is to add a heartbeat to the API so we can keep track of the health of the core.

**Comment by synctext** [comment]
> keep track of the health of the core

Hopefully we can avoid this. Our core and GUI should simply be rock solid.
