### ISSUE TITLE
No "Loading..." message for downloads.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#2915]
##### Tribler version/branch+revision: #####

devel 50c5fa119d51784d94ad5b045970336623765b42

##### Steps to reproduce the behavior: #####

1. Start Triber core using twistd
2. After seeing "Tribler started", start the GUI using `./tribler.sh`
3. Browse views: channels, subscriptions, downloads

##### Expected behavior: #####

All those views show "Loading ..." message until the actual information gets delivered to the GUI

##### Actual behavior: #####

Download list look empty until finally, one by one the downloads start flowing in. It takes enough time to think "where are all my downloads?".

@devos50

**Comment by devos50** [comment]
This issue is a bit more involved than I originally thought. It's very easy to display a single row of information in a `QListWidget` but it's more difficult when displaying it in our downloads list (which is a `QTreeWidget`.

One solution is to simply hide the whole table with downloads and replace it with a single label that says 'no downloads active' or 'loading' but I want to show the downloads list (with at least the header) to the user so I don't think this solution is very clear.

I will postpone this issue to a later milestone.
