### ISSUE TITLE
Error message in console. 

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2933]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

Windows 10.

Tribler RC-1. 

Console output (below). Not entirely sure what caused it. I did however notice it, after coming back to the computer today, and had a download torrent window open. (The one where you select a place to download to, what files to include, etc.) Might be a issue caused by that being open for too long. GUI crashed when i attempted to add another torrent from file. Got the select file window, but crashed after selecting it. (When one would expect the download torrent window to open.)

##### Relevant log file output: #####
![image](https://cloud.githubusercontent.com/assets/1584461/25804198/cf777a0e-33fa-11e7-98f6-84b5d1edab02.png)

Console output was only done once or twice for each of the mentioned components, but went on for a loop when i pressed download on the forgotten torrent.

**Comment by devos50** [comment]
Thank you for your report. This seems to be a Qt issue: https://github.com/telegramdesktop/tdesktop/issues/292 and https://github.com/telegramdesktop/tdesktop/issues/292. It might be fixed in Qt 5.6.0 but we are still using Qt 5.2 on Windows. Upgrading the Qt version used on Windows is a bit tricky since we have to compile it with an older C++ version (2012).

I will postpone this issue past the Tribler 7 release.

**Comment by Thomasedv** [comment]
Just want to update, i get this pretty frequently. Though, it falls in line with referenced issues in Qt. In the recent week, i've been moving a monitor a lot and unplugging it from the PC to use with the Xbox. So, you're probably correct, as that was mentioned in there too.

**Comment by qstokkink** [comment]
We upgraded the Qt version of our Windows builder, so this should be fixed now.
