### ISSUE TITLE
Crash on attempting to change anonymity (to 0 hops, off)

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#2969]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
RC-2 2
##### Operating system and version: #####
Windows 10

##### Expected behavior: #####
Change happens, and Tribler continues as normally.

Possibly very important: Torrent was from a watch folder.

##### Actual behavior: #####
Tribler crashes as the change happens. On restart, the torrent remains as it was. 

##### Steps to reproduce the behavior: #####
Right click, change anonymity -> no anonymity. 

Likely caused by Tribler readding the torrent from the watch folder, before the one without anonymity is readded, causing the crash.   

##### Relevant log file output: #####
Forgot to copy-paste, but it got sent with the crash reporter.... sorry. Said duplicate torrent error though.

**Comment by devos50** [comment]
Thank you for your report, I've seen the crash in the error reporter. This is probably a race condition where the current download has not been removed, yet we try to add the download again with a different amount of hops. To fix this, we should make removal of torrents asynchronous (there is already an issue for this somewhere), but I'm not sure whether we could do that before Tribler 7 is released since this is slightly disruptive.

@qstokkink do you think making removal of downloads asynchronous is feasible for Tribler 7?

**Comment by qstokkink** [comment]
@devos50 As this is a hard crash within the _normal_ user experience boundaries, I think we have no choice but to fix this.

**Comment by devos50** [comment]
Related to #2907.
