### ISSUE TITLE
Inconsistent data in Trustchain database

### ISSUE THREAD

**Issue by vandenheuvel** [Tribler/tribler#3003]
I found the following two rows in my trustchain database. 

```'6134643462646F776E376932383530303531313062746F74616C5F646F776E3769323835303035313862746F74616C5F757037693337313237343832627570376933373132373438'	'4C69624E61434C504B3AFA5819C971B0FBD9B21E4DD0B80158710AF15EE11A360059C1457B9A2991F929919390BBC6B4C953C714419FAA783791ACD40429554FC32F36C6CCA2B5C92683'	1	'4C69624E61434C504B3ADB2B5E786A70E73840B3DDCB88D10F904FA59C4B3376DCA4760AC27BBEE7BD5DDA873B6AFE09D679290770C8B34CD4922D3D93F39578B914C0AD71D6CD5D1ABE'	0	'3030303030303030303030303030303030303030303030303030303030303030'	'053F7A9042EF53BFB35B89B2BC8C547F44D9928FC28ACF83554B41D9FE682CBB38FF669F42F093455BD992CAA9D139EC269A44DB5084848A3E4865C3001C410F'	2017-06-16 09:21:14	'3795DF679EEA645DA6A0677CE529002BA45A0CF49C6A21851F48115506E14708'```

```'6134643462646F776E376932383530303531313062746F74616C5F646F776E3769323835303035313862746F74616C5F757037693337313237343832627570376933373132373438'	'4C69624E61434C504B3ADB2B5E786A70E73840B3DDCB88D10F904FA59C4B3376DCA4760AC27BBEE7BD5DDA873B6AFE09D679290770C8B34CD4922D3D93F39578B914C0AD71D6CD5D1ABE'	4	'4C69624E61434C504B3AFA5819C971B0FBD9B21E4DD0B80158710AF15EE11A360059C1457B9A2991F929919390BBC6B4C953C714419FAA783791ACD40429554FC32F36C6CCA2B5C92683'	1	'0D3ABFC98B1738D695F9F58AE8384D70855EA239EFE4D3217951F45C522077A9'	'5B64F0A2CA60D516C45786098525D0F977E740D88556D21116BBED8810D7B2C1A3D60DFA01FDA29DD4B79C8CED5544C20C07599C51A25A7207A50551B3BBDA01'	2017-06-16 09:21:14	'C96AF0B1A652D2CF6AEFCFFCBDE7990280DF3107BD4BE1E1DA2120167AA3F105'```

Not that the transactions are identical with unequal up and download while the `public_key` and `link_public_key` are swapped for the  two different half blocks. Moreover, the sequence numbers (0, 4) don't match.

**Comment by qstokkink** [comment]
This took me a while to verify but this is correct behavior.

Blocks are created as follows:

1. An initatior creates a correctly signed (half)block with some sequence number and a linked sequence number of 0 (because it doesn't know what it's linked to)
2. The other party receives this and creates his (half)block with the linked sequence number of the initiator and (of course) his own sequence number

Note that the first block is **signed and inserted into the blockchain with linked sequence number 0** and as such "cannot" be removed from the chain anymore. To find the actual linked block you need to call the `get_linked()` database method.
