### ISSUE TITLE
You guys need to rethink

### ISSUE THREAD

**Issue by filicado** [Tribler/tribler#3052]
I have beenfollowing this project for years and it only once worked for me a year back or two.
Since then there is always another reason why it doesn't install/run/launch or crashes
I've played around with it under Windows 10, Ubuntu, Arch and macOS.

You guys should seriously consider releasing this as snap or flatpak image it just is to frail and unstable a piece of software otherwise. It won't ever run reliably on many systems. I think the ~300 issues listed here may speak to this too.

**Comment by qstokkink** [comment]
Thank you for your long-term interest in Tribler. We are continuously trying to balance bringing you the latest features from the brightest students passing through the TU Delft and releasing a stable piece of software. Most recently a student has created Docker images for us. We will investigate Snap and Flatpak as well.

At the end of the day, Tribler does not have any full-time developers though: it remains a labor of love. We depend on student and community contributions (in the form of bug reports and pull requests) to survive. Once summer vacation is over, we will once again try our very best to deliver a bug-free Tribler version to you.

**Comment by synctext** [comment]
@filicado Thank you for the wakeup call.

Yes. We need to put more effort in Quality Assurance. Tribler should install without problems and have fewer bugs. Less exciting research and more boring fixing.

With new blockchain funding we should be able to finance that.

**Comment by pimlie** [comment]
@synctext @qstokkink 

I was wondering, do you guys use Tribler personally as well for (real world) torrenting or is it mostly 'just' a research project? Because looking at the type of issues that Tribler 7 is experiencing and especially their (breaking) impact my first guess would be its mostly the latter?

**Comment by qstokkink** [comment]
@pimlie Believe it or not, but we actually do use our own product. <sup><sub>Our workplace blocks torrent traffic, so it's the only way we can view the latest season of our favorite copyright-free VODOs and Linux distributions.</sub></sup> Since a few months we only have full-time researchers and no more full-time developers though. So everyone is stabilizing their own research branch and not (or too little) the "stable" `next` branch.

Thankfully, exciting research is what brings in funding, and funding is what brings in full-time developers, who provide stability to Tribler. We were kind of stagnant on the exciting research for a little bit, which is why our funding dried up and Tribler's stability decreased. As @synctext mentioned, we did some exciting research again and got funding, which got us more developers, which is where we are right now. So, very soon, bugs should be getting fixed again and Tribler 7 can be released.

**Comment by pimlie** [comment]
@qstokkink Thanks for the quick update, thats good too hear :)

Have you thought about accepting donations from users? E.g. opening an [opencollective](https://opencollective.com/) page so users could support the development or is that against TUDelft policy?

**Comment by qstokkink** [comment]
@pimlie Truthfully, asking money from our users would go against the whole spirit of the project. Tribler has always focused on bringing the latest and greatest for absolutely no cost to its users. It's supposed to work like a win-win situation for both end-users and researchers, or not work at all. This translates into Tribler's design as well, which is why our upcoming market (see experimental `devel` branch) has no transaction costs when exchanging currency.

Side note: we have enough funding again for the next couple of years, so we can stick to this principle. Who knows what we would've resorted to if we actually ran out of money.

**Comment by pimlie** [comment]
> we have enough funding again for the next couple of years

Wow, thats really great. Now you are getting me really excited about whats to come! ;)

**Comment by hbiyik** [comment]
@filicado @pimlie 
i think one of the best thing of this project, that it never works as expected in real world, but this is not because the idea/science is wrong (even if it was i wouldn't really understand), mostly because the implementation is missing or rushed or sometimes not tested as it is supposed to. So it always forces you to understand what is going on behind the curtains, just wanted to say that it is not a bug, but a feature for enthusiasts :).

**Comment by synctext** [comment]
@hbiyik good to hear from you again!
Could you please help us fix some outstanding Kodi issue?
@EinNarr is getting stuck getting his credit mining master thesis work. He needs Kodi builds that work.
https://github.com/Tribler/tribler/issues/2609

See below the Kodi platform toys we got in the lab now (a few Google Pixels, 100+ Raspberry Pi board, 6x Nexus 5, nexus 6, nexus 10, etc):
![20170913_145042](https://user-images.githubusercontent.com/325224/30378441-7a1c99f6-9893-11e7-9a82-b7a8cc98c43a.jpg)
So a few dedicated devices doing coin farming is not too far of. (we even didn't raise 180 million $ in an ICO for that). plus, this week we're buying 10 additional dedicated Tor-like relay servers with uncapped Internet bandwidth...
