### ISSUE TITLE
Tribler is checking completed download.

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3102]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Steps to reproduce the behavior: #####
After a abend and restart, ALL torrent files are checked, also the already those already seeding
##### Expected behavior: #####
Skip checking completed downloads
##### Actual behavior: #####
All files are checked, which takes a long time, when you have a lot of active Torrents.

**Comment by Nubro01** [comment]
This used to work perfectly in 6.5, so not an enhancement.
The version from september 24th, checks every torrent even if I am able to shutdown normally, which almost never happens, because the  just 3 Torrents of Flash season 1,2,3, all arround 8 gig, take longer then Tribler stays alive. Only if I make the screen as small as possible then I am able to finish the checking and close normally. At restart that checking starts again. Imagine when I have more then 3 torrents seeding. This is not workable and definately not an enhancement for 7.1! 

Also the anonimity change seems to work now, but when I change back and forth everytime a check if performed, why, the files do not change. so?

**Comment by qstokkink** [comment]
We probably only want to do this:
https://github.com/Tribler/tribler/blob/ec17e73b426b8ec5a6bf81531f85f42b7f30351d/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L1168-L1176

If this file does not exist:
https://github.com/Tribler/tribler/blob/ec17e73b426b8ec5a6bf81531f85f42b7f30351d/Tribler/Core/Libtorrent/LibtorrentDownloadImpl.py#L556-L557

Because if the download state already exists, this would overwrite it on startup with an empty state.
