### ISSUE TITLE
Self sovereign identity - group 9

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#3243]
@SandeshMj @shivanandkohalli @BSJAIN92 @umeer @himanshu-7 

> You will create your own blockchain, almost from scratch. Your blockchain will be special! Your blockchain will form a web of trust. This web of trust will be stored in the form of signed trust certificates. It will operate on smartphones exclusively. It will be a more advanced version of identity projects like: [www.uport.me](https://brightspace.tudelft.nl/content/enforced/49652-CS4160+2017+2/www.uport.me?_&d2lSessionVal=PtKfmhSWCxkeJ6zE9ALAjt8Tu)
> This identity blockchain aims to generate trust and complete ownership by the users. [Self-sovereign identity](https://bitsonblocks.net/2017/05/17/a-gentle-introduction-to-self-sovereign-identity/) is the concept that people and businesses can store their own identity data on their own devices, and provide it efficiently to those who need to validate it, without relying on a central repository of identity data. It’s a digital way of doing what we do today with bits of paper. This has benefits compared with both current manual processes and central repositories such as India’s Aadhaar.
> Attack-resilience is created by optionally using government issued identity documents to sign trust certificates. Fake or modified Dutch identity documents are rare. This ensures that a friendship link in this web-of-trust is authenticated and means more then a like, retweet or linkedin recommendation.
> In the past [various people have implemented](https://www.nfcworld.com/2013/06/26/324803/novay-releases-nfc-passport-verification-app/) Dutch paspoort NFC readers for Android. We have implemented an [open source implementation](https://github.com/Tribler/tribler/issues/2918#issuecomment-306734647) for you to use as a starting point. This contains an e-passport lib, it can fully talk to Dutch identity documents, both NFC and OCR of the machine readable zone. You will link e-passports with Trustchain. Two students have created a starting point for you to get going, see project A for details and links on Android Trustchain. To same time we recommend a focus on offline features using Bluetooth and NFC.
> Your blockchain engineering project consists of implementing as much as possible [from the list of 10 principles for self-sovereign identities](https://www.coindesk.com/path-self-sovereign-identity/). Students attempting Cum Laude gradation [may attempt to use our implementation](https://github.com/qstokkink/py-ipv8/blob/master/ipv8/attestation/wallet/primitives/cryptosystem/boneh.py) of the [Boneh crypto system](https://www.stanford.edu/~dabo/papers/2dnf.pdf).

This ticket will contain information for group 9 of the CS4160 Self-Sovereign Identity project.
Feel free to post your important updates and questions in this issue.

Search terms for further reading:
 - Sovrin
 - uPort
 - IBM idemix
 - zkSNARKS

You can also check out issue `3013` in this repository.

Meeting schedule: `Tuesdays weekly 13:30`

**Comment by qstokkink** [comment]
Heads up:
Your first meeting is `21st November 2017, 13:30`

**Comment by qstokkink** [comment]
For next meeting `5th December 2017`:

 - Have a functional Blockchain implementation
 - Have a good idea on what goes into the blocks and underlying proofs

**Comment by umeer** [comment]
Today 12-Dec, we are not meeting with you as we have not made relevant progress this week, we will meet you next week.

**Comment by umeer** [comment]
@qstokkink Can you add these accounts as well?
himanshu-7
BSJAIN92
umeer

**Comment by qstokkink** [comment]
@umeer I have sent out the team invites, once you accept I can assign you to this issue.

Also, I will see you next week then: you should have something up and running at that time or you will probably run into trouble regarding the overall project planning.

**Comment by qstokkink** [comment]
First and foremost: best wishes for 2018!
Your meeting tomorrow will be in this building:
https://www.google.nl/maps/dir//51.9990903,4.3785233/@51.999109,4.3785435,18.08z/data=!4m2!4m1!3e2?hl=en
In room 3.420 (third floor).

**Comment by SandeshMj** [comment]
@qstokkink If we want to postpone it by one week, it will be on 6th february, since this is a holiday, does that mean we will have the presentation after the break?

**Comment by qstokkink** [comment]
@SandeshMj please send an e-mail the course instructors and we can work out a date with you.

**Comment by BSJAIN92** [comment]
@qstokkink Hey! We are having some confusion. let's say we want to present on 9th Feb, will it mean -20% for us? Or the negative grading kicks in after 16th feb?

**Comment by qstokkink** [comment]
@BSJAIN92 I had to e-mail my collegues for clarification: this should be updated on Brightspace soon. The rule will be that the penalty will be -10% for delays past 30-1-2018 (with the absolute deadline of 16-2-2018). As the 9th of february is still within the next week, that should be a -10%.

**Comment by BSJAIN92** [comment]
@qstokkink Thanks for confirming! We will let you know once we have decided on the date. Would it also be possible for you to meet one of us tomorrow?

**Comment by qstokkink** [comment]
@BSJAIN92 Sure, you can drop by tomorrow at any time (except 14:30).

**Comment by qstokkink** [comment]
@BSJAIN92 Note that the dates changed a little bit (see Brightspace): the report is now tied to the 2nd of february and the presentation can be up to the 16th of february without a point deduction.

**Comment by BSJAIN92** [comment]
@qstokkink Thanks for the information! We will now proceed accordingly.

**Comment by BSJAIN92** [comment]
Some information about our basic work towards taking a step ahead for self sovereign identity.

Let's start off with the simple example of a bar. In order to verify the age to be above a certain number, let's say 18, one had to produce a legal document that has the date of birth of the user. Here, along with the age, the actual date of birth and other additional details present in the document like complete name, address/nationality etc are also shared while the requirement was a simple yes or no if the user  is of the age.

There can be a solution for the problem where user can carry a bunch of various cards specifying individual identity, or more simply by hiding the non-essential values by hand. But the approach has to be more secure where a mistake of not placing hand properly on card won't cause you to share details you don't want.

Our application is a step towards implementing decentralized, permission less blockchain implementation of self sovereign identity.


This is the homepage that can be seen by the application users.

![image](https://user-images.githubusercontent.com/8111083/35011472-7ffbcc7c-fb06-11e7-874c-2b9e80912b20.png)

Main functionalities are: 
Chain Explorer - Explore the generated blockchain.
Reset the application data - For testing and debugging
Authenticate Identity Details with government
Validate the identity information with a 3rd party seeking it.

Here is the screenshot of the chain explorer looks like.

![image](https://user-images.githubusercontent.com/8111083/35011557-db1d7902-fb06-11e7-8f57-61ce0a3fd343.png)

It has the information about who authenticated information with whom, the blocks, public and link public keys, transaction hash etc.


The application supports the authentication and verification of the identity of the user. The user can place his/her identity values in the application and then request an authentication from the concerned authority. 

![image](https://user-images.githubusercontent.com/8111083/35011705-6a815d52-fb07-11e7-8e87-975a71044e86.png)

User here enters value in "Attr" and goes for authentication. Authority enters the value in "value" and loads a corresponding QR code. User then can scan the QR code and the application will authenticate the information. For the purpose of ZKP, similar process is followed.


Here is a screenshot of such a qr code generated.

![image](https://user-images.githubusercontent.com/8111083/35012000-750946da-fb08-11e7-9340-8f3125792bc6.png)

Now user can use the app for verification purposes wherever required and information sharing is deemed fit from the user. 

![image](https://user-images.githubusercontent.com/8111083/35012903-c44addd2-fb0b-11e7-8fef-10e2d024751c.png)

The process for the same is pretty simple. The third party selects the information they want to validate and go for "validate" to generate the QR code for the same. User selects the information that is required to be validated and clicks on validate and scan the QR code.

Team:
Bhavya Jain - https://www.linkedin.com/in/contact-jain-bhavya/
Himanshu Shah - https://www.linkedin.com/in/shah-himanshu/
Sandesh Manganahalli Jayaprakash - https://www.linkedin.com/in/sandesh-mj-2480b3a8/
Shivanand Kohalli - https://www.linkedin.com/in/shivanand-kohalli/
Umeer Mohammad - https://www.linkedin.com/in/umeer/
under supervision of Quinten Stokkink

**Comment by shivanandkohalli** [comment]
@qstokkink 
Please find the report attached. 
[Self Soveriegn Identity.docx .pdf](https://github.com/Tribler/tribler/files/1691054/Self.Soveriegn.Identity.docx.pdf)
The code and README doc can be found here:
https://github.com/umeer/PersonalBlockchain/releases/tag/v1.0.1

**Comment by shivanandkohalli** [comment]
@qstokkink Hey, we were finalizing our presentation which is scheduled on 12th Feb. We wanted to know if there is a breakup of time for the presentation, demo and Q&A session in the scheduled 30 minutes.

**Comment by qstokkink** [comment]
@shivanandkohalli Yes there is. The guideline is as follows:

1. 15 minutes of presentation, which should roughly consist of 5 minutes of slides and 10 minutes of demo
2. 15 minutes of Q&A

**Comment by BSJAIN92** [comment]
Hi @qstokkink ! Please find today's presentation here:
https://docs.google.com/presentation/d/1eYN7Xah6pgLRiA2WnTwb8kzGKlQkx58cSVofYSU9pC4/edit?usp=sharing

**Comment by qstokkink** [comment]
@BSJAIN92 Thanks. You can expect your grade within 2 weeks.
