### ISSUE TITLE
Tribler hardly seeding and very low on CPU % usage

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3257]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Nov 22 2017
##### Tribler version/branch+revision: #####
Tribler 7
##### Operating system and version: #####
Windows 10 Insider 17046
##### Steps to reproduce the behavior: #####
Run Tribler on a 32 GIG I7 6700K processor
##### Expected behavior: #####
Upload to use 25 Mbs of available network speed and CPU % arround 20 % ?
##### Actual behavior: #####
Upload speed just at 400 Kb or mostly less and CPU only at 1.8 % usage

While typing this I suddently see a 1.8 MB download to one specific user and cpu is still at 1.8%, so that is very good!!! It seems leechers determine what they want me to seed? It this so? Can I do something to have them ask for more? Or is Tribler responding incorrect info when seeders ask for an upload?

**Comment by devos50** [comment]
The allocation of available outbound bandwidth is outside our control and is completely managed by libtorrent. Even if a torrent has a high number of leechers and you are a seeder, it is not guaranteed that you will seed much to these users (it is likely however). It also depends heavily on the popularity of the torrent.

Since this is not something we can solve without implementing a custom scheduling algorithm in libtorrent (which we will not work on most likely), I will close this issue. Thanks for the report anyway and please let me know if you have any other questions.
