### ISSUE TITLE
integration testing of Tribler on Linux, Mac, and Windows

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3288]
We need a test where individual software modules are combined and tested as a group.

Not just a fake-core with the real QT GUI, but everything.
https://github.com/Tribler/tribler/blob/next/Tribler/Test/GUI/test_gui.py#L20

**Comment by devos50** [comment]
While integration tests are definitely helpful to have, it's hard to properly design and implement them, especially since the data returned by the Tribler core is non-deterministic (this is the main reason why I've created a fake core, so I can control all data returned to the GUI and create situations that are uncommon when using the real core).

If we are going to make some proper integration tests, I think we should start with creating tests for only the Tribler core for now. This can be accomplished as follows: we enable/disable modules in the Tribler core by changing the Session configuration (the core is built very modular) and we attempt to test whether the functionality works or not, while using real data. Examples of modules we can test are the video server, libtorrent, metadata store, Dispersy communities and the torrent checker.

As a first step, I think it's helpful to have a permanent seeded (video) torrent by us (we already have a container that runs a Transmission server) and test whether our VOD functionality works (i.e. HTTP requests to the video server returns data within reasonable time). Next, we can test other components of Tribler.

**Comment by xoriole** [comment]
Yes, integration tests are definitely helpful and they are lacking in Tribler at the moment. Even though the data returned by the Tribler core is not always deterministic I think we can still have integration tests to test the behavior of the system as a whole and not just the data itself.

Yes, the core is modular I agree and it's a good idea to start with core modules integration test and gradually grow the test cases. These tests with more realistic scenario would definitely help to ensure the stability of the system as a whole as we add more features to Tribler.

**Comment by synctext** [comment]
Thank you, very insightful! Good topic for a Devel meeting and create a ToDo list.

**Comment by xoriole** [comment]
This is addressed by the application tester which runs on all supported platforms. I'm closing this issue as a general one in favor of creating new issues for the extension of the application for newer use cases.
