### ISSUE TITLE
Anonymous downloading/hidden seeding incompatible with newer version of Libtorrent

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#3353]
After upgrading libtorrent to a newer version on bbq (1.1.5), it seems that anonymous downloading and hidden seeding is failing: https://jenkins.tribler.org/job/GH_Tribler_PR_tests_linux/5524/.

Also the anon downloading/hidden seeding unit tests are failing so it's quite easy to reproduce.

This might be solved with #3084 but I haven't investigated that yet.

**Comment by devos50** [comment]
I've downgraded libtorrent on bbq so this issue becomes a bit less urgent for now. I will postpone it to 7.1.

**Comment by arvidn** [comment]
does this anonymous tunnel rely on SOCKS5 support in libtorrent by any chance?
One thing I changed recently was attempting to receive incoming connections over SOCKS5 (i.e. it's no longer done).

My understanding was that this support was based on a very optimistic reading of the spec, and no socks5 server actually supports incoming connections. So, if tribler implements its own socks proxy, perhaps it relies on this feature.

**Comment by qstokkink** [comment]
@arvidn Correct. This is exactly what we do.

**Comment by arvidn** [comment]
I see. so, I could fix this for 1.1.6 by putting it back in. However, I would want to put it behind a setting that's off by default (to not spam normal socks5 proxies with these connections).

Perhaps in the long run, it would make sense to provide a more direct way of interfacing with or wrapping peer connections. I'd be open to suggestions.

**Comment by devos50** [comment]
@arvidn thank you for your response. We critically rely on this feature and we would appreciate it if you could create an option to enable it again.

I'm running some experiments that need anonymous downloading/hidden seeding and a SOCKS5-compatible libtorrent, capable of accepting incoming connections. Could you specify in which commit you disabled incoming SOCKS5 connections support so I could, for the time being, maintain my own fork and revert this specific commit? Thank you! 👍

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/commit/02bb1251d256b7c40f1321fc6227101e7b9f20dd

**Comment by arvidn** [comment]
I would appreciate some review or test with this patch: https://github.com/arvidn/libtorrent/pull/2711
this is against the RC_1_1, I intend to bring this back for libtorrent-1.1.7

As you can see, this is quite a large and complicated patch, that's why I would prefer to have a better, more direct, way of integrating with a tunnel like Tribler's. A way that requires less overhead and parsing, and ideally wouldn't even use loopback sockets. It's difficult to have callbacks go back into python though, as libtorrent is multi threaded. But maybe there's a lighter weight protocol/transport we could come up with.

**Comment by qstokkink** [comment]
Callbacks directly into Python would indeed be ideal. But the only other (realistic) alternative to loopback sockets I can think of is directly piping to a process, which is a pain on Windows and would require libtorrent to do child process management. 

As far as minimizing overhead and parsing is concerned: what we do now is extract the infohash and target peer from the packet. If libtorrent gave us these directly it would save us some parsing.

Also, I guess we could get rid of the SOCKS5 protocol.  QUIC maybe?

**Comment by devos50** [comment]
@arvidn I will test it out next week, thanks for your effort! That's not a simple patch indeed.

In the meantime, I did some tests to test the compatibility of Tribler with different libtorrent versions. From libtorrent 1.0.7 - 1.0.11, anonymous seeding + downloading works fine, however, from 1.1.0 anonymous downloading stops working, even after applying the patch in #3084. After some more debugging, it seems to be an issue in the SOCKS5 - libtorrent communication, in particular, the UDP ASSOCIATE message does not come through. I observe CONNECT/BIND messages being sent to the SOCKS5 server, however, and I'm pretty sure that the response to libtorrent is correct. @arvidn is this a known issue in 1.1.0 (and maybe higher versions)? I could provide some more information if you wish.

**Comment by arvidn** [comment]
there was [this](https://github.com/arvidn/libtorrent/issues/1373) issue in 1.1.1. Which resulted in [this](https://github.com/arvidn/libtorrent/commit/ad7e796d05fd9d682c812e43127d7cb2071df057) that made it into 1.1.2. Then there was another [patch](https://github.com/arvidn/libtorrent/commit/acd98d5c40591366a7e43e62848bb2509448fc7c), which made it into 1.1.4.

As far as I can tell, at least 1.1.4 is supposed to have working UDP ASSOCIATE support. That last patch was simply to delay 5 seconds before retrying a SOCKS5 connection if the UDP ASSOCIATE command failed.

There is a simulation test for this case.

Is it possible the SOCKS5 server is not ready to accept incoming connections by the time libtorrent is configured to use it? I'm not confident in the error-handling and retry mechanism in such case.

**Comment by arvidn** [comment]
I have a question on Tribler behavior (as a SOCKS5 tunnel). Feel free to point me to the code if it's easily answered there.

When I send an endpoint address with ``INADDR_ANY`` and a requested listen port (which is either what the user has requested or random). The response is then interpreted as the actual listen interface (IP, port) that the server is listening on. Although, what seems to be an error in libtorrent is that it never refreshes its idea of the listen port, but sticks to the requested one. This port is then included in tracker announces and DHT announces, etc.

Do you use the listen endpoint for anything meaningful? Do you respond with anything meaningful?
Does it matter what libtorrent sends as the listen port to the tracker, or does the tunnel not use trackers anyway?
I'm thinking that perhaps I can at least simplify this portion of the code, to not announce a listen port if libtorrent is listening via socks5.

@qstokkink you mention info-hash and "target peer" (which I interpret as the IP address). How do you find and connect to peers over the tunnel, do you use some fake IP as the key?
Do you use trackers at all when using tunnels, or do you discover peers some other way?

My main reference point is the I2P proxy protocol. It has a wider scope than just a proxy. It also defines new fields for the tracker response, to return public keys (endpoint addresses) instead of IPs, and those are used to specify whom to connect to over their protocol.

But I don't think it would be that hard to come up with a new "proxy" protocol where the info-hash and some peer identifier (whatever you use) would just be part of the protocol itself.

**Comment by arvidn** [comment]
Do you intercept UDP tracker announces in the socks5 server as well then? and to translate the listen port argument at the exit node?
What I'm thinking is that instead of fixing the support in libtorrent to keep track of the remote listen port correctly, I just remove that support. iiuc, you don't need it. is that right?

**Comment by devos50** [comment]
This is fixed by #3377 and #3376.

**Comment by arvidn** [comment]
FYI. libtorrent's release branch ``RC_1_1`` now has this feature back in. But it's disabled by default and can be enabled by setting ``incoming_socks5_connections`` to true. This will be included in libtorrent 1.1.7 when it's released.

**Comment by qstokkink** [comment]
@arvidn thanks! We'll take it for a spin.

**Comment by Captain-Coder** [comment]
@devos50 @qstokkink , I hope you guys noted that the feature arvidn is talking about is incomming _TCP_ connections? As far as I understand the patch (https://github.com/arvidn/libtorrent/commit/02bb1251d256b7c40f1321fc6227101e7b9f20dd) it does not affect udp over socks in any way. And we only use UDP.

We only support TCP up to the point of returning HOST_UNREACHABLE. So any trackers that are HTTP will fail to connect. When a port is leaked to the outside world it can be through UDP trackers or DHT. The libtorrent DHT correctly sets implied_port such that the actual tunnel exit port is recorded in the DHT (provided that the dht node accepts the implied port request). But the UDP tracker case is not covered yet afaik. But the client running libtorrent might have no idea what the exit port actually is.

**Comment by arvidn** [comment]
oh, so you don't use the SOCKS5 BIND command for accepting connections?
Did my patch make any difference for the tests passing?

**Comment by Captain-Coder** [comment]
https://github.com/Tribler/tribler/blob/1f3a5b7367f7a0a4cf31e13a284d7e3c9e34620c/Tribler/community/tunnel/Socks5/server.py#L185 up to line 198 is all TCP that we support. We definately don't support tcp binding on the public facing end of the socks server.

I'm guessing bind code is to pacify any application/testing framework that thinks it needs to do a bind request.

@devos50 should know if it made any difference to tests passing. But in my opinion it shouldn't. In my imagination it could conceivably make a difference if there is an unidentified race condition somewhere. But I don't think so.

**Comment by arvidn** [comment]
I see. In that case I'm tempted to rip this out of libtorrent again. But perhaps I should wait until you get your tests passing. Just supporting UDP makes sense and seems simpler anyway (until you need to shave off protocol layers to pull things out of the payload of course).

**Comment by arvidn** [comment]
@devos50 is my understanding correct that this issue was resolved without my patch to re-enable incoming TCP connections over socks5?

**Comment by arvidn** [comment]
I will undo my patch to restore support for incoming SOCKS5 TCP connections in libtorrent then. using UDP associate and uTP connections seems reasonable.

**Comment by Zorgodon** [comment]
@arvidn Even if this functionality was not needed in Tribler, it would still be useful in libtorrent proper, no?
What is the current status of receiving incoming TCP connections over SOCKS5 in libtorrent?
