### ISSUE TITLE
Can't select multiple downloads to apply bulk action on them

### ISSUE THREAD

**Issue by slrslr** [Tribler/tribler#3453]
##### Tribler version/branch+revision: #####
7.0.0 x64 downloaded today from tribler.org, previously i used alpha version so i have %appdata%/.Tribler from previous version. Before alpha i had 6.x verion.
##### Operating system and version: #####
Windows 10 64bit
##### Issue: #####
When i go to Downloads section, i see my torrents there and i try to click one, then i hold Ctrl or Shift key and click one more torrent. But it does not select multiple torrents. I wanted to bulk start/stop selected torrents.

**Comment by Thomasedv** [comment]
I think this should be added for a few reasons:

* In the event a lot of torrent are stopped, like due to lack of space on a full drive, you need to manually start them again. With a lot of torrents, you got an problem. 

* Removing many torrents takes a lot of time, especially with the confirmation popup that lets you select to cancel, or also to include the downloaded files. 

* With the Tribler 7.1 builds, you can mine torrents, but there is no good way to stop them. You can disable the setting in the debug settings panel and uncheck the channel you're mining from, but torrents will still keep their state and stay there. So, now a lot of torrents that you many not want are still active. You either need to stop all of them manually, or use even more time to delete all of them.
