### ISSUE TITLE
Tribler ignores default download location for watch folder

### ISSUE THREAD

**Issue by Thomasedv** [Tribler/tribler#3543]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

Tribler_7.1.0-exp1-57-g861c9e5d0_x64.exe (from Jenkins, Build-Tribler_Win64_next)

##### Operating system and version: #####
Windows 10 

##### Steps to reproduce the behavior: #####
Set default location to some folder. 
Set watch folder.
Save settings
Restart Tribler

##### Expected behavior: #####
Torrents will be downloaded to the default download location, as previous version have done. 

##### Actual behavior: #####
Torrents are downloaded to the TriblerDownloads folder, regardless of the folder chosen in the settings. 

##### Relevant log file output: #####
 
None

**Comment by devos50** [comment]
Thank you for your report. We made significant changes to the way the settings in Tribler are stored and read. It seems that there was a bug in this code. I fixed this issue and I will open a pull request to fix this in a moment 👍

**Comment by Thomasedv** [comment]
Well, that was a fast response. Nice!

One another topic, i'm wondering if i should make an issue for it, but Tribler seems to be unable to shut down properly once it's connected to a hoop/circuit or something like that. It just freezes. Is this known, or should i make an issue for it? I initially tried the dev builds since i was having this issue in the 7.0.* releases.

**Comment by devos50** [comment]
@Thomasedv is this reproducible behavior (it happens every time)? Do you see the spinning gears when shutting Tribler down? Please create a separate issue for this.

We can debug this in more detail if you could provide us with your Tribler logs (which can be found in `~/.Tribler/logs`). If you're hesitant with sharing this publicly (since it might contain infohashes of torrents you are downloading), you can also email them to me if you wish and I will share them with the developer team.

**Comment by Thomasedv** [comment]
Will create an issue for it!
