### ISSUE TITLE
Save files to : download location

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#3556]
Not backward compatible with V7.0
Upgrade fails. All downloads messed up.

**Comment by devos50** [comment]
Do you mean the locations in the drop-down menu when you add a new torrent? Or the location where existing downloads are being saved on the disk?

I could try to fix this tomorrow.

**Comment by colin1497** [comment]
I just installed Tribler_7.1.0-exp1-140-geda807908_x64.  All of my library is trying to redownload to the default download location, which happens to be on my boot drive, which was filled before I realized what it was doing.

**Comment by qstokkink** [comment]
The [DownloadConfig will automatically switch to the triblerdownloads folder if it does not have a setting](https://github.com/Tribler/tribler/blob/next/Tribler/Core/DownloadConfig.py#L39).
Since the setting was not found, it means that the [config_converter.py failed to write this for some reason, even though it really should have done this](https://github.com/Tribler/tribler/blob/next/Tribler/Core/Upgrade/config_converter.py#L64).
