### ISSUE TITLE
https://jenkins.tribler.org/job/Build_Tribler_next/ not available!!!

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3749]
#### Please, fill all relevant items: ####

- [ ] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

**Comment by xoriole** [comment]
Thank you for the report. Yes, Jenkins server at https://jenkins.tribler.org is currently down for server maintainence. 

New server is setup at https://jenkins-ci.tribler.org/ and build job is here at 
https://jenkins-ci.tribler.org/job/Build_Tribler_next/

**Comment by NoNameForMee** [comment]
@qstokkink, I am all for closing this issue, in due time (i.e. when the problem at hand is resolved).

Now I understand a new set of jenkings servers are up and running and that the old address is more or less deprecated. If the new https://jenkins-ci.tribler.org is to fully replace the old https://jenkins.tribler.org, then I would have expected that all the code and documentation would change to references the new domain before this issue is fully closed/resolved.

Old code links which still needs to change (if the new link is to replace the old):
https://github.com/Tribler/tribler/search?q=jenkins.tribler.org&type=Code

If the servers are only down temporarily, and the link is to still to be https://jenkins.tribler.org in the future, then having this issue open until the servers are back up would help users to  know where to find the files during the server downtime.

**Comment by synctext** [comment]
Next time should try to not break old URLs, when adding services / archiving old stuff. Both Jenkins and elsewhere.
