### ISSUE TITLE
Which dns to whitelist?

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3777]
I am running a Raspberry Pi with Pi-Hole to stop all internet advertising.
Within the Tribler log I get some dns resolve errors for;
etracker.hotplug
retracker.hotplug.ru
tracker.publicbt.com
asnet.pw
tracker.istole.it.
tracker.publicbt.com.

Should I whitelist them or what?
Is there a complete list of what to whitelists so Tribler can find everything?

Regards

**Comment by devos50** [comment]
There is no list with all trackers that Tribler supports (in fact, Tribler supports adding torrents with user-provided trackers). I think the easiest solution is to whitelist them.

Maybe the pi-hole community provides a list of torrent trackers that are blacklisted? A quick search leads me to this: http://www.torrenttrackerlist.com/torrent-tracker-list/.

Since this issue is not related to Tribler development, I will close it. Please let me know whether your question has been answered 👍
