### ISSUE TITLE
Credit Mining for Others lower Token Balance

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3778]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
August 9th is doing nothing so went back to the 6th
##### Operating system and version: #####
Windows 10 build 17735
##### Steps to reproduce the behavior: #####
Start Credit mining by selecting mining icon in Channels
##### Expected behavior: #####
Token balance to stay the same or increase, since I help other!
##### Actual behavior: #####
Token balance is going down.
##### Relevant log file output: #####
![image](https://user-images.githubusercontent.com/1146496/43990789-b3d53e64-9d60-11e8-8e5e-1bf77ee17205.png)

**Comment by devos50** [comment]
Thank you for your report. The most likely explanation for this is that credit mining first 'invests' in a swarm by downloading its content. This is needed since a user that performs credit mining needs the content locally in order to seed it to others. @egbertbouman could you confirm this?

Related to this issue, I'm planning to give more insights in the token history of users (as documented in issue #3731.

**Comment by egbertbouman** [comment]
@devos50 That would be my guess. Credit mining also doesn't perform well when there are a lot of overseeded swarms, so that could also be a factor.

**Comment by Nubro01** [comment]
![image](https://user-images.githubusercontent.com/1146496/44099888-f10a005a-9fe3-11e8-8e31-9961d6ec5527.png)
I am already now on -6.6 gig and I fail to see what this is not a bug, I geuss I just have to stop seeding anonymous and uncheck the option enable token mining, this is costing me and it looks that I am not gaining from this. I had a +6000 score before and now all that is gone!!!

**Comment by EinNarr** [comment]
@Nubro01 I am very sorry about the negative balance change to your account.
The current algorithm does not perform well, sometimes even negatively. I suggest you temporally turn it off before we release an update to it. We are currently working hard and doing experiments on that to find out a more optimized algorithm.

Sorry for your inconvenience.

**Comment by devos50** [comment]
I think this issue is too much work to address in Tribler 7.4, which mostly focusses on Python 3 compatibility. Let's move it to the next milestone.

**Comment by synctext** [comment]
Agreed, RC1 of 7.4.0 is due upcoming days...

**Comment by Nubro01** [comment]
In 7.4 my token ballance is again lowering, while I am NOT downloading, just seeding. I have no clue who or what is downloading through my machine at this very moment. If I am assisting others in their downloads then I should get tokens instead of loosing tokens!

**Comment by xoriole** [comment]
@Nubro01 This is discussed in the forum here:
https://forum.tribler.org/t/something-wrong-with-token-balance/5558/8

There is an existing issue of leaking torrent while doing anonymous seeding because of seeding to non-Tribler users but if you're not seeding anything it could a separate bug. We'll revisit this issue after 7.4 release.

**Comment by ichorid** [comment]
Let's continue discussion of Mining-related problems on #4363
