### ISSUE TITLE
Make Tribler configuration portable

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#3904]
Currently, Tribler does not support importing configuration from different machines, mostly because the configurations are tied to the absolute paths (state dir, download dir etc). It will be quite useful for us in debugging to have a portable configuration. We can replicate the exact state of another Tribler instance with this.

**Comment by qstokkink** [comment]
Can you do relative directories over different disks in Windows?

**Comment by devos50** [comment]
I think the `state_dir` option still needs to be absolute since it can be anywhere on the disk of a specific user. Other fields should (must?) be relative to this state dir, for example, the location of the EC keys.

**Comment by ichorid** [comment]
After v7.3 configuration files use relative paths internally. This only needs a small push to make Tribler config completely portable.

**Comment by smaragdus** [comment]
[qBittorrent](https://github.com/qbittorrent/qBittorrent) offers an easy method of running the program in portable mode- the user just needs to create an empty folder (`profile`) in the program folder next to the executable (`qbittorrent.exe`) and all configuration and data files will be saved in this `profile` folder, The user can also run the program in portable mode using a command-line argument (`qbittorrent.exe --portable`) but I find using the `profile` folder method to initiate portable mode more convenient.

[uTorrent](https://www.utorrent.com/) can also be run in portable mode (at least version 2.2.1.25302, I suppose the same is valid for later versions as well). In order to use the program in portable mode the user just needs to create an empty configuration file (`settings.dat`) in program folder (next to the executable- `uTorrent.exe`) and the program will run on portable mode.

I hope that portable mode will also be available for [Tribler](https://github.com/Tribler/tribler).

**Comment by ichorid** [comment]
@smaragdus , you can try experimenting with creating this "portable mode" yourself, just by running Tribller with `TSTATEDIR=.\" environment variable. Currently, there should no absolute paths are created by default in Tribler config files, so the thing should just... work? (except for the GUI settings, which are always stored in QT-managed system store which is specific to the platform).

**Comment by qstokkink** [comment]
> [...] the thing should just... work?

I believe this is the case. Even the GUI settings should be part of the portable config now (since #8102, scheduled for Tribler 8.0). Therefore, this issue should be finally resolved now.
