### ISSUE TITLE
Token balance decreasing while ONLY seeding!

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#3928]
- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.
Oct 2nd 2018
##### Tribler version/branch+revision: #####
7.1
##### Operating system and version: #####
WIndows 10 17763 1809
##### Steps to reproduce the behavior: #####
Start Tribler and ONLY seed!
##### Expected behavior: #####
While seeding and obly giving token balence should increase
##### Actual behavior: #####
it decreases

**Comment by qstokkink** [comment]
Right now the payouts are as follows:

| Peer | Payout |
| --- | --- |
| Hidden seeding Tribler user | ![#c5f015](https://placehold.it/15/c5f015/000000?text=+) |
| Plain seeding Tribler user | ![#c5f015](https://placehold.it/15/c5f015/000000?text=+) |
| Other users | ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) |

Since we do not refuse upload to non-Tribler users, there will be no payout and thus you will lose tokens to non-Tribler users. We should probably create the option to only seed to other Tribler users.

**Comment by Thomasedv** [comment]
Could you elaborate a bit on what it costs a Tribler user to upload? I'm not quite sure i understand how uploading is a cost. (And why it should be, even to non-tribler users)

**Comment by qstokkink** [comment]
@Thomasedv this is regarding anonymous downloading/seeding:

We set up Tor-like *tunnels* to anonymize your traffic. Our bandwidth tokens are based on the amount of bandwidth you send over these tunnels. When you send any traffic over such an anonymizing circuit you pay those who helped you anonymize your data. However, because this is anonymized, we cannot distinguish between downloading and uploading a torrent; both downloading and uploading is simply data sent through the tunnel, which you pay for.
This situation changes if the uploader and downloader are both Tribler users. In this case we can properly forward payouts along the circuit, such that the downloader pays the uploader (and all of the intermediate tunnel peers).

**Comment by markx** [comment]
That makes sense, but I think it'll be nice to at least make this clear in the UI.

**Comment by devos50** [comment]
@markx We have added an info tooltip to the user interface in a recent commit, which explains the payout mechanism.

**Comment by qstokkink** [comment]
@devos50 can we close this issue then?

**Comment by devos50** [comment]
Yeah, this issue is also discussed in #3778.

**Comment by Nubro01** [comment]
Hi,

Ik zag dat er op het Forum de nieuwe Ttribler 7.2 stond, maar is er ook een nieuwe jenkins download locatie?

Ro
