### ISSUE TITLE
Enhancing the block explorer at explorer.tribler.org

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4000]
- [ ] caching of results, scale to many visitors
- [ ] highlight new results. This is a great real-time feed, but updates to the list should flash briefly or given another subtle emphasis
- [ ] explorer.tribler.org and statistics.tribler are merged to 1 infrastructure

**Comment by devos50** [comment]
Congrats on issue 4000! 🎉 

Also, we should fix the bug in the 'recent blocks' section which shows blocks in the future.

**Comment by devos50** [comment]
The block explorer crawler is close to dying (requests take a very long time to complete) and seems to be heavily overloaded. I suspect that the SQL query to build a map with all missing blocks takes a significant amount of time to complete. We should disable that one and see whether things improve.

**Comment by devos50** [comment]
Fun fact: here is a _very_ small part of the current TrustChain visualisation. It shows only a few nodes but there are edges are all over the place. Note that the well-connected nodes are regular users, and not exit nodes.

![schermafbeelding 2018-11-22 om 18 06 36](https://user-images.githubusercontent.com/1707075/48916147-796a4680-ee81-11e8-891d-2e109ed3ed31.png)

**Comment by synctext** [comment]
Insightful, calling it "entanglement of trustchain" seems to not do it justice. Something like massively cross-connected web-of-transactions. Or for Elon-Musk-age Javascript generation: giga-connected DAG.

**Comment by devos50** [comment]
To improve loading speeds and significantly reduce disk I/O, I've added an index to the `block_timestamp` and `block_hash` fields. This increased the storage requirements of the TrustChain database with around 7%. This change has been deployed on the TrustChain crawler. Whether this will go in production, is open for discussion, since these indices are only helpful for database queries performed by the crawler.

There are however still a few open issues regarding the explorer:
- [ ] sanitize recent blocks overview by including the current time as parameter. All blocks created after this timestamp, will be ignored (with a small threshold).
- [ ] cache the statistics page. This query is heavy since it involves a `GROUP BY`. This one can probably be stored in memory and updated when we receive a new block.
- [ ] fix or remove the visualization; this image is getting too big.

**Comment by synctext** [comment]
After our discussion and recent nice progress...:

Crawlers can hammer our clients. We want to avoid two or more crawlers requesting the same Trustchain data. We need to avoid this! Can we create a scalable never-request-twice crawler infrastructure? It should also not miss blocks.

Seems we will ddos our own network if we would have, say, 16 servers who all try to collect Trustchain blocks at full speed. We can limit this to 1 or 2 crawler, to lower the network burden. However, what we really need is a parallel crawler with a single shared datastructure of 'recent visited' peers. That single crawler could run on a dual 12-core Xeon machine and easily keep up with 1 million concurrent Trustchain producers. Or should we have shared 'already collected Trustchain records'? 

Design ideas. The multi-threaded or multi-process crawlers would share a single read-only 'recent visited' list of peers to avoid for load balancing. Each crawler thread would publish such a list and have read-only access to the others. By making this recent visited log 'append-only' with timestamps we can avoid the need for much locking complexuty hopefully. Or ring buffer usage, as we need only fixed size lists? Or single shared append-only datastructure for all crawlers where for each public-key seen and each possible Trustchain block sequence number we have a 0, 1, or NULL (peer not yet seen before).

Thoughts?

**Comment by devos50** [comment]
I just made a few QoL fixes to the explorer.

> Can we create a scalable never-request-twice crawler infrastructure? It should also not miss blocks.

Especially the last part is hard, due to the large amount of churn in our network. Although we are pushing each new block to 25 users around us, our crawler is only interested in blocks of the peer it is currently crawling. This means that the crawler might miss out quite a few blocks. Having parallel crawler that are active in different parts of the network would help with this.

> Design ideas. The multi-threaded or multi-process crawlers would share a single read-only 'recent visited' list of peers to avoid for load balancing.

I was thinking about something similar, where we have a 'central coordinator' that keeps track of all peers that are visited, _and which crawl requests have been performed_. This avoids multiple crawlers to send the same request to peers. Engineering this would take some time and requires robust communication between different processes. I will think about it.

**Comment by qstokkink** [comment]
You could probably use the dht to keep track of the latest block per peer and see if the crawler has it.

**Comment by qstokkink** [comment]
Trustchain has been removed and, therefore, this issue is no longer relevant.

I am quite amazed that our explorer is still online though.
