### ISSUE TITLE
Incorrect torrent upload/download ratio

### ISSUE THREAD

**Issue by yuliaSharabi** [Tribler/tribler#4161]
##### Tribler version/branch+revision: #####
v7.1.5
##### Operating system and version: #####
Ubuntu 16.4
##### Steps to reproduce the behavior: #####
Create 3 movies in the downloads
Ratio just decreasing , I started today with -6.1 and it decreased to -6.3.
Is there any settings I need to apply to make it seed? What am I doing wrong? I've read your Wiki page and searched in the issues but yet don't understand what is wrong :(

![51497795-f0ae4f00-1dcc-11e9-812a-b63f0093dad8](https://user-images.githubusercontent.com/1707075/51521542-2a13a880-1e27-11e9-9e93-5028be0da0c8.png)

**Comment by yuliaSharabi** [comment]
Hi, thanks for quick response.
Well, all of them are finished downloading for more than 24 hours. No seeding at all.(checked it when clicked on the token balance icon)
![image](https://user-images.githubusercontent.com/22341165/51552255-dd58bd80-1e78-11e9-8474-4eb5d4081a1a.png)

The last one (let's call it #3) is tucked on Streaming for more than 24 hours. ration for 24 hours still -6.3. I'd like to help you understanding the bug root cause.(I am a QA) Let me know which info you are missing.

**Comment by wkrick** [comment]
I'm seeing the same problem.  I have a bunch of torrents that are actively seeding but the ratio is stuck at zero.  The weird thing is that if you just stare at them for a while, you sometimes see the ratio change for a split second, then it goes back to zero.  I let them seed for days but I still stay deeply in the negative token-wise.  I suspect a bug somewhere.  Let me know if there's any information I can provide that will help with the debugging.  Here's a screenshot of active seeds with a zero ratio...

![image](https://user-images.githubusercontent.com/10203734/51790249-84cb3e00-2160-11e9-90fa-2774ee64d2e3.png)

**Comment by wkrick** [comment]
I downloaded two more torrents since my last comment.  One is just under 1GB and the other is just under 10GB.  The 1GB is completed and seeding, the 10GB one is about 70% complete.  My token balance went from -20.9GB to -64.2GB (and climbing).  That's a change of nearly 44GB for downloading 11GB.  Is this working correctly?

**Comment by devos50** [comment]
@wkrick that totally depends on the number of hops you are using for anonymity. By default, you are using one hop for downloads. According to your screenshot, you are downloading with three hop anonymity which is quite expensive (you pay 5x for the bandwidth being used). That should explain your quickly decreasing balance. In 7.3, we will release a fix where one would sometime lose balance even without downloading something.

**Comment by qstokkink** [comment]
Hmm.. it seems like the ratio is calculated from the `libtorrent` information. We might not be able to fix this in our codebase:

https://github.com/Tribler/tribler/blob/15e21f64eda8963be7ec5157b8b6115313869385/Tribler/Core/DownloadState.py#L114

**Comment by devos50** [comment]
We did some investigation of this issue. The ratio is computed from the `all_time_upload` and `all_time_download` fields, whereas the numbers shown in the torrent details pane are derived from `total_upload` and `total_download` in a `torrent_status` object.

We should keep track of *all* bytes being uploaded and downloaded since these are the bytes you actually pay for if you are using an exit node. So this includes communication overhead which does not directly include "useful" traffic (where you exchange pieces with others). One workaround for this is to manually keep track of all bytes exchanged in a libtorrent download, by using the `total_upload` and `total_download` fields. These values can be written away during checkpointing.

This issue is a bit more involved than we thought and at this point, it might not be a good idea to make changes to the way we manage data reported by libtorrent. We will fix this later.

**Comment by Nubro01** [comment]
On the current 7.3 the problem is also there!
![afbeelding](https://user-images.githubusercontent.com/1146496/54191137-95880700-44b5-11e9-8122-2c0261e64585.png)

**Comment by ichorid** [comment]
Let's discuss mining-related problems in #4363
