### ISSUE TITLE
BSc Seminar 2019: Survey of existing smart contract platforms

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#4239]
### Towards extreme smart contract parallelism

Smart contracts are a new execution model for applications that run on top of a blockchain. They allow developers to write business logic that enforces agreements between two or more parties, without trusted intermediaries like notaries. Smart contracts can reason about money and assets. Currently, there are several thousands of contracts deployed on the Ethereum blockchain, some of which manage assets worth billions of dollars.

Despite all hype, traditional blockchain fabrics like Ethereum have poor transaction throughput. For example, the performance of Ethereum is theoretically limited to around 23 transactions per second which is by far not enough to host all financial applications in the world. In fact, some applications like Cryptokitties have been popular enough to slow down the entire network and significantly increase transaction costs. This motivates the search for solutions with higher throughput and performance.

A more fundamental approach to improve the throughput of blockchains is to rely on different organisations of the blockchain. TrustChain is an Internet-deployed blockchain, designed and implemented by Delft University of Technology. TrustChain currently contains over 11 million transactions, created by over 10.000 unique users. The TrustChain fabric achieves superior transaction throughput compared to Bitcoin and Ethereum by deploying a different security model. TrustChain enables parallel execution of transactions, in contrast to traditional blockchains.

The goal of the literature survey is to conduct a survey of existing smart contract fabrics and report on them. You will learn how smart contracts work exactly and compare different approaches to run these contracts on blockchains.

**Comment by devos50** [comment]
Suggested literature for next meeting:
- [The original Bitcoin paper](http://www.academia.edu/download/54517945/Bitcoin_paper_Original_2.pdf)
- [Basic explanation of Ethereum](https://blockgeeks.com/guides/ethereum/)
- Please find related work to Ethereum (e.g. other platforms to run smart contract code).

**Comment by ikdekker** [comment]
@devos50 The link to the Bitcoin paper is broken (404). Is [this](https://bitcoin.org/bitcoin.pdf) the paper you tried to link?

**Comment by devos50** [comment]
@ikdekker yes

**Comment by ikdekker** [comment]
## BSc seminar - Meeting notes 22 february 2019
### Discussion
We discussed that the members of our group are not familiar with blockchain technology. Because smart contracts is a more advanced topic, it was decided that the group would have to do some research and see if this would be a good fit. Therefore, the students will decide the topic of the paper prior to the next meeting. It was also agreed on to get more familiar with blockchain (and Ethereum in specific) and Mr de Vos recommended us some papers to read. In addition to this, we will also find literature related to blockchain and possibly related to our chosen topic.

### Points of action
- decide on research topic
- familiarize ourselves with blockchain technology
- gather and read related literature

**Comment by ikdekker** [comment]
A topic we could be researching is the way smart contracts can be used to replace existing technologies or create decentralized constructs. For example, how Ethereum could be combined with a system like IPFS to store larger files to create a network which offers certain services.

Papers/topics I have read about so far are: the bitcoin paper, the way Ethereum works, PoS implementations (and the nothing at stake theory). I have also looked into different smart contract blockchains, like EOS, Stellar and Codius (smart oracle?).

**Comment by devos50** [comment]
See #3488 for the seminar project last year.

**Comment by devos50** [comment]
Further reading:
- Zheng, Zibin, et al. "Blockchain challenges and opportunities: A survey." Work Pap.–2016 (2016).
- Atzei, Nicola, Massimo Bartoletti, and Tiziana Cimoli. "A survey of attacks on ethereum smart contracts (sok)." International Conference on Principles of Security and Trust. Springer, Berlin, Heidelberg, 2017.

**Comment by devos50** [comment]
For next meeting:
- Please read the literature I linked and dive into the other literature regarding smart contracts.
- Please come up with a few possible research questions regarding smart contracts, i.e. their applications.

**Comment by joasiee** [comment]
Meeting notes:

Discussion researched subjects:
- Smart contracts
- Proof of x
- Dao hack
- EVM not capable of non-determinism, no random number generator
- timestamps unreliable
- smart contracts not capable of interaction with real world, oracles can be implemented to do this

Workload:
- Our own responsibility to distribute evenly

Paper:
Goal of the project:
- Smart contracts survey
- What are possible applications of smart contracts?
- Smart contracts in conjunction with IPFS?
- smart contract application fields:
  - energy trading
  - betting (poker, blackjack, sport betting, etc)
  - digital voting

TODO;
- set up github repository for sharing of papers/documents/etc
- Start with intro paper
  - goal of the paper
  - explanation of smart contract
- come up with 1 or 2 research questions
- read paper from last year: https://github.com/Tribler/tribler/issues/3488
- read https://github.com/Tribler/tribler/issues/4239#issuecomment-468248738
- do more research on our own

POSSIBLE:
- overleaf integration with github for the paper?
- scrape coinmarketcap to gather data?

NEXT MEETING: Friday 8th of March, 13:00, same building and room

**Comment by ikdekker** [comment]
These are all meeting agendas and minutes (so far).
[Meeting agenda 22 feb.docx](https://github.com/Tribler/tribler/files/2918946/Meeting.agenda.22.feb.docx) and the [minutes](https://github.com/Tribler/tribler/issues/4239#issuecomment-467128575)
[Meeting agenda 28 feb.docx](https://github.com/Tribler/tribler/files/2918947/Meeting.agenda.28.feb.docx) and the [minutes](https://github.com/Tribler/tribler/issues/4239#issuecomment-468251914)

**Comment by ikdekker** [comment]
This [repo*](https://github.com/ikdekker/bsc-smart-contract-research) contains our research.
*We have not yet added our resources/papers.

**Comment by ikdekker** [comment]
## Meeting minutes - 8 march


### Progress since previous meeting

Since the previous meeting the student have read and gathers some more papers.
Mostly on the applications of smart contracts. A IEEE two-column style paper was
set up. As well as a GitHub repo where progress is kept and papers are
collected.

### Research question
 
There was a choice between technical or conceptual research question.

Technical would be interesting, as we can create our own piece of software ontop
of Trustchain. This would also benefit our grade.

If we choose to implement:  
Build on TrustChain -> create a transaction people can execute with python code
uploaded to it and save the statechange on the chain. This would be a "new"
implementation, parallelized smart contract.

**Current research question**  
How can we trustfully execute code in a decentralized environment?

This research question has been decided on because we can partially combine the
results with the implementation mentioned before.

*Problem statement*: running programs from an untrusted source could mess up
your system.

### Other possible research directions

*Scalability was advised against, has been done last year.

**MSc student (Michel) master thesis: dApps**  
He is working on distributed applications (dApps) and creating a platform to
download/deploy packages in a distributed way. There is no ecosystem for dApps
and distributed package management. A possible research direction would be a
survey of the existing ecosystems and surrounding areas. This idea was mostly
dismissed since it has little blockchain/smart contract relevance.

Michel also guides a group of honour students. 
They research decentralized system: Agreements for legalized signatures.
Onderteken.nl is service to upload a document and sign it with a personal
signature. Ensuring that some contract is signed, this is trustable since the
signing is non-retractable. The goal is to remove the single point of trust, eg
a notary and eventually replace notaries with digital systems. It is hard to
create a legal system digital that is accepted.

They are also to do this without global consensus, which is a challenge since
the whole network should be aware of document states.

**MSc student (Jetse): scaling and voting system**  
He is working on a consensus mechanism, where witnesses are chosen. It is
possible to calculate the probablility of malicious entity. There are very small
chances for malicious nodes to "hack" the system.


### Todo:

Read about new execution environments (and how it applies on trustchain).

Check out some interesting implementations:

- Docker is a good example of contained code execution.
- HyperLedger vs Ethereum, how are programs verified.
- Intel SGX

### Deadlines / goals:

- create sub-questions and assign them (today)
- we will write ~2 pages before next friday
- we will complete our draft before two weeks from now (22/4).
- [optional] attempt to set up the IPV8 environment (Linux environment is advised)


### Useful for the students:

- [IPV8](https://github.com/Tribler/py-ipv8) - Link a TrustChain project, which we could set up as preparation for implementing the smart contract on TC. 
- [TU WRITE course](https://brightspace.tudelft.nl//d2l/home/63835) - Good and complete guides and information on writing all parts of the paper.

**Comment by JetseBrouwer** [comment]
Just casually dropping this here: [Malicious code execution in solidity by sprinkling some well arranged inline-assembly in the constructor](https://www.youtube.com/watch?v=WP-EnGhIYEc)

**Comment by devos50** [comment]
Current three-page draft:

[BSc_2019_Smart_Contracts(1).pdf](https://github.com/Tribler/tribler/files/2977708/BSc_2019_Smart_Contracts.1.pdf)

**Comment by ikdekker** [comment]
@devos50

We would like to send in another draft of the paper today or tomorrow and would like to know when we could send one.

Since our peer review deadline is friday, it would be good to have a meeting before then. Are you available tomorrow (thursday) or friday? If so, we will upload our paper for review.

We are available tomorrow and friday at lunch (around 13:00).

**Comment by devos50** [comment]
@ikdekker I'm also available tomorrow. I can give some feedback during the lunch then.

**Comment by ikdekker** [comment]
@devos50
Alright, we will meet you at the regular building & room. We will try to finalize the draft of this version today.

**Comment by ikdekker** [comment]
Second draft (same as the version emailed to @devos50 ): 
[2019-03-21 Bachelor_Seminar_Paper.pdf](https://github.com/Tribler/tribler/files/2991256/2019-03-21.Bachelor_Seminar_Paper.pdf)

**Comment by ikdekker** [comment]
[The meeting docs comment](https://github.com/Tribler/tribler/issues/4239#issuecomment-468613418) has been updated for the meeting this afternoon.

**Comment by ikdekker** [comment]
@devos50 Just a quick inquery of your opinion on the structure overview in the introduction. Since we have to mention the subquestion, would option 2. suffice? Or should we stick with 1. and add subquestions before the structure?

**1. original section reference**
To  answer  the  question  ’How  can  we  trustfully  executecode in a decentralized environment?’(section VII) this paper is  broken  up  into  a  few  parts.  First  the  term  decentralized computing  will  be  discussed  (section  II).  Then  a  general discussion  of  security  (section  III)  is  given  as  this  is  closelyrelated  to  trustfully  execution  code  (section  IV.  Once  the definitions  are  out  of  the  way,  an  overview  of  the  existing environments  is  given(section  V),  followed  by  an  evaluation of  these  techniques  for  decentralized  environments  (section??)

---
**2. possible section reference**
To answer the question ’How can we trustfully execute codein a decentralized environment?’ this paper is broken up into a few subquestions:

1)  What is decentralized computing? (section II)  
2)  What constitutes security? (section III)  
3)  What does Trust mean with respect to code execution?  
4)  What   Trusted   execution   environments   are   currently available? (section??)  
5)  How does this translate to distributed environments?

**Comment by ikdekker** [comment]
## Meeting minutes - 21 march


### Feedback

The paper should be readable/clear from just reading the section titles.

We should add boinc and gollem as important decentralized computing.

keywords -> computation, trust, blockchain, security, (1 more, should search and look at related papers)

The introduction should now be changed to be about the increasing amount of code run with its complexity and dependencie, making a trusted and secure execution environment necessary.

### Research question + sub questions

we should add the sub-questions in a manner that they are clear questions connecting to the different sections. They can be in the introduction.

research question: 'How can we execute code in a secure and trusted manner?'

sub questions: 
 - 'How can we securely execute code?'
 - 'How can we trustfully execute code?'
 - 'What are the applications of secure and trusted code execution?'    

 In the applications we should create a table with some different metrics to make easy comparisons between different implementations. The strengths and weaknesses of each individual implementation do not need to be explained however we should compare the strengths and weaknesses of the different techniques used.

### methodology

The methodology just needs to be mentioned not described with a large diagram.

### related work:

changed by changing the question

### British English?

It does not matter if British English or American English is used in the paper.

### TODO

For tomorrow we should make sure the paper has a correct structure and is ready for the pear review.

**Comment by ikdekker** [comment]
@devos50 Yesterday was the peer-review deadline. We have tried to process yesterday's meeting notes (see comment above) as much as possible. This is the version we have turned in:  
[TI3706_2018_19_Q3_paper_25.pdf](https://github.com/Tribler/tribler/files/2999247/TI3706_2018_19_Q3_paper_25.pdf)

**Comment by ArnoutvdKnaap** [comment]
@devos50 We are currently working on processing the feedback received. We should have this done tomorrow. At this time a link to the pdf will follow. Would you like to meet during the lunch break on Thursday or Friday?

**Comment by devos50** [comment]
Good to hear. Let's do Thursday during the lunch 👍

**Comment by ikdekker** [comment]
@devos50 here's our provisional paper.

[BSc_2019_Smart_Contracts.pdf](https://github.com/Tribler/tribler/files/3039311/BSc_2019_Smart_Contracts.pdf)

**Comment by ikdekker** [comment]
Here is the meeting agenda for later

[Meeting agenda 4 april.docx](https://github.com/Tribler/tribler/files/3042919/Meeting.agenda.4.april.docx)

**Comment by ikdekker** [comment]
## Meeting minutes - 4 april
10:45 until 11:45 presentation 18th of april

Group decided to not do the implementation.

#### TODO
Process feedback and finalize paper, and send it to Martijn for a last review.

#### Feedback paper
The paper needs to have some examples of real world applications of the techniques the paper talks about.

Paper should read more fluently, so structure should be improved and the chapters should flow more naturually.

Abbreviations should be introduced in the paper, for example it is never explained that VM stands for Virtual Machine.

Citation should implemented as: as Author states (citation) …

Software has become fundamental to our daily lives should be cited.

“Contemporary” not modern word so better find another word.

“Sub questions” should be changed to “sub-questions”

Change "preliminaries" name to "trusted execution"

Sub conclusions should be called summary

Latex for picture instead of begin{figure}[h] begin{figure}[t]

Conclusion or summary should be under every chapter for consistency reasons

**Comment by ikdekker** [comment]
Since we most likely won't have any more meetings, [this comment](https://github.com/Tribler/tribler/issues/4239#issuecomment-468613418) can be used as a summary of our progress. I might update this comment with the final version of the paper soon, too.

**Comment by ikdekker** [comment]
@devos50 

The deadline is approaching fast and we have implemented the feedback you have given. Some additional data was added to the paper and some parts were rewritten. We would appreciate it if you could review our paper for the final time.

Sections that have improved/changed the most:

- Abstract/intro
- Chapter
- Section V-B
- Section VI
- Conclusion

[BSc_2019_Smart_Contracts (2).pdf](https://github.com/Tribler/tribler/files/3057786/BSc_2019_Smart_Contracts.2.pdf)

**Comment by ikdekker** [comment]
@devos50 
Have you checked our paper out yet, or are you planning to do so before tomorrow (deadline)?
This is the latest version:
[BSc_2019_Smart_Contracts (3).pdf](https://github.com/Tribler/tribler/files/3063489/BSc_2019_Smart_Contracts.3.pdf)

**Comment by devos50** [comment]
Not fully reviewed yet, quite busy with my own paper.

Some feedback already:

Abstract:
- try to avoid the quotes in the abstract
- It sounds like the development of TEEs is initiated by companies that have to deal with malicious software. Isn't this field bootstrapped by scientific research?
- Write in active voice (e.g. a survey has been realised -> we present a survey).
- By looking at is slightly informal, maybe say "By exploring ..." ?
- The sentence that starts with "In this paper, security..." seems a bit off?
- "of a new system" -> "new systems"
- The last part of the abstract seems to be unfinished.

(I will update this comment with more feedback)

**Comment by devos50** [comment]
More (high-level) feedback:
- Please improve the caption of table 1, and make the header row of the table bold text.
- The first sentence of Andix OS is informal.
- reference 20 formatting seems off

**Comment by ikdekker** [comment]
@devos50 Thanks for the feedback and good luck with your own paper 😄

**Comment by ikdekker** [comment]
[Final version of the paper](https://github.com/Tribler/tribler/files/3069693/BSc_2019_Trusted_Computing.pdf)

**Comment by ikdekker** [comment]
[Final version of the paper](https://github.com/Tribler/tribler/files/3069693/BSc_2019_Trusted_Computing.pdf)

**Comment by devos50** [comment]
This work has been finished and graded.
