### ISSUE TITLE
Gossiping torrent popularity to scale to millions of torrents

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4256]
A Tribler Giga channel can scale to billions of torrents (https://github.com/Tribler/tribler/issues/3971) and is shared in the network, however the health of the torrent (being a dynamic value) is not included in the channel and is not propagated. This leads to having access to large number of torrents but without information if it is alive or not. So, we need a mechanism to share the health of the torrents in the Giga channel so popular content gets to the surface so users can browse through them.

To find out the popularity of the torrents in the Giga channel and to dissiminate the popular torrents in the network, we start with a simple approach based on random selections.

Some key points:
- Do DHT health check for a random torrent every 4 mins ?? No need to store the metainfo.
- Do only weekly update of the torrent
- Gossip *daily* top 5 and random 5 torrents that you have *checked* and are *alive*.

After the first deployment, we will know how well the random approach works and the optimizations can follow.

**Comment by qstokkink** [comment]
https://www.tribler.org/IPv8Datasync/Results/

**Comment by devos50** [comment]
First initial results of a DHT lookup experiment to establish the amount of traffic it takes to do torrent lookups. In this small experiment, I do multiple lookups of random torrents in an academic dataset using the torrent health endpoint of Tribler (nothing else is running). After every lookup, I query how much bytes the DHT in libtorrent did process (both incoming and outgoing) using the `dht.dht_bytes_in` and `dht.dht_bytes_out` fields provided by a libtorrent session. The following graph shows the lookup ID on the horizontal axis and the bytes uploaded/downloaded on the vertical axis, in KB.

![dht_lookup_exp](https://user-images.githubusercontent.com/1707075/53423720-23f28800-39e2-11e9-8c45-a1c8fc2dcc48.png)

After 156 lookups, it takes on average 930 bytes of incoming data and 1159 bytes of outgoing data per DHT lookup. I do not expect this number to change much.

Regarding CPU usage during these lookups, it differs between 5% and 10%.

**Comment by devos50** [comment]
Tomorrow I will plot all possible statistics regarding DHT traffic and try to figure out why the traffic increases. A possible solution is to reset the DHT session after a specific amount of lookups.

**Comment by devos50** [comment]
Findings so far:
- *Getting accurate health information from an info hash only is hard.*
- Our current way to get torrent health data, based on the information in the libtorrent DHT, is as follows: start downloading the torrent with the speicific infohash in upload mode. As soon as we have received the metadata from the DHT, we take a snapshot of the current list of peers we are connected to, and remove the download. This will only report (a select number of) peers in the swarm and does not consider seeders. I've tested this manually.
- The `get_peers` method seems to be exposed. My next step is to try and use this method to get peers that are actively seeding the torrent. This also avoids that you join the torrent swarm.

**Comment by devos50** [comment]
Update: I managed to get the peers from the DHT. Now we should find a way to classify them as seeder or leecher.

**Comment by qstokkink** [comment]
#109

**Comment by devos50** [comment]
@qstokkink thanks for the links!

**Comment by devos50** [comment]
I performed 1300 BEP33 lookups with the modified libtorrent code (see #4321 for details).

Some results:

**Message sent and received**

![message](https://user-images.githubusercontent.com/1707075/54531824-83f7a100-4986-11e9-9259-987336f2e31e.png)

Here we plot the statistics on messages being sent and received in the DHT, as reported by the libtorrent session. Note that there are many outgoing `get_peers` messages which is not unexpected since we are doing DHT lookups frequently. Also, we receive numerous incoming `get_peers` message.

**Bandwidth usage**

![bytes](https://user-images.githubusercontent.com/1707075/54532344-d7b6ba00-4987-11e9-9da2-7d5d4f852758.png)

Note how BEP33 does not require any libtorrent session bandwidth, outside for the DHT traffic. Since we are not actually joining the swarm, libtorrent does not have to maintain connections to other peers, only to DHT nodes. The bandwidth uses increases roughly linear and there seems to be no additional bandwidth overhead after each lookup.

After 1300 lookups, each lookup requires **13266 bytes (13.0KB)** of incoming traffic and **10731 bytes (10.5KB)** of outgoing traffic. In total, each lookup requires **23997 bytes (23.4KB)**. Most of the traffic is probably related to the bloom filters being sent around. These bloom filters are 256 bytes and there are two of them in each incoming `get_peers` response.

**DHT statistics**

![statistics](https://user-images.githubusercontent.com/1707075/54532735-d043e080-4988-11e9-94d7-112a247ed92f.png)

We now plot several statistics of the DHT, like the number of nodes in our routing table and the torrents tracked. The number of peers tracked remains around 100. The number of nodes in our routing table quickly increases after startup to around 400. We do no track mutable/immutable data items.

**Dead torrents**

Of the 1300 lookups, **823 torrents** did not have any seeders and they are considered dead (**61.9%**).

**Conclusions**

I think we should implement BEP33 lookups in Tribler. The tradeoffs are as follows:

Advantages:
- It is a relatively easy method to estimate the size of libtorrent swarms and the results are a reliable approximation of the real size since we can combine multiple bloom filters. I manually verified this by doing lookups for some very healthy torrents (1000+ seeders/leechers), dead torrents (0 seeders) and almost dead torrents (a few seeders and/or leechers). In all situations, BEP33 gave me reliable results.
- Results come in quick, usually a few seconds after calling `dht_get_peers`.
- BEP33 bloom filters are already filled by libtorrent and uTorrent implementations.
- We do not actually join the swarm when doing a health lookup and libtorrent does not maintain peer connections to others.

Disadvantages:
- It requires modifications to the libtorrent code. This means that BEP33 lookups are not supported in Debian, at least not until we support lookups in the upstream code (which requires a PR). We can however ship a modified libtorrent core on Windows and Mac (which accounts for 80-90% of our user base).
- We require a dedicated libtorrent session for these lookups and we have to manually decode every incoming DHT packet and extract the bloom filter out of it. This might influence performance.
- The size of the bloom filter (256 bytes) limits users to tracking at most 6000 seeders/leechers. I think this is not really a problem here since the difference between 10000 and 6000 seeders is not really impactful on the end user.

**Comment by synctext** [comment]
BEP33 for the win!
Given the scalability and bandwidth efficiency this is very useful. Finally we can make progress with relevance ranking through BEP33 popularity.

**Comment by devos50** [comment]
With #4434 and https://github.com/Tribler/gumby/pull/409, I consider the second iteration of the `PopularityCommunity` done. The algorithm is relatively simple: the overlay performs a random walk through the network. Every five seconds, you gossip at most 5 random torrents checked by you, and the top 5 torrents you have checked (based on seeders) to a randomly connected peer.

A new validation experiment has been added to verify the correctness of the popularity community. I plot the total number of torrents that have health information (based on the `last_check` field) over the duration of the experiment below. Note that torrent health dissemination only starts after 45 seconds (when the random walk in the popularity community starts). The slow start can be explained by the fact that peers do not have at least health information of five torrents to gossip around. The total experiment duration is two minutes.

![num_healths](https://user-images.githubusercontent.com/1707075/55230549-6f39c980-5220-11e9-8cde-b077746799c4.png)

I now think we should observe how this mechanism behaves in the wild.

**Comment by devos50** [comment]
I consider this issue appropriately addressed for the 7.3 release. As said before, we should observe how it works in the wild. Therefore I move this issue to 7.4 so we can re-visit and improve our torrent selection algorithm if necessary.

**Comment by devos50** [comment]
Since this issue is more leaning towards a full research project, I'm unassigning myself. My recommendations for the next steps:
- Further testing and better integration of BEP33 across all platforms.
- Setup a crawler to get some performance numbers from the deployed network, and iterate on these results.

Highly related to #3868

**Comment by synctext** [comment]
Would like to make this feature a key issue of a next release. Such as 7.6 "Bug Fix" and then: 7.7 "search&popularity".

**Comment by qstokkink** [comment]
The functionality of the OP has been implemented for several years now. Closing.
