### ISSUE TITLE
Regular checkpoint download/upload and ratio needed

### ISSUE THREAD

**Issue by Thatoo** [Tribler/tribler#4500]
##### Tribler version/branch+revision: #####
7.2.2
##### Operating system and version: #####
Ubuntu 18.04
##### Steps to reproduce the behavior: #####
[Computer freeze for any reason]
Reboot happen without closing properly Tribler
Open Tribler
Token Balance backed to last time Tribler has been opened
##### Expected behavior: #####
Tribler do checkpoint download/upload regularly, not only when closing
[Computer freeze for any reason]
Reboot happen without closing properly Tribler
Open Tribler
Token Balance is [almost] the same as when the reboot happened without closing properly Tribler (equal to last checkpoint0
##### Actual behavior: #####
Tribler don't do any checkpoint download/upload when open, only when we close it. So if any bug happen and the computer crash, when one open Tribler again, ratio of each torrent is back to what it was at last opening and Token balance too. All the download and upload ratio done between the last opening of Tribler and the crash are gone...

**Comment by devos50** [comment]
Thank you for your report!

> All the download and upload ratio done between the last opening of Tribler and the crash are gone...

This is due to a bug regarding persistence of upload/download ratios, most likely in libtorrent. We have to investigate this more, but until that time, we reset the ratios when restarting Tribler.

> and Token balance too

Checkpointing of downloads is independent of the token balance. The token balance, however, can change if you close Tribler (but this is not visible to you). Specifically, when closing Tribler, you will close all anonymous circuits and perform payouts for pending bandwidth tokens to other users. This might decrease your token balance the next time you start Tribler. Could this be an explanation for what you are observing?

**Comment by Thatoo** [comment]
You're welcome. If my report can help to improve Tribler, I'm happy I did.

About what you explain on Token Balance : could be it. I'm not sure to understand fully.

**Comment by ichorid** [comment]
In short, we need to save the torrents' state and tokens state regularly so only a minimum amount of information is lost in case of crash or sudden power loss.

**Comment by qstokkink** [comment]
The token balance has been removed from Tribler a while ago. Therefore, I'll close this issue.
