### ISSUE TITLE
Replace Twisted with asyncio?

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#4646]
What problem does this solve and how does this contribute to the long-term maintainability?
Mentioned within tech roadmap: #4566

**Comment by ichorid** [comment]
AFAIK, Twisted was the first successful attempt to add asynchronous programming into Python. The library became bloated over the years. `asyncio` moved the concept to the Python core, cleaning up the syntax along the way. There are even better alternatives to `asyncio` in the development now, like `trio` for example. Moving from Twisted to `asyncio` results in 2 times less code on average. Moving from `asyncio` to `trio` results in [10 times less code sometimes](https://www.youtube.com/watch?v=i-R704I8ySE).

The main reason for moving from Twisted is to make the code more comprehensible.

**Comment by ichorid** [comment]
From Trio's author:

"For example, consider the Happy Eyeballs algorithm ([RFC 8305](https://tools.ietf.org/html/rfc8305)), which is a simple concurrent algorithm for speeding up the establishment of TCP connections. Conceptually, the algorithm isn't complicated – you race several connection attempts against each other, with a staggered start to avoid overloading the network. But if you look at [Twisted's best implementation](https://github.com/twisted/twisted/compare/trunk...glyph:statemachine-hostnameendpoint), it's almost 600 lines of Python, and still has [at least one logic bug](https://twistedmatrix.com/trac/ticket/9345). The equivalent in Trio is more than 15x shorter. More importantly, using Trio I was able to [write it in minutes instead of months](https://www.youtube.com/watch?v=i-R704I8ySE), and I got the logic correct on my first try.

Basically, the guy claims to do for concurrent programming the same thing Dijkstra did for the regular programming: remove "goto" statements to create structured code. It is achieved in a very simple and obvious manner: any threads/coroutines/deferreds/futures, etc. can now only be spawned inside specialized context managers called "nurseries" (facilities for treating children :wink:), which are equivalent of basic blocks in structured programming. Now, nurseries are **guaranteed** to finish at the end of the current context, and catch all the errors produced by the children. That is super-cool and convenient, relieving the programmer of almost all headaches associated with treating "spaghetti-code" that is essentially result of using **any** modern async framework. 

Conveniently, Python 3.8 [copies that feature](https://twitter.com/1st1/status/1041855365745455104) by the name "cancel scopes" to work with `asyncio`

I don't mean that we should jump in the `trio` bandwagon right away, but replacing Twisted for something that keeps developers's sanity will be a welcomed change. Personally, I would prefer moving to a system that was designed for sanity from the beginnging, such as `trio`. However, if Python 3.8 will deliver the same sanity-keeping feature, we are better to move on to it to stay with the more mature solution.

**Comment by synctext** [comment]
Nice! What is the impact of requiring Python 2.8?

**Comment by ichorid** [comment]
We'll have to wait until 3.8 propagates to distros we support, like Ubuntu and Debian. I guess that will take about 1-2 months after 3.8 release. The release is planned for October of this year, so we can reasonably expect that by the end of the year we can move to it seamlessly.

Meanwhile, we can start migrating from Twisted to asyncio. When 3.8 lands, both our code and our team will be ready to introduce cancel scopes into Tribler and IPv8.

**Comment by ichorid** [comment]
All hail @egbertbouman !

**Comment by synctext** [comment]
All hail the King, killed 8,628 LoC. https://github.com/Tribler/tribler/pull/4967
![image](https://user-images.githubusercontent.com/325224/70691720-0e70f500-1cba-11ea-9f83-7abea8b96312.png)
