### ISSUE TITLE
Video player issue on reset

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4775]
Version: 7.3.0
Platform: Windows-10-10.0.18362-SP0
uptime: 58768.2129998 secs

```python
Traceback (most recent call last):
File "TriblerGUI\widgets\downloadspage.py", line 342, in on_remove_download_dialog
File "TriblerGUI\widgets\videoplayerpage.py", line 239, in reset_player
AttributeError: 'NoneType' object has no attribute 'stop'
```

Message from the reporter:

>I was setting up my channel and after I added some, I clicked on play within my channel. Player opened but nothing really happend after so I clicked on download and noticed Tribler is trying to download what I added to my channel. When I tried to remove it from download list the error occured.

**Comment by devos50** [comment]
Issues 26558, 26570, 26574, 26577 in the error reporter.

This seems to happen on different platforms, including Windows Vista. It seems to happen when removing a download that is currently being streamed. I guess this might be due to VLC. Checking whether the mediaplayer still exists probably addresses this issue.
