### ISSUE TITLE
Duplicate keys - Black

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4797]
```
Error: Could not open file /home/tribler/tudelft/tribler/pyproject.toml: 
Error reading configuration file: Duplicate keys! (line 6 column 1 char 131)
```

https://github.com/Tribler/tribler/blob/6c5a6b457f6af499795a64d6dbd7d0d2f70f0d0d/pyproject.toml#L1-L16

**Comment by devos50** [comment]
This might be helpful: https://poetry.eustace.io/docs/pyproject/#include-and-exclude

**Comment by ichorid** [comment]
Funny thing, my machine shows no error! I'll handle it, though.

**Comment by ichorid** [comment]
Now that was a little bit tricky. Buyer beware:
pre-commit hooks **stash** non-staged files before calling the hooks. That's why I didn't see the fail @devos50 did: pre-commit stashed the changes to `pyproject.toml` and ran the thing with the older version of it from my branch!

Fixed in https://github.com/Tribler/tribler/commit/f1f9331fb098c5edaccaa239e210a6db2be78eac

**Comment by qstokkink** [comment]
Please don't push directly to `devel`, always use PRs.

**Comment by ichorid** [comment]
@qstokkink , even in case of trivial single-line changes that do not affect the codebase, require no automated checking, and can't be checked/reviewed by anyone but the author?

**Comment by qstokkink** [comment]
Yes.

**Comment by ichorid** [comment]
:man_shrugging:

**Comment by synctext** [comment]
Also pushed tiny readme.md changes once directly to devel. Almost got my permissions revoked:-)
