### ISSUE TITLE
Failed to find libvlc - snap - fedora

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4804]
Failed to find libvlc in Fedora
![snap-build-fedora](https://user-images.githubusercontent.com/1442867/64341280-4c3ded80-cfe8-11e9-83c2-ffc6d8ada7aa.png)

Past issue: https://github.com/Tribler/tribler/issues/4418

**Comment by sksksksk** [comment]
I run into this today. I am on Ubuntu 19.10 and installed the snap package via
sudo snap install tribler-bittorrent --beta --devmode
tribler-bittorrent (beta) 7.3.0-beta1 from Sandip Pandey (sandippandey) installed

So it's still version 7.3.0
Installing with --edge gets the same version

Running tribler produces the same error mentioned in this issue

NameError: no function 'libvlc_new'

Would this be fixed in 7.5? How do I get this version via snap?

**Comment by synctext** [comment]
Sorry, we've focused on .deb packaging and have not updated snap for a while. We're understaffed, volunteers welcome. Both the .deb package and Tribler-v7.5.0.tar.xz sources are available here: https://github.com/Tribler/tribler/releases/latest

**Comment by sksksksk** [comment]
@synctext fully understandable. The problem with the deb package is that it requires the vlc package. For someone having installed vlc via snap, it results in having 2 vlc binaries. I'll se what I'm going to do.
Thanks for your great work

**Comment by ichorid** [comment]
RIP VLC
