### ISSUE TITLE
Triber update proposal is displayed when running that exact version from git

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#4838]
##### Tribler version/branch+revision: #####

v7.3.0 360172b579b2d2140d9bd675ed1804efd161a7f4

##### Operating system and version: #####

Linux

##### Steps to reproduce the behavior: #####

1. Update Tribler git repository to v7.3.0
2. Start `./tribler.sh`

##### Expected behavior: #####

No update proposal is displayed, or it proposes to update to at least 7.3.1.

##### Actual behavior: #####

![tv](https://user-images.githubusercontent.com/173219/64914138-d22f0680-d755-11e9-9dfd-deeacf00e19e.png)

**Comment by devos50** [comment]
This indeed happens when running Tribler from git. We do not actively keep the information in `version.py` up to date in the git repository (but we update this information when building a Tribler release).

To address this issue, I propose to simply not show the update dialog if the `version_id` variable contains `GIT`.

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/4833
