### ISSUE TITLE
Stop reading bootstrap SQL dump at each startup

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#4862]
Currently, we fully read and execute the bootstrap SQL dump at each startup. This increases the startup time (which is critical for a torrent client). Also, it puts unnecessary load on TrustChain SQL engine, which can potentially slow down other TrustChain-related startup sequences.

Instead, we should detect if the current bootstrap file has already been processed before, and only load the SQL dump if necessary.

**Comment by qstokkink** [comment]
We could turn this into a REST endpoint and have the GUI control when to perform the bootstrap SQL statement.

**Comment by devos50** [comment]
I suppose we will address this issue after the 7.5 release?

**Comment by ichorid** [comment]
For 7.5, we just disabled reading SQL from the bootstrap file. We can solve it later in 7.5.x or 7.6 series.

**Comment by ichorid** [comment]
By, Trustchain!

**Comment by devos50** [comment]
TrustChain is not gone yet and the bootstrap code is still there. We left it in since it will trigger bandwidth payouts which will make sure that you are connected to other users.

The content in the bootstrap file, however, is currently not being parsed. However, there are plans to address this soonish.

**Comment by ichorid** [comment]
:shrug:

**Comment by qstokkink** [comment]
This code seems to have been removed now making this issue no longer relevant.
