### ISSUE TITLE
Bootstrap.nodes - invalid mode ('wb') or filename

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4877]
```python
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <type 'exceptions.IOError'>: [Errno 22] invalid mode ('wb') or filename: u'C:\\Users\\hp\\AppData\\Roaming\\.Tribler\\bootstrap\\bootstrap.nodes'
lib\site-packages\twisted\python\context.py:85:callWithContext
Tribler\Core\APIImplementation\LaunchManyCore.py:565:sesscb_states_callback
Tribler\Core\bootstrap.py:82:fetch_bootstrap_peers
lib\site-packages\twisted\internet\defer.py:310:addCallbacks
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:653:_runCallbacks
Tribler\Core\bootstrap.py:72:on_success
Tribler\Core\bootstrap.py:87:persist_nodes
]
```
Report [#27758](http://reporter.tribler.org/stacktrace/27758)

platform.details Windows-7-6.1.7601-SP1
python.version 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40)
tribler_uptime 119.04399991

**Comment by ichorid** [comment]
The problem happens because of some kind of race condition because we write some `persist nodes` into a file. Using files as persistent storage that is subject to change at each run is a really bad idea, because of race conditions, file locking semantics, etc. There is a reason why databases use WAL and journalling.

We should eliminate the file writing altogether. If it is impossible, we should either use a separate SQL instance for this kind of info, or (the worst possible case), account for all kind of errors and race conditions that come with file writing.

@grimadas , could you please look into this?

**Comment by xoriole** [comment]
Fixed by https://github.com/Tribler/tribler/pull/4971
