### ISSUE TITLE
Enumerating iglob in for-each possibly not needed?

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler#4897]
- [x] I have read CONTRIBUTING.rst
##### Tribler version/branch+revision: #####
devel
##### Operating system and version: #####
All

In the following line there's an `enumerate` used

https://github.com/Tribler/tribler/blob/887bd0499b27b8850ea890ff49fe09a4a592e354/Tribler/Core/Upgrade/config_converter.py#L50

Reading the iglob docs for [py 2](https://docs.python.org/2/library/glob.html#glob.iglob) and [py 3](https://docs.python.org/3/library/glob.html#glob.iglob) indicates to me that it returns an iterator. Since the index isn't used and no further transformations are done on the `iglob` iterator itself, is it possible it was necessary to enumerate the iterator in the past but as it stands it may no longer be necessary? Or am I missing something?

**Comment by ichorid** [comment]
The reason was either some legacy code transition or something to do with threads. But `iglob` iterator is thread-safe. @devos50 what was the reason for this?

@Solomon1732 , you can change it to iterator and try it out for yourself. If there *is* a test for this, and it will not fail, assume it is safe to file a PR for the change. If there is *no* test for this, consider writing the test along with the proposed change (yep, that's not fair...).

**Comment by Solomon1732** [comment]
https://github.com/Tribler/tribler/blob/887bd0499b27b8850ea890ff49fe09a4a592e354/Tribler/Test/Core/Upgrade/test_config_upgrade_70_71.py#L80

@ichorid I can see that there's *a* test for the function in question, but I can't tell if it's one that checks the functionality in question... I think it does, but I'm not sure 😅

**Comment by Solomon1732** [comment]
Closing since #4902 fixed the bug
