### ISSUE TITLE
Play breaks Download

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#4899]
On 7.3.1 if you have a torrent downloading at 10% progress then press play on one of its files that is at 100%, the whole torrent will be set to 100% and change to "streaming" and the speed will drop to 0 B/s. (The file will play)
Stopping and starting the torrent has no effect.
Restarting Tribler then selecting all files in the torrent and including them resolves the issue.

Please rename "Play" to "Exclude others and Play"

**Comment by synctext** [comment]
Yes, this should really be fixed soon. Streaming needs a bit of love&refactoring. vaguely remember an existing open issue for this.

We need full state recovery. When pressing play: all active downloads and seedings go into: "Paused for streaming", "Exclusive Streaming" and "100%" is made into a proper buffer indicator. We don't know how many seconds we have in the playlist buffer; just MBytes. Somehow exposure this to user.

OR
we remove all this complexity that no user ever asked for. Streaming only switches piece picking. No unintuitive global pauze. If you want to download 40 files and stream 1 swarm, what should Tribler do? Just do what you ask perhaps.
How many days of work is this minimal and the above heavy refactoring?

When going into streaming mode we seem to drop all peer connections and Libtorrent does some internal reconfiguration. We really could use a "Hot Streaming Switch" and adjustment of piece picking algorithm. Not easy, needed in long term. In a decade we want to replace YouTube, right!?!

**Comment by devos50** [comment]
I agree that VoD streaming requires some serious attention. The state machine (and code) is complex and there are many edge cases which makes the whole mechanism unintuitive for end-users. We should first come up with a (basic and simple) design that specifies what happens if the user enters and leaves VoD mode. Don't we already have an issue for this BTW?

> We don't know how many seconds we have in the playlist buffer; just MBytes

This information could be computed from the video metadata. If I remember correctly, the metadata is contained in the first parts of the file, and the Matroska file format stores it at the end. This is why we first download the first and last 10% of the file in VoD mode.

> adjustment of piece picking algorithm.

I think this requires us to maintain/bundle our own version of libtorrent?

**Comment by devos50** [comment]
Shall we address this in 7.6?

**Comment by hbiyik** [comment]
Fixed in

https://github.com/Tribler/tribler/pull/5301
