### ISSUE TITLE
Future proof Windows builder

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4921]
Consider using this installer: https://github.com/jrsoftware/issrc (suggested by @devos50) The whole Python3, VC2008 runtime and 32-bit world will be different. Can it support all of our needs? NSIS installer scripts are ancient, but at least they work! 
_Inno Setup is a free installer for Windows programs. First introduced in 1997, Inno Setup today rivals and even surpasses many commercial installers in feature set and stability._

_Originally posted by @synctext in https://github.com/Tribler/tribler/issues/3259#issuecomment-538905073_

**Comment by ichorid** [comment]
For reference [the list of installation software](https://en.wikipedia.org/wiki/List_of_installation_software).

Basically, there are only three open-source alternatives:
* Nullsoft installer
* InnoSetup
* WiX (produces Windows Installer packages).

@xoriole , what advantages does InnoSetup offer over our current installer? What kind of problems it would solve?

**Comment by ichorid** [comment]
BTW, it would be really cool if we will push Tribler to Windows Store, to increase reach.

**Comment by Solomon1732** [comment]
Pushing Tribler to Windows Store would make it convenience for me as a user. Due not, however, that due to US laws regarding exporting and importing certain classes of software it might limit Tribler's capability in the Store. I would look into it deeper (I'm not verse in US legalese). I know it limits VLC's capabilities somewhat in the Store version because of this.

**Comment by qstokkink** [comment]
I think the discussion in this issue has now completed: we've investigated other software but we ended up with NSIS again anyway.
