### ISSUE TITLE
Trust statistics 2.0

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#4939]
Every now and then, our users raise the question about their token balance. Even with good intentions of running Tribler to help the community, they are labelled as selfish users (in Trust graph) because of their negative token balance where they have no idea how they got their balance in the negative.

We should provide answers to them with more details breaking down the balance represented in a clear GUI. 
Something like:
- **Downloaded (- MB)**
  - Torrents
  - Channels
  - Bootstrap
- **Anonymous seeding**
  - Tribler Users (+ MB)
  - Non-Tribler Users (- MB)
- **Relayed (+ MB)**

**Comment by Dmole** [comment]
1)
Would be nice to know when a build like V7.4.0-exp3 is going to scrap a token balance.
Maybe offer to backup the old data, so users can bring it down to 0 with an old version of the app.
Or maybe ban old versions of the app from the network as they are not playing by the same rules.

2)
V7.4.0-exp3 still calculated -ve token balance which is easaly reset by the user.

3)
I suspect the "Empty tokens" could be be reverted.

Still relevant;
https://github.com/Tribler/tribler/issues/3657

**Comment by Dmole** [comment]
Above linked bug report should not have been closed;
![WTF](https://user-images.githubusercontent.com/1793802/70760502-d00a2300-1d17-11ea-849c-dc27fecae962.png)

**Comment by devos50** [comment]
@Dmole are you only running Tribler and not downloading anything?

If Tribler runs idle (and you do not have anonymous downloads running), it will provide relay services to other peers in the network. This will result in a decrease of your balance since you first download (encrypted) data from others. However, you will relay this data, for which you will be rewarded with more tokens that you 'invested'. This is the reason why the 'bytes taken' and 'bytes given' show a similar pattern.

We should make this behavior more clear overall.

**Comment by Dmole** [comment]
Correct (as discussed in the linked issue).

"People who helped you" should be "Incoming data (including relay traffic)" because really I was not helped by that at all; got no data for myself, and token balance is reset regularly so that's not really a help either.

Also I find it improbable that more than one person on this small network happen to want the same data at the same time. The seed for others option is off so it's not like the data is cached in quantity, or for long periods of time.

and what's up with this?;

![WTF2](https://user-images.githubusercontent.com/1793802/70803582-63783e00-1d82-11ea-8b6e-af9e16f568b0.png)

**Comment by slrslr** [comment]
Confusion about Trust Statistics brought me there.
Since i installed Tribler a few weeks back i have not downloaded any torrent. This is what i see in Tribler 7.9.0:

![](https://i.imgur.com/UzhMpEv.png)

confusion: 25GB of downloaded data (that is quite alot...), one would ask how is that possible.

As i read @devos50 comment above the reason should be:
`"you first download (encrypted) data from others. However, you will relay this data, for which you will be rewarded with more tokens that you 'invested'"`
so i am helping other users improve their anonymity, that is what i want.

The description on that tab and question mark [tooltip](https://en.wikipedia.org/wiki/Tooltip) does not tell the user that "part of the taken and given data transfer is used to relay other people bittorrent traffic helping increase their anonymity while not exposing this computer IP (exit relay setting is disabled)." (if i understand correctly) so the sentence similar to that can be handy to be placed into the infobox opened under questionmark icon.

And maybe replacing:
This is done by letting run Tribler idle. -> This is done by letting run Tribler idle. Following figures includes also relayed traffic (?) (? = link to a tooltip box with a sentence (similar to one i mentioned above) explaining what it is or trigger same infobox as is under already used questionmark icon)

Btw. I am ABLE to find exit relay setting, but not regular relay setting, maybe it can not be disabled or bandwidth limitted, no problem, hopefully if i am on slow internet, this relay will not eat too much of the band-width.

**Comment by drew2a** [comment]
As we don't use trust calculation anymore and the trust graph was recently removed (see #7761), is this issue probably not relevant anymore? @xoriole
