### ISSUE TITLE
Set default anonymous level for channel seeding/downloading/updating

### ISSUE THREAD

**Issue by CrocodileCroco** [Tribler/tribler#4982]
When i download (subscribe) a channel, there is no option to do it anonymously, same for updating channel, you always need to go to the downloads tab and make it anonymous

You should be able to seed/dl/update channels anonymously

**Comment by ichorid** [comment]
Anonymous seeding of channels is pointless, because of how channel gossip works: you gossip subscribed channels, so **everyone** around you know what channels you are subscribed to. An open Channels system incentivizes people to only share links to legal and quality content.

Tribler is about providing *links* to information (i.e. infohashes), and *means* of downloading it without fear of spying by 3rd parties (e.g. nosy ISPs).

So, "anonymous channels" not gonna happen in the foreseeable future.

**Comment by snakyjake1** [comment]
If I understand correctly, if I create my own channel, then anyone can associate my IP address with my content?
