### ISSUE TITLE
Superfluous test in assertion

### ISSUE THREAD

**Issue by Solomon1732** [Tribler/tribler#5016]
- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Development
##### Operating system and version: #####
All
##### Expected behavior: #####
Not check if collection's length is equal or bigger than zero.
##### Actual behavior: #####
Assertion checks collection's length if it's equal or bigger than zero.

```
assert 0 <= len(self._prefix) < 256, len(self._prefix)
```
Note that it checks len >= 0, which is always true (len < 256 is of course fine).
https://github.com/Tribler/tribler/blob/devel/Tribler/community/market/core/bloomfilter.py#L132

**Comment by Solomon1732** [comment]
Looking more at the whole line it looks like the intention might be to check `0 < len(self._prefix) < 256`, but I'm not sure.

**Comment by Solomon1732** [comment]
I guess #5017 deals with this bug?

**Comment by devos50** [comment]
@Solomon1732 yes, you probably uncovered a bug in 14-year old code 👍 

Since the BloomFilter has moved to AnyDex, I removed the entire file. This is something that should be addressed in the [AnyDex repo](https://github.com/tribler/anydex-core) however, but I am thinking about removing the BloomFIlter functionality entirely, or use a library.

Currently I'm trying to fix the documentation issues (moving it to Python 3).

**Comment by Solomon1732** [comment]
To be honest it wasn't entirely me who discovered the bug. It showed up as a "major bug" in SonarCloud checks in #5014 . I merely brought it to light 😄

**Comment by devos50** [comment]
@Solomon1732 you can at least take some of the credits then ;)
