### ISSUE TITLE
Upgrade PR checkers to Python 3

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#5029]
The `Print statements checker` and `External import checker` PR checks are still running Python 2 and silently failing. We should upgrade these to work with our latest codebase.

In the process we might as well move the scripts themselves to https://github.com/Tribler/tribler-utils

**Comment by Solomon1732** [comment]
Minor comment on https://github.com/Tribler/tribler-utils :
Judging by the `xrange` in the repo ([here](https://github.com/Tribler/tribler-utils/blob/master/bootstrap_creator.py#L11)) it looks like it's written in python 2, or am I mistaken? Currently, though, due to its size it would be really simple to port it to python 3. That is, if it is desired.

I didn't want to open an issue there since the repo was mentioned elsewhere. I don't know if you have any intention to port the repo to py3

**Comment by qstokkink** [comment]
> looks like it's written in python 2

It's actually importing `xrange` from `six` for dual Python2/3 compatibility. As Python 2 support will formally be dropped in two days (!), I think it is safe to port it fully to Python 3.

Right now the `tribler-utils` repository is not used though. The PR tests are actually cloned from old Gists me and @devos50 made back in the day, for example: https://gist.github.com/qstokkink/0b1119bc458931d79b0402f80cf20749

**Comment by Solomon1732** [comment]
Tribler/tribler-utils#2 has been merged, and with it the migration of tribler-utils to python 3.

**Comment by devos50** [comment]
This issue has been addressed 👍
