### ISSUE TITLE
[7.4.2] /tmp/*tribler* should be cleaned up on exit

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5125]
[7.4.2] /tmp/\*tribler\* should be cleaned up on exit

**Comment by devos50** [comment]
Note that we only want this on a clean exit, and not when Tribler has crashed. Therefore, the GUI should notify the core somehow whether it should remove the log files in the `/tmp` directory (which can be done by adding an additional flag to the shutdown HTTP endpoint).

Since it has been like this for many years now, I will defer the issue to the 7.6 release.
