### ISSUE TITLE
[7.4.4] Version Manager can't handle missing modules

### ISSUE THREAD

**Issue by MeadowHillSoftware** [Tribler/tribler#5199]
##### Actual behavior: Pre-existing torrents not loaded, tokens disappear

When I first ran this version, I received an error message telling me to run "pip3 install pyasn1". I ran this command and received a permissions-related error so I ran "**sudo** pip3 install pyasn1". Tribler started successfully, but my existing torrents weren't loaded and my token balance dropped from ~800MB to 0MB.

I have since ran "sudo pip3 **uninstall** pyasn1" and installed the version of pyasn1 from the Manjaro repositories instead in hopes that would solve the problem but it hasn't. Any ideas?

**Comment by ichorid** [comment]
Thanks for reporting!
We introduced a forward-copying system to keep user's data safe during upgrades. 7.4.x series was the first Tribler series to use it. Apparently, the system can't handle crashes during the upgrade process itself.
One way or another, your data should be safe. You can revert to the previous version of Tribler that you used before, and that version should "pick" the correct directory. Then you can remove 7.4.4 state subdir and try upgrading again.

For more detailed information, please refer to [this wiki page](https://github.com/Tribler/tribler/wiki/Getting-back-your-Tribler-state-dir-after-update-to-7.4.2).

**Comment by ichorid** [comment]
I'll add a task for checking for this kind of situation in 7.5.

**Comment by MeadowHillSoftware** [comment]
According to version_history.json, my last version was 7.4.4. Arch linux had a 7.4.4-1 package and a 7.4.4-2 package. I currently have the 7.4.4-2 installed. I assume the previous package I had was 7.4.4-1. I only have a 7.4.4 folder in the .Tribler directory. I don't have any other version folders in there. Should I try to roll back to 7.3.2?

**Comment by ichorid** [comment]
Yes, you definitely need to roll back to your previous Tribler version by editing the version history file and deleting 7.4.4 subdirectory.

**Comment by MeadowHillSoftware** [comment]
Torrents still missing.

So I edited the version_history.json, deleted the 7.4.4 folder and cloned the 7.3.2 repository:

`git clone --single-branch --branch release-7.3.2 https://github.com/Tribler/tribler.git`

I received an error:

`Traceback (most recent call last):
  File "/home/user/MHS/tribler/TriblerGUI/event_request_manager.py", line 136, in <lambda>
    self.reply.error.connect(lambda error: self.on_error(error, reschedule_on_err=reschedule_on_err))
  File "/home/user/MHS/tribler/TriblerGUI/event_request_manager.py", line 81, in on_error
    raise RuntimeError("Could not connect with the Tribler Core within 60 seconds")
RuntimeError: Could not connect with the Tribler Core within 60 seconds`

I updated sumodules:

`git submodule update --init --recursive`

It started up fine after that but my torrents still didn't load. I realized that I should have deleted version_history.json instead. So I deleted the file and started Tribler again. Torrents still weren't loaded.

One thing I should mention is that when I first had problems with 7.4.4, I ran an old version of Tribler (7.3.0-rc1-6-g379d4052f) that I had lying around in a folder. That version didn't load my torrents either so after a few days I stopped running it and opened up this issue. Running this old version might have complicated things. I also just ran it again to see what would happen.

I have no clue what I need to do here.

**Comment by ichorid** [comment]
Ok, so if you're running Tribler directly out of the repository, it becomes much harder to predict how version management will work for you because:
 1. final version_id that is used by the version management module is only applied *by release builder script*.
 2. we fiddle with file formats constantly and there is no guarantee that two GIT-based versions will play nicely with each other's configs if you switch them around.

So, if you prefer running Tribler from the repository, you're mostly on your own. BTW, latest `devel` should help with that a bit, since we're now updating the major/minor version numbers in the repository, and version management scripts got completely rewritten for 7.5.

Having said all that, here is what you can do:
Download checkpoints are stored in `.Tribler/dlcheckpoints/*.state` for 7.3 and earlier, and in `.Tribler/<Tribler_version>/dlcheckpoints/*.conf` for 7.4 and later.
Also, 7.4 introduced a new format of download checkpoint files. 7.4 and later will automatically convert `*.state` files into `*.conf` files if it finds them in its `dlcheckpoints` directory.

So, if you want to go back to 7.3, you can look around your Tribler `dlcheckpoints` dirs and collect your `*.state` files and put them into `.Tribler/dlcheckpoints` dir. Or if you want to go to 7.4 and later, you can put these into your `.Tribler/<version>/dlcheckpoints` dir.

**Comment by MeadowHillSoftware** [comment]
So I recreated the 7.4.4 folder and copied the dlcheckpoint files into it and started the 7.4.4-2. It started up and loaded my torrents. So far, so good. Unfortunately my token balance is still showing as 0MB. The trust statistics page shows "0 MBytes Given to the community," "0 People you helped," "0 MBytes Taken from community," and "0 People who helped you" but the graph on that page shows that I have more than 20 GB of tokens (~229 given, ~205 taken). When I ran that old build (7.3.0-rc1-6-g379d4052f) for a few days my token balance spiked like crazy from ~800MB to ~23.8GB. I figured that must have been some glitch since I've never gained tokens at that rate. I'm not sure what to make of this discrepancy.

**Comment by ichorid** [comment]
Glad to hear your downloads are back! Regarding the balance, it is bound to your private/public keypair and your TrustChain database. These are stored in `.Tribler/*.pem` and `.Tribler/sqlite/trustchain.db` and `.Tribler/sqlite/market.db`. Be very careful with these, as if you lose your private key it is impossible to get it back. So, before overwriting anything, always make a backup.

To get your balance back, you can try to copy the abovementioned files to where they belong.
In your case, you want to copy them from `.Tribler` dir to `.Tribler/7.4.4` dir. You'll have to overwrite the files that were already created by 7.4.4 though.

**Comment by MeadowHillSoftware** [comment]
Still showing a discrepancy between the graph and the text on the Trust Statistics page.

I noticed that the 7.4.4 folder had neither ec.pem nor ecpub.pem in it. I don't know how relevant this is. Still having the same issue whether or not those are present. I even tried removing those two files from the .Tribler folder in addition to the .Tribler/7.4.4 folder and that didn't change anything either.

**Comment by loadletter** [comment]
I'm having the same issue with balance on V7.5.0-rc1 after upgrading from 7.3.2, my trustchain id, total blocks and the bandwith given/taken graph are OK but the number of users helped and token balance remains at 0 and trust graph doesn't show any other peer.

**Comment by ichorid** [comment]
@devos50 , do I remember correctly that we changed tokens storage format resulting in zeroing of tokens during upgrade to post-7.3 versions?

**Comment by devos50** [comment]
@ichorid no, we did not change the format of tokens recently. The migration to Python 3 has caused some issues when signing and validating blocks which could have resulted in a bug when computing the balance.

@MeadowHillSoftware could you try [our 7.5 release candidate](https://github.com/tribler/tribler/releases) to see if that solves this issue?

**Comment by ichorid** [comment]
I've checked the code of `run_tribler.py`. The Version Manager procedures run after the Dependencies Checker, meaning that if Tribler fails to start because of a missing dependency, it should not affect forking the state directory.

So, closing this one. Discussion of the token balance error should continue in #5255
