### ISSUE TITLE
Hidden seeding needs in-GUI explanation regarding tokens

### ISSUE THREAD

**Issue by mehlon** [Tribler/tribler#5212]
Anonymous downloading of torrents costs bandwidth tokens. 
But it's unclear from the user interface and the FAQ whether the option "anonymous seeding using proxies" also costs tokens. Does it?
I think this should be clarified in either the user interface or the FAQ.

**Comment by ichorid** [comment]
That is a good question! Indeed, anonymous seeding *should not* cost anything by design. However, there is a bug in our accounting system that, in some cases, may cause "a leak" of tokens from the hidden seeder.

Regarding the documentation, we would prefer to build the system in such a way that a typical user would not have questions for basic Tribler usage, such as safe downloading / hidden seeding. The fact that you ask about it means we have to work harder on the simplicity of usage and context information :wink:

**Comment by mehlon** [comment]
If someone's seeding anonymously and you try to download non-anonymously, does that also cost tokens? Or will the client simply be unable to connect to the seeder?

**Comment by ichorid** [comment]
If you're downloading non-anonymously you never pay for anything.

**Comment by egbertbouman** [comment]
Actually, I think that even a non-anonymous Bittorrent transfer between 2 Tribler users results in a transfer of tokens (see [download_manager.py#L338](https://github.com/Tribler/tribler/blob/4f9bc65a474f99b67256fa4ade679ba269cf1456/src/tribler-core/tribler_core/modules/libtorrent/download_manager.py#L338)).

Having said that, since Tribler 7.5 anonymous seeders no longer seed through exit nodes. It could still happen while the 2 peers are still downloading though.

**Comment by mehlon** [comment]
Does the "number of hops" setting for a torrent change what happens with seeding? Does it seed non-anonymously if the number of hops is set to 0? The UI says "Anonymous - no" in the "Downloads" tab, so I would think that it's probably both downloading and seeding non-anonymously.

**Comment by egbertbouman** [comment]
If you change the hop-count while seeding, Tribler will change the hop-count of the circuits over which you are seeding. If you don't want to seed anonymously anymore, you can set the hop-count to 0.

**Comment by mehlon** [comment]
So if I'm getting this right:
Non-anonymous seeding: no cost
Non-anonymous downloading: no cost
Anonymous seeding: no cost, regardless of number of hops
Anonymous downloading: costs tokens equal to number of hops * file size

**Comment by ichorid** [comment]
You're completely right. Though, there is a bug resulting in "leaking" control traffic through exit nodes to non-Tribler clients when you're seeding anonymously. We're currently working on a fairer traffic accounting system.
