### ISSUE TITLE
Token balance graph error

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5255]
Somehow the first and last datapoint is connected with 2nd "Bytes taken" line.
![Screenshot from 2020-03-28 13-12-08](https://user-images.githubusercontent.com/325224/77822742-d7521280-70f5-11ea-9e5a-1f532707b03b.png)

**Comment by ichorid** [comment]
This is also reported by a user at the forum.

**Comment by devos50** [comment]
I can't seem to reproduce this issue on Mac, by plotting some basic time series.

@synctext To further debug this, I need the `trustchain.db` in the `sqlite` directory of your Tribler state directory. Furthermore, I need your public key, which you can find by going to the debug pane -> Trustchain. A screenshot should suffice 👍

**Comment by triblerteam** [comment]
fixed!
![Screenshot from 2020-04-02 15-26-36](https://user-images.githubusercontent.com/1482045/78254531-5d0aff00-74f6-11ea-8cee-8eed0078944a.png)

**Comment by synctext** [comment]
Back :-) emailing...
![Screenshot from 2020-04-02 19-40-23](https://user-images.githubusercontent.com/325224/78280927-2810a380-751a-11ea-8a27-056852a75439.png)

**Comment by synctext** [comment]
Using resize and zoom:
![Screenshot from 2020-04-03 10-38-13](https://user-images.githubusercontent.com/325224/78341006-449ef100-7597-11ea-85b1-1be8720828ad.png)

**Comment by devos50** [comment]
I tried to reproduce this issue on Mac, but it does not seem to trigger with the database provided by @synctext:

![Schermafbeelding 2020-04-03 om 11 33 17](https://user-images.githubusercontent.com/1707075/78347126-48834100-75a0-11ea-9cfb-d49e5e6d7681.png)

I also digged into the code to verify that the blocks are being delivered to the GUI in order, which seems to be the case. There are also no bandwidth inconsistencies in the block data (e.g., the total up of a subsequent block is lower) which could lead to this behavior. The bug also does not trigger on our Ubuntu 18.04 testing machine.

[This bug report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=533799) about the magical error in stdout seems to indicate that it is a problem with the GTK3 backend, and therefore outside our reach to fix. I haven't received any similar reports of this issue on non-Linux machines yet. When Ubuntu 20.04 is released (later this month), I will see if I can reproduce the error with that OS. For now, I am postponing this issue to a later milestone since I am unable to reproduce it, and it seems to be specific to Ubuntu.

**Comment by MeadowHillSoftware** [comment]
Something similar happening Manjaro with 7.4.4: https://github.com/Tribler/tribler/issues/5199#issuecomment-599243285

**Comment by synctext** [comment]
Reproduced with 7.5.0RC6: key event is that my laptop was in sleep mode for a few hours and glitch seemed to happen after a _resume_ and or offline period. Could be a stale packet problem, old peer cache something, clock issue, database default counter or just a complete coincidence. Sleep times _and period disconnected from Internet_ of laptop are clearly visible. Zoom on glitch:

![Screenshot from 2020-06-17 10-13-18](https://user-images.githubusercontent.com/325224/84873515-a691d180-b083-11ea-832c-6c85a1015f4f.png)
And the broader picture on overall wallet:
![Screenshot from 2020-06-17 10-12-22](https://user-images.githubusercontent.com/325224/84873562-b90c0b00-b083-11ea-9d49-d45b16175a13.png)

**Comment by devos50** [comment]
I think I found the issue! We are not sorting the elements based on the x-axis, see [here](https://github.com/Tribler/tribler/blob/devel/src/tribler-gui/tribler_gui/widgets/graphs/timeseriesplot.py#L45).

I will fix this in #5626
