### ISSUE TITLE
download file include/exclude bug

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5300]
sadly another showstopper in RC5.
bug when adding files to an existing swarm download. They appear 100% in GUI, but remain in .unwanted directory.
Mac running RC5.

**Comment by devos50** [comment]
I will try to reproduce this one tonight 👍

**Comment by devos50** [comment]
It actually seems that the `.unwanted` directory got removed: https://github.com/Tribler/tribler/pull/5031/commits/a33bb898f1e34b1ac3ad8a2e53caf5dd8fed7bc8. @egbertbouman can you comment on this?

**Comment by egbertbouman** [comment]
@devos50 As part of the download core refactoring, the .unwanted directory was removed because it wasn't working properly with more recent versions of libtorrent. Currently, the unwanted parts are stored in a part-file named after the infohash of the swarm. To keep things simple, we didn't bother trying to convert the .unwanted directory to the part file. That's why the .unwanted directory is still there. If you remove it, it should not come back.

**Comment by synctext** [comment]
interesting. Removed .unwanted, restarted Tribler, but the .unwanted got raised from the dead.

**Comment by synctext** [comment]
tried few times, .unwanted keeps coming back. file checks etc. all has no effect.

**Comment by egbertbouman** [comment]
In that case, it's probably the checkpoint itself that's doing this. According to the libtorrent docs, the resume data may have a list of renamed files.

Do you remember with which version of Tribler this download was created?

**Comment by ichorid** [comment]
I've seen similar behavior with some torrents created with 7.4 after switching to 7.5. Could not get rid of it, had to find and delete the correpsonding `.state` file manually. Thought it was because of my experiments with different Tribler versions, so paid no heed to it :man_shrugging:
