### ISSUE TITLE
pending UDP connections after exit

### ISSUE THREAD

**Issue by BenBipod** [Tribler/tribler#5376]
- [X] I have read CONTRIBUTING.rst

- [ ] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
7.5.0-GIT

##### Operating system and version: #####
Ubuntu 20.04

##### Steps to reproduce the behavior: #####
* start tribler from docker container with host networking (option --net host)
* stop tribler
* confirm tribler actually stopped with docker ps yielding no result
* find pending UDP connections (port 7759) in monitoring tool of internet router

##### Expected behavior: #####
All of tribler's connections should be shut down when exiting the application. This should happen in such a way that they do not longer exist for the internet router (I am no networking expert, but this is what I would expect).

##### Actual behavior: #####
Many (dozens) connections are kept pending. They even have traffic hours after shutdown of the application (the router monitoring shows growing "transfer" in bytes and packets). The sockets on the client machine appear to be closed, as they are not reported by netstat.

**Comment by ichorid** [comment]
UDP is a connection-less protocol. One cannot "open" or "close" a UDP connection. Instead, one can only send a UDP packet to some address and hope it reaches its destination.

The router shows open connections because there is literally no way for it to know if the connection was closed or not. However, the router must keep a mapping of external ports to internal ip:port pairs (a NAT) to be able to forward external packets to their destination. Also, external Tribler instances know nothing about some node going offline, so they continue to send the packets in.

In brief, that's totally normal and expected for a router to keep the connections/mappings, if it serves as a NAT.
