### ISSUE TITLE
Exceptions in tasks are not captured by our test suite

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5460]
If there is a task error while executing the unit tests, [it does not stop the test and report the failure](https://github.com/Tribler/py-ipv8/blob/master/ipv8/taskmanager.py#L135). Instead, the exception is simply logged and ignored. This can result in tests that will never terminate.

I wonder why all task errors are being ignored in the first place. I would also suggest to add an additional flag to raise these kind of errors during the unit tests, so we can at least reveal erroneous task exceptions.

**Comment by egbertbouman** [comment]
Not all tasks are only being logged & ignored by default. You have to set the `ignore` keyword argument for this to happen. In IPv8, we use this in places where we don't want the error to end up in the `unhandled_error_observer` (e.g., in packet handlers).

Having said that, perhaps the issue is with the task-decorator, where `ignore=(Exception,)` by default. This means that you have to await the task-decorated function in order to get exceptions. Perhaps the default should be `ignore=()` instead.

**Comment by qstokkink** [comment]
The test suite should not do magic, it should test what the programmer has implemented. If a programmer sets a particular error to be ignored, it should be ignored.
