### ISSUE TITLE
Issues with Trust Statistics 

### ISSUE THREAD

**Issue by ohgollychan** [Tribler/tribler#5527]
Note: the title changed 3 times because I kept finding new issues while I was writing this report.
##### Tribler version/branch+revision: #####
7.5.1
##### Operating system and version: #####
Windows 10
##### Steps to reproduce the behavior: #####
My trust statistics did not update for 15 hours, which is the reason why I started writing this report(I started writing this report at 04:40). My statistics updated while I was writing this report(05:10).
![image](https://user-images.githubusercontent.com/68978882/88872060-0f8f6c00-d222-11ea-8ce7-e8b0f4a79a4e.png)
![image](https://user-images.githubusercontent.com/68978882/88872550-15d21800-d223-11ea-8db2-cd2b2ec6943a.png)
but the time does not match.

According to my trust statistics, I have interacted with 34 users
![image](https://user-images.githubusercontent.com/68978882/88871968-d48d3880-d221-11ea-857e-630074e6c7f3.png)
But my trust graph says I interacted with 320.
![image](https://user-images.githubusercontent.com/68978882/88871993-e66edb80-d221-11ea-8de4-9e9aa499c769.png)

I didn't download anything, but the amount of bandwidth I took from the community increased.
![image](https://user-images.githubusercontent.com/68978882/88873028-5da56f00-d224-11ea-95b6-c6fa7c70457c.png)
![image](https://user-images.githubusercontent.com/68978882/88872985-3cdd1980-d224-11ea-8e08-cec496bcc16b.png)

**Comment by synctext** [comment]
thnx!
we need to clarify matters. You interacted with 3 people a total of 320 times I think. 320 records are made?

**Comment by devos50** [comment]
Thank you for your report.

First, it seems that the graph itself is glitchy and does not display the right values, as seen in your last screenshot. This is probably related to the plotting library we use and we have an open issue for this: #5255. We aim to address this in Tribler 7.6.

The second problem you report is the inconsistencies in balance. While it is expected that you take something from the community (because you are relaying encrypted bandwidth), the amount of bandwidth you contribute should always be higher than the bandwidth you take from the community. Unfortunately, we recently uncovered a very nasty bug that affects how these balances are computed (which is related to our recent move to Python 3), also see https://github.com/Tribler/py-ipv8/issues/764. This bug might still affect Tribler instances that have a database created with Python 2.

You could try to **backup** and then rename your Tribler state directory (on Windows located in `%APPDATA\.Tribler`) and start a fresh instance of Tribler. Note that this will also wipe existing downloads *so please take care while doing so*. If you noticed that your balance drops significantly again (without having active downloads), we can debug this further.

If you are interested in more details, we have a technical explanation of how bandwidth tokens are paid out [here](https://github.com/Tribler/tribler/wiki/Paying-out-bandwidth-tokens-in-TrustChain).
