### ISSUE TITLE
See my own nic;s in peer list

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#5528]
##### Tribler version/branch+revision: #####
7.5.2 juli 21th
##### Operating system and version: #####
Windows 10
##### Steps to reproduce the behavior: #####
Started download and watched peers seeding and leeching and suddenly say my own two nic's in the list
![tribler752](https://user-images.githubusercontent.com/1146496/89022478-667c6a80-d322-11ea-9465-999f960efd06.jpg)

##### Expected behavior: #####
Never saw my own addresses before

**Comment by Nubro01** [comment]
Still the case in 7.6. Must add that I have two NIC's active on that machine. On my laptop I do not see this problem.

**Comment by qstokkink** [comment]
We conducted a small investigation: this is actually the expected behavior if you have two NICs. For the first time you are seeing Tribler work correctly in years apparently 😃

Being able to use two NICs may even give you a small speed boost in the torrent protocol.

I will close this issue as it is expected behavior that should have a positive effect on your download speed.
