### ISSUE TITLE
Checklist for user growth

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#5545]
**1. Measure! Measure! Measure!**
-  All new features that are added to Tribler should include functionality to track the usage of the feature without compromising user privacy. Analysis of the collected anonymous usage data should determine whether or not further resources should be put into further development of the feature. This might not always fit with research and experiments.

**2. Popularity of content**
-  Popular content should be made widely available to the users, either via gossiping or with keyword search or recommendations. Content is what drives user acquisition and retention on a platform like Tribler. To make the content discoverable, metadata plays an important role. So, crowdsourcing metadata should be given a higher priority. Related #2455, #4256

**3. Opt-in for usage statistics**
- All users using the stable version should have an option to opt in to send anonymized usage data to the Tribler Team. For any non-stable experimental version, usage data collection could be enabled by default since the User is purposefully choosing to try out the experimental version. To make this happen, we need to develop a privacy-preserving framework to collect usage and behavior data for each Tribler feature. (Relates back to point 1).

**4. Broader reach and awareness**
- Tribler has been an academic project and will always be, but that should not limit the reach of the software to a broader common public. For that, web/social media presence is vital. Besides scientific articles and papers, some effort on spreading the word especially about new releases and features should be done.

**Comment by devos50** [comment]
> This might not always fit with research and experiments.

Indeed, some integrated features are just there to collect data and are not there to expand the user base (e.g., as we did with the Noodle protocol at the beginning of this year). I think that the decentralized market can also be considered as a research feature.

> some effort on spreading the word especially about new releases and features should be done.

We have 289 members subscribed to our [Tribler subreddit](https://www.reddit.com/r/tribler), and 555 followers on [our Twitter feed](https://twitter.com/TriblerTeam). I think that building a bigger Reddit community could be a good move since that platform is accessible and widely used. The people posting on our forums are usually developers/users interested in the technical details.

**Comment by ichorid** [comment]
I would say that before doing web/social media we should first make our priorities clear and our software usable. Otherwise, it will add even more ill fame to our already bad reputation.

**Comment by synctext** [comment]
Done 1! Great success: [1st International Workshop on Distributed Infrastructure for Common Good](https://dicg2020.github.io/) .
Now we need to survive and even thrive for the 2nd edition of this workshop.

**Comment by qstokkink** [comment]
This mindset has been adopted by the team and I will therefore consider this issue "solved".
