### ISSUE TITLE
Missing dependency: qrcode

### ISSUE THREAD

**Issue by da2x** [Tribler/tribler#5630]
#### Tribler version/branch+revision: #####
7.5.2

##### Operating system and version: #####
Windows 10.2004

##### Steps to reproduce the behavior: #####
0. Go to Settings: Anonymity
1. Click Fully empty tokens

##### Actual behavior: #####
Error message saying `'qrcode' module is missing. This module can be installed through apt-get or pip`. These instructions are fine for Linux users, but Windows users will struggle to follow them.

#### Expected behavior: ####
The dependency should be bundled with the installer.

##### Relevant bugs: #####
Fixed before for macOS in #3725. I can't verify that it works on macOS, because I can't get Tribler to run on Mac.

**Comment by devos50** [comment]
We made that an optional dependency since it is a non-critical feature of Tribler.

In fact, this feature might even be removed since it is completely unused. The original idea was that you could bootstrap a new identity in our Android app and transfer bandwidth tokens to that new identity through scanning a QR code. However, this Android app is now superseded by [the superapp](https://github.com/Tribler/trustchain-superapp), which does not support this feature.
