### ISSUE TITLE
Error message must be more meaningful. Not just `Got Tribler core error: 1`.

### ISSUE THREAD

**Issue by KOLANICH** [Tribler/tribler#5637]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####

From git.

##### Operating system and version: #####

Doesn't matter. I use Linux-based OS with overcommit disabled.

##### Steps to reproduce the behavior: #####

When tribbler core crashes, it is hard to figure out what exactly happened.

##### Expected behavior: #####

The GUI should have access to all the error messages of core.

##### Actual behavior: #####

The message is only `Got Tribler core error: 1`.

##### Relevant log file output: #####

All the logs are empty.

**Comment by devos50** [comment]
First, our contributing guide can be found [here](https://github.com/Tribler/tribler/blob/devel/doc/contributing.rst).

> The GUI should have access to all the error messages of core.

I see the issue here and get the frustration. Tribler consists of two processes: the GUI and the core. The core process is spawned by the GUI process. It is very likely that the message you receive is an error that immediately happens when the GUI process spawns the core process. We redirect all logging of the core process through the GUI and monitor if there are any tracebacks. These tracebacks, however, might never be visible, making this issue very hard to debug. There can be many causes for this behaviour, e.g., the Python interpreter has crashed or some library is causing havoc.

Which version/branch of Tribler are you running?

**Comment by drew2a** [comment]
This issue has been addressed in
- #7647
