### ISSUE TITLE
[PopularityCommunity] Unknown infohashes obtained through Popularity Community do not show up in Channels

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5642]
Receiving a new `torrent health info` through Popularity Community does not affect the Channels interface.

When a new `torrent health info` received through Popularity Community, a new `TorrentState` entity is added:

```
self.metadata_store.TorrentState(infohash=infohash, seeders=seeders,
                                                        leechers=leechers, last_check=last_check)
```
https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/popularity/popularity_community.py#L66-L68

But it does not affect the Channels interface because there is no corresponding Torrent entry in `MetadataStore``.

@ichorid please, specify which data should be added to the Database.

**Comment by qstokkink** [comment]
If you want to start an actual download, you can do the following:

1. Turn the infohash into a magnet link:

https://github.com/Tribler/tribler/blob/c4ba1744e26ed230a9cfaf3e41ab2c7e6e18feec/src/tribler-gui/tribler_gui/utilities.py#L269

2. Start a a download from this magnet link using `session.dlmgr.start_download_from_uri(your_magnetlink_here)`.

**Comment by devos50** [comment]
What do you mean by "adding the new torrent to Tribler"?

**Comment by ichorid** [comment]
I guess @drew2a means that when some health info about an infohash is received through PopularityCommunity, if there is no corresponding Torrent entry in MetadataStore, the info will just be stored in the TorrentState for the future use. In no way the user is able to see it in the Channels interface, because there is no (signed of FFA) Torrent entry for it.

There are two ways to solve this problem:
 1. send the full serialized Torrent entry with each Popularity community infohash
 2. query the sender for respective Torrent entry through RemoteQueryCommunity upon receiving an unknown infohash

**Comment by drew2a** [comment]
@qstokkink @devos50 thank you, now I realized that the description is not clear enough, @ichorid has explained everything correctly.
