### ISSUE TITLE
Channels 3.0: linked communities

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5721]
## The challenge
Channels 2.0 showed us that the following factors extremely constrain the design space for a truly decentralized data storage/sharing system:
* Degree of a host (IPv8 peer) should be small (50-100 peers). This fact contrasts sharply with centralized systems, where hosts' degrees are often distributed according to the power law.
* Using data hashes (i.e. BitTorrent infohash) as the identifier/rally point for a swarm is impossible for extensive dynamic collections of data. The bigger the collection is, the more often the root hash changes.

Channels 2.0 were based on the idea of putting everything into a single giant database distributed to all users. It proved infeasible for several reasons:
* It is essentially centralized (legal and human corruption SPOF).
* It is impossible to update in real-time.
* It is impossible to edit collectively.
* The size of the DB eventually grows beyond control.
* No user will ever use more than 0.01% of thе database, but all the unused data is still stored/sent/updated on their PC.

## The solution
Design directions to address the above issues:
* Completely stop using offline DBs. Everything should be done in-memory, Google-style.
* Serve only the data that is required. 
* Use the network itself as the index.
* Break down the data into a hierarchy of _resources_ - content graph nodes with a relatively small degree.
* Stop spreading the whole DB. Instead, spread it hierarchically between hosts.
* Efficient traversal of a hierarchy requires a structured overlay.
* **Fight churn by providing strong horizontal connections to achieve redundancy**.
* **Connect resources vertically by redundant directed connections**.

## The design
 * A resource (e.g. a sub-channel) = an IPv8 community
 * For each _parent_->_child_ link, the host serving the parent resource must connect to a small number (2-3) of hosts serving the child resource.
 * The same rule applies for _child_->_parent_ link. (E.g. a host serving the child resource must connect to 2-3 hosts serving the corresponding parent resource).
 * A single host can serve multiple resources.
 * A decentralized, self-organizing orchestration system decides which host must serve which resource (TBD, suggestions for the exact algorithm are welcome!)

This federation of IPv8 communities possesses the properties of both unstructured and structured overlays:
 * Stochastic horizontal connections = resilience to churn.
 * Redundant vertical connections = directed search.

![Channels_network_chart2](https://user-images.githubusercontent.com/2509103/98449904-1e968c00-2138-11eb-800b-b3e270bfa85e.png)

**Comment by qstokkink** [comment]
As you specifically requested feedback, I have commented on all of your bullet points. If you need further details, please let me know.

## Challenge

> Degree of a host (IPv8 peer) should be small (50-100 peers).

Yes, and the peer count could even be smaller. With the IPv8 default settings (20-30 peers) you reach millions of users within 3 seconds using gossip. Extrapolating, using the default protocol settings, the entire world population would be served within a minute.

> Using data hashes (i.e. BitTorrent infohash) as the identifier/rally point for a swarm is impossible for extensive dynamic collections of data. The bigger the collection is, the more often the root hash changes.

Agreed. Git/Bittorrent style hashing is tied to the content, not the identity of a channel. Depending on your use case this may be either very good or very bad.

> It is essentially centralized (legal and human corruption SPOF).

Well, if it's distributed to all users it is decentralized. If the original author is gone, the data lives on. Unless you allow for deletion by the original author of course.

> It is impossible to update in real-time.

No true peer-to-peer dissemination is ever real-time. Only direct messaging is real time (which is not dissemination in the network). Waiting for a few minutes or hours for updates to process should be acceptable (otherwise, use a server :) ).

> It is impossible to edit collectively.

We've had this for years in Dispersy. Nobody uses this. One of the reasons is that you would need a strong identity system to make this happen.

> The size of the DB eventually grows beyond control.

100%. This has bitten us time and time again. We have a wealth of issues surrounding the mega store (random collected torrents). The user response to garbage is a state directory clear, undermining any form of decentral dissemination.

> No user will ever use more than 0.01% of thе database, but all the unused data is still stored/sent/updated on their PC.

Which may, or may not, be a problem. Preempting data a user may be interested in is very efficient (we have a paper on this: "4P: Performant private peer-to-peer file sharing"). That said, garbage is garbage :). This is a precarious balance.

## Solution

> Completely stop using offline DBs. Everything should be done in-memory, Google-style.

Extreme solutions are never good. Not storing anything on disk would put all users into a cold-start scenario all the time, which is slow and leads to less diversity of content. However, I do fully support keeping random garbage content in memory, to be dropped the next session.

> Serve only the data that is required.

Completely agree.

> Use the network itself as the index.

Also, completely agree.

> Break down the data into a hierarchy of resources - content graph nodes with a relatively small degree.

This requires a lot from users. Just dumping torrents in the application is annoying enough, let alone having to manually apply hierarchies.

> Stop spreading the whole DB. Instead, spread it hierarchically between hosts.

I don't agree hierarchy leads to more desirable results, just different ones. You may very well be spreading garbage with a different structure.

> Efficient traversal of a hierarchy requires a structured overlay.

Yes.

> Fight churn by providing strong horizontal connections to achieve redundancy.
> Connect resources vertically by redundant directed connections.

So, you want a lot of connections to prevent network partitioning and information loss in a structured network. Makes sense I guess, the more connections you have the less chance you have of partitioning and information loss.
There is always a chance of catastrophic failure though in depending on network structure.

## Design

> A resource (e.g. a sub-channel) = an IPv8 community

Just because IPv8 handles peer-to-peer messaging it is not that great for resource sharing, see also https://sourcemaking.com/antipatterns/golden-hammer. If you want resource sharing, your best bet is to use peer-to-peer software that is made for resource sharing, like libtorrent.

> - For each parent->child link, the host serving the parent resource must connect to a small number (2-3) of hosts serving the child resource.
> - The same rule applies for child->parent link. (E.g. a host serving the child resource must connect to 2-3 hosts serving the corresponding parent resource).
> - A single host can serve multiple resources.
> - A decentralized, self-organizing orchestration system decides which host must serve which resource (TBD, suggestions for the exact algorithm are welcome!)
>
> This federation of IPv8 communities possesses the properties of both unstructured and structured overlays:
>
>    - Stochastic horizontal connections = resilience to churn.
>    - Redundant vertical connections = directed search.


This is quite literally a DHT. Now you could make your own, depend on IPv8's very crummy natural DHT (Communities), IPv8's actual DHTCommunity, a bleeding-edge implementation (e.g. the "eQuus: A provably robust and locality-aware peer-to-peer system" paper) or a mature DHT used in the wild like libtorrent. I would prefer the latter.

**Comment by devos50** [comment]
I’ve read through the design. I have some questions and thoughts, some of which I wrote down below. Maybe it was also the intention of the author to keep the description high-level, to challenge us to think about some of the details? :)

Before I comment on the design of your new channel mechanism, I am trying to better understand your arguments on why channels 2.0 (current implementation) is infeasible. I want to have this clear before I would agree with another redesign of the channels backend. _A grand design requires a grand motivation_ (apologies in advance for my conservative stance on this :). Though channels 2.0 has known shortcomings, I don't see insurmountable obstacles for a successful deployment of it. So, let me comment on your arguments:

> It is essentially centralized (legal and human corruption SPOF).

Can you elaborate on how strategic legal/human corruption can subvert specific items the current network? From my understanding, it would require an adversary to shutdown the libtorrent swarm to stop spreading specific content. Moreover, content is already replicated in the network. I think that in your new design this corruption is easier to achieve since an adversary only needs to shut down a few nodes in an IPv8 community.

> It is impossible to update in real-time.

I'm not sure what "real-time" means in the context of channels. I assume that it means that channel updates are immediately propagated to nodes that have subscribed to the channel. In channels 2.0, there is definitely a latency since the new info hash needs to be shared, and the content needs to be downloaded. I do wonder whether Tribler strictly requires this real-time feature. Are there signs that users want this?

> It is impossible to edit collectively.

Collective collaboration was in an older iteration of the channel mechanism, and it got removed.

> The size of the DB eventually grows beyond control.

If the popularity community is functional, we could consider pruning the metadata of dead torrents, and only store full information on alive torrents. Is storage a key concern currently?

> No user will ever use more than 0.01% of thе database, but all the unused data is still stored/sent/updated on their PC.

I agree with this point. This concern also applies to the TrustChain database, for example, where the vast majority of records remains unused (besides for fraud detection). Again, a proper pruning strategy could be sufficient to address this.

Regarding your design:
- The idea of storing everything in memory looks promising. I wonder whether you also considered a hybrid approach, where important data is persisted to disk, and some other data is served from memory?
- How do you achieve keyword search in this system? Your linking structure does not allow for a targeted text search for content and would require the flooding of query messages in the network (which has been proven to be problematic - see Gnutella).
- Are parent/link connections the same as horizontal/vertical connections?
- Do I as peer start serving a channel when I subscribe to it? If so, it sounds similar to IPFS.
- (for the future) For our Plexus blockchain, we are also using horizontal/vertical chains. This distinction, however, only pertains to the data structure itself. If BAMI is deployed and functional, I see opportunities to store all channel content in our blockchain ledger.
- One compelling advantage of (dumb) unstructured networks in my eyes is that maintaining random connections, and sending out random queries to random users, is often "good enough". I successfully used this trick twice already, for order matchmaking and TrustChain fraud detection. As such I am probably biased towards unstructured overlays. Wouldn't structured overlays require much administration overhead and implementation effort?
