### ISSUE TITLE
Cannot download torrent file anonymously using devel branch

### ISSUE THREAD

**Issue by kozlovsky** [Tribler/tribler#5761]
I'm trying to download Ubuntu 20.10 torrent anonymously using the latest `devel` branch.
https://releases.ubuntu.com/20.10/ubuntu-20.10-desktop-amd64.iso.torrent

The downloading does not start, and I can see in logs: "Could not create circuit, no available exit-nodes".
More detailed log information with relevant log lines available here: https://pastebin.com/Uhxxzm54

The same torrent can be successfully downloaded using version 7.5.3 of Tribler.

I think that the devel branch behaves this way for any anonymous downloads. Can anybody try and check it?

**Comment by devos50** [comment]
It works for me, however, it does not start to transfer bytes. A further inspection in the debug panel shows that I only found two other peers in the `TriblerTunnelCommunity`, which are likely machines of developers.

My best guess is that there is something wrong with the exit nodes. Did anyone change them recently?

**Comment by kozlovsky** [comment]
It is possible that there are some changes on exit nodes, but I can successfully download the same torrent anonymously using Tribler 7.5.3. So I suspect the reason is in some latest IPv8 changes. Maybe @qstokkink or @egbertbouman can help here.

**Comment by qstokkink** [comment]
Firstly: yes the TunnelCommunity id changed since `7.5.4`. I'll now give you a quick tutorial on how to see if there are exit nodes available.

## Anonymous download debug instructions

You can see the available peers on this tab of the debug screen:

![available peers](https://user-images.githubusercontent.com/3630389/100710615-446a2600-33b0-11eb-8f5f-47669187cdc6.png)

Specifically, to download anonymously you need at least one peer with flag 2 (this the `PEER_FLAG_EXIT_BT` constant, telling others in the network you wish to serve as a Bittorrent traffic exit node).

---

As you can see on my debug tab, I also cannot find exit node peers in the network. That is why anonymous downloads are not working. This *may* be due to a bug and this *may* also be due to the fact none of the people running exit nodes have upgraded to the `devel` branch. I'd consider the latter more likely.
