### ISSUE TITLE
[7.6.0-exp1] Token balance bug

### ISSUE THREAD

**Issue by Shidouuu** [Tribler/tribler#5789]
For some reason my token balance just shot up by like 10 GB, and later 3. I've only maybe gotten like a gigabyte and a half in 7.5.4 in a day, and this has only been running for a few hours. 
When I updated from 7.5.4, my token balance got reset. It wasn't exactly very much, but still annoying.

![image](https://user-images.githubusercontent.com/36283656/101099152-3673fb00-3592-11eb-8f4d-ec02f3cfedb6.png)

**Comment by snakyjake1** [comment]
I'm not downloading anything, yet my balance is going negative.
I think I'm headed towards bankruptcy! (yeah, I might delete my negative balance and start over).

**Comment by devos50** [comment]
Thanks for reporting!

> For some reason my token balance just shot up by like 10 GB, and later 3.

This could be because your computer has been used to relay (encrypted traffic), and you got rewarded for it.

> When I updated from 7.5.4, my token balance got reset. It wasn't exactly very much, but still annoying.

Indeed, we did a reset of the token balance because we switched the underlying architecture of the bandwidth accounting module. We understand that can be annoying and for this reason, we have implemented a mechanism that automatically compensates for the lost token balance.

> I'm not downloading anything, yet my balance is going negative.

Our new accounting mechanism counts _all_ interactions, and a bootstrap download will trigger to make sure that you are connected to some other peers in the network. This might cause you to go into the negative. The idea is that we eventually show a ranking overview instead of a raw balance, which we believe is more meaningful to our users.

**Comment by Shidouuu** [comment]
> This could be because your computer has been used to relay (encrypted traffic), and you got rewarded for it.

Maybe, but I think 88 GB is a bit too much

![image](https://user-images.githubusercontent.com/36283656/101173810-09b2f880-3611-11eb-9558-fb6bdb71ddbd.png)

**Comment by devos50** [comment]
Well, with that amount you will be considered a good user! 😀 

But that's quite a lot indeed. Maybe there are some rogue payouts going on, or peers that are sending random payouts to others. We will try to debug this 👍

**Comment by Shidouuu** [comment]
...it seems I've been punished
![image](https://user-images.githubusercontent.com/36283656/101187549-7f739000-3622-11eb-8fc7-32f228c00747.png)

**Comment by snakyjake1** [comment]
You must: 
![image](https://user-images.githubusercontent.com/8312560/101190649-929d5480-3650-11eb-9a71-ce2555f21008.png)

I'm so negative, that I should consider bankruptcy and reinstall:
![image](https://user-images.githubusercontent.com/8312560/101190717-aba60580-3650-11eb-83b4-aacacf9125dd.png)

Or someone is stealing from me.

:upside_down_face:

**Comment by devos50** [comment]
Sorry, I really can't resist this one:

![s6hdwntp7a701](https://user-images.githubusercontent.com/1707075/101194753-b10a4c80-365e-11eb-981f-deba2941e46e.jpg)

On a serious note, there seems to be something wrong indeed and it can either be a messed-up counter or a malicious (benevolent?) peer. Since we monitor the transactions, we have a view on the global graph.

**Comment by Shidouuu** [comment]
Bug? What bug? I've only downloaded 203 Gigabytes
![image](https://user-images.githubusercontent.com/36283656/101195317-3bd25380-362d-11eb-9d66-25ace7010d78.png)

**Comment by snakyjake1** [comment]
Some other info regarding my large token deficit...I also have bandwidth limits setup.  Not sure if the ratio between upload/download might cause a deficit/discrepancy.

**Comment by scribblemaniac** [comment]
I am also seeing a net negative token balance (~ -6GB after 1 day) on 7.6.0-exp1. I do not have bandwidth limits set.

> Indeed, we did a reset of the token balance because we switched the underlying architecture of the bandwidth accounting module. We understand that can be annoying and for this reason, we have implemented a mechanism that automatically compensates for the lost token balance.

Can you elaborate on this a bit? OP may not have lost very much, but I'm sure there are many who will. Are you invalidating all tokens issued prior to this update as well?

**Comment by devos50** [comment]
>  am also seeing a net negative token balance (~ -6GB after 1 day)

Are you downloading anonymously? This decrease is not significant and can relate to your running downloads.

**Comment by scribblemaniac** [comment]
> Are you downloading anonymously? This decrease is not significant and can relate to your running downloads.

I should have specified that I have not been downloading anything, just idling as a non-exit node and seeding. My balance seems to have increased dramatically now so I must have been used for a download. I will follow up if I see it start trending downwards again.

**Comment by Shidouuu** [comment]
lol that's a new record
![image](https://user-images.githubusercontent.com/36283656/101267458-f09c6b80-3726-11eb-99f5-a9bf4c0f2d4d.png)

**Comment by devos50** [comment]
I likely found the issue, which seems to be related to payouts in the tunnel community. The error is in [this line](https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/modules/tunnel/community/triblertunnel_community.py#L357), where a relay computes the amount of bytes it pays to the next hop.This amount is based on the amount in the previous transaction, however, this number is the pairwise total between two peers. Basing the next payout on this number is incorrect. I also reproduced this behavior by modifying the `test_payouts` tests, but it requires prior interactions between peers for this to occur.

To further elaborate, imagine a situation between users A, B, and C where A did a previous payment of 2GB to B. Now, A downloads some data over a circuit with B being relay and C being exit node, say 250MB. When destroying the circuit, A will perform a payout of 750MB to B. Next, B _should_ perform a payout of 500MB to C but it will perform a payout of 2GB instead.

The question remains on how to properly fix this. Many peers have already been affected by this bug, leading to skewed balances. One solution could be to do a hard upgrade (again) of the tunnel community since I have to modify the code in there. This requires some additional management of the exit nodes. Maybe there is a better way to do this?

**Comment by ichorid** [comment]
>Maybe there is a better way to do this?

@egbertbouman  is summoned to this thread :mage_man:


My personal opinion, we should not show the balance to the user until it starts to affect the user experience in some way. We can still have LedgerZero enabled in the background to experiment with it.

**Comment by devos50** [comment]
> until it starts to affect the user experience in some way.

It already affects users in some way. When there is congestion at the exit nodes, users with higher bandwidth contributions will experience more stable and higher download speeds. I'm not sure if this effect is very noticeable.

@grimadas and I have a few plans to further improve LedgerZero and we will discuss/finetune these ideas tomorrow.

**Comment by egbertbouman** [comment]
Since @ichorid summoned me, let me add my 2 cents. From what I gather, the damage is done. We could keep the community ID, but as long as 7.6.0 peers remain online, incorrect payouts will continue to be made.

Personally, I think that *if* payouts are visible from the GUI, they should be correct. If that means we need to update the community ID, then so be it.

**Comment by devos50** [comment]
We could choose to continue with this (bugged) version for now. We want to make a few additional improvements soon, and these changes also might require an upgrade of the community.

**Comment by Shidouuu** [comment]
I've probably broken some kind of record by now

![image](https://user-images.githubusercontent.com/36283656/101502918-86aade80-393f-11eb-9983-ec83232d2c05.png)

All jokes aside, this should definitely get fixed as soon as it can imo, otherwise we're just going to keep getting skewed balances. I don't think it makes sense to hide the balance, since that's just avoiding the problem, and it's going to be implemented back anyways.

**Comment by devos50** [comment]
@Shidouuu we have located the bug, but we are still discussing if a hard protocol break is the best course of action at this point. We are very much aware that hiding the token balance is not a solution but just hiding the problem. We would like to make a few other additions to the bandwidth accounting mechanism and it might be preferable to break the protocol when we are doing so.
