### ISSUE TITLE
[UX] Search results are not relevant

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5887]
Version: 7.6.1 (latest devel)

![image](https://user-images.githubusercontent.com/13798583/103223342-0f151180-4937-11eb-9b1f-d8af3f3f6a4e.png)

##### Steps to reproduce the behavior: #####

1. Run a Tribler instance
2. Search for "ubuntu"

##### Expected behavior: #####

Results, ranked by relevance and health

Note: maybe, folders should be more relevant than torrents (a discussion is needed)
##### Actual behavior: #####

Probably, I see the raw results of a Full-Text Search query execution from DB.

**Comment by drew2a** [comment]
@ichorid @kozlovsky can you guys take a look at this?

**Comment by drew2a** [comment]
The exception is occurred in `def perform_files_request(self):`, during any call of any UI item (in this case it is `anon_download_checkbox`):

https://github.com/Tribler/tribler/blob/626f9818758ddaad27250e677414d103ec45993b/src/tribler-gui/tribler_gui/dialogs/startdownloaddialog.py#L157-L158

How it happened. `def perform_files_request(self):` invoked from multiple places: 
![image](https://user-images.githubusercontent.com/13798583/103226470-438bcc00-493d-11eb-97de-25b4406b65cc.png)

Some of them are callbacks. These callbacks can be invoked when the dialog is closed. If the dialog is closed, then it's items are no longer available. That's why the issue occurs.

@ichorid @xoriole does it seem to be true?

**Comment by kozlovsky** [comment]
I'll look at it

**Comment by drew2a** [comment]
When results come from your peers, then the results are ordered randomly.

**Comment by ichorid** [comment]
Well, when you query other peers, the search query is interpreted by *their* MDS and then handled to the GUI directly (sans entries already known to our MDS). The remotely received entries are appended to the top of the table in the GUI, for simplicity. It is indeed possible to sort them and deduplicate them. There are two ways to achieve this:
 1. Implement additional sorting in the GUI. This will add a lot of complexity to the code, as we would have to duplicate the sorting/merging routines.
 2. Repeat the local query in the Core on every received result and update the GUI on these. This will result in annoying "blinking"  of the GUI results table, breaking user interaction and adding complexity to tables stack logic.

**Comment by drew2a** [comment]
There is a third option: to show the results of the remote search in a different view.

**Comment by ichorid** [comment]
> There is a third option: to show the results of the remote search in a different view.

How would channels navigation look then? Like frames in a browser?

**Comment by drew2a** [comment]
It is not channel navigation. It is the result of search navigation.
How it would look is an open question.

We have discussed it with @xoriole and @kozlovsky.
Our ideas are:
1. Tabs 
2. A split page

**Comment by ichorid** [comment]
Mockups, anyone? :wink:

**Comment by synctext** [comment]
Yes, we will dedicate a whole month to relevance ranking. Refresh results and re-order. Put a limit of 1500ms on the whole. requires we have somewhat reliable popularity stats for swarms.

**Comment by kozlovsky** [comment]
I'm not sure that two separate tabs for "local" and "remote" results would be convenient for a typical user for two reasons:
1. It requires additional action from the user to switch to the second tab, and until that, the remote results remain hidden.
2. Remote results are somewhat ephemeral: after they are received, they become local results. So they disappear from the second tab pretty quickly, and it may be confusing to a user.

Instead, I suggest having a single list. But instead of the current design, where remote results are displayed above local results, I propose to display remote results below local results. Firstly we can display local results sorted in order "healthy and relevant items at the top," and then we can display remote results when they arrive at the order of arriving.

The benefit of this approach is the stability of the list item positions: when new data arrives from the remote machines, the result list is not flickering, and items do not move suddenly (at the current design, it may be confusing to the user when he wants to click on an item, and instead he clicks on another item which suddenly appeared at the top of the list). And if the user explicitly refreshes the search result, previous "remote" items become integrated with the previous "local" items, while new "remote" items start appending to the bottom of the list.

To implement this, Core can pass the `max_local_rowid` value to GUI on the first query, and then, when GUI requests the second (or third, etc.) page of results, it passes this `max_local_rowid` back to Core. Core select all objects ("local" and "remote") from the database, but "local" objects (which have rowid less or equal to `max_local_rowid` value from the first request) are displayed first using "healthy+relevant" ordering, while objects with rowid greater than `max_local_rowid` value are displayed at the bottom ordered by their rowid values.

So, I see three benefits:
1) results are stable and not move under the mouse cursor suddenly
2) local (that is, previously loaded) results are displayed in "healthy+relevant" order
3) remote results appeared on the same list without the necessity to switch to another tab.

Objections: we discussed this idea with @drew2a and @xoriole before, and @xoriole discussed the situation when this approach () might produce suboptimal results. Consider the situation when a user searches "Ubuntu 20.10 Groovy Gorilla". He does not have exact matches in the local database (because he was not subscribed to suitable channels nor performed this search before). But he has multiple partial results "Ubuntu." The result page will then be filled with not-so-relevant local results while the most relevant items will be hidden at the bottom of the result list.

So this design has some benefits and some drawbacks, but at this moment I think that the benefits are bigger.

**Comment by ichorid** [comment]
The idea of showing a "snapshot" of the local database is a good one.

How would you define "healthy+relevant" ordering then? You'll have to come up with some kind of score function, Google-rank-style.

**Comment by kozlovsky** [comment]
By "healthy" I mean "have at least one known seeder", these results can be displayed at the top. Then the value of the [bm25](https://www.sqlite.org/fts5.html#the_bm25_function) similarity function can be taken into account second in order. So, we will see:
* the most relevant local items with seeders;
* a bit less relevant local items with seeders;
* the most relevant local items without known seeders;
* a bit less relevant local items without seeders;
* real-time results from remote nodes in order of arriving.

As another option it is possible to use some weighted score function wich mix "healthy" and "other" items into a single list (say, by multiplying the bm25 output by 1.0 for "healthy" and by 0.5 for "other" items).

**Comment by synctext** [comment]
> a third option: to show the results of the remote search in a different view.

Results from remote search and local results need to be merged in real-time in future Tribler. We're essentially building a distributed Google that is as simple as possible. We will start designing this in detail, after popularity community #3868 is operational after years of tuning.

> You'll have to come up with some kind of score function, Google-rank-style.

Exactly!
