### ISSUE TITLE
Tribler crashed when clicking on "Loading torrents files anonymously"

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5894]
```
Traceback (most recent call last):
  File "/Users/<user>/Projects/github.com/Tribler/tribler/src/tribler-gui/tribler_gui/widgets/clickablewidgets.py", line 10, in mousePressEvent
    self.clicked.emit(False)
TypeError: ClickableLabel.clicked[] signal has 0 argument(s) but 1 provided
```

##### Tribler version/branch+revision: #####
7.6.1 (latest devel)

##### Operating system and version: #####
macOS

##### Steps to reproduce the behavior: #####
Click on this label:
![image](https://user-images.githubusercontent.com/13798583/103346082-26bdd880-4aa4-11eb-890b-ef62e8352a6f.png)

**Comment by qstokkink** [comment]
I propose conforming to the `ClickableLineEdit` and `Qt`'s [`QAbstractButton`](https://doc.qt.io/qt-5/qabstractbutton.html#clicked) interface, giving the signal a boolean argument:

https://github.com/Tribler/tribler/blob/d0fd7d4712a99183e3269898c7d2da6c312015e9/src/tribler-gui/tribler_gui/widgets/clickable_line_edit.py#L5-L13

Concretely: `pyqtSignal(bool)` instead of `pyqtSignal()`.

**Comment by drew2a** [comment]
Yes, but it is a strange UX solution.

Ordinary looking label, but... clickable!

**Comment by drew2a** [comment]
I've posted a quick fix. 
But, probably we should work on this label later.
