### ISSUE TITLE
IPv8 trackers often respond with an empty wan_introduction_address

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#5936]

**Comment by egbertbouman** [comment]
Currently, when we send an introduction request to an IPv8 tracker, the tracker will only respond with a non-empty `wan_introduction_address` for 30% of the time. The old Dispersy trackers, however, to have this field populated 90+% of the time (see table below). This could slow down the bootstrapping process.
Of course, receiving an empty `wan_introduction_address` doesn't mean our entire request was in vain since the tracker will note our IP and will send it to other peers that are requesting peers for bootstrapping.

```
DiscoveryCommunity (7e313685c1912a141279f8248fc8db5899c5df5a)
100 introduction-requests, 10s apart

Tracker                 Responses    Non-empty introduction    Unique introductions
--------------------  -----------  ------------------------ -----------------------
130.161.119.206:6421          100                        93                      29
130.161.119.206:6422          100                        93                      31
131.180.27.155:6423           100                        90                      28
131.180.27.156:6424           100                        95                      33
131.180.27.161:6427           100                        29                      16
131.180.27.161:6521           100                        29                      16
131.180.27.161:6522           100                        30                      19
131.180.27.162:6523           100                        32                      19
131.180.27.162:6524           100                        31                      19
130.161.119.215:6525          100                        30                      19
130.161.119.215:6526          100                        30                      18
130.161.119.201:6527          100                        30                      18
130.161.119.201:6528          100                        30                      18
```

Another issue is that when the IPv8 trackers do return a `wan_introduction_address`, it is often the same IP for all trackers. This likely means that IPv8 trackers have very few peers in their `Network`.

Finally, I noticed that IPv8 trackers don't support `puncture-request` messages, meaning that they don't participate in the NAT puncturing process.

I think that ideally, IPv8 trackers would take a more active role in the network. For instance, by keeping a much larger cache of active peers and by aiding in the NAT puncturing process.

**Comment by egbertbouman** [comment]
Currently, when we send an introduction request to an IPv8 tracker, the tracker will only respond with a non-empty `wan_introduction_address` for 30% of the time. The old Dispersy trackers, however, to have this field populated 90+% of the time (see table below). This could slow down the bootstrapping process.
Of course, receiving an empty `wan_introduction_address` doesn't mean our entire request was in vain since the tracker will note our IP and will send it to other peers that are requesting peers for bootstrapping.

```
DiscoveryCommunity (7e313685c1912a141279f8248fc8db5899c5df5a)
100 introduction-requests, 10s apart

Tracker                 Responses    Non-empty introduction    Unique introductions
--------------------  -----------  ------------------------ -----------------------
130.161.119.206:6421          100                        93                      29
130.161.119.206:6422          100                        93                      31
131.180.27.155:6423           100                        90                      28
131.180.27.156:6424           100                        95                      33
131.180.27.161:6427           100                        29                      16
131.180.27.161:6521           100                        29                      16
131.180.27.161:6522           100                        30                      19
131.180.27.162:6523           100                        32                      19
131.180.27.162:6524           100                        31                      19
130.161.119.215:6525          100                        30                      19
130.161.119.215:6526          100                        30                      18
130.161.119.201:6527          100                        30                      18
130.161.119.201:6528          100                        30                      18
```

Another issue is that when the IPv8 trackers do return a `wan_introduction_address`, it is often the same IP for all trackers. This likely means that IPv8 trackers have very few peers in their `Network`. I think that ideally, IPv8 trackers would keep a much larger cache of active peers.

**Comment by ichorid** [comment]
I've noticed this while testing Channels 3.0 prototype. Only one in three attempts to connect two peers in a custom community would work on average.

**Comment by qstokkink** [comment]
_Precondition:_ All of these trackers are **should** be running the exact same script.

If the precondition holds, this is probably due to [the flat 2 minute](https://github.com/Tribler/py-ipv8/blob/master/scripts/tracker_service.py#L39) timeout in the tracker scripts.

We could increase the timeout if the trackers know only a small amount of peers. However, due to the _hardware_ NAT puncturing timeout, the success rate of IntroductionRequests may then decrease as the firewall/router mappings close.

**Comment by egbertbouman** [comment]
@qstokkink Yes, this is why I didn't suggest just increasing the 120s removal time. We only want to gossip peers that we still can connect to.

**Comment by qstokkink** [comment]
@egbertbouman if I read between the lines, it seems to me like concrete suggestion of this issue is then to add a keep-alive message to the bootstrap script (at least when the peer count is low). Is that correct?

**Comment by ichorid** [comment]
>add a keep-alive message to the bootstrap script (at least when the peer count is low).

Sounds like a good idea. Seriously.

**Comment by egbertbouman** [comment]
@qstokkink That's correct. Although we also need to consider that peers may decide not to respond to an introduction request if the `max_peers` limit is reached. If that's the case, the tracker should also stop gossiping the peer even if it is still online. So, this keep-alive should probably also show if a peer is still looking for new peers (or we just don't respond to the keep-alive).

**Comment by qstokkink** [comment]
Sounds good. Thanks for clarifying 👍

**Comment by egbertbouman** [comment]
This previously mentioned keep-alive mechanism is added in https://github.com/Tribler/py-ipv8/pull/954. Hopefully, this will fix the low number of introduction addresses that we get from trackers.

I also made a [Jenkins job](https://jenkins-ci.tribler.org/job/Test_BootstrapIntroductions/1/) that gives some information about the `wan_introduction_address`/`lan_introduction_address` that we get from the live trackers. I plan on extending the graph with additional metrics in the future.

**Comment by egbertbouman** [comment]
I extended the Jenkins experiment a bit to show the number of reachable addresses. It turns out that a peer that does 100 bootstrap attempts at a >10s interval typically gets around 10 unique reachable peers from a tracker.

**Comment by synctext** [comment]
Could we please document the exact timeout and tracker behaviour in readthedoc?

**Comment by egbertbouman** [comment]
@synctext Sure. And I guess we should probably also discuss the basics of introduction-requests/responses and NAT puncturing. I don't think this documented either (or at least not that I can easily find).

**Comment by qstokkink** [comment]
If you want documentation on the original 2011 magic values (120 second timeout etc.) you can reference this paper:

Halkes G, Pouwelse J. UDP NAT and Firewall Puncturing in the Wild. InInternational Conference on Research in Networking 2011 May 9 (pp. 1-12). Springer, Berlin, Heidelberg.

**Comment by qstokkink** [comment]
This issue seems to have been fixed along the way by the following PR and resource:

- https://github.com/Tribler/py-ipv8/pull/954
- https://py-ipv8.readthedocs.io/en/latest/reference/peer_discovery.html

@egbertbouman (since you're assigned) can we close this?

**Comment by egbertbouman** [comment]
Sorry for the late response, but yes, I think we can close it.
