### ISSUE TITLE
[Wireframes] Keyword search results with thumbnail-based entries 

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#5957]
Below are two variants of wireframes that represent keyword search results.

![Keyword search results](https://user-images.githubusercontent.com/13798583/106026298-f0d33a80-60c9-11eb-800b-98a4572f5d0d.png)

**Comment by synctext** [comment]
good discussion material! Could we have a design sketch with the current result density and inclusion of partial thumbnail results? We will always have some results not having thumbnails and years of transition I fear.

**Comment by drew2a** [comment]
For this particular situation, I propose using a placeholder, based on the file's extension (auto-generated picture).

We discussed it with @xoriole and @kozlovsky.

**Comment by ichorid** [comment]
Is it gonna be infinite-scrolled or paginated?

**Comment by synctext** [comment]
infinate scroll is now the industry best-practice.

**Comment by ichorid** [comment]
> infinate scroll is now the industry best-practice.

Well, it depends... Google still uses pagination. The consensus here is that infinite scroll is better for variable-size items (e.g. Pinterest) and user engagement (e.g. Google Images), while pagination is better for navigation (e.g. Google search, webshops).

However, the biggest problem we got here is that infinite search is, ahem, infinitely slower with QT when implemented with standard widgets, because for every added widget the QT reactor adds all the necessary triggers, etc.

**Comment by qstokkink** [comment]
Given the latest GUI rework, this issue is no longer relevant.
