### ISSUE TITLE
Could not create circuit, no available exit-nodes

### ISSUE THREAD

**Issue by B00ze64** [Tribler/tribler#5971]
- [x] I have read CONTRIBUTING.rst
- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

##### Tribler version/branch+revision: #####
Tribler_7.7.1-63-g0c7f76f8d_x64.exe
##### Operating system and version: #####
Win7x64
##### Steps to reproduce the behavior: #####
Just selected a torrent (ubuntu) with lots of peers, with 1 anonymity jump.
##### Expected behavior: #####
Finds an exit node and downloads.
##### Actual behavior: #####
Endless Could not create circuit, no available exit-nodes (works fine with anonymity disabled.)
##### Relevant log file output: #####
[tribler-core-info.zip](https://github.com/Tribler/tribler/files/5901669/tribler-core-info.zip)

**Comment by drew2a** [comment]
Hi @Senemu, glad to hear that your issue has been resolved. 
For us to better understand the root cause, could you please elaborate on what specific settings you deleted? Did you only remove `triblerd.conf` or did this also include the GUI settings? Your response could help us prevent similar problems in the future. Thank you!

**Comment by drew2a** [comment]
@Senemu thank you for this information!

**Comment by drew2a** [comment]
We have made a lot of changes since the opening of the current issue. So, I hope the original problem is solved (at least we haven't seen it since then). If the problem occurs again, please try the latest release at https://github.com/Tribler/tribler/releases, and if the problem persists, please reopen the issue.
