### ISSUE TITLE
Trust statistics enabled without user testing while still broken.

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5999]
rm -r ~/.Tribler
apt install Tribler_v7.8.0.deb
Tokens starts at 0 (seems like an easy way to game the system if there is any penalty for <0 )
Leave Tribler running for a bit with 0 Torrents, then observe;

    Given = 385MB
    Taken = 488MB
    Tokens = -102MB

... think about it

Should Taken =0?
If not should Given=Taken?
even if there were some explanation for this (like some chunks are discarded as they were provided by another node first) that would mean that actively trying to contribute could have a net negative impact on ones tokens, making the feature counter productive.

#5917

#3657

#5807

#4939

**Comment by devos50** [comment]
Thanks for your feedback and continuous testing of our releases! Our main goal with this release was to fix the bug where the system would make erroneous amounts of payouts which, as far as I can tell, has fortunately not occurred yet.

There can be various reasons why your token balance is negative since there are many mechanisms at work in the background. When acting as a relay node for others, you would take a bit and give a bit, but this should eventually result in a positive balance (since you give more than you take). In addition, traffic that you use to download channel content is also accounted and paid for. I also do not rule out that it is a software bug related to the payouts (although with less impact than the bug in the 7.7 release).

I am thinking to implement an overview that breakdowns the evolution of ones balance, showing which payouts have been made and why exactly they have been made. There are some issues here because it's hard to trace it back to a particular download. This addition would make it more transparent to users how they exactly. In addition, we would like to increase the opportunities to earn tokens but for now we see this as a long-term issue.

**Comment by drew2a** [comment]
Given that we no longer employ trust calculations, it appears that this issue is now outdated. Consequently, I'll be closing it. Thank you for your understanding.
