### ISSUE TITLE
Gibibyte or gigabyte

### ISSUE THREAD

**Issue by noughtmare** [Tribler/tribler#6006]
It was a bit confusing for me to see different values in the trust statistics and the token balance. After a quick calculation I think the trust statistics graph in Tribler V7.8.0 is in gigabyte with the unit symbol Gbytes, but the Token balance is in gibibyte with the unit symbol GB. I would suggest showing both in gibibyte with the symbol GiB to avoid confusion.

**Comment by devos50** [comment]
Good find! This seems to be an inconsistency indeed. I did some debugging and it turns out that we are using autoscaling units as provided by `pyqtgraph`. This mechanism automatically divides by 1000 when increasing an order of magnitude, instead of 1024. Where possible, I would like to keep the byte units in Mbytes, Gbytes, ... since we are already using this notation throughout the GUI.

I haven't found any easy way to modify these units in our graphs easily. One solution could be to always show the vertical axis in the trust graph in Mbytes. This should provide enough granularity for users. @xoriole since you implemented this graph, do you have any suggestions for this?

**Comment by xoriole** [comment]
Good point. We can keep Mbytes, Gbytes for consistency across Tribler. I can update that in the next PR.

**Comment by devos50** [comment]
That would be great, thanks!
