### ISSUE TITLE
The run of pytest produces temp folders and keeps them after execution

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6158]
This is inconvenient for developers and will lead to decreasing amount of local test runs.

![image](https://user-images.githubusercontent.com/13798583/121006540-482c9a00-c791-11eb-8079-24d3260ea38e.png)

**Comment by devos50** [comment]
Tests should indeed never leave intermittent artefacts since they pollute the working directory and could conflict with subsequent test runs. IIRC, when using the `tmp_dir` pytest fixture, pytest cleans them up nicely, even if the tests fails. The IPv8 tests in Tribler (e.g., as implemented in the `TestRemoteQueryCommunity`) are also using temporary directories which seem to be not cleaned up properly.

**Comment by qstokkink** [comment]
`TestBase.temporary_directory()` only leaves behind its folders if you hard-crash the Python interpreter in such a way that it skips the `TestBase.tearDown()`.

If your tests crash as hard as this, they are extremely bad and deserve your immediate attention. The folder is left behind for your manual inspection, to see what went wrong and why.

That said, if you like pytest's `tmp_dir` better: use `tmp_dir` 🤷

**Comment by ichorid** [comment]
I completely agree that the original source dirs should **never** be touched by **anything** inside the testsuite. Thus, temporary dirs should be created in the specifically designated place, such as `/tmp/`

**Comment by qstokkink** [comment]
Putting temporary files in the source directory is not something we just randomly did. This stems from many many years pure agony, finding temporary files in "temp" directories that they should've been removed from.

Here's a nice one from 2018, where our Windows tester wasn't responding anymore due to a surprise 129GB in our `Temp` directory: #3867
Another mention in 2016: https://github.com/Tribler/tribler/pull/2007#discussion_r55204403

The only directory you can reliably read from, write to and delete files from on all platforms and all versions is the source directory.

Once again though, this is just why it is the way that it is. You're still welcome to use `pytest`'s `tmp_dir`.

**Comment by drew2a** [comment]
I've checked all the tests locally: seems that they work correctly (all generated data have been deleted).

I remember that a half year ago these tests kept generated data "as is". No matter of test results.

The screenshot below is from the `builder_tester_win64` machine. 

So, I will manually remove these files from `builder_tester_win64` and wait for a couple of days.

**Comment by qstokkink** [comment]
> The screenshot above is from the builder_tester_win64 machine.

❗ This is quite vital and possibly even more problematic than temp files on local developer machines.

Jenkins used to clean the workspace between runs to allow every test run to work from a clean environment (no matter what the previous run did). Temp files are placed in the source directory and are therefore part of the workspace, which should be clean. This could mean that our assumption that each test run is clean has been violated.

**Comment by qstokkink** [comment]
Confirmed. The Windows builder doesn't actually fully clean the workspace:

![afbeelding](https://user-images.githubusercontent.com/3630389/121322601-68826300-c90f-11eb-92cf-6bef51800bd7.png)

Only some selected stuff is removed.

**Comment by qstokkink** [comment]
By the way, the common file between all of these temp folders is a `.db` file. These files commonly get left behind if a database connection is not closed while ending the test (this disallows the file from being deleted).

We should inspect these test classes, to make sure the test `tearDown()` waits until the db connection is closed. Even better would be to use a memory database instead of a physical file.

**Comment by ichorid** [comment]
> Even better would be to use a memory database instead of a physical file.

We use in-memory DBs where possible. Unfortunately, by default SQLite will point all connections to the same in-memory database, meaning that testing e.g. two IPv8 peers with two distinct in-memory databases becomes impossible. There is an [option for the initialisation](https://www.sqlite.org/inmemorydb.html#temp_db) of SQLite connection for that, but Pony does not know how to pass those to SQLite. @kozlovsky ?

**Comment by qstokkink** [comment]
I changed the `PR_mac_pytest` and `PR_win64_pytest` to be equal to the `PR_linux_pytest` (simply wipe the whole workspace). Artifacts will no longer persist between test runs.

The `*_temp_*` folders will still be left behind on Windows due to the fact that the `.db` files can't be removed if they're not closed. This is still an open issue. However, now they will only stick around for a single run, instead of accumulating forever.

**Comment by qstokkink** [comment]
Just had a quick look at the offending test case classes. They all seem to spawn a `MetadataStore` which is unmanaged and therefore never shut down. The fix should be as easy as assigning these `MetadataStore` instances to a field (for example `self.mds`) for these three test case classes and calling `MetadataStore.shutdown()` on the `TestCase.tearDown()`. Something like this:

```python
async def tearDown(self):
    self.mds.shutdown()
    await super().tearDown()
```
