### ISSUE TITLE
Upgrade to Libtorrent 2.0.

### ISSUE THREAD

**Issue by Destroyinator69420** [Tribler/tribler#6184]
#### Please, fill all relevant items: ####

- [x] I have read CONTRIBUTING.rst

- [x] I have tried with the latest pre-release version and I still can reproduce the issue.

**Comment by devos50** [comment]
Thanks for the suggestion! This is definitely something we would like to explore further. However, since libtorrent is deeply integrated into Tribler, this likely requires (much?) more work than one might think.

Note that there is already a duplicate issue for this, see #5556. As such, I will close this one. Please continue the conversation on our existing issue 👍
