### ISSUE TITLE
We should consider showing torrent health in the 'popular torrents' tab

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6444]
See title. When I go to the 'popular torrents' page, I get a list of popular torrents. However, I'm unable to see _how_ popular they are exactly, i.e., is a particular torrent seeded by 10 or 1000 users?

Is there any particular reason why torrent health has been hidden on this page? If not, I would suggest showing this information 👍

**Comment by ichorid** [comment]
At first, the health column was there. But there was a problem: when clicking on the health indicator, the results were predominantly :red_circle: . The reason is simple:  [DHT health checks are slow and unreliable over tunnels](https://github.com/Tribler/tribler/issues/3065). So, we disabled the user's ability to click on the health bar. This proved to be rather frustrating, so we disabled the health bar at all.

I'm out of ideas here.

**Comment by devos50** [comment]
> Frustrating from a user perspective.

Did we receive feedback from users that they consider it frustrating (maybe I missed it)? Personally, I wouldn't mind if I was unable to recheck the health on a particular page. Of course, the preferred solution would be to fix the anonymous lookups.
