### ISSUE TITLE
Downloads table too wide

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#6452]
Our download table is too wide and does not fit into the default window size, which makes it hard to use. Other torrent clients limit the table width and only show the most essential info.
I propose shortening the downloads table to 4-5 columns and put the detailed info under the "Details" tab.

**Comment by devos50** [comment]
Interesting idea. I never actually had the need to browse to the right since some of the columns are just not very interesting (for example, the 'added on' or 'ratio' columns).

Instead of the anonymous column, we could display an icon, for example, a lock when the download is anonymous (maybe in the Tribler color?). This should save some space.

**Comment by ichorid** [comment]
Alternatively:
![Home_Layout](https://user-images.githubusercontent.com/2509103/140577376-966b3e7a-6769-4b15-abe0-a47bb31bf7d6.png)

**Comment by qstokkink** [comment]
Tribler now has a web-based front end and this issue is no longer relevant.
