### ISSUE TITLE
[Tests] GUI tests on Mac randomly fails with Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6564]
The full log: https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_GUI_macOS/3519/console

```python
Fatal Python error: Segmentation fault

Current thread 0x00000001086b95c0 (most recent call first):
<no Python frame>
/var/folders/9h/rc1ccw796x7dsjy2_nxjrxw40000gn/T/jenkins7492326316941345297.sh: line 11: 20855 Segmentation fault: 11  pytest src/tribler-gui/tribler_gui --guitests -p no:randomly -v --cov=tribler_gui --cov-report=xml
Build step 'Execute shell' marked build as failure
```

Error occurred during in https://github.com/Tribler/tribler/pull/6563

**Comment by devos50** [comment]
I did see this one earlier on my machine but it's very hard to reproduce and seems to happen randomly. A screenshot of the crash details as reported by MacOS:

![Schermafbeelding 2021-11-19 om 09 57 22](https://user-images.githubusercontent.com/1707075/142594616-9716ef6c-b2f7-46a3-b4ef-6a5c922267d8.png)

So this seems to happen during some cleanup procedures when exiting the Python interpreter. Searching for `sip_api_visit_wrappers` brings me to [this issue](https://github.com/spesmilo/electrum/issues/6889), reporting a similar crash. [Some more information](https://www.riverbankcomputing.com/static/Docs/PyQt5/gotchas.html#crashes-on-exit):

> When the Python interpreter leaves a scope (for example when it returns from a function) it will potentially garbage collect all objects local to that scope. The order in which it is done is, in effect, random. Theoretically this can cause problems because it may mean that the C++ destructors of any wrapped Qt instances are called in an order that Qt isn’t expecting and may result in a crash. However, in practice, this is only likely to be a problem when the application is terminating.
>
> As a way of mitigating this possiblity PyQt5 ensures that the C++ destructors of any QObject instances owned by Python are invoked before the destructor of any QCoreApplication instance is invoked. Note however that the order in which the QObject destructors are invoked is still random.

Since the stack trace does not provide any further useful information, this one can be pretty nasty to debug. It could be that we are mis-managing a particular `QObject` but given the sheer amount of objects in our application, we probably need to attach a debugger to the crashing process to determine which object is causing the crash.

Updating the version of Python/Qt/sip might also helpful.

**Comment by kozlovsky** [comment]
Good finding about the sip!

Seems related to:
https://gitanswer.com/pyqtgraph-segmentation-fault-during-garbage-collection-python-826318977
https://github.com/mantidproject/mantidimaging/issues/875
https://github.com/mantidproject/mantidimaging/pull/894

If I understand correctly, it is possible that the error happened not when the Python interpreter exits, but when pyqtgraph closes the ImaveView object. Then we probably can avoid segfault by changing the way we work with pyqtgraph.

**Comment by drew2a** [comment]
The error Stil occurred in https://github.com/Tribler/tribler/pull/6702
Console output: https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_GUI_macOS/3881/console

**Comment by drew2a** [comment]
Didn't see any segmentation fault errors for a long time.
