### ISSUE TITLE
Our Windows builder frequently leaves directories behind after the Tribler tests have finished

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#6603]
Our tests are writing files to the `/tmp` directory and are not properly removed, at least on our Windows 64-bit machine that run the tests. See the following screenshot:

![Schermafbeelding 2021-12-01 om 12 34 25](https://user-images.githubusercontent.com/1707075/144233491-b22a9a42-dd81-4573-80f9-514612e56343.png)

There seem to be two kind of directories that are left behind:

- Directories named with ~10 random characters: they contain the following items:
![Schermafbeelding 2021-12-01 om 13 06 18](https://user-images.githubusercontent.com/1707075/144233600-fb2e0993-26d3-4e13-9d25-0fab503b4424.png)
This makes me suspect that these directories are left behind by a test that does something with downloading (e.g., our lib torrent or channel tests).
- Directories that contain libtorrent metadata when doing DHT lookups. The directory is created [here](https://github.com/Tribler/tribler/blob/main/src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py#L143) and should be cleaned-up [here](https://github.com/Tribler/tribler/blob/main/src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py#L190).

**Comment by qstokkink** [comment]
For the second bullet point:

https://github.com/Tribler/tribler/blob/bd86c5ee5578606914654c76fc23843882ed6e1a/src/tribler-core/tribler_core/components/libtorrent/download_manager/download_manager.py#L143

This temporary directory should be managed by the test suite. At least during the tests, this temporary directory should be created by `pytest`. Otherwise, should anything go wrong, nothing is managing the directory.
