### ISSUE TITLE
[7.11 RC1] Search result items have the wrong height sometimes. 

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#6661]
**Describe the bug**
Search result items have the wrong height sometimes. I see this behavior in GUI Test Mode, but I'm guessing Tribler can behave this way during the normal run.

**To Reproduce**
1. Run Tibler in GUI Test Mode
2. Search for something
3. Wait for the result (don't press "Show Results")
4. See an error

**Screenshots**
![image](https://user-images.githubusercontent.com/13798583/146362011-ca53ff9e-0737-4939-823a-38bdae4e145e.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Tribler's version 7.11

**Additional context**
When I do window resize, everything back to normal:
![image](https://user-images.githubusercontent.com/13798583/146362637-a4f184e1-015f-4153-acc4-7b9120e4e524.png)

**Comment by drew2a** [comment]
@devos50 it could be a side effect of UI-for-tags change.

**Comment by devos50** [comment]
The issue seems to be that `index.model().name_column_width` returns a value of 0 when the table is not visible. This makes Qt think that each tag overflows to the next line when returning size hints for the row height. Scheduling a redraw after transiting from the intermediate search screen might help (I'll try it out).
