### ISSUE TITLE
Endpoints documentation pages empty

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#6674]
The read the docs pages for all the endpoints are empty. For eg.

https://tribler.readthedocs.io/en/latest/restapi/createtorrent.html
https://tribler.readthedocs.io/en/latest/restapi/debug.html

**Comment by drew2a** [comment]
Most likely the root cause for this bug is refactoring that was introduced in #6573 (or in the later refactorings).

And the reason for empty docs pages for all the endpoints is the following. 
During the documentation generation, we start `RESTManager`:
https://github.com/Tribler/tribler/blob/1a4e89be2bec998be006fec16095ff24908927e3/doc/extract_swagger.py#L21-L23

But the root endpoint doesn't have any endpoint because they are added in `RESTComponent`:
https://github.com/Tribler/tribler/blob/1a4e89be2bec998be006fec16095ff24908927e3/src/tribler/core/components/restapi/restapi_component.py#L90-L116

Therefore the build documentation process is successful, but there is no documentation for endpoints.

I'll try to fix this, despite the fact that the use case of using swagger for generation readthedocs documentation is a bit hacky and overwhelming.

**Comment by drew2a** [comment]
It works:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/13798583/177748885-99b07b73-8ef4-4526-9d50-f050d858274b.png">
