### ISSUE TITLE
Tribler crashes when a segmentation fault on Ubuntu 21.10

### ISSUE THREAD

**Issue by pdftk** [Tribler/tribler#6701]
**Describe the bug**
Tribler does not start. The terminal tells me Speicherzugriffsfehler (Speicherabzug geschrieben). Google translates this to _Memory access error (memory dumped)_

**To Reproduce**
1.Try starting Tribler in a terminal.
2. See error message

**Expected behavior**
Start tribler up.

**Screenshot**
Is attached.

**Desktop (please complete the following information):**
 - OS: Xubuntu 21.10
 - Tribler's version: 7.11.0

**Additional context**
Using sudo does not work either.
![Bildschirmfoto_2022-01-03_17-00-16](https://user-images.githubusercontent.com/7899947/147953153-5497bf2d-d21b-4817-9c9e-fe742c38ae65.png)

**Comment by devos50** [comment]
Thanks for your report! On Linux systems, we are logging the output of Tribler to a file in the `/tmp` directory. Do you see any logs in there with `tribler` in the name, and if so, could you please share these logs by either posting them here or by sending them to us by email?

**Comment by pdftk** [comment]
[marko-tribler-ANiJMCrR.log](https://github.com/Tribler/tribler/files/7803395/marko-tribler-ANiJMCrR.log)
Of course.

**Comment by devos50** [comment]
I don't see anything suspicious in the logs. I guess that Tribler crashes when it loads the 'core' component since it looks like the GUI manages to (partially) start. I'm not sure if we have tested Tribler on Ubuntu 21.10 but if not, we should and further investigate this. 👍

**Comment by devos50** [comment]
I just created a VM with Ubuntu 21.10 and Tribler indeed crashes with a segmentation fault. The stack trace:

<img width="873" alt="Schermafbeelding 2022-01-04 om 10 24 30" src="https://user-images.githubusercontent.com/1707075/148037486-4acba48f-2db8-43cf-bef4-3114c80d201f.png">

**Comment by scribblemaniac** [comment]
I have this issue as well. Wanted to add that while I had this issue with v7.11.0 installed from the deb package, I do not have this issue directly running src/tribler.sh from the v7.11.0 tag. I can't build the package myself so I can't say if that would make a difference.

**Comment by Fuzzillogic** [comment]
Since I have the same issue (but on Kubuntu 21.10), here's my output of `dpkg-query -l | grep -I qt5`:
[qt5-packages.txt](https://github.com/Tribler/tribler/files/7872500/qt5-packages.txt)

**Comment by scribblemaniac** [comment]
Mine has some differences:
[qt5-packages.txt](https://github.com/Tribler/tribler/files/7873584/qt5-packages.txt)

**Comment by xoriole** [comment]
Running the core with startup fixes resulted in the following underlying issue on Ubuntu 21.10.
```
undefined symbol: g_tls_channel_binding_error_quark
```
<img width="656" alt="Screenshot 2022-01-19 at 11 48 21" src="https://user-images.githubusercontent.com/1442867/150116221-b57e3f2d-dc16-4af2-a7da-8616d82f3a3c.png">

**Comment by xoriole** [comment]
Updates:
1. The segmentation fault occurs running the core only (with `--core` flag) which implies the issue lies on the core and might not be PyQt related.
2. Tried building a frozen tribler with ipv8 service as starter instead of `run_tribler.py`, the executable runs fine, see below. This excludes ipv8 as possible cause of the segfault.

![ipv8](https://user-images.githubusercontent.com/1442867/150969951-bdb48e7c-3eb7-4263-af32-e026ae4d0cdb.png)

3. Next library to check is `libtorrent`

**Comment by xoriole** [comment]
I tried an isolated libtorrent build, it worked fine. Since pyipv8 and libtorrent build both were running, I wondered why the core was failing when running with `--core` flag. To find that, I created a separate core build that executes the core only without going through `run_tribler.py` and `--core` flag. The independent core build actually worked without any segfault. 

This implies the following:
1) Our current mechanism of running core build still references the GUI components (eg. PyQt5) which we should fix.
2) The segfault is not caused the core and the earlier observation was wrong.

Upon further investigation, I found out that the  `undefined symbol: g_tls_channel_binding_error_quark` of `libgiognutls` is invoked by the GUI, QSocketNotifier. The cause actually being incomplete support for wayland (which exists on Ubuntu 21.04 +) on Qt build where our build only included support for QT_QPA_PLATFORM=xcb so far. So, fixing the support for wayland should fix the issue.

**Comment by drew2a** [comment]
> Our current mechanism of running core build still references the GUI components (eg. PyQt5) which we should fix.

I know two places that reference PyQt5:
1. https://github.com/Tribler/tribler/blob/285f7497229e8467606031218cede72d55b60e61/src/tribler-common/tribler_common/sentry_reporter/sentry_reporter.py#L250
2. https://github.com/Tribler/tribler/blob/285f7497229e8467606031218cede72d55b60e61/src/tribler-core/tribler_core/check_os.py#L104

Both of them use local import that triggers only in case of rare Tribler errors.

It is not clear what exactly should we fix.
