### ISSUE TITLE
"refusing to be exit node" log message may be confusing and seems to have overt log severity

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#6720]
**Describe the bug**
Logs in console include a lot of ["Dropping data packets, refusing to be an exit node"](https://github.com/Tribler/py-ipv8/blob/90c325e7dbf13649e13c3c0b6c303c67177969a4/ipv8/messaging/anonymization/tunnel.py#L194) messages with ERROR severity.

**To Reproduce**
1. Start Triber
2. Enable exit node mode
3. Observe logs.

**Expected behavior**
No "ERROR"-severity log flood (unless some actual error is happening with this Tribler instance).
Message about refused outgoing connection is more clear (does not suggest that exit node mode is not enabled in config) and has lower log severity.  

**Desktop (please complete the following information):**
 - OS: Linux
 - Triber 7.11.0, pre-built from Github releases.

**Comment by qstokkink** [comment]
This happens when an exit node receives data from the Internet, which it is refusing. This _should_ never happen as both the exit node and the originating peer agree on the type of data that will be exited (either only e2e hidden services data or BitTorrent data to the Internet). All incoming and outgoing messages of that type should then pass through normally. Throwing out random messages from a stream can lead to serious errors or degraded performance.

We can demote this to `WARNING`. However, we should also investigate whether we are throwing out critical data.

**Comment by vi** [comment]
May it be the reason of why token balance goes down and down the more I run Tribler despite of no anonymous bittorrent downloads happening (or uploads)  and exit node mode being active?

**Comment by qstokkink** [comment]
I would say that it is unlikely because the payouts are unit tested and we know from network crawls that there are exit nodes with huge token balances out there. The payout mechanism should also not be invoked when dropping data. That said, who knows, it may be some very rare bug.

**Comment by qstokkink** [comment]
I figured out one of the types of packets that was being dropped. I made an upstream issue for IPv8.

**Comment by drew2a** [comment]
@vi @qstokkink is this issue addressed in https://github.com/Tribler/py-ipv8/issues/1079 and could it be closed here?

**Comment by qstokkink** [comment]
That commit is not included in the latest IPv8 release yet. I guess it makes sense to close this issue for Tribler.
