### ISSUE TITLE
Tribler separates capital and not capital letters while sorting by name

### ISSUE THREAD

**Issue by kotenok2000** [Tribler/tribler#6721]
**Describe the bug**
Tribler separates 
**To Reproduce**
1. Go to discovered channels
2. Click on Name to sort by name
3. Scroll down 
4. See that tribler separates channels with name beginning with capital letter from channels with not capital letter.

**Expected behavior**
Tribler treats capital and not capital letter the same.
**Screenshots**
![Снимок экрана (108)](https://user-images.githubusercontent.com/8822292/149315011-f33a2348-2d6e-4078-a3ce-e033326a56df.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tribler's version 7.11.0

**Additional context**

**Comment by devos50** [comment]
This seems to be possible by using a [`QSortFilterProxyModel`](https://doc.qt.io/qt-5/qsortfilterproxymodel.html), and by adding `proxy_model.setSortCaseSensitivity(Qt.CaseInsensitive)`. The problem, however, is that we need to set this proxy model as the main model in `TriblerTableViewController`. The proxy model, however, does not have the attributes that the original model exposed (e.g., `data_items`) and we have to replace calls to `self.model()` with `self.model().sourceModel()`. This can be error prone since not all table logic is covered by the GUI tests.

**Comment by ichorid** [comment]
The sorting is done by Channels endpoint only. So, it should be fixed in SQL queries on the Core side.

**Comment by devos50** [comment]
Ah, I missed the server-side sorting part, thanks 👍

**Comment by kotenok2000** [comment]
Can you look at this issue too?
https://github.com/Tribler/tribler/issues/6712
