### ISSUE TITLE
master thesis - zero trust architecture for legal entities

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#6786]
t.b.d.
- Real code
- Superapp
- government agency? (AFM,DNB,RvIG,Enisa,VWS, ?)
- idea: eidas-high certification of our Trustchain wallet, see [commercial vendor details](https://www.electronicid.eu/en/blog/post/selfie-based-identification-solutions-not-compliance-kyc-aml/en) and another guide [with info](https://www.cryptomathic.com/news-events/blog/understanding-the-certification-authority-in-the-context-of-eidas). With a friendly notary, live streaming, and hardware PUF; we should/could comply.

(starting today, but 10 ECTS left)

**Comment by Nieuwlaar** [comment]
### Topic Funneling 1:

**Ministerie van Volksgezondheid, Welzijn en Sport:**
Project 1:
Improvement of MediTrail (https://repository.tudelft.nl/islandora/object/uuid%3A1774b1e9-3860-4a02-adaa-be9a92557169)
- Encryption of files (when MediTrail files leave the system, all data is unprotected)
- Integration Medic dossier on superapp
- Implement TrustChain transactions
- Connect MediTrail with 2024 EU passport 
Project 2:
Improving communication of the health sector
- Integrate TrustChain in communication between hospitals
- Secure document sharing between hospitals

**Autoriteit Financiële Markten:**
Project 3:
-	Integrate music ownership with passport linkage or other SSI

**PaperDAO**
Project 4
-	Make a DAO like MusicDAO for academic research
-	Integrate distributed crawling, ML, paper processing and filessharing 

**Rijksdienst voor Identiteitsgegevens:**
Project 5:
-	Implement a digital passport infrastructure / EBSI
-	Create a personal data vault
-	Integrate trusted data communication
Came across: https://github.com/Tribler/tribler/issues/6023#issuecomment-908311253

**European Union Agency for Cybersecurity (ENISA):**
Project 6:
-	Tbd (waiting for mail)

**De Nederlandsche Bank:**
Project 7:
- Experiment with a EuroToken issued by DNB
- Issue an actual authority-backed digital Euro?

### Projects still in the funnel of interest: 4, 5, 6, and 7.

**Comment by Nieuwlaar** [comment]
### Status update:

- Applied for [ENISA Traineeship](https://www.enisa.europa.eu/recruitment/vacancies/traineeship-notice-3/application_submission)

**Read:**
- General background information of eIDAS, ENISA, digital Euro and SSI.
- [ENISA - Trust Services Security Incident 2020 - Annual Report](https://www.enisa.europa.eu/publications/trust-services-security-incident-2020-annual-report)
- [ENISA Report - Digital Identity - Leveraging the SSI Concept to Build Trust](https://www.enisa.europa.eu/publications/digital-identity-leveraging-the-ssi-concept-to-build-trust)
- [ENISA Report - Remote Identity Proofing - Attacks & Countermeasures](https://www.enisa.europa.eu/publications/remote-identity-proofing-attacks-countermeasures)
- [Industry-Grade Self-Sovereign Identity](https://repository.tudelft.nl/islandora/object/uuid%3A32711378-2f6f-452e-b65c-1866c471e934?collection=education)

**Comment by synctext** [comment]
- Proposal: we take exactly 1 month, until 11 April at 11:11am for a deep-dive into the **viability** of eIDAS high compliance
- Currently unknown regulation with unknown technical component, and unknown reliance on paper-document procedures written in lawyer-speak.

**Comment by Nieuwlaar** [comment]
Status update:
Contacted Jean-Paul Bakkers from BZK, Geert-Jon Jepkes, IT architect eHerkenning and involved in DigiD eIDAS notification, and Bob Hulsebosch, process manager during DigiD hoog notification. From research and this contact, it can be concluded that creating a decentralized eIDAS high compliant standard and implementation is infeasible in a master thesis project, because of the following reasons:
- Most failed eIDAS level of assurance requests are kept secret (the applicant can choose to keep the eIDAS request secret).
- Self-assessment of TrustChain with respect to assurance levels indicates an overall level of assurance of ‘none’.
- The notification procedure requires a lot of communication and paperwork toward EC and Cooperation Network (peer review commission, consisting of around 15 to 25 members from all EU Member States).
- The notification procedure (pre-notification, peer review, notification, publication, and mandatory recognition) takes at least a year.
- Peer review process tends to take longer when innovative ideas are requested. Storing data in a SE or TEE on mobile phones is considered as innovative and requires a lot of proofing that the data is handled secure.
- No decentral eIDAS ‘high’ compliant service currently exists. Sovrin has a roadmap to comply to eIDAS ‘high’ which started from January 2019 and should have been finished before 2022, but as of today Sovrin is not eIDAS ‘high’. Furthermore, another decentral SSI from Catalan, Spain (IdentiCAT, with 550.000 euro budget) was expected in early 2020, but at the moment is nowhere to be found. 
- eIDAS level of assurance requirements require central control (e.g., central revocation of keys)
- Many unforeseen problems are expected when creating a standard for decentral eIDAS ‘high’ services and applying for eIDAS ‘high’ without the supervision of someone (BZK, ENISA, DigiD, eHerkenning) who has eIDAS compliance experience.

**Comment by synctext** [comment]
Goal:
- get a government position (or EU level)
- get a minimal viable wallet operational from our Superapp efforts (strip&doc ?)
- Remove all decentralisation and replace with "offline disaster-mode", no-Internet-needed, always-works storyline, in-case-of-central-server failure, critical infrastructure reliability, backup mode.
- Explore adopting use-case stakeholders, digital drivers license, UZI pas, digital Euro, stable coin is now dollar dominated, Euro DAO, and a operational KYC with machine learning; innovation-on-top.
- prepare for a 3-year long project with mandatory EU-wide acceptance of TUDelft technology. Open source critical infrastructure with end-to-end verifiable security :wine_glass: :1st_place_medal: :beers:

**Comment by Nieuwlaar** [comment]
- Contacted potential use-case stakeholders, following have my CV, are interested, and know I need assistance in eIDAS compliance (I have sent them this issue as well); RDW, VWS, CIBG, BZK, ENISA, Logius, RvIG, ICTU, and more. No concrete collaboration has emerged from this for now.
- Created a new app called IDelft within the superapp
- Currently working on adding functionality from the valuetransfer app into IDelft, specifically the onboarding of IDs and passports (not functional yet)

**Comment by synctext** [comment]
- 100% certain we can get you into .GOV (afm,kvk,rvig, etc.)
- Prior work by Tim on access and legal entity matters: https://repository.tudelft.nl/islandora/object/uuid%3Aaab1f3ff-da54-47f7-8998-847cb78322c8
- after 9 weeks you are now getting the required knowledge on what is novel and whats done before.

**Comment by Nieuwlaar** [comment]
Brief summary of the findings in these four directions:
- The token route is the previous idea of creating an eIDAS high compliant implementation (identity proofing at 'high' level of assurance), creating such a token is infeasible in a MSc thesis.
- Biometrics route: For eIDAS 'high', only facial/fingerprint recognition can be used for ID proofing (facial is preferred). Facial recognition requires a lot of proofing of security in eIDAS peer review. Seems like a very nice next step once there is a basis for eIDAS ID proofing. 
- DAO route: Difficult to find bridging information on DAO and KYC. However, an interesting use case may be a decentralized cryptoexchange complying to Dutch law (Wet ter voorkoming van witwassen en financieren van terrorisme en Sanctiewet 1977) which implies ID proofing. 
- Signature route: 3 different types of electronic signatures: Simple, advanced and qualified. Seems like a nice use case where each type can be implemented gradually. Goal TU Delft having a qualified signature creation device (QSCD)(required for generating a qualified signature). Even better: TU Delft being able to provide QSCDs by obtaining rights to issue QSCD certificates, in other words become a qualified trust service provider (QTSP) (unsure about feasibility, however, if TU Delft = QTSP, all TrustChain peers QSCDs?). Qualified signatures are legally equal to so called 'wet' signatures.

More information can be found in Section 4:
[survey_eidas_high_compliance (1).pdf](https://github.com/Tribler/tribler/files/8768865/survey_eidas_high_compliance.1.pdf)

**Comment by synctext** [comment]
- Doing SSI after DigiD is too ambitious
- Grand challenge for government will be digitisation, they dont have the people and are obsessively focused on legal matters. 
- Blockchain and AI are going at "warp-speed", compared to government pace of innovation.
- Investments in AI, machine learning and robotic process automation (RPA) technology are set to reach $232 billion by 2025, [a new report](https://www.itproportal.com/news/ai-investment-will-hit-dollar232-billion-by-2025/) from KPMG has shown. A skills shortage and lack of common infrastructure is dampening progress.
- Delft University has 50 master student / year as "_production_". [We are highly ranked](https://www.coindesk.com/learn/2021/10/04/the-top-universities-for-blockchain-by-coindesk-2021/). Simply combining

**Comment by Nieuwlaar** [comment]
- Applied for an internship at Logius in the eIDAS team (expected response: This week)
- Build a working pruned version of the valuetransfer app with ID boarding (not included in the video due to ID details): 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34306523/172608549-0a69bb1b-3009-410f-a765-632de1bc7a48.gif)

**Comment by Nieuwlaar** [comment]
Update:
- Spoke with Ka-Kin Fung from the eIDAS team of Logius, he finished 7 peer reviews of eIDAS compliance. If TU Delft were to go for an official eIDAS 'high' peer review, interesting to learn from his and his team's findings (Some of these peer reviews he did with the aforementioned Geert-Jon Jepkes). They did the whole process for DigiD. Pilots are never peer reviewed. Decentralized eIDAS identification has never been peer reviewed before. [All public peer reviews here.](https://ec.europa.eu/digital-building-blocks/wikis/display/EIDCOMMUNITY/Overview+of+pre-notified+and+notified+eID+schemes+under+eIDAS)
- Identification is one of the pillars of trust in many use case, also at the KVK. Hence I think it would be nice to dedicate a chapter to identification with an outline of the current eIDAS situation, a look into the 'futuristic' eIDAS2 legislation and other upcoming laws, and a strong focus on the ultimate goal of a decentralized eIDAS 'high' compliant solution.
- Started at the KVK, enjoying it very much. Currently, having meetings with many people to get into the KVK ambiance.
- KVK has a very interesting SSI and Proof of Attorney (Machtiging) use case that can be developed. It concerns RDW's numberplate addition/suspension machtiging which is recorded in the KVK Handelsregister. KVK InnovationLab wants to build a SSI solution to learn from Proofs of Attorney in a SSI environment. So far the topic has been discussed within the team and RDW, and they decided they want [Microsoft's SSI wallet](https://docs.microsoft.com/en-us/azure/active-directory/verifiable-credentials/decentralized-identifier-overview) to be used. I think this use case is more interesting than a Sligro one, this use case considers an actual legal binding machtiging! Would very much like to do this, wondering if that is ok?
- I wrote the introduction and draft problem description (Introduction is pretty ok, the problem description will be redone completely, I will repost once finished) [Here](https://github.com/Tribler/tribler/files/9100417/MSc_Erwin_Nieuwlaar_10.pdf) is my work so far.
- Wondering what you think of below's schematic overview as "het rode draad" of my thesis?:
![image](https://user-images.githubusercontent.com/34306523/178685338-e12b7f5a-c2c3-4035-be44-dc09ca673fda.png)

**Comment by synctext** [comment]
inspirational update, good efforts.

"Deploying pillars of trust: eIDAS2, Trustchain, IPv8, and EBSI"
That is worthy of a solid master thesis focus! Linking various sources-of-legal-truth,  tamper-proof ledger storage, quantum-proof IPv8 communication, and root-of-trust from EBSI.
Uncompromising open source.

**Comment by Nieuwlaar** [comment]
- Wondering which journals would be interested in publishing my work, if everything works out. At the moment I thought [Elsevier Blockchain](https://www.journals.elsevier.com/blockchain-research-and-applications), [IEEE Blockchain](https://blockchain.ieee.org/), [ACM Digital Government](https://dl.acm.org/journal/dgov) or [ACM Distributed Ledger](https://dl.acm.org/journal/dlt) might be interesting. 
- Is it perhaps interesting to have an (associate/assistant)-professor from TPM in my graduation committee, as a part of my work implies law and society? (I did a decentralized identity management literary project under the supervision of Jolien Ubacht last year)

**Comment by synctext** [comment]
Dutch government already has trouble keeping up with the pace of innovation in Europe. Sadly we even want to have a "[Dutch flavour](https://www.digitaleoverheid.nl/nieuws/praat-mee-over-de-europese-digitale-identiteit/)" to the European Identity and eIDAS 2.0 legal framework.
```
Programma EDI Stelsel NL
Om dit te realiseren moet er een stelsel voor Europese digitale identiteit in Nederland worden ingericht. Hiervoor zet het Programma EDI Stelsel NL van het ministerie van BZK nu de eerste stappen. Veel moet nog worden uitgezocht, maar 1 ding is zeker: het stelsel wordt ingericht op basis van een open houding en zoveel mogelijk co-creatie.
```

Current methodology is to try to avoid these fragile "grand visions" and meticulously use a small "use-case" based approach. By limiting the scope we increase realisation 

ToDo: the IEEE writing style pointers

**Comment by Nieuwlaar** [comment]
- Fixed crashing dialogs in Superapp [#118](https://github.com/Tribler/trustchain-superapp/pull/118)
- Changed some appearance of ValueTransferapp/ConfIDapp. Introduced [IDelft](https://user-images.githubusercontent.com/34306523/190116739-d019bb5b-3eab-4c57-8d08-a3a82b0772cf.png) (also in [#118](https://github.com/Tribler/trustchain-superapp/pull/118))
- Created [happy flow](https://user-images.githubusercontent.com/34306523/190117387-77a28b21-fd40-4311-b06f-a3332d135d4d.png).  Prerequisite of happy flow: KVK credentials are already written on EBSI
- Working on getting the right access from KVK and RDW to use their data. Trying to get access to actual production data from KVK (very uncommon; KVKs own implementation uses pre-production), RDW will never provide production data access for PoCs/MVPs, will use RDW pre-production or public data (RDW developers use this as well)

**Comment by synctext** [comment]
- solid progress
- You now have the beginnings of a use-case to build your entire master thesis on
- Identified the key stakeholders within both RDW and KvK
-

**Comment by Nieuwlaar** [comment]
- Met with Sharif, he showed his progress. His [VC EBSI compliance](https://ec.europa.eu/digital-building-blocks/wikis/display/EBSIDOC/Verifiable+Credentials+Lifecycle) is different than the[ Credential Issuance compliance](https://ec.europa.eu/digital-building-blocks/wikis/display/EBSIDOC/Credential+Issuance+Guidelines) which I would need. KVK schould become a Trusted Issuer(have not looked too much into detail at this yet). Looking forward to his PR.
- Want to create EBSI's first layer 2 network using IPv8, TrustChain and Rowdy's work (world's first legal backed layer 2 network?). Overview is given in Figure 1, and happyflow in Figure 2. 
**Figure 1:**
![Figure 1](https://user-images.githubusercontent.com/34306523/192838377-20295e44-053f-4c1f-8b86-6d0c98f08f0a.png)
**Figure 2:**
![Figure 2](https://user-images.githubusercontent.com/34306523/192838659-fb8c2fb4-b488-4b46-bb5e-2caa02226d18.png)

- Currently busy with merging Rowdy's work regarding [IPv8](https://github.com/Tribler/kotlin-ipv8/pull/65) and [superapp](https://github.com/InvictusRMC/trustchain-superapp/tree/communication_protocols) to make the EBSI layer 2 possible. This will take some time, [current progress here](https://github.com/Nieuwlaar/trustchain-superapp/tree/rowdy_6).

**Preliminary answers to issues mentioned in previous meeting (performance analysis, deployment and thesis challenge):**
Performance analysis:
- Evaluate how large the chain of attestations be
- Evaluate time to revocation of n-size-attestation-chain

Deployment evaluation:
- Create KVK attestation on EBSI and use this as trust anchor for layer 2 chained attestations
- Ability to revoke the whole chain

Technical challenge solved:
- Not everyone can be an EBSI Trusted Issuer, but in layer 2 you can with an anchor to a Trusted Issuer
- [Formulier 13](https://www.kvk.nl/download/Formulier-13-inschrijving-gevolmachtigde_tcm109-365579.pdf) which can be used for this but is highly inefficient becomes obsolete with regard to attestations (KVK centralized)
- Privacy by design attestations with EBSI anchored trust

Next sprint: Hopefully merge Rowdy's work and start [EBSI credential issuance compliance.](https://ec.europa.eu/digital-building-blocks/wikis/display/EBSIDOC/Credential+Issuance+Guidelines)

**Comment by synctext** [comment]
- [EU Large Scale Pilot, NL EDI view](https://edi.pleio.nl/groups/view/b3d6dbc0-959c-4c07-9048-14fb9f736bcd/edi-programma-algemeen/wiki/view/37573324-b007-437d-949a-e06957f162db/potential)

**Comment by Nieuwlaar** [comment]
- Requested eHerkenning
- KVK will have a DID in the EBSI Trusted Issuer Register (expected this week)
- Building upon the PR/work of Rowdy's attestations
- Communicating with EBSI to resolve issues I am having with regard to authorization and authentication (most likely an outdated documentation issue)
- Working on EBSI functionality, currently able to create and bind DIDs in console:
<img width="504" alt="DID_registered_complete" src="https://user-images.githubusercontent.com/34306523/197331687-0bc41c89-3ec5-4717-8e4d-63b7ffef28fc.png">
- Getting used to the EBSI structure (quite a lot of possibilities). The API structure:
<img width="602" alt="ap_structure" src="https://user-images.githubusercontent.com/34306523/197331826-789d6dfe-618b-499d-a7d3-c9b7f5cc8bdd.png">


Next sprint: Create and bind DID documents within superapp.

**Comment by Nieuwlaar** [comment]
- KVK DID is added to the EBSI Trusted Issuer Registry 😄: `did:ebsi:zgbNBgEqAwNMYV1T9MtUmSk`
![image](https://user-images.githubusercontent.com/34306523/197577728-a72d4f9c-66eb-4e92-890b-6ec264e004a6.png)

**Comment by Nieuwlaar** [comment]
- There are three categories to obtain rights and obligations (R&O) with regard to authorizing (machtigen); attribution, mandating, and delegation. 
- Attribution: R&O obtained from law
- Mandating: R&O obtained from legal/natural person mandating. Responsibility remains at the person mandating.
- Delegation: R&O obtained from legal/natural person delegating. Responsibility goes to the delegated. The delegates (he/she who delegated) can no longer exercise authority.
- Within a company, mostly mandating is done (not delegation).
- As well as the KVK RDW use case as the replacement of eHerkenning concerns mandating. Therefore, will focus on legally bound mandating for now (adding legally binding delegation later is not a big step. Technologically, delegating is easier. The difference is who consents to the delegation/mandate. Most incentives focus on delegation while mandating seems to be much more applicable in the real world)
- Getting very close to writing VCs to EBSI

**Comment by Nieuwlaar** [comment]
![image](https://user-images.githubusercontent.com/34306523/200527778-ef8006d7-d1bb-4bf1-8684-aed4f59b45e5.png)
- Fixed confidapp crashes
- New logo/name: confidapp -> IDelft

**Comment by Nieuwlaar** [comment]
The previously mentioned statements regarding rights and obligations are all true, but concern public law. In the eHerkenning, RDW, and Makro/Sligro use case the legal basis is private law (as it concerns machtigingen within a company). The previous wrong statements have been striked through. The correct notion of machtigen within a company is "power of attorney", in case this power is limited it becomes a "special power of attorney". As I want my work to be legally binding, I found it useful to correct and explain this.

**Comment by Nieuwlaar** [comment]
- Integrated KVK HRM database service
- Superapp is now able to receive/store KVK-signed truth
- Loaded the first Powers of Attorney in superapp (see .gif)
- Created PoA structure
- Started with backend communication of PoAs for sharing (doormachtigen) between peers
- Stumbled on more issues with EBSI (Trusted Schemas Registry)
- Implementation of EBSI in superapp is a master thesis in itself. Perhaps very interesting for TU Delft and KVK with an eye on GLEIF and Eurochambres
- Focussing on making a decentralized alternative of eHerkenning with irrefutable truth from KVK
- With this system, all authorizations can be managed decentrally, causing a huge system change (if desired, all roles/powers/authorizations within any organization can be defined within the superapp, endless possibilities)

Next sprint:
- Create presentation of PoAs (in QR format, for easy sharing)
- Create visualization of complete PoA (in the same dialog as PoA presentation)
- Enable verification of PoA (QR scanner integration)
- Add a pop-up to approve a receiving PoA
- Solve the RDW issue/use case
- Design how all communication will be cryptographically secure (confidentiality, data integrity, authentication, and non-repudiation/irrefutability)
- write problem description

Thereafter:
- Implement cryptographic security
- Implement revocation
- Finish thesis

<img src=https://user-images.githubusercontent.com/34306523/206278970-79842bde-dfd0-466a-b1ac-8ebf512fd770.gif width=200>

**Comment by synctext** [comment]
Can you give some advise for the future for us as a lab?
What has long-term future? Empower citizens, give them control over their digital lives or help businesses with new digital government services, which are still immature. The Chamber of Commerce has 48 products (roughly), yet the inherent system complexity is limited. The digital transformation of this organisation is not yet as far as RDW? EBSI alternative for parts of expensive eHerkenning?

**Comment by Nieuwlaar** [comment]
[apk_poa](https://drive.google.com/file/d/14ksCI61FXEyvLkG8Hj9xazTdKZKHTi3p/view?usp=sharing)

**Comment by Nieuwlaar** [comment]
Mashed my previous work [survey_eidas_high_compliance (2).pdf](https://github.com/Tribler/tribler/files/10368652/survey_eidas_high_compliance.55.pdf) and
[MSc_Erwin_Nieuwlaar (36).pdf](https://github.com/Tribler/tribler/files/10368653/MSc_Erwin_Nieuwlaar.43.pdf) into a few sentences. They are now included in the current document: [MSc_final (53).pdf](https://github.com/Tribler/tribler/files/10368659/MSc_final.63.pdf)
- Wrote Problem Description
- Wrote System Architecture
- Tried to be as brief as possible (maybe too brief?)

> Can you give some advise for the future for us as a lab?
- Remote identifying at eIDAS level of assurance (LoA) high is gold (potentie om alle fysieke balies in de EU te vervangen) (PhD level)
- Combining the above with a LoA high authentication to local private keys (secure element integration), creating a tamperproof protocol that incorperates: "something you know (PIN), something you have (Phone), something you are (Biometrics/something centralized)" including loss of 1 of these. This is a problem EDI will have to deal with and is not solved yet.
- EU reference wallet will soon be available, adding EU wide Legal Entities to this wallet would be nice for TU Delft. Proving that brokers and QTSPs may not be needed in the new digital identity era. Alternatively, let a master student hack/exploit this wallet. 
- KVK will most likely partitionate in 2 LSPs regarding EDI ([POTENTIAL ](https://www.digital-identity-wallet.eu/)and [EWC](https://eudiwalletconsortium.org/)), a anual graduation project at the KVK is interesting to keep updated regarding EDI and the legal entity perspective thereof.
> what is your 1 year dream assignment {external phd???,LSP}?

Do LSP at KVK. If turns out not challenging enough: add external phd

**Comment by synctext** [comment]
- Your scientific contribution: portable trust. Get to the point a bit more quickly. Like: our architecture is build around a new primitive irrefutable cryptographic proof that a natural person is a legal representative of a company.

**Comment by Nieuwlaar** [comment]
- [EBSI early adopters programme re-opened](https://ec.europa.eu/digital-building-blocks/wikis/display/EBSI/Early+Adopters), perhaps interesting for funding / new MSc project
- Rewrote abstract and introduction: [MSc_final_E_Nieuwlaar.pdf](https://github.com/Tribler/tribler/files/10517764/MSc_final_E_Nieuwlaar.pdf)
- Will rewrite Problem Description based on trust for legal entities, will argue that current trust/verification is very unportable (and many other issues). Figure to show current legal entity representation (fig 1 of thesis):

![overview_identity_legal_entity_binding](https://user-images.githubusercontent.com/34306523/215062115-1f765865-c739-420d-92ed-3c6d442fa360.png)
- Implemented PoA verification:
![Studio_Project (1) (1)](https://user-images.githubusercontent.com/34306523/215064905-c9809cce-b003-4df3-b947-fb741102a094.gif)
- Implemented Chained PoAs including revocation (video too lengthy for gif):
https://user-images.githubusercontent.com/34306523/215063555-385b5ba7-00a0-4a0d-b9c5-e02800036a6c.mp4

Current idea for Performance Analysis:
- Measure speed of calls to KVK pre-prod server (for multiple devices on wifi and 4G)
- Measure speed of PoA issuance (for multiple devices on wifi and 4G)
- Measure speed of PoA revocation (for multiple devices on wifi and 4G)

**Comment by synctext** [comment]
- Consider a more scientific intro: a primitive for a new economy. [zero-trust computer security concept](https://en.wikipedia.org/wiki/Zero_trust_security_model) is not explained. Could be the whole intro. Zero trust architecture in US context not mentioned. Dream: security based on the laws of physics and mathematics. Fraud is astronomical unlikely.
- ```Fig. 1. Current situation of organization representation```, this is engineering. Lacks scientific grandeur.

**Comment by Nieuwlaar** [comment]
- [Thesis draft](https://github.com/Tribler/tribler/files/10930457/MSc_final.27.pdf)
- Makro live demo will be on the 20th of March at their HQ
- Met with Jolien, and incorporated her feedback into my draft thesis
- Made flame charts (one of them in the draft)

Things that I think are left to do:
- Add Makro demo picture
- Polish text/layout of thesis
- Final presentation

**Comment by synctext** [comment]
- ```Our reference implementation focuses on creating a peer-to-peer protocol while integrating the Member State Chamber of Commerce Company Register of the Netherlands (KVK) to serve as the root of trust and the Makro as a verifier.```. too complex. With government assistance we conducted a pilot deployment of our prototype with live connectivity to the legal source of truth, the chamber of commerce. A commercial retailer acted as the verifier of the  PoA with EBSI acting as the legal root-of-trust.

**Comment by Nieuwlaar** [comment]
- Current status: [MSc_final.pdf](https://github.com/Tribler/tribler/files/11177104/MSc_final.45.pdf)
- Makro demo on the 14th of April

**Comment by synctext** [comment]
- Nearly done :tada: 
- :heavy_check_mark: all forms ready for 26 April defence.
-

**Comment by Nieuwlaar** [comment]
[draftslides5.pdf](https://github.com/Tribler/tribler/files/11311259/draftslides5.pdf)

[Uploading MSc_Erwin_Nieuwlaar (12).pdf…]()
