### ISSUE TITLE
Ability to add/remove Trackers

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#6792]
**Is your feature request related to a problem? Please describe.**

Want to add/remove trackers on my torrents.
Cannot do so, as no option available. This is surprising considering every torrent client provides this option. 

**Describe alternatives you've considered**

**Here are the screenshots to better describe the issue.**

**Trackers add/remove option provided by another torrent client - by right-clicking.**

![Untitled](https://user-images.githubusercontent.com/97702149/156311261-17a470ad-ed85-43cd-827c-e86ec802d5e2.png)

**No option to add/remove trackers in Tribler - even after right-click or left-click.**

![Untitled1](https://user-images.githubusercontent.com/97702149/156311394-d4276e75-f356-48ea-8fe5-e6c33fd1e3bf.png)

_____________________________________________________________________
**EDIT** :- Is it even necessary to add trackers? I mean DHT is perfectly capable of handling most of the work which Tribler pursues or has pursued.

**Comment by absolutep** [comment]
any update on this?

**Comment by drew2a** [comment]
@absolutep hi! 

As far as I know, this issue is not on the priority list.
Unfortunately changing Tribler's GUI is not an easy task.

From the Tribler Core's side, it is trivial. 

Refs:
* https://github.com/arvidn/libtorrent/issues/2776
* https://libtorrent.org/reference-Torrent_Handle.html#replace-trackers-add-tracker-trackers

**Comment by absolutep** [comment]
okay!
closing this issue then
