### ISSUE TITLE
Add Magnet Dialog disappears until restarted 

### ISSUE THREAD

**Issue by HurriedPatience** [Tribler/tribler#6884]
**Describe the bug**
The "Import torrent from Magnet/URL" dialog disappears until restart.

**To Reproduce**
1. Go to 'Add torrent'
2. Click on 'Import torrent from Magnet/URL'
3. Click Tribler somewhere off that dialog.
4. Then Click on 'Import torrent from Magnet/URL'
5. You won't see that dialog anymore.  No matter what else you do.
6. Until you restart

**Expected behavior**
That dialog shouldn't 'hide'.  Either cancel that dialog when focus lost or make it modal.  The former option would be similar to two other dialog behaviors, see below.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 10 latest
 - Tribler's version 7.11.0

**Additional context**
The other similar dialogs don't have this behavior like "Create torrent from file" nor "Create channel".  Both of these Cancel.  Could this be related to https://github.com/Tribler/tribler/issues/6597?

**Comment by drew2a** [comment]
@HurriedPatience thank you for reporting this bug.

From my understanding, this bug is not directly related to #6597 although it also shows the inconsistency of dialog logic.

The root cause of this bug is`self.add_torrent_url_dialog_active` logic:

https://github.com/Tribler/tribler/blob/17e28f604026e8fe82dd810a278495a4aa3d6ed0/src/tribler/gui/tribler_window.py#L1017
