### ISSUE TITLE
Tribler interface seems wonky

### ISSUE THREAD

**Issue by dtantono** [Tribler/tribler#6973]
**Describe the bug**
I use both Linux and Windows. But, the Windows version seems wonky, and I cannot find the setting button. 

**To Reproduce**
1. Go to Start menu
2. Search on Tribler
3. double click on Tribler icon
4. I cannot find the setting

**Expected behavior**
The UI should should similar with the Linux version

**Screenshots**
![image](https://user-images.githubusercontent.com/29157187/179384233-2fad91ea-b9fe-4bff-b110-b63c87541160.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tribler's version 7.11

**Additional context**

**Comment by devos50** [comment]
Thank you for your report. It looks like the Tribler window is bigger than the screen size. I remember that we have some checks to see if this is the case, and automatically resize the window to fit the display screen. We might want to check this logic.

**Comment by drew2a** [comment]
@devos50 the logic seems to work fine.

@dtantono could you please provide more information about your case (Tribler logs, screen resolution, number of displays)? Then we can figure out the root cause of the problem and fix it.

Note: on your screenshot, I see the "downloads page" which is strange to see right after "double click on Tribler icon" (point four on your "steps to reproduce" list), if it is a mistake, please correct the list.

**Comment by dtantono** [comment]
I have three monitors and all of My screen resolutions are: FHD 1920x1080 also it looks like the app UI overstretching my three monitors. if you mean the tribler log I can find it in C:\Users\AppData\Roaming\.Tribler\7.11\log
<img width="2880" alt="Untitled" src="https://user-images.githubusercontent.com/29157187/185106826-1002badd-6c52-42a9-900f-557aaa21b761.png">
[resources.log](https://github.com/Tribler/tribler/files/9359114/resources.log)



![image](https://user-images.githubusercontent.com/29157187/185105925-2dc2d7bc-dbe0-4567-b684-226c43c9810a.png)
