### ISSUE TITLE
msc placeholder: daos, scams, FROST, message drop, something

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7074]
- First literature survey! then msc
- this quarter 1.5 courses.
- did initial brainstorm
- interest in FROST
- cryptocurrencies, P2P in general
- Martijn chat about FROST
- Read about Gitcoin, consitutionDAO, etc.
- ToDo: [read into DAO papers](https://scholar.google.com/scholar?hl=en&q=dao+~autonomous)
- identify open search issues.
- coding skills: loves coding, hackthon level.
- Thesis idea: lots of various topics, not a single deep dive, full stack engineering (e.g. product launch)?

**Comment by rahimklaber** [comment]
This is a short draft of my idea:  [Are_Daos_A_Scam_draft.pdf](https://github.com/Tribler/tribler/files/9746682/Are_Daos_A_Scam_draft.pdf)
Bassically, I want to give an overview of what DAOs are and the issues they have.

I've also read some papers, but most of the interesting things are found outside of papers on blogs or articles.
Some of the stuff I found interesting:
- https://decrypt.co/38050/steem-steemit-tron-justin-sun-cryptocurrency-war
	-  Someone was able to take over a blockchain by acquiring enough votes.
- https://www.cnbc.com/2021/10/03/162-million-up-for-grabs-after-bug-in-defi-protocol-compound-.html
	- A bug in Compound allowed more tokens to be claimed than was intended. The bug took a while to be fixed, since it involved passing a governance proposal.
- https://dxdocs.eth.limo/docs/Governance/REP/
	- DAO members are rewarded with reputation for contributing to the DAO. Reputation is non-transferable and decayes when member is inactive.
- Many DAOs seem to rely multisig schemes. So you end up with situation where a small amount of people control the DAO, or atleast can do some harm.

**Comment by synctext** [comment]
This angle is difficult to bring in the science. More scientific example are going into these type of [algorithms to generate trust](https://arxiv.org/pdf/2207.09950.pdf) or another wild angle is [technology is becoming political; see Susskind book](https://www.theguardian.com/books/2022/jun/19/the-digital-republic-by-jamie-susskind-review-why-the-west-was-no-match-for-the-tech-giants).

**Comment by rahimklaber** [comment]
### lit survey
this is what I currently have [lit_survey_current.pdf](https://github.com/Tribler/tribler/files/9901778/lit_survey_current.pdf).
I combined what I was doing previously with researching DAOs' governance procedures.
I couldn't really find a scientific angle + my writing is still not that good ☹

### thesis

Do we really need to use FROST? Depending on what improvements FROST made over its predecessors, it might be worth it to use older schemes as they already have mature implementations. I found a go [library ](https://github.com/bnb-chain/tss-lib) that allows creating threshold signatures for ECDSA and EdDSA. Then we could use [go mobile](https://github.com/golang/mobile) to call it from android.

**Comment by synctext** [comment]
Solid idea! Somehow I failed to read more, after seeing FROST. I just wanted it after reading. :smile: 
- https://github.com/ZenGo-X/gotham-city#abstract
- https://github.com/unboundsecurity/blockchain-crypto-mpc#5-benchmarking-and-performance

**Comment by rahimklaber** [comment]
[current version of survey](https://github.com/Tribler/tribler/files/10036337/curr_ver.pdf)
I think it is a bit better now, but I think there is still a bit of work to be done.
The angle I'm going with now is that It is hard to fully understand DAOs since there isn't any good documentation and you have to gather information from many different sources.

**Comment by synctext** [comment]
- 8-pages
- Figure 1: no overlap with terminology of Figure 2. Too small, make it flatter "worker", "managers", division head, CEO graph of something
- "2.4 Voting" missing from Figure 2. Please make consistent if possible.
- "4.2 Open development" scientific wording: {transparency and} level of openness

**Comment by rahimklaber** [comment]
## Update


[lit survey.pdf](https://github.com/Tribler/tribler/files/10164759/Are_Daos_A_Scam.pdf)


- I think the lit survey should be ok now. I fixed a bunch of errors and added stuff based on your suggestions.
- Spent some time looking at the DAO code in the super app
    - Rowdy suggested I benchmark the DAO code by doing simulations on a computer
- Read a bit of the Frost paper, looked into bip340/taproot and the FROST internet-draft [https://github.com/cfrg/draft-irtf-cfrg-frost/blob/master/draft-irtf-cfrg-frost.md](https://github.com/cfrg/draft-irtf-cfrg-frost/blob/master/draft-irtf-cfrg-frost.md)
- Got frost working with a rust library (https://github.com/serai-dex/serai) and used jni to call it from java. Bip340 signatures are currently not officially supported, so had to do some hacks to get that to work.
    - I am currently doing this on my computer and will try to get it working on android later.

## What I’m planning to do next sprint

- Figure out how to run the superapp DAO code on PC and benchmark it.
    - look at musig’s complexity and see if my results make sense
- Figure out how to use Schnorr with bitcoin and try to create a bitcoin transaction with frost.
- Improve the wrapper I wrote to be able to call FROST in JVM.

**Comment by rahimklaber** [comment]
### small update
- Got signing to work in a 250-of-500 configuration. It took ~37 minutes.
- My code could probably be improved to be faster.
- the repo is here by the way: https://github.com/rahimklaber/jni_frost_test/tree/master/src/main/kotlin
  - I only compiled it for windows.
  - It is pretty ugly, but it works.
  - currently, the path to the native library is hardcoded, so that also needs to be changed.

**Comment by rahimklaber** [comment]
## Update
- I submitted the survey to arxiv on saturday. It should be visible on tuesday. If I understand correctly, I will get a code to give you so it shows up on your list.
- I successfully submitted a bitcoin transaction on regtest that was signed using frost 🎊. (Or atleast bitcoin didn’t give me an error)
    - Bitcoin taproot transaction require you to sign a transaction with a modified key. It took some time figuring this out.
    - I am using this [lib](https://github.com/serai-dex/serai/tree/develop/crypto/frost), which seems pretty mature as it has started to be audited (https://github.com/serai-dex/serai/issues/199). I also got some help from the author, who helped me figure out the bitcoin transactions.
    - In my testing code I construct the transaction with bitcoinj and then sign it using the native code.
- Next steps -> Compile with NDK?


## possible directions
- A possible thesis direction would be to create a DAO with two tiers of members. A few hundred members ( or up untill what is realistic with FROST) would be part of the threshold scheme and the rest would be able to vote using trustchain. The threshold members would be responsible executing the proposals. This would be the same as DAOs with multisigs with few members, but this would be more safe due to the amound of theshold members.
- Another Idea is to improve the [XChange paper](https://link.springer.com/article/10.1007/s11280-021-00870-x). My idea is to apply the idea from paper to payment channels and improve the safety by allowing market makers to lock funds and therefore increasing its trustworthyness. The locked funds would be governed by a FROST DAO.
    - Maker makers would be the ones who send a payment second. So they are the ones who are able to steal.
    - Since payment channels would be used, trading can be extremely quick. Using payment channels would also make it feasible to split a trade up in many smaller trades, therefore lowering the potential profit of a market maker cheating.
    - If a market maker does cheat, the DAO would use his locked funds payback the person who was cheated.

**Comment by synctext** [comment]
- The Tribler principle of a zero-server architecture is still far from mainstream. [You found a nice team which is also getting closer to this](https://www.reddit.com/r/Monero/comments/vudljh/announcing_serai_a_new_dex_for_monero_bitcoin_and/) versus usual DeFi central server stuff.

**Comment by kayabaNerve** [comment]
While quite late, I'd like to contribute FROST is far simpler than any threshold ECDSA protocol, relying on far fewer assumptions. It also has extensive security review in:

- [The original paper](https://eprint.iacr.org/2020/852)
- [This further analysis](https://eprint.iacr.org/2021/1375)
- [This even further analysis](https://eprint.iacr.org/2022/833)
- [This CRYPTO2022 submission](https://crypto.iacr.org/2022/papers/538806_1_En_18_Chapter_OnlinePDF.pdf)

[Threshold ECDSA also has review, yet provides a much larger surface taking several rounds to complete, and relying on far more assumptions to be proven.](https://eprint.iacr.org/2020/1390) Part of this can be cited back to ECDSA being a convoluted attempt at avoiding a patent, [leading itself to not have a security proof given the discrete log problem.](https://crypto.stackexchange.com/questions/71029/are-dsa-and-ecdsa-provably-secure-assuming-dl-security)

Practically, FROST is 2-rounds, only one requiring knowledge of the message. The lowest thresold ECDSA protocol is 4 rounds to sign, when the famed GG20 is 7. Binance's tss-lib has been forked to GG20 by THORChain, and their fork has since had several security issues with it, from [AlphaRays](https://eprint.iacr.org/2021/1621) to the ability to cause honest parties to be blamed to leaking key shares. Despite this, THORChain's library was prior audited (though the quality of this audit now must be called into question) and is likely the better choice than the tss-lib it comes from (as I assume it has had far more scrutiny, yet I may just be unaware of the review on Binance's lib. Their one published audit is years old, prior to Alpha Rays).

As for Binance's EdDSA impl, they appear to use a 3-round threshold signature protocol (not FROST, yet not vulnerable to Drijver's application of Wagner's algorithm thanks to a hashed commitment round). I'm unsure what actual protocol it implements, yet I can note FROST achieves a 2-round protocol with the same raw bandwidth for their messages. It didn't include any horrendously expensive proof to achieve the reduced complexity.

I also believe, regarding performance, no threshold ECDSA is linear to amount of signers. GG20 is quadratic, which is why THORChain takes tens of seconds to sign for their 20 participants. FROST is linear, and I've benchmarked <0.7s per-signer for a 333-500 group.

While I believe this is months late, and y'all are using FROST (specifically my lib, currently under audit :D ), I thought I would chime in as I can :)

**Comment by rahimklaber** [comment]
@kayabaNerve Thanks. This is great and It'll be helpful when writing my thesis.

**Comment by rahimklaber** [comment]
- The paper was put on hold by arxiv. I’m guessing it is since I’m new? 😞
- I was able to cross-compile the rust code to native code for android.
- I got a basic app working that uses frost to join and sign
    - I made a short clip of it: [https://www.youtube.com/shorts/uW6-qZi62ts](https://www.youtube.com/shorts/uW6-qZi62ts).
    - Clicking Join will attempt to join/create a new frost group.
    - clicking sign will attempt to sign some random data.
- I thought a lot about how signing and joining a frost group would work.
    - It gets very complicated due to the asynchronous nature and we might need extra messages to explicitly define who is participating in signing.
        - Signing only needs t < n participants, so you don’t want everyone to take part in it if not necessary.
    - Message ordering is also a problem. It can be tricky since a peer might start sending messages related to signing or joining a frost group, before you start listening/saving these messages.
        - In my example, there is a leader who signals the start of signing/joining the group such that other peers know that they can start sending messages.
        - Making it work consistently without a leader would be complicated I think.
        - Though having a leader-based scheme might not be a big problem. If the “leader” is the one who wants to join or proposed a transaction then others might not care that he is the leader, since making sure everything goes well is good for him.
    - There is also the problem of multiple people wanting to join.
        - Currently this must happen sequentially, but it would be better to wait some amount of time and make a new frost group with everyone who wanted to join in that period.
        - However, this also gets into the leader/leaderless problem as in this case there wouldn’t be an easy candidate for a leader.
    - It could also be nice to implement a way for peers to store message for a peer that is offline. Could be done with Trustchain, but seems a bit overkill. Though this is out of scope I think.

- I think I made it pretty testable, and I will write some tests next sprint
    - I made interfaces for functionality that I need and then I used anonymous objects when I need to implement the interfaces
    
    ```kotlin
    // interface for network
    interface NetworkManager{
        fun send(peer: Peer, msg: FrostMessage)
        fun broadcast(msg: FrostMessage)
        fun getMyPeer() : Peer
        fun getPeerFromMid(mid: String) : Peer
    }
    // abstract over frost community with the network manager
    FrostManager(frostCommunity.channel,
                networkManager = object : NetworkManager {
                    override fun send(peer: Peer, msg: FrostMessage) {
                        Log.d("FROST","sending: $msg")
                        frostCommunity.sendForPublic(peer, msg)
                    }
    
                    override fun broadcast(msg: FrostMessage) {
                        Log.d("FROST","broadcasting: $msg")
                        frostCommunity.broadcast(msg)
                    }
    
                    override fun getMyPeer(): Peer = frostCommunity.myPeer
    
                    override fun getPeerFromMid(mid: String): Peer =
                        frostCommunity.getPeers().find { it.mid == mid } ?: error("Could not find peer")
    
                }
            )
    ```
    
    plans for next sprint
    - write a problem description
    - Get example to work with 3 or more devices
    - start thinking/prototyping bitcoin integration
    - Make tests

**Comment by synctext** [comment]
Please document the possible final goals of your master thesis, brainstorm:
- 100 devices
- 1 new ```initiator``` joining the DAO
- Not everybody is online
- Having a selective re-try mechanism (IPv8 gossip community)
- Golden testing scenario is that users are online once a day and will make their sign/reject decision
- Performance analysis and scalability projection
- Craft a user interface for 100-256 DAO users. Each user listed in status as: unresponsive, pending, online, rejected, and approved:
<IMG src=https://user-images.githubusercontent.com/325224/215051718-ccf8642d-8247-4ab4-b932-9a0028c45936.png width=200>

**Comment by rahimklaber** [comment]
[apk]()
[demo video in case apk doesn't work](https://www.youtube.com/watch?v=AVQ6CXEfNkI)

Arxiv still has the survey on hold. 🤔 

- I compiled shared libs to all platforms, so the app should work on all phones.
- I made the UI nicer and changed the signing so that the others now have to accept explicitly.
	- the grid does not actually work, I was playing around with it.
	- There's a page for creating proposals.
	- And a page for accepting/viewing your proposals.
- Fixed a bunch of bugs.
- I tested it and It should work with > 2 people, though I changed some stuff afterward.

I think I will work on making these things work and then maybe add extra stuff:
-  Bitcoin integration
	- a form with fields for destination and amount. 
	- Making the sending of messages more reliable.
	- Dealing with offline users.
	- Save information in a database so the app can be closed
	-  performance analysis
	- scalability analysis and recommendations
		- for example, batching the preprocessing step to increase scalability and performance.


Thesis paper brainstorm: 
- Title?: A framework for true collective ownership of Bitcoin.
- idea/story:
	- Introduce the problem by saying that groups of people want to work together and need to own money collectively.
	- Show how DAOs are not good, and they are not actually decentarlized, etc. 
	- Instead of DAOs based on smartcontracts and tokens, Threshold signatures can be used.
	- However, threshold signatures are expensive and do not scale well.
	- Frost scales well and can be used to allow a group of users control a bitcoin/cryptocurrency wallet.
		- Maybe compare frost to other threshold schemes and also multi-sig schemes that use smartcontracts
	- Introduce the app I built and explain how it works.
	- Show some performance graphs.
	- Show some scalability graphs.
	- Discuss how performance and scalability can be improved.
	- Discuss the shortcomings of this approach.

**Comment by rahimklaber** [comment]
I didn't do much this time.
- The review got rejected from arxiv.
- I added a database that stores the details of your frost group, and all messages you send and receive. 
	- when the app closes and opens, the FROST details are loaded from the database.
	- I will use the stored messages to to deal with members that were offline when a message was sent. Once they come online, they will receive those messages from other peers.
- At first I used EVA to deal with the reliable messaging problem.  When I tested it, I saw that EVA won't work since the first message it sends is not sent again on failure.
	- instead, I sent a message a few times to account for failure. This was mostly needed to be able to use an emulator since the emulator's networking is unreliable. I haven't had any problems sending messages to the emulator, so this seems to work.
- added the activity grid. 
	- ![Capture](https://user-images.githubusercontent.com/21971137/222987966-afb5e33d-0135-4713-9fcc-f30ad6cfb105.PNG)
- Added a test for the core FROST part of the application.


For the next weeks:
- send updates to peers when we receive a ping from them.
  - So imagine if peer A pings peer B. peer B will now send peer A any requests that peer B received and details regarding those requests. So if peer B is signing, then it would send in what stage of the signing it is. peer A could then request additional information if anything received concerns itself.
    - Not sure if I'll make it this complicated. 
    - This should handle the scenario when a user might not have received a msg/the user was offline.
    - The only problem is that this will result in peers spamming each other. This was partly 
- start migrating app to superapp and rewrite it in a nice way.
- start writing the paper. I think I have a decent amount of stuff I can write about.

**Comment by synctext** [comment]
- not the most productive sprint
- ```first message it sends is not sent again on failure.``` Please fix that and document all fixes to EVA :+1: 
-

**Comment by rahimklaber** [comment]
[apk](https://drive.google.com/file/d/1WGOyZxKExjFuu12xSMFk8_E-xj8yCaMW/view?usp=share_link)
- I made the system more reliable
	- I don't think there are other big issues with the core of the system. Though, I suspect problems with pop up when stress testing it.
	- I use timeouts + acknowledgements
		- I send a message and wait for ack. If I don't receive it I repeat the process 5 times. If at the end no acks were received, I consider the precedure to have failed.  
		- I haven't noticed any problems. Though I have to be carefull, I found some bugs that depend on network latency and are therefore hard to debug.
			- This happened because I send messages without waiting for the previous message to fail or succeed. 
		- I'm not sure how many times to resend or how much time to wait before timing out.
	- I tested the reliability by adding delays in the code. 
- I added my app to the superapp.
- I tried writing a bit of the start of the paper, but its hard without writing bs.
[FROSTDAO.pdf](https://github.com/Tribler/tribler/files/11073062/FROSTDAO.pdf)


For the next weeks
- How nice should the app look? Maybe I should beautify it.
- Do some simulations and check how many participants can use frost without it breaking.
- write?
- Do you have anything you want me to focus on?

Before choosing to do just acks for reliability I spend time looking into other ways. I think a future project could be adding quic to ipv8. I know you said its too heavy, but you could have quic for peers you interact with often and then have normal udp for other peers/ messages. There is a java quic lib aswell https://github.com/ptrd/kwik. I played around with it and it worked.

**Comment by synctext** [comment]
The draft text lacks a nice storyline and goes too fast. We want a fully decentralised P2P DAO. Digital democracy, collective wealth, rise of the robots that do all our work, we take eternal vacation :tropical_drink:

**Comment by rahimklaber** [comment]
I ported the code to work on my pc and found a few bugs in the process. These bugs were rare on android due to some stuff running on the same threads, while on my pc they run different threads.

I was able to run an experiment with 30 clients. but doing more than 50 is problematic. Every client runs on its own jvm and even after lowering the max memory I sometimes get problems. Another issue is that nodes don't always know the address of another node, so I need to fix it somehow.

**Comment by synctext** [comment]
- ```I'm thinking there is a race condition somewhere causing it.```
  - Security and reliability are critical for your master thesis :construction: 
  - You deal with actual crypto money :money_mouth_face: :money_with_wings: :money_mouth_face:

**Comment by rahimklaber** [comment]
[thesis.pdf](https://github.com/Tribler/tribler/files/11348736/thesis.pdf)

- I made some integration tests and added a code coverage table to the pdf. 
    - The code is separated from the UI so I could test the functionality without having to touch the UI parts.
    - I tested almost all of the functionality. The things I didn't test are related to UI.
    - Next step full application test?
- I found and fixed some bugs and I was able to run some experiments without any issues.
  - Note: The experiments are not simulated or emulated. They are using real software and real sockets. 
  - I believe I fixed the race condition. 
  - I madea graph for the amount of time keygen and signing takes and I have a graph showing how much data is sent during keygen and signing.
  - I will also make some graphs on how packet drop affects the duration and amount of data sent. Though, I need to think about how to do it, since packet drop happens naturally during the experiments. Especially, when eva is used.
  - Maybe I'll also make a graph that shows the influence of latency. Though I don't think this is interesting.
  - I will make the graphs nicer.
- I wrote a bit and I think that I can write the paper quite fast. 
    - What are the requirements for the paper?
- I started working on adding Bitcoin and am around 70% done. 
    - I got bitcoinj working with taproot addresses and was able to send funds to a taproot address. I am using Bitcoin to keep track of the DAO account.
    - Potential issue: each input needs to be signed individually. So imagine the DAO account has a bunch of small inputs. In this case spending funds will need many FROST signature rounds.

**Comment by synctext** [comment]
- "Collective Money Using FROST"
- See most recent thesis format example from Lab: [zero-trust stuff](https://repository.tudelft.nl/islandora/object/uuid%3Aac27c1a9-0497-41e2-9fb5-44943b40df0c)

**Comment by rahimklaber** [comment]
Can start setting up a date for the defense?
[thesis.pdf](https://github.com/Tribler/tribler/files/11476280/thesis.pdf)
[apk](https://drive.google.com/file/d/1IOjRXpGXSSXHSUn19CPF3Xr0ljleVQ_o/view?usp=sharing)

- I wrote a bit about the experiments.
- I got Bitcoin to work. A member of a DAO can make a proposal to send a certain amount of Bitcoin to an address.
- it is not user-friendly at all right now, but it works.
- To make it simpler, I only use one Input per "proposal" since each input requires a separate signature.
- There is some stuff to handle if we want this to work well, which I probably won't do. 
    - When a new user joins the DAO, the old inputs need to be migrated to the newly generated key. This gets complicated fast.
    - BitcoinJ is problematic and may cause failures due to not having the latest Bitcoin state. This is because I look up transaction data from Bitcoinj when signing.

**Comment by rahimklaber** [comment]
I probably won't be able to show the app while I'm in Curacao so I made a recording. https://www.youtube.com/watch?v=CVgsn-JL4g0

I still need to add/fix a bunch of stuff, but its way nicer than before.
I do the following in the video:
- I create a FROST group.
- I send Bitcoin to the shared account.
- I show how you can reject proposals, which will then fail if enough people reject.
- I make a proposal to send Bitcoin to the personal account of the phone on the right. Once the proposal is accepted, you can see that the balance of the account has increased.
I'm running my own network, so I used the cmdline to mine blocks.

**Comment by synctext** [comment]
- you have voting / governance / democracy operational!?!
  - not claimed in your thesis draft stoyline
  - [The Myth of Digital Democracy](https://www.researchgate.net/publication/220434163_The_Myth_of_Digital_Democracy_Digital_Citizenship_the_Internet_Society_and_Participation)

**Comment by synctext** [comment]
_Harvard Kennedy School on DAO._

Hubbard, Sarah, Connor Spelliscy, Nathan Schneider and Samuel Vance-Law. “[Toward Equitable Ownership and Governance in the Digital Public Sphere.](https://www.belfercenter.org/publication/toward-equitable-ownership-and-governance-digital-public-sphere)” , June 8, 2023.  This paper explores how newly developed DAO tooling could help co-ops compete in the online economy. Specifically, we outline how DAO tooling could provide co-ops with:

- Effective Voting—DAOs test novel and varied governance systems that appear to offer some unique benefits not available to legacy organizations. These include systems such as reputation-weighted voting, holographic consensus, conviction voting, and quadratic voting.
- Increased Member Engagement—DAO tooling allows organizations to gamify milestones for their members, autonomously tracking the progress of members toward their goals, and rewarding them based on behavior. This encourages members to stay on task both for short-term gain and to develop a strong reputation in the long term.
- Predictable Compensation/Patronage—DAO tooling can offer insight into the contributions of community members and the payment systems that are directly linked to those contributions. Co-ops could use these tools to make patronage more predictable, transparent, and equitable.
- Organizational Transparency—Traditional co-ops, especially at scale, usually become less transparent to their members as they grow. In contrast, on-chain DAO activity like token voting, treasury management, and the payment of salaries and subsidies for public goods can be recorded on an immutable public ledger viewable by anyone with an internet connection.
- Member Accountability—It is often hard to identify rule-breakers and enforce accountability as a co-op grows. In a DAO using on-chain reputation, a user’s reputation can automatically change based on the quality and quantity of contributions to a community. Reputation can be non-transferable, tied to a particular individual or organization, and recorded on an immutable public record.
- Improved Capital Formation—Co-ops are at a significant disadvantage to corporations when raising the funds necessary to scale and compete. DAOs have started experimenting with alternative forms of funding that could ultimately be relevant to co-ops.

**Comment by rahimklaber** [comment]
Is this enough to start the defense process? I got a job which starts in September, so I'd like to finish before then.

I spent this sprint writing: 
[FROSTDAO__Collective_Ownership_of_wealth_using_FROST.pdf](https://github.com/Tribler/tribler/files/11886167/FROSTDAO__Collective_Ownership_of_wealth_using_FROST.pdf)

The writing still isn't that good, but I think it is much better than before.
The figures need to be tweaked and a bunch of them are placeholders. I'm also missing references.

What do you think of the plots? I used scatter plots because you can quickly see the variability and because the graphs have a lot of values on the x-axis, so box plots did not look nice.

You mentioned that the problem description sounds more like requirements than a problem. I tried to change it, but I'm not sure how good it is. This is the old problem description:
```
The internet has revolutionized the way individuals collaborate and work towards a common goal, even across borders. 
However, despite this, there remains a significant challenge when it comes to the collective management of wealth.
Establishing a company or making joint investments can be complicated and cumbersome, particularly when the individuals involved are from different countries.
Existing financial services do not address this issue, highlighting the need for a novel solution.

We aim to solve this problem by creating a peer-2-peer leaderless decentralized system.
This system will allow groups of individuals to form decentralized autonomous organizations (DAOs)~\cite{DAO} that enable them to collectively and democratically manage their wealth.
The key principle guiding our approach is decentralization, ensuring that every aspect of the system operates without reliance on any central authority or intermediary. 

To achieve this, we envision a fully open-source system and transparent system that allows participants to examine and verify every operation.
There is no central authority, therefore transparency is crucial to be able to identify potential bad actors. Building an open-source system allows anyone to contribute and ensures that the system can evolve based on the users.

Our system should be accessible to anyone, regardless of their background or technical expertise.
To ensure this, we aim to create the entire system using only mobile devices, therefore maximizing the number of potential users.
To support many users, our system should scale to millions without reducing security or performance.

By constructing this decentralized peer-to-peer leaderless system, we aim to address the existing limitations of traditional financial services and provide a robust and easy-to-use solution for decentralized collaborative wealth management. 
```

**Comment by synctext** [comment]
- 9 thesis pages :rocket: 
- Not only 2008, also in 2023 there was excessive risk taking. A [bank run was carefully orchestrated](https://www.axios.com/2023/04/24/twitter-svb-bank-run) to force the government to restore 100% of funds without limits. Basically, what normal people would call extortion. :boom: As there are no "controlled bank bankruptcies", there is no functioning marketplace sadly.

**Comment by rahimklaber** [comment]
[FROSTDAO__Collective_Ownership_of_wealth_using_FROST.pdf](https://github.com/Tribler/tribler/files/12000953/FROSTDAO__Collective_Ownership_of_wealth_using_FROST.pdf)

Aside from the abstract, I think the writing of the first chapters is decent.

**Comment by synctext** [comment]
Delft literature survey, [20 DAO participants is the tipping point for sustainability](https://pure.tudelft.nl/ws/portalfiles/portal/154586329/1_s2.0_S2096720923000180_main.pdf).

**Comment by synctext** [comment]
- Reads like a real master thesis :rocket: :rocket: :rocket: 
- "We focus on the problem of wealth under democratic control. Our goal is to enable a leaderless group of collaborating humans of unbounded size to control a Bitcoin wallet of unconstrained wealth democratically" This is the perfect opening of the Problem Description. Please move the introductory text to the intro.
- minor polish. Too similar "Existing solutions suffer from various problems. They are either expensive in terms of Bitcoin fees or expensive in terms of computation [10], [14]." and just a bit later this repeats: "Existing DAOs have several problems."
- "IPv8 employs hole-punching" unclear, also mention the terms UDP and NAT _briefly_.
- "do not have a dedicted public IP**v4** address [20]."
- "In this case, the organization could be overtaken by a Sybil attack[21]." suggestions: Secure identity is a known hard problem and a known DAO security concern. Please consider promoting our SSI work with [[a citation](https://doi.org/10.1109/Cybermatics_2018.2018.00230)]
- "In contrast to our design, accepting an entrance fee and migrating funds from the old account are not implemented." suggestion for reformulation: Our proof-of-principle prototype lacks features such entrance fee and migrating funds when a new user joins.
- "The DAO can _make investments_ and spend funds by creating and accepting proposals."
- "_Any_ member~~s~~ of the DAO can create a _new investment_ proposal."
- "to create ~~fake~~ testing Bitcoins"
- "Figure 11: Figures depicting activity grid of a DAO with ~~25~~ 24 members". Off by one error :1234: 
- "We did not have enough phones; one phone was used, and the other members of the DAO were running on a computer. " Experimental setup details are not for Figure text. suggestion: For testing purposes the screenshots are obtained from a real Android phone, while others DAO members executed from common PC hardware.
- "Figure 15: Duration of the key generation running on the _**improved**_ ??? IPV8 stack using our EVA and serialization improvements."

**Comment by rahimklaber** [comment]
[draft_presentation.pdf](https://github.com/Tribler/tribler/files/12415923/draft_presentation.pdf)

**Comment by synctext** [comment]
Review of draft master thesis presentation:
- slide 3: "Blockchain", what does it solve? first practical solution after 30 years of crypto money theory +limited transaction rate
-
