### ISSUE TITLE
Can not build Tribler on Apple Silicon (M1)

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7252]
macOS: 13.0.1 (22A400)
Chip: Apple M1

```python
➜ pip install libtorrent==1.2.15

ERROR: Could not find a version that satisfies the requirement libtorrent==1.2.15 (from versions: none)
ERROR: No matching distribution found for libtorrent==1.2.15
```
https://github.com/arvidn/libtorrent/issues/7131

```python
➜ pip install PyQt5==5.15.1

...
ERROR: Command errored out with exit status 1:
...
        Complete output (29 lines):
        Traceback (most recent call last):
          File "<path>/_in_process.py", line 143, in prepare_metadata_for_build_wheel
            hook = backend.prepare_metadata_for_build_wheel
        AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel' 
```

**Comment by Solomon1732** [comment]
I can confirm for Fedora 37. I was about to open a bug report before I saw this one already being open.

**Describe the bug**
When I run `pip3 install --upgrade -r tribler/requirements.txt`, it fails with the following error:
> ERROR: Could not find a version that satisfies the requirement libtorrent==1.2.15 (from versions: none)
ERROR: No matching distribution found for libtorrent==1.2.15

**To Reproduce**
Steps to reproduce the behavior:

1. Open the terminal in `/home/[user]`
2. Run `sudo dnf install python3-devel python3-pip git`
3. Run `git clone https://github.com/tribler/tribler`
4. Run `pip3 install --upgrade -r tribler/requirements.txt`
5. See error

**Expected behavior**
Pip installs successfully and without errors.

**Desktop (please complete the following information):**

- OS: [Fedora 37]
- Tribler's version [main branch]

**Additional context**
I am trying to set up a development environment as per [these](https://tribler.readthedocs.io/en/latest/development/development.html#fedora-centos-redhat) instructions.

**Comment by Solomon1732** [comment]
On further thought, something else came to my mind. This bug prevents me from setting up a testing environment on a local machine. Since I can't fulfil the requirements (and basic ones at that), I can't locally test Tribler. To test any PR I make in any way I'm forced to use this project's PR system.

**Comment by InvictusRMC** [comment]
@Solomon1732 I got Tribler working on M1 with a local workaround, see also https://github.com/Tribler/tribler/pull/7448
![image](https://github.com/Tribler/tribler/assets/22516119/3c0fdc6f-5127-4922-8cac-eb4bc323bb07)

**Comment by Solomon1732** [comment]
I should have specified before: I have this problem in Fedora 37 on Intel 😅. I'll try to see if it also shows up in Fedora 38 (also Intel).

**Comment by InvictusRMC** [comment]
> I should have specified before: I have this problem in Fedora 37 on Intel 😅. I'll try to see if it also shows up in Fedora 38 (also Intel).

Are you running 3.11? Because this was also the Apple Silicone issue.

**Comment by Solomon1732** [comment]
I checked and yes, it's the problem. It also holds true for Fedora 38. Mind you, I'm using them in close to vanilla form. I didn't change the python version manually.

**Comment by Solomon1732** [comment]
I forgot to mention, it's a problem also on Intel CPUs. It's not limited to M1s

**Comment by drew2a** [comment]
I unassign myself from this issue as I no longer have access to an M1.
