### ISSUE TITLE
Blockchain Engineering 2023 - Upload for Profit

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7294]
Team issue for 10 weeks of blockchain engineering course at Delft University of Technology

**Upload for Profit.** By using idle bandwidth on your smartphone you can earn money. Your system will explore how to earn as much tokens as possible, known as token mining. You make a profitable investment when you download content once and upload it numerous times. Due to storage limitations the key decision to make is: which Tiktok-like content to invest in. By doing yield prediction you maximize your income. Required background reading: [Decentralized credit mining in P2P systems](https://dl.ifip.org/db/conf/networking/networking2015/1570066439.pdf).

Discussed: 20 and 21 April (week 10) final meeting.

- {looong}Sprint goal: having an operational skeleton mining app running. familiar with libtorrent. 20 small {bittorrent} swarms as investment ([creative commons content](https://www.google.com/search?q=creative+commons)). Second device downloads and pays tokens through IPv8 overlay.
- Phone-to-Phone overlay and tokens. transaction format [[example trustchain docs](https://github.com/Tribler/kotlin-ipv8/blob/master/doc/TrustChainCommunity.md)], sign with private key, and transfer to another phone using overlay. [Python IPv8 overlay examples and tutorial](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial.html)
- Popularity community. Awareness of videos going viral. [tiktok recommendation details](https://www.shaped.ai/blog/the-secret-sauce-of-tik-toks-recommendations). Example from [2005 of our fully distributed recommender](https://grouplens.org/beyond2005/full/pouwelse.pdf)
- {tentative} final project goal. Lots of content seeding, performance analysis, yield prediction

**Comment by Floor97** [comment]
On Wednesday we discussed to compile and understand the code before a meeting we had on Thursday at 15:00. 
There were still some issues with compiling for one member, but they had it up and compiling by the end of Friday as well. 

During the meeting on Thursday we mostly tried to understand the code, in terms of IPv8 and libtorrent, and resolve compiling issues. In the end we created 3 issues:  [peer discovery on IPv8](https://github.com/ChrisSBras/trustchain-superapp/issues/2),  
 [20 small swarms](https://github.com/ChrisSBras/trustchain-superapp/issues/1), [token transactions](https://github.com/ChrisSBras/trustchain-superapp/issues/3). 

On Thursday the first pull request was created, however the pipeline seemed to be failing. We tried to figure out why this was happening. It seems to mainly be because we forked the project. "The problem was the variables in gitlab ci/cd was protected. When variables are protected only the protected branch can read them. My branch wasn't protected so variables was empty when calling them"

**Comment by synctext** [comment]
Some pointers from prior Kotlin coding inside superapp:
- [IPv8 community for content discovery and magnet link downloading](https://github.com/Tribler/trustchain-superapp/blob/master/musicdao/src/main/java/nl/tudelft/trustchain/musicdao/core/torrent/TorrentEngine.kt#L99)

**Comment by Floor97** [comment]
Added [meeting notes to wiki](https://github.com/ChrisSBras/trustchain-superapp/wiki/Meeting-Notes)
Sprint 2 issues:
* [#1](https://github.com/ChrisSBras/trustchain-superapp/issues/1): 20 Small Swarms - Assigned to: Chelsea 
* [#3](https://github.com/ChrisSBras/trustchain-superapp/issues/3): Token Transactions - Assigned to: Alex 
* [#5](https://github.com/ChrisSBras/trustchain-superapp/issues/5): Basic Content Discovery - Assigned to: Floor
* [#6](https://github.com/ChrisSBras/trustchain-superapp/issues/6): Simulate a Community - Assigned to: Chris
* [#7](https://github.com/ChrisSBras/trustchain-superapp/issues/7): Coin Toss Recommendor - Assigned to: Juno

**Comment by synctext** [comment]
- Chris: meaningful goal of getting 3 emulated IPv8 peers going inside a single community

**Comment by Floor97** [comment]
Wednesday working session update:
* [#1](https://github.com/ChrisSBras/trustchain-superapp/issues/1): 20 small swarms, assigned to Chelsea, now reassigned to Floor. The torrent files seem to work in bittorrent, but will not run in the superapp. Might be a problem in the python script, or amount of seeders. Since Chelsea has to still work on the loading bar in the app as well, Floor will continue with this issue of retrieving more torrent files and making sure they run in the superapp as well.
* [#3](https://github.com/ChrisSBras/trustchain-superapp/issues/3) Token Transaction, assigned to: Alex. Regarding the wallet, I am working to separate the code a bit and I still have to check if it works with the gossip community.
* [#5](https://github.com/ChrisSBras/trustchain-superapp/issues/5): Basic Content Discovery, assigned to: Floor. A [pull request](https://github.com/ChrisSBras/trustchain-superapp/pull/8) has been opened to merge the gossiper. It sends one random magnet link every 4 seconds to a random peer. The receiving peer downloads and can view the video in the app after receiving the gossip. Waiting on an email from Pouwelse to see if any more functionality is expected.
* [#6](https://github.com/ChrisSBras/trustchain-superapp/issues/6) Simulate a community, assigned to: Chris. The dummy nodes seem to work with real phones, still not with emulator for some reason. Looking into this.
* [#7](https://github.com/ChrisSBras/trustchain-superapp/issues/7) Coin Toss Recommender, assigned to: Juno. Discussed with Pouwelse to structure the recommendation profile as a list of magnet links with some parameters stuck to it (watching time, engagement(?), freshness(?)) and to see whether we can get anything to work which is better than coin toss. The input to the recommender should thus not be a list of magnet links but a list of profiles and a basic class for the profile should be added.
* [#9](https://github.com/ChrisSBras/trustchain-superapp/issues/9) Progress bar for download swarms, assigned to: Chelsea. Starting to work on that from this session.

**Comment by synctext** [comment]
btw small sample of copyright free videos: https://webtorrent.io/free-torrents
_Basic Content Discovery_ can be expanded with and integrated with the content recommender. Gossip also watching time. Add a signature, this results in a ClickLog approach. By collecting many ClickLogs you can detect a patterns of what is "hot content". This is the gold you are after for _upload for profit_.
Can you think of the MvP for closing this critical loop? Content gets watched, gets recommended, results in engagement expressed in **aggregate watching time**, invest in this swarm, watch the profit tokens roll in :rocket: {warning: this is cutting-edge scientific research: unknown difficulty level}

**Comment by Floor97** [comment]
Update:
*  Floor: At the start of the week I finalised the gossiper by having it send only one magnet link at a time, and fixing a downloading issue. The gossiper was then [merged](https://github.com/ChrisSBras/trustchain-superapp/pull/8) closing issue [#5](https://github.com/ChrisSBras/trustchain-superapp/issues/5) of Basic Content Discovery. Then halfway into the week I was assigned to issue [#1](https://github.com/ChrisSBras/trustchain-superapp/issues/1) where I discovered that the downloading didn't work because when we change the default torrent file it only contains one video, and it needs to contain at least 2 ([code](https://github.com/ChrisSBras/trustchain-superapp/blob/master/detoks/src/main/java/nl/tudelft/trustchain/detoks/TorrentManager.kt#L119). It would be better if multiple torrent files can be pulled from raw without hardcoding. This is what I am currently trying to achieve by reflection, but this is not working yet. Finally I am also assigned to [#12](https://github.com/ChrisSBras/trustchain-superapp/issues/12) the extended gossiper. Here I will work with Juno to add useful metrics for the recommender to the gossiper.
* Chris: I added a [PR](https://github.com/ChrisSBras/trustchain-superapp/pull/10) for the dummy nodes (issue [#6](https://github.com/ChrisSBras/trustchain-superapp/issues/6)). They now seem to work and will send a random torrent magnet link to their peers every x seconds. You can easily specify from the commandline how many nodes you want to spawn.
* Alex: I made a [pr](https://github.com/ChrisSBras/trustchain-superapp/pull/11) for the wallets (issue [#3](https://github.com/ChrisSBras/trustchain-superapp/issues/3)). I wanted to make a pr for the bigger branch however the pipeline failed so I was a a bit unsure if I should do it or not, I ll ask today.
* Chelsea: I implemented a really basic progress bar for downloading swarms, but it's only using dummy data for now, so not committed code (issue [#9](https://github.com/ChrisSBras/trustchain-superapp/issues/9)).
* Juno: I implemented profiles/time tracking for how long a video has been watched for but it isnt free of bugs so I will wait with making a pr (issue [#7](https://github.com/ChrisSBras/trustchain-superapp/issues/7)).

**Comment by synctext** [comment]
- Still in progress: receive 1 or any amount of magnet links via gossip; then download some

**Comment by Floor97** [comment]
Updated the [meeting notes](https://github.com/ChrisSBras/trustchain-superapp/wiki/Meeting-Notes) for this Monday. Next meeting is Wednesday afternoon at 15:30, stand-up and working session.

**Comment by Floor97** [comment]
More [extended meeting notes](https://github.com/ChrisSBras/trustchain-superapp/wiki/Meeting-Notes#wednesday-15-03) were taken where it was discussed how we arrived at some of the issues.

Update on issues, Wednesday (15/03):
* Floor: Concluded that it is best to share the 20 torrents through the dummy nodes, since these dynamically select a couple torrents to boot with. This is better for testing purposes than hardcoding all 20 torrents in the superapp. This has been added in the [dummy node merge](https://github.com/ChrisSBras/trustchain-superapp/pull/10). This closes issue [#1](https://github.com/ChrisSBras/trustchain-superapp/issues/1). Now going to work on extended gossiper that shares if a video was watched, how long it was watched, and processes this into the profiles in the recommender (issue [#12](https://github.com/ChrisSBras/trustchain-superapp/issues/12)).
* Juno: basic recommender is ready and pull request was opened. Further going to work on building a basic framework for the recommender by separating watched/unwatched videos and implementing an algorithm to sort unwatched videos for recommender (issue [#14](https://github.com/ChrisSBras/trustchain-superapp/issues/14)).
* Chris: Change dummy nodes to run in docker container to make it easier to run (issue [#18](https://github.com/ChrisSBras/trustchain-superapp/issues/18)). Extending the dummy nodes with the recommender functionality (issue [#15](https://github.com/ChrisSBras/trustchain-superapp/issues/15)). Also, updating with the extended gossiper once that is uploaded next sprint [#16](https://github.com/ChrisSBras/trustchain-superapp/issues/16). 
* Alex: Working on moving from ipv8 community to Trustchain Community to be able to store transactions in SQLite database (issue [#17](https://github.com/ChrisSBras/trustchain-superapp/issues/17)).
* Chelsea: moving the progress bar from MainActivity to DeToksCommunity. Specifically linking it to the discovered peers (issue [#9](https://github.com/ChrisSBras/trustchain-superapp/issues/9)).

**Comment by synctext** [comment]
Comments:
- Great progress this week :rocket: 
- Engagement metric. This is hard/impossible for the global network.
- See IPFS search example, its hard to get global stats without leaving spam/Sybil vulnerability, https://stdtc-eth.ipns.dweb.link/
- For instance, in a real decentral TikTok scenario with a billion users, you would get 50k profiles on your .5 Terabyte storage of your smartphone. Thus you can see the engagement metrics for 0.005% of the global network.

**Comment by Floor97** [comment]
Update (21/03):
We added the [pr](https://github.com/Tribler/trustchain-superapp/pull/143) for our current master branch which merges the extended gossiper functionality, a recommender framework and torrent files and docker containers for the dummy nodes.

* Floor: fixed and updated gossipers, and cleaned code for the [pr](https://github.com/Tribler/trustchain-superapp/pull/143) at the start of the week. From now going to work on how to seed videos so we can apply that in yield prediction later (Issue [#22](https://github.com/ChrisSBras/trustchain-superapp/issues/22)). 
* Chris: Currently support for multiple gossipers is being added to the dummy nodes to be able to add the other gossipers as available in the DeToks community in the app (Issue [#16](https://github.com/ChrisSBras/trustchain-superapp/issues/16)).
* Juno: [merged](https://github.com/ChrisSBras/trustchain-superapp/pull/20) a framework update for the recommender. Now going to look into getting more and more accurate metrics for the recommender (issue [#23](https://github.com/ChrisSBras/trustchain-superapp/issues/23)), and research ways to do yield prediction (issue [#21](https://github.com/ChrisSBras/trustchain-superapp/issues/21))
* Alex: Agreement blocks still do not get sent when trying to listen for incoming blocks. Otherwise the chain is persistent and stored in a sqlite database, in a similar manner to all other trustchain apps in the superapp (issue [#17](https://github.com/ChrisSBras/trustchain-superapp/issues/17)).
* Chelsea: Continued working on making the progress bar update in real-time in the VideoAdapter class (issue [#9](https://github.com/ChrisSBras/trustchain-superapp/issues/9)).

**Comment by Floor97** [comment]
Sprint update:
* Floor: Monday and Tuesday I refactored messages, and added a [boot gossiper](https://github.com/ChrisSBras/trustchain-superapp/blob/master/detoks/src/main/java/nl/tudelft/trustchain/detoks/gossiper/BootGossiper.kt) which can share data when booting (now used for network size estimation). I also prepped and set up the [pr](https://github.com/Tribler/trustchain-superapp/pull/143) into the trustchain-superapp repo. (issue [#22](https://github.com/ChrisSBras/trustchain-superapp/issues/22)) - The rest of the week I looked into seeding torrents. There isn´t much documentation, but I did find this [code](https://github.com/ChrisSBras/trustchain-superapp/blob/master/freedomOfComputing/src/main/java/nl/tudelft/trustchain/FOC/AppGossiper.kt#L321) in the project which talks about a fix/hack. I think this should be fine to use, but we need to reconsider how we identify videos. Also found nice functions to use for yield prediction.
* Chris: (issue [#16](https://github.com/ChrisSBras/trustchain-superapp/issues/16)) - The dummynodes have been refactored to now allow for multiple gossipers. The networkgossiper is not fully working yet, will try to fix it today. The watchtime gossiper sends random watchtime profiles which are generated on creation of a node. The nodes still send unsigned messages, but that is easily swappable to signed messages. I also tried running 10k+ nodes, but that is simply not possible on 1 pc with the current sim. A more realistic number would be in the 10s to maybe a 100.  (also open issue [#15](https://github.com/ChrisSBras/trustchain-superapp/issues/23)).
* Chelsea: (issue [#9](https://github.com/ChrisSBras/trustchain-superapp/issues/9)) - Moved the progress bar to VideoAdapter, so the videos load now and the number of peers update whenever a user scrolls, but it still does not update continuously similar to PR Tribler#141 of the Tribler/trustchain-superapp which also has issues making UI updates on the fly. I looked into musicdao's debugging screen, but couldn't figure out how to incorporate it into detoks. I found more creative commons videos which download fast, but they don't have many seeders.
* Alex: (issue [#17](https://github.com/ChrisSBras/trustchain-superapp/issues/17)) - A proposal block is created when a peer wants to send a token to another peer. However, creating the response block does not work. The onSignatureRequest method from BlockSigner does not intercept the incoming proposal block, whereas if I use a listener or the TransactionValidator it works. I tried sending the response block from inside those methods, but I ran into errors. I looked into existing code, but all the examples which I could find use the same structure described in the [tutorial](https://github.com/Tribler/kotlin-ipv8/blob/0f74caa509ed2870fe1154ba2d0d76992e1d56fd/doc/TrustChainTutorial.md), which I already tried. The transactions do get stored inside the store (SQLite database) and are persistent.
* Juno: Worked on changing the recommender data structure and finishing up the pull request to upstream, haven't been able to do much more. (also open issues [#23](https://github.com/ChrisSBras/trustchain-superapp/issues/23) and [#21](https://github.com/ChrisSBras/trustchain-superapp/issues/21))

**Comment by Floor97** [comment]
Update:
- Floor: (issue [#27](https://github.com/ChrisSBras/trustchain-superapp/issues/27)) - I made the `GossipMessage` class generic, where each gossiper has an extended message class which specifies how to deal with the specific pairs. Also made sure all torrents are identified with hashes. This was merged in the following [pr](https://github.com/ChrisSBras/trustchain-superapp/pull/29). (issue [#21](https://github.com/ChrisSBras/trustchain-superapp/issues/21)) - I implemented a framework for the different strategies of sorting the handlers. Seeding and leaching take from the same strategies. (issue [#24](https://github.com/ChrisSBras/trustchain-superapp/issues/24)) - I started on a GUI for the strategies, where a user can select the leaching and seeding strategies, turn seeding on and off, and select the bandwidth a user wants to spend on it in a day.
- Chelsea: (issue [#28](https://github.com/ChrisSBras/trustchain-superapp/issues/28)) -  researched how to add tabs to the UI to display videos on one tab and torrent information on the other.
- Chris: (issue [#16](https://github.com/ChrisSBras/trustchain-superapp/issues/16)) - The networksize algorithm is ported into the nodes, though there are still some issues with the size estimate.
- Juno: (issue [#23](https://github.com/ChrisSBras/trustchain-superapp/issues/23)) - Added fields to the profile for duration, hop count and times we have received a torrent, added mostly still untested functionality to update these fields in the right places (torrentmanager/torrent gossiper), looked further into the video adapter but it is convoluted and not easy to work with.
- Alex: (issue [#17](https://github.com/ChrisSBras/trustchain-superapp/issues/17)) - For now I looked at the other transaction implementations from https://github.com/Tribler/trustchain-superapp/pull/141 and https://github.com/Tribler/trustchain-superapp/pull/145, trying to see if there s something I can use to fix my issue

**Comment by Floor97** [comment]
The [apk](https://we.tl/t-rqBe7fBYEA), not much changed for master since last week that you can see.

Weekly update:
* Floor: (issue [#27](https://github.com/ChrisSBras/trustchain-superapp/issues/27)) - I made the `GossipMessage` class generic, where each gossiper has an extended message class which specifies how to deal with the specific pairs. Also made sure all torrents are identified with hashes. This was merged in the following [pr](https://github.com/ChrisSBras/trustchain-superapp/pull/29). (issue [#21](https://github.com/ChrisSBras/trustchain-superapp/issues/21), [code](https://github.com/ChrisSBras/trustchain-superapp/compare/master...ChrisSBras:trustchain-superapp:21-apply-yield-prediction), for this and next issue) - Implemented a framework for the recommender and seeding videos in `Strategy` class. Set up methods to change the leaching strategy, and start, stop or change the seeding (strategy) in `TorrentManager`. There is still some bugs to work out, because all videos currently play and are regarded as downloaded by the torrent manager, but are not seeding yet, usually stuck at 98%. (issue [#24](https://github.com/ChrisSBras/trustchain-superapp/issues/24), [demo](https://user-images.githubusercontent.com/45147538/229451382-aea69b1e-633e-4079-aa80-643445bcd8c9.mp4)) - Implemented a GUI for the leaching and seeding strategy selection. Here the user can select the leaching and seeding strategies. Turn seeding on/off and adjust the maximum bandwidth and storage capacity that can be used for seeding. It refreshes every 2 seconds and shows a list of the seeded torrents, the total download, upload and balance per hash. Though the balance is currently a dummy value.
* Chelsea: (issue [#9](https://github.com/ChrisSBras/trustchain-superapp/issues/9)) - The text displaying the number of peers connected now updates in real-time, so I think #9 can be closed? (issue [#28](https://github.com/ChrisSBras/trustchain-superapp/issues/28)) - I started to implement a torrent debug screen. There is a "Torrent Info" button that navigates the user from the detoksFragment to a new torrentFragment. I tried to implement a back button which would bring the user back to the video which they were watching when they clicked the "Torrent Info" button, but for now it brings them to the first video of the loop. I also looked into how to access the torrent specific information in order to display them
* Chris: (issue [#16](https://github.com/ChrisSBras/trustchain-superapp/issues/16)) - The networksize algorithm is ported into the nodes, though there are still some issues with the size estimate.
* Juno: (issue [#23](https://github.com/ChrisSBras/trustchain-superapp/issues/23)) - Added fields to the profile for duration, hop count and times we have received a torrent, added mostly still untested functionality to update these fields in the right places (torrentmanager/torrent gossiper), looked further into the video adapter but it is convoluted and not easy to work with.
* Alex: (issue [#17](https://github.com/ChrisSBras/trustchain-superapp/issues/17)) - For now I looked at the other transaction implementations from https://github.com/Tribler/trustchain-superapp/pull/141 and https://github.com/Tribler/trustchain-superapp/pull/145, trying to see if there s something I can use to fix my issue

**Comment by synctext** [comment]
- documentation has too many screens. Just one basic .GIF and add high-level overview
- Nice detailed docs, with [deeplinks](https://github.com/ChrisSBras/trustchain-superapp/blob/2ceafb4a824558fa5d500dcdd132b8caca2cd3b0/detoks/src/main/java/nl/tudelft/trustchain/detoks/gossiper/NetworkSizeGossiper.kt)
- concept of "bootstrapping a torrent"
  - use well-known named torrent inside apk app data
  - seed using Libtorrent
  -

**Comment by ChelseaGuan** [comment]
[Demo recommender apk](https://we.tl/t-Y5RklefrhB ) : Contains hardcoded metrics to demonstrate the recommender system.
[Demo torrents apk](https://we.tl/t-votoIbHTi5 ) : Contains many torrents to demonstrate the normal functionality of the app.

[Upload for Profit PR](https://github.com/Tribler/trustchain-superapp/pull/159)

**Comment by synctext** [comment]
Nice and usable prototype! Conducted final meeting. closing issue.
