### ISSUE TITLE
Blockchain Engineering 2023 - Upvote Token II

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7307]
Upvoting token. Each user can give away an infinite amount of ❤️ tokens. Content creators are rewarded with ❤️ tokens, boosting their visibility. Content gathering lots of ❤️ will get more attention and go viral. Content creators can see in real-time who is giving them a ❤️ token. The ❤️ token economy design and implementation is your responsibility. Part of your demonstration will be a wipe-based UX implementation which favours viral content. Fraud and manipulation of [your token economy such as the Sybil attack](https://dl.acm.org/doi/10.1145/2185354.2185355) can be ignored. Bonus background reading: [The like economy: Social buttons and the data-intensive web](https://doi.org/10.1177/1461444812472322).

**Comment by WJehee** [comment]
# Status update

All 6 members are added to organization, all members can compile the project and have read the background.
Added a like button to the main screen.

**Comment by synctext** [comment]
- Week3 and 1 member has done actual "test coding"
- Sprint goal: like button press, create upvote inside Trustchain transaction, send to channel owner.
-

**Comment by ivanstodorov** [comment]
https://github.com/NikolayBlagoev/trustchain-superapp/tree/profile-page

**Comment by synctext** [comment]
- Learning how things are done in Kotlin. 
- Selected one "volunteer" for user interface and integration

**Comment by WJehee** [comment]
# Meeting (14-03-2023)
## Done
- Embedded like into trustchain block
- ...

## Goals
- Request chain crawl when joining the network after inactivity [(issue)](https://github.com/NikolayBlagoev/trustchain-superapp/issues/11)
- Like functionality even without any peers [(issue)](https://github.com/NikolayBlagoev/trustchain-superapp/issues/13)
- Gather more videos and likes so we can start giving recommendations
- Integrate profile page with actual data
- Create pull request for March 20th

**Comment by synctext** [comment]
- Great content checkin by [Chelsea with Archive.org](https://github.com/ChrisSBras/trustchain-superapp/issues/1#issuecomment-1465608449) hacking https://github.com/Tribler/trustchain-superapp/commit/bd8f42daf66ff7b5e1075b031b4e36c167375ff4

**Comment by WJehee** [comment]
Made the [pull request](https://github.com/Tribler/trustchain-superapp/pull/141)!
We still need to fix the merge conflicts however, hopefully we can get that done within the next few days.

**Comment by WJehee** [comment]
# Meeting (23-03-2023)

## Progress
- Created the pull request into the main repo, but some questions:
  - How should we deal with merge conflicts for the UI? multiple groups are working on the same tasks as us and thus there are many conflicting things going on.
- Integrated profile page with the backend
- Content uploading
- Added timestamp to Like so we can sort based on most recently uploaded

## Goals
- Request chain crawl when joining the network after inactivity [(issue)](https://github.com/NikolayBlagoev/trustchain-superapp/issues/11)
- Like functionality even without any peers [(issue)](https://github.com/NikolayBlagoev/trustchain-superapp/issues/13)
- Generate content and likes + work on recommending content

**Comment by synctext** [comment]
- Made PR, but no review request. So idle for a week. 
- .APK for testing on issue next meeting (drive link?)
-

**Comment by WJehee** [comment]
#  Meeting (31-03-2023)
## Progress
- Fixed merge conflicts and fixed all the requested changes by reviewer, hasn't be reviewed again since however
- Recommender system theoretically works but still requires manual testing
- General bug fixes + live updating of profile page almost done
- Setup a private tracker that automatically seeds content

## Goals
- Hot content page ([issue](https://github.com/NikolayBlagoev/trustchain-superapp/issues/28))
- Refactoring/cleanup of code

**Comment by WJehee** [comment]
# Meeting (07-04-2023)
[Latest APK](...)

## Progress
- External storage permission on-demand works (since last week)
- PR is ready to merge, not merged still
- UI improvements: more live updating, red upload button
- [Animated GIF](...)

## Goals
- Peer / connections tab
- Hot content page / recommender details page

**Comment by synctext** [comment]
- 24 MByte .GIF demo :roll_eyes: 
- Solid demo, very happy with this team progress
-

**Comment by WJehee** [comment]
# Meeting (20-04-2023)

- [APK]()
- [Documentation in main readme](https://github.com/NikolayBlagoev/trustchain-superapp/tree/dev#detoks-1)
- [2nd level documentation](https://github.com/NikolayBlagoev/trustchain-superapp/blob/dev/detoks/README.md)

**Comment by synctext** [comment]
- user journey: it crashed on first start :rofl: 
  - 2nd try works
  - can upload video :+1: 
  - no refresh, but shows on profile page
  -

**Comment by NikolayBlagoev** [comment]
The tracker was not used for the demo. It is provided as an altruistic "dummy node" which can seed content when the original creator is not online. It is used as a more stable alternative to the IPv8 python package which was quite buggy and often refused to work. This implementation on the other hand was stable and would never fail us when we would need to test content uploading/downloading.

Currently we rely on public trackers to discover content (the bittorrent public trackers) and not on a private tracker (the phones seed the content themselves). There is no way as far as I am aware to have working magnet links reliably without trackers (and they havve become the defacto standard in the modern torrenting world).

The issue we aimed to counteract is the following (a short incentive analysis):
1) when a user creates their own video, they have interest to seed it (as they want  others to discover it).
2) When another user downloads that video, they are obligated to also upload (by the bittorrent protocol, as otherwise their download speed would also halt). Thus when downloading another person also has incentive to seed.
3) When the video is downloaded the other person no longer has an incentive to seed. Even in the current bittorrent protocol, seeding after the file is fully downloaded is considered purely altruistic behaviour.
4) The original user can then disconnect from the network (application closed, changed networks, etc. - all of which were issues not fully resolved by either IPv8 or libtorrent). Thus their video can no longer be downloaded by abyone. If the network were large enough, there could often be many active users currently sharing content between each other, thus, probabilistically, that content would not be lost.
5) However, as we are in a stage with only 3 users, we provide altruistic nodes which can help the network in the early stages and thus not lose engagement.
