### ISSUE TITLE
Blockchain Engineering 2023 - Offline Token Money II

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7308]
Team issue for 10 weeks of blockchain engineering course at Delft University of Technology

**Offline token money.** Your task is to create easy payments using tokens, without Internet. Giving and receiving tokens should be easy and effortless. Special requirement is that it should also work in an emergency: when the Internet is down. Probably you need to use QR-codes scanning to move Tiktok Tokens between devices. The hard scientific task is to address the double spending risk. Required background reading from Delft: [Double spending prevention of digital Euros using a web-of-trust](https://arxiv.org/pdf/2204.06831.pdf).

- Discussed: 20 and 21 April (week 10) final meeting.
- {tentative} final project goal. Create token. Transfer token to another device. Some measure for double spending mitigation. 
- Prior work around Euro token transactions:
  - [digital Euro engine](https://github.com/Tribler/tribler/files/10721496/Performance_Analysis_of_an_Offline_Digital_Euro_Prototype_13_02_23.pdf) {thesis work, nearly finished, https://github.com/KoningR/eurotoken }
  - [Another digital Euro in trustchain-superapp](https://github.com/Tribler/trustchain-superapp#digital-euro)
  - [Github details of previous team: code, links, context, and comments](https://github.com/Tribler/tribler/issues/6785#issuecomment-1098918015)
- You can assume a central authority in the form of a "ECB Digital Euro Public Key", hardcoded public key. Not a central trusted server.
- First sprint goal: Create unique coin ```EURO 000001```, signed by yourself, Show QR code, scan QR code (all this is already operational inside [Superapp](https://github.com/Tribler/trustchain-superapp/blob/master/valuetransfer/src/main/java/nl/tudelft/trustchain/valuetransfer/dialogs/QRCodeDialog.kt#L26)), copy inside [trustchain data structure](https://github.com/Tribler/kotlin-ipv8/blob/master/doc/TrustChainCommunity.md).
  - feel free to build upon the work already done: https://github.com/Tribler/trustchain-superapp/pull/129

**Comment by Ne184** [comment]
The team went through the double spending paper and notice that it should be the receiver the one who needs to get the warning message and the trust-score of the sender, since he is the one who is expecting to receive money.

Everyone also looked at the Trustchain paper to get acquaint how Trustchain is working and be able to reason about the double spending issue in an offline scenario.

QR scanner was developed, but need to be integrated with DetToks.
QR code was also successfully produced

**Comment by synctext** [comment]
Great find! Receiver is taking the risk :police_officer: did not notice this problem earlier. The flow does not match typical trading situations!

**Comment by synctext** [comment]
Offline Euro is coming: https://ec.europa.eu/commission/presscorner/detail/en/SPEECH_23_1547

**Comment by julio1998** [comment]
Based on the meeting of last week we revised our flow and reduced the task to a viable MVP. 

**Score:** the score should be dependent on the size of the EuroToken. The more transactions in the token, the larger the token. This is because by a change of owners a block is added to the token.

**Verification:** two ideas 1) Verify each user in the chain of owners, checking that they had the token and checking with every user in their "address book". 2) Add transaction to TrustChain. The transaction will be between the initiator and final owner of the EuroToken. If the transaction is added, it is considered valid. Double spending should be detected by comparison of chains in the TrustChain network.

Our MVP can be divided in the following tasks:
- Create and store EuroToken
- Verify EuroToken
- Encode and create QR for EuroToken
- Verify EuroToken with transaction on TrustChain
- [OPTIONAL] Detect double spending on TrustChain

Each task has its corresponding UI.

What we've done since the last meeting:

- Added a new page to create tokens and show it on the screen (Ali)
- Add the functionality for adding a friend in the list of friends, add list  to the wallet  (update the encoding of the QR code to encode token which is also assigned the new owner) though some stuff are still hard coded (Nevana & Vyshnavi)
- Setup TrustChain Community inside the DeToks app. Experienced some difficulties during creation, should be running by Wednesday (Julio)

**Comment by julio1998** [comment]
We have been working on creating a working APK. Unfortunately we have run into some issues that slowed down our progress. Up until this point we have a working QR code scanner and are able to add and retrieve the wallet of the user. We are not able to display this in the app. We also experienced issues with generating a proper APK.

TODO's:
- Display tokens from user wallet
- Display tokens in admin wallet
- Make money transfer between two users
- Verify token from user by admin

**Comment by synctext** [comment]
- :warning: concern about the progress. Not as much progress as needed by Week 8. Partial running code.

**Comment by VyshnaviMN** [comment]
GIF - https://drive.google.com/file/d/1Om2BhDseR2K3bHnyacP2KV7krysMa7cg/view?usp=sharing

APK - https://drive.google.com/file/d/1MH3qiH1NXBtPdBbfjCnsNqvs3r8FT5Wg/view?usp=sharing

**Comment by Ne184** [comment]
Decentralised TikTok skeleton app for the CS4160 Blockchain Engineering (2022/23) course.

Detoks - Offline Token 2
An easy payment application that makes sending and receiving tokens easy. A user can choose the amount to be received and create a request which can be paid by a preadded contact. The payment can then be done by scanning the generated QR code and a transaction is then made. A Eurotoken is minted and verified by a central authority.

GIF - https://drive.google.com/file/d/1Om2BhDseR2K3bHnyacP2KV7krysMa7cg/view?usp=sharing

APK - https://drive.google.com/file/d/1MH3qiH1NXBtPdBbfjCnsNqvs3r8FT5Wg/view?usp=sharing

Use case
The application can be used for the following use cases:

Create and store EuroToken (add screenshot)
Encode and create QR for EuroToken (screenshot)
Send and receive EuroToken between contacts
Add new contact
Double spending
To mitigate double spending, contacts are to be added before users can send or receive EuroTokens. This makes it easier for admins to track double-spend EuroToken and give users warnings when trying to add malicious users. Another important concept is used to make sure that the detection of double spending is relatively on time. After receiving a new token, the token is valid for a limited amount of time (a month). After that month a token must be verified before being able to re-spend it. The token will be restamped with a new timestamp which makes it a valid euro token.

Future work
To detect the double spending, two ideas were discussed which can be implemented in the future:

Using the verifivation mechanism, double spending can be easily detected when two users try to verify the same token. The authority will be able to direcly detect the double spender.
To prevent double spending in offline transactions, a given precentage of the user tokens is preserved and cannot be used to make payments until the user comes online.

**Comment by synctext** [comment]
- For first time the .APK installs!
- Observed a crash
- Coins expire in 3 minutes (develop setting enabled)

**Comment by VyshnaviMN** [comment]
![WhatsApp Image 2023-04-21 at 13 11 35](https://user-images.githubusercontent.com/51911288/233622419-b0c14d6f-bf4f-4c95-9b20-0410eb40a821.jpg)

**Comment by Ne184** [comment]
![341293116_174704952174198_3206087210429801774_n](https://user-images.githubusercontent.com/64256244/233624595-92e0c52d-7af8-4261-a521-09f4f9885976.jpg)

**Comment by Ne184** [comment]
<img src="https://user-images.githubusercontent.com/64256244/233625947-af15f349-c9fb-4c7c-91b3-e94531c302ee.jpg" width="200" height="500">

**Comment by VyshnaviMN** [comment]
Sending token to Prof

<img src="https://user-images.githubusercontent.com/51911288/233626037-17d91742-2e54-4a69-b54a-559e2563c203.jpg" width="200" height="500">

**Comment by alikahawa** [comment]
![WhatsApp Image 2023-04-21 at 13 36 24](https://user-images.githubusercontent.com/33638860/233626329-61f71ad0-8eaa-446c-866e-66bc086d7374.jpeg)

**Comment by VyshnaviMN** [comment]
Updated README.MD
https://github.com/Ne184/trustchain-superapp/blob/master/README.md#detoks---offline-token-2

Latest APK:
https://drive.google.com/file/d/1zxzoBY8qajuBgrMbMmRIugr_gUV28PUf/view?usp=share_link

Added Standard Euro Denominations (.5 Euro, .05 Euro, 1 Euro, 2 Euro, 5 Euro)
- Supports fraction sums
- Can send more than 1 coin at a time

**Comment by synctext** [comment]
- ```An offline payment application that makes sending and receiving tokens easily.``` Please note that developers probably do not understand that this app is _exclusively_ offline. No usage of the IPv8 networking stack is made, not for the token transfer and neither for the ```Add Friend`` feature.
