### ISSUE TITLE
Msc placeholder: exploring LLM as a database

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7435]
_placeholder for brainstorm_. Finished all master courses. (part-time side job)
Exploring for 1 month what a good master thesis direction is around LLM. 

Draft master thesis (again placeholder): **Adding memory to LLM and large-scale ingestion of facts**

Recommended paper to understand your thesis context and goal further. With donations of resources by volunteers it is possible to build a giant foundational model. [Towards Crowdsourced Training of Large Neural Networks using Decentralized Mixture-of-Experts](https://arxiv.org/pdf/2002.04013.pdf). 

with 22k stars this is more popular: https://github.com/imartinez/privateGPT ```LLM: default to [ggml-gpt4all-j-v1.3-groovy.bin](https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin). If you prefer a different GPT4All-J compatible model, just download it and reference it in your .env file.```
A possible starting point is the Vicuna enhancement, as a database: https://github.com/csunny/DB-GPT ```In addition, we provide private domain knowledge base question-answering capability through LangChain. Furthermore, we also provide support for additional plugins, and our design natively supports the Auto-GPT plugin.```
Third option: [NanoGPT](https://github.com/karpathy/nanoGPT) ```The simplest, fastest repository for training/finetuning medium-sized GPTs. It is a rewrite of [minGPT](https://github.com/karpathy/minGPT) that prioritizes teeth over education. Still under active development, but currently the file train.py reproduces GPT-2 (124M) on OpenWebText```
Fourth: smaller than medium{nano} is https://github.com/Lightning-AI/Lit-Parrot ```Hackable implementation of state-of-the-art open-source large language models.```
Concrete ToDo:
- hardware, DAS6 with RTX A4000 GPU account in future
- software and model setup
- first changes and enhancements (trivial changes is OK at this early stage of master thesis)
- Understand [adding memory state through Langchain](https://python.langchain.com/en/latest/modules/memory.html)
- Get this running ??? https://python.langchain.com/en/latest/modules/memory/getting_started.html#conversationbuffermemory
- after 1 month we write down the draft master thesis goal (modify as needed)

![image](https://github.com/Tribler/tribler/assets/325224/fe91990f-e551-429d-93bb-a85dc9656d53)

Please register here:  https://mare.ewi.tudelft.nl/

**Comment by synctext** [comment]
For now the most simple around seems to be nanoGPT. Simplicity is always the superior starting point for extreme decentralisation. Thus this seems like a good start for fully LLM as a database + decentralisation or local-only.

**Comment by synctext** [comment]
URL | Description
---|---
https://youtu.be/eogpIG53Cis | Blade Runner (1982) Official Trailer - Ridley Scott, Harrison Ford Movie
https://youtu.be/vKQi3bBA1y8 | The Matrix (1999) Official Trailer #1 - Sci-Fi Action Movie
https://youtu.be/k64P4l2Wmeg | The Terminator (1984) Official Trailer - Arnold Schwarzenegge Movie
https://youtu.be/bwcADuJZDNA | Mad Max: The Road Warrior | 4K Trailer | Warner Bros. Entertainment
https://www.decayfilm.com/static/files/Decay_2012_1080p.torrent | DECAY is a zombie film made and set at the LHC
```magnet : ?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10``` | Sintel
https://webtorrent.io/free-torrents | public domain and Creative Commons torrents

Big Buck Bunny [(torrent file)](https://webtorrent.io/torrents/big-buck-bunny.torrent) [(magnet link)](magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent)

Cosmos Laundromat [(torrent file)](https://webtorrent.io/torrents/cosmos-laundromat.torrent) [(magnet link)](magnet:?xt=urn:btih:c9e15763f722f23e98a29decdfae341b98d53056&dn=Cosmos+Laundromat&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fcosmos-laundromat.torrent)

Sintel [(torrent file)](https://webtorrent.io/torrents/sintel.torrent) [(magnet link)](magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent)

Tears of Steel [(torrent file)](https://webtorrent.io/torrents/tears-of-steel.torrent) [(magnet link)](magnet:?xt=urn:btih:209c8226b299b308beaf2b9cd3fb49212dbd13ec&dn=Tears+of+Steel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Ftears-of-steel.torrent)

**Comment by bimbridge** [comment]
- I have nanoGPT running on my local env. It works both on my GPU and CPU.
   
![image](https://github.com/Tribler/tribler/assets/94065795/0bee246d-0e1c-4266-b16d-2b63dc3d2c9c)

**Comment by keonchennl** [comment]
- I have nanoGPT running on my local env. It works both on my GPU and CPU.
   
![image](https://github.com/Tribler/tribler/assets/94065795/0bee246d-0e1c-4266-b16d-2b63dc3d2c9c)

The pretrained part of the GPT2 model (baseline) is from https://huggingface.co/gpt2

**Comment by synctext** [comment]
### URL2Vec: AI crisis for copyright monopolies

{Possible thesis brainstorm} Many have written about the ongoing [copyright crisis due to generative AI in the creative industry](https://arstechnica.com/tech-policy/2023/07/generative-ai-in-games-will-create-a-copyright-crisis/). This thesis demonstrates that AI, specifically Large Language Models pose another threat. We build upon breakthroughs in on-device machine learning and embedding to create a decentralised Google-ish search engine. 

We present a tool which is able to learn online URLs for Youtube, Tiktok, Bittorrent, and IPFS. In principle, this tool removes the need for Internet intermediaries such Big Tech and Hollywood. Independent producers or influencers can easily research their audience based on our URL2Vec tooling. This will put further pressure on the legal construct of copyright.

**Comment by qstokkink** [comment]
Working from the "Naive ToDo" list, concrete steps toward publishable results could be the following:

1. Adapt https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html to create AI that can convert `token sequence -> linear (i.e., 1 magnet link)`
2. Add NanoGPT to this model for `NL -> token sequence -> linear (i.e., 1 magnetlink)`
3. Train this and see what happens.
4. Use RNN instead of a linear layer for `NL -> token sequence -> generated magnetlink (20 bytes/160 bits output)`
5. Train this new model and see if it is better than the results from step 3.
6. Publish results?

**Comment by qstokkink** [comment]
It seems my idea for comparison (between transformers and RNNs) has been performed before: https://arxiv.org/pdf/2005.09471.pdf
Instead of natural language next word prediction, you would be investigating next word prediction of a fixed-size resource but this is probably good related work to reference.

**Comment by synctext** [comment]
Open LLM challenges. Great background read for writing introduction and citations for Problem Description: https://huyenchip.com/2023/08/16/llm-research-open-challenges.html

**Comment by synctext** [comment]
- this tutorial prepares for the complexity of nanoGPT: https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html
- NanoGPT uses positional encoding! assign weights to the position of the terms, used in NanoGPT
- Do it "The Right Way!". Actually model the magnet link with 20 Bytes of the SHA1 hash (160 bits). Generate 160 bits in the generative AI at the neuron level. Next step sequence model and next token prediction. First bytes of a magnet link predicts the remainder of the URL.

**Comment by keonchennl** [comment]
Some progress has been made:
- I finetuned the pretrained model [BertForSequenceClassification (bert-base-uncased)] (https://huggingface.co/docs/transformers/v4.32.1/en/model_doc/bert#transformers.BertForSequenceClassification) on the [USVideos dataset](https://www.kaggle.com/datasets/datasnaek/youtube-new?resource=download&select=USvideos.csv).
  - Notebook including results can be found [here](https://github.com/keonchennl/youtube-url-ml-map-search/blob/main/youtube_video_id_predictor.ipynb) 
  - Index was used as label instead of one-hot encoding in the end since the model expects 1 value instead of a vector as the label
  - The training was initially on my local env. After 2 epoch the model was able to predict 63.5% video ids correctly including the 4 given video titles.
  - Later the training was moved to [Colab](https://colab.research.google.com/drive/16d5BnMceoDNEtyihXf_zatAoZjlPQryq?authuser=1#scrollTo=kGgiLpbejU5e) for better training. Weird thing happened that the performance dropped after more steps.
- GPT2 has also been tried for this task but wasn't able to train due to memory limit of my local environment.

Some reflections:
- We now only care about the 'look up' result. In this way, we are basically using the training data itself to test the result. Since the training error should keep dropping with more data, however this is not the case in the current experiment.
- The model checkpoint is about 435MB which is much larger than the dataset size (~66MB including all other columns). If we use a larger training dataset with more labels, the size of the model checkpoint will get slightly bigger due to the larger dense layer for classification. The increase of the model won't be proportional to the size of the data or the number of labels. Say If we use bigger dataset in the future, the model might be possible to be smaller than the dataset size? which could be the compression we want?

**Comment by synctext** [comment]
- ```2 epoch the model was able to predict 63.5% video ids correctly including the 4 given video titles.``` :clap: :confetti_ball: 
  - amazing success after only a few weeks of exploring with the magic of AI
  - Congrats with 63.5% recall !!

**Comment by keonchennl** [comment]
- Some experiments were performed based on cleaning the dataset
  - If we remove all the duplicates based on `video_ids`, resulting in `6351` unique values, and perform more epochs (20 or 30) of training, the recall rate drops to nearly 0. The training error almost did not drop.
  ![image](https://github.com/Tribler/tribler/assets/66115421/4557e28e-02c6-44ed-9cc4-9f294a3bc813)
  - Similar results were also shown on removing duplicates based on column 'title'
- However, when I used original data containing duplicates for training, I was able to achieve a recall of 96.19%
  - The training error dropped drastically after 8 epochs of training
  ![image](https://github.com/Tribler/tribler/assets/66115421/e52cbb44-62b8-42b7-8c3b-c8d131d08e07)
  - This explains the overfitting since the duplicates in the original data may contribute to faster convergence.

**Comment by synctext** [comment]
- Spend 1 week why the 6351 fails to convergence and the 40949 with convergence already from 1k to 2k steps.

**Comment by keonchennl** [comment]
Notebook [https://colab.research.google.com/drive/19jAa7-8cxW4PYnh5TaRwdKyv9fjX0yl9?usp=sharing]

**Comment by synctext** [comment]
- Related work update: [Why AutoGPT engineers ditched vector databases](https://dariuszsemba.com/blog/why-autogpt-engineers-ditched-vector-databases/)
  - numerous startups focus on Vector Databases
  - the first negative story, in reality this does not work! Because: memory
    - by these people https://github.com/Significant-Gravitas/AutoGPT

**Comment by keonchennl** [comment]
- Sicked for a week
- Code clean up
- Made the training work for the new notebook [Notebook](https://colab.research.google.com/drive/19jAa7-8cxW4PYnh5TaRwdKyv9fjX0yl9?usp=sharing)

**Comment by synctext** [comment]
- Please write a progress update **before** the meeting, this did not happen multiple times.
- Keep laser-sharp focus on progress. Why did you revisit the non-duplicates non-converging approach?

**Comment by synctext** [comment]
From our phd student Petru: https://github.com/Tribler/tribler/issues/7586#issuecomment-1790956120
_[Transformer Memory as a Differentiable Search Index](https://arxiv.org/pdf/2202.06991.pdf). The paper argues that instead of using a dual-encoder method (where we encode the query and the document on the same space and then find the document which is nearest neighbour to the query) we can use the differentiable-search-index (DSI), where we have a neural network map directly the query to the document. The paper presents a number of methods to achieve this but the easiest one to implement for me at this time was to simply assign each document one number, have the output layer of the network be composed of the same number of neutrons as the number of documents and make the network essentially assign probabilities to each document, given a query. Additionally, the paper performs this work with a Transformer architecture, raising the possibility of us integrating Nanogpt into the future architecture._

**Comment by keonchennl** [comment]
## Dictionary extracted from titles from US videos dataset 
[dictionary_title_with_stop_words.txt](https://github.com/Tribler/tribler/files/13437513/dictionary_title_with_stop_words.txt)
[dictionary_title_without_stop_words.txt](https://github.com/Tribler/tribler/files/13437514/dictionary_title_without_stop_words.txt)
## Investigation about the broken code ([Notebook](https://colab.research.google.com/drive/19jAa7-8cxW4PYnh5TaRwdKyv9fjX0yl9?usp=sharing))
  1. Fixed a bug in the dataset class
  1. Things were tried to check why the result of the best model (with 96% recall) could not have been reproduced.
    - It turns out that the training still works but the data that was used to calculate the evaluation score was not the one for training.
    - A subset of the dataset (32759 samples) was used for training the model but the whole dataset (40949 samples) was used for evaluation
    - It happened due to the exploration of the dataset splitting and de-duplication
  1. It was able to reproduce the 96% recall using the same subset data (32759 samples).
    - The best model can be found [here](https://drive.google.com/drive/folders/1-gLLixQA99Tzk1LXR5R60o92RUCUu9fO?usp=sharing) 
    - The data for reproduction can be found [here ](https://drive.google.com/file/d/1-1tkQ1oNc0uH7CNLSw5Ow-hVN30ZKsIv/view?usp=sharing) or be retrieved via a 80/20 split with a random state of 42 (see the notebook).

## Findings
  1.  With the same training data. the model has high possibility of not converging because of the randomness in the training process. 5 experiments have been performed, but only 1 has loss dropped below 7.5. 
![image](https://github.com/Tribler/tribler/assets/66115421/564e9d5f-be39-49a1-a8a9-c9ff495dca41)
  1. With the best model, the performance given the whole title is good. But the fewer words we give the worse performance it may have. For example, if we give 'cat', it can hardly predict title that has 'cat'.
  1. I checked the [Differentiable Search Index (DSI) approach](https://github.com/Tribler/tribler/issues/7435#issuecomment-1801896341) Fine tuning, a `BertForSequenceClassification` (encoder + a classification layer) looks a bit similar to the DSI approach that paper proposed. Perhaps it's nice to look into applying a (encoder + decoder) seq-to-seq model.
  1. The metric now is comparing the exact title. Maybe I should involve other [relevance metrics](https://opensourceconnections.com/blog/2020/02/28/choosing-your-search-relevance-metric/#ndcg). Such that the 'cat' example works well.

## Experiments with Word2Vec
  1. I explored starting with word2vec from scratch.
    - word2vec => vectors => nearest neighbor => the closest  
    - [Notebook can be found here](https://colab.research.google.com/drive/1rKln9hvZfVENRUmmMKgAgiVQXdUr4OKz?usp=sharing)
    - To represent the video better. Words from description and tags are also included for training.
    - Different hyperparameters are tried.
    - The best recall we get so far is 18.67%
    - The exact title prediction gives bad performance. But the one word prediction looks better than the BERT model.
  1. Then rather than training from scratch, using `google news neg 300` model is also tried. [Notebook](https://colab.research.google.com/drive/1ECfJPzeHGgn2r2yJXbLRc8eS76QR2D-Y?usp=sharing)
    - bad performance as well
    - index issue
    - rare word issue. e.g. 'aquarius' is not in the vocabulary

**Comment by synctext** [comment]
- making progress!
- Can you make your notebook stand-alone? (```us_videos_data = pd.read_csv(workdir_path / 'USvideos.csv')```) 
  - URL: https://www.kaggle.com/datasets/datasnaek/youtube-new?resource=download&select=USvideos.csv
  - Download fresh every time script runs? 
  - No need for magic data on your Google Drive!
  - Simply works without 'install'

**Comment by bimbridge** [comment]
- Draft of part of the thesis https://www.overleaf.com/read/jnbcnktyfrgq#719f90
- Refactored according to the feedback from Quinten

**Comment by keonchennl** [comment]
- Draft https://www.overleaf.com/read/jnbcnktyfrgq#719f90
- Refactored according to the feedback from Quiten
- Notebook updated

**Comment by synctext** [comment]
- First master thesis text :tada: 
- ```We perform training on a NVIDIA T4 GPU for 8 epochs.```, add that you simply use the Google free GPU cloud offering

**Comment by keonchennl** [comment]
- Got hands on and learned how to work with the DAS system
  - DAS6 is pretty bare-metal so a bit difficult to set the environment (compiling Python, installing dependencies etc)
  - Waiting for an internal update of a C compiler on the DAS6-delft side for compiling Python, which requires admin privilege
- Not sufficient time was made for experimenting due to work and personal reasons
- Checked model T5 and the nanoT5 repo
  - Since it's a text-to-text model and it suits very general tasks, modifying the model (such as by adding a layer) seems not a proper way.
  - Instead, I could maybe try:
    1. Fine-tuning (or pertaining?) nanoT5 with the us-videos dataset such that it 'remembers' the data
    1. Use prompt engineering for evaluation. e.g. Prompt: 'Retrieve a video ID to your knowledge given the following text: "<some input text such as a video title>" and return the video ID (an 11-character string) directly' and the output is then expected to be the video id
    1. Use the output for performance evaluation  
- The other Idea: BERT + last layer as direct video id output:
  - Since BERT only used 'encoder', this might work things out.
  - I haven't tried it out

**Comment by synctext** [comment]
- Not as much progress as hoped
- Please explore using Google Colab with NanoT5 using Pytorch
- Fine-tuning of video IDs
- core of your master thesis: operational DSI
- Aim for a loss-function figure.

**Comment by synctext** [comment]
- This level of progress is not leading to a master thesis
- Please contact Petru, as suggested on 6 Nov

**Comment by keonchennl** [comment]
- Thanks to the 'debug' session with Petru, things got clarified and a defect in the code was discovered and fixed. Some findings during exploration after the session:
  - The plateau of the learning graph: The learning was still going on but might be getting around some local optimum. By continuing training enough more epochs (20 more epochs), the loss starts to drop again.
 
![image](https://github.com/Tribler/tribler/assets/66115421/5b35eb9e-8c74-452b-8015-0f014552dd96)

  - Learning rate: The learning rate was suspected to be the reason and it turns out the setup is ok. I used the default initial learning rate of 0.001, the default AdamW optimizer, and the linear scheduler, which can get the model to converge well.  
  - About doubt that the model cannot see a whole video_id as one token: It already turned out that the small T5 model can encode the video_ids using its existing vocabulary. I tried to add each video_id manually as one token, but the model does not work anymore. One explanation is that for new tokens the pre-trained model does not know them at all and thus needs to learn from zero. However, the input words are mostly in the vocabulary. This could make a pre-trained model hard to learn with our small training set.
  - The max-length for model.generate() can affect the performance. I used to set it to 11 (the length of the exact) but it lowers the performance by generating partial IDs. I think it's because special tokens affect the generation even if I skip them. But later I found setting it to 15 gives the best results.

-  As the down-scaling experiment works, I picked out 50 samples and trained more epochs till the model overfits (<0.0001 loss). **The recall rate gets nicely to at most 100%**. (But not stable - it varies from 76% to 100%) However, since it overfits very much, only the exact title gives a valid and correct ID. If I input a partial ID or one or a few words from the title, the model starts to hallucinate a lot. 
- I then scaled up to 200 samples, which also got 99% recall. (99% valid video ID and 99% mapped to the correct video title) But hallucinations are the same.
- Then I also tried the full unique data set (6455 with unique titles). The training time starts to explode. The plateau in the learning graph still appeared but the loss continued going down after some more epochs. With 3 hours of training, the loss can only drop to 0.02 and results in a 20% recall.
- Later I realized that 'overfit as much as possible' might be the wrong direction. Because for searching we actually want the model to generalize to handle fuzzy searchs. We want it to also perform well when we input part of the title or some keywords. In the exploration with BERT, the final mapping from the output index embedding to the video_id somehow hid this issue. Now that the model directly outputs the video_id, it's time to avoid overfitting.
- 
- I then came back to the 50 samples exploration. I tried data augmentation: I sampled phrases and words from each title and included the lower cases of the words for these corpora. The augmented data set size goes up to ~650, about 15 times of the original dataset. **But this seems to work well. The recall rate reaches 100% after 100 epochs of training of 3 hours.**
![image](https://github.com/Tribler/tribler/assets/66115421/23a98d38-475a-4450-88f3-9d1698220760)
![image](https://github.com/Tribler/tribler/assets/66115421/c6cc02b3-bfa8-4181-a6d7-a8e98682e696)

A demo notebook can be found [here](https://colab.research.google.com/drive/1WNNCVxkiQB4LskVhccCMPC9Lgad4Ddps?usp=sharing)

**Comment by keonchennl** [comment]
- As the 50-sample dataset gives good results, I tried scaling up directly to train with 6455 samples with augmented data again. I set the epoch less than the 50 samples run, the required training time is expected to be 17 hours. But it still crashed at the 13th hour due to the Colab environment. Colab [free tier allows at most 12 hours max connection
](https://research.google.com/colaboratory/faq.html#usage-limits) even if I used a custom GCP compute engine
- I retried using 2030 samples (augmented to 15108 samples) with 2006 video ids. And trained for 13 hours. The training finished successfully. But the result recall rate was low ![image](https://github.com/Tribler/tribler/assets/66115421/2de16743-103b-4299-80a4-ff16cdbcf746)
- I then looked into the augmented data and think the augmentation can be optimized. I switched to use Spacy to sub-sampling key words from the title. And I optimized the letter casing when proprocessing the data.

**Comment by synctext** [comment]
- Bug FIXED! Great step forward with thesis! 
- Your dataset is extremely limited with "Video Title"
- No semantic data to train on for an LLM with size of your "small T5"

URL | Description | tags
---|---|---
https://youtu.be/eogpIG53Cis | Blade Runner (1982) Official Trailer - Ridley Scott, Harrison Ford Movie | trailers HD, hd, trailers, trailer, 2013, official, HD, classic trailers, oldhollywoodtrailers, Harrison Ford, sci-fi, thriller, classic, blade runner, blade runner official trailer, blade runner trailer
https://youtu.be/vKQi3bBA1y8 | The Matrix (1999) Official Trailer #1 - Sci-Fi Action Movie | classic movie, movieclips, movieclipstrailers, movie clips, movieclipsDOTcom, movieclipscomingsoon, zefr, jslewis, Matrix, The Matrix movie, The Matrix trailer, The Matrix film, Lana Wachowski, Andy Wachowski, wachowkis, Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, matrix, sci-fi, action, bullet time
https://youtu.be/k64P4l2Wmeg | The Terminator (1984) Official Trailer - Arnold Schwarzenegge Movie | The Terminator, The Terminator movie, The Terminator trailer, 1984, James Cameron, Arnold Schwarzenegger, Linda Hamilton, Michael Biehn, Lance Henriksen, Earl Boen, Bill Paxton, Dick Miller, cyborg, indestructible, assassinate, war against the machines, soldier, i'll be back, Come with me if you want to live., Kyle Reese, Sarah Connor, Terminator, action, sci-fi, fandango, movieclips, trailer, classic trailer, trailer vault, mgm, hd
https://youtu.be/bwcADuJZDNA | Mad Max: The Road Warrior | 4K Trailer  Warner Bros. Entertainment | Warner brothers movies, warner bros movies 2019, warner bros movies trailers, warner bros movies 2020, warner brothers home entertainment, warnermedia, buy movies on youtube, stream movies online, rent movies online, Buy Mad Max: The Road Warrior online, Watch Mad Max: The Road Warrior online, Rent Mad Max: The Road Warrior, Stream Mad Max: The Road Warrior online, Stream Mad Max: The Road Warrior full movie online, watch Mad Max: The Road Warrior full movie online, 4K Trailer

**Comment by keonchennl** [comment]
> * Results 1 step == 20 samples.

Here I meant that it requires '20 steps' for `200 samples` (the full dataset).

**Comment by synctext** [comment]
- latest related work [to include called "self-retrieval"](https://arxiv.org/pdf/2403.00801.pdf)
- You mention smartphones, indeed [LLM-on-mobiles is being worked on by Samsung](https://techblog.comsoc.org/2024/03/07/koreas-kaist-develops-next-generation-ultra-low-power-genai-llm-accelerator/)
-

**Comment by keonchennl** [comment]
- I didn't make much progress in this sprint
- I refactored a bit on the T5 section [draft.pdf](https://github.com/Tribler/tribler/files/14848144/draft.pdf)
- I tried to validate the current way of training in the experiments and checked with Petru
    - Because the orginal data does not contain a query, I agumented the dataset by generate unseen queries (made up by using parts from the video title.
    - If we don't use 'real' query data we can not really check how well the model generalize.

**Comment by synctext** [comment]
- ```Self-retrieval benefits from index with meaningful natural language index```

**Comment by keonchennl** [comment]
The 3rd Experiment with Tags:
- Reform training data: I treat each tag as a user query and perform augmentation on each query. Augmentation involves keywords extraction from the tag and adding lower cases.
- I filtered the samples such that each tag (query) is unique. This means one tag maps to only one `video_id`. One `video_id` still have multiple tags.
- I split out a test set (without performing augmentation). But I found the test error does not make sense anymore. Because many tags in the test set are completely unseen and irrelevant of those in the training set. The model doesn't know which `video_id` it associates with. So I decide to only count precisions(recall) on the training set.
- For 100 original data samples, about 2300 (tag, video_id) unique pairs are generated.
    - I trained 70, 150, 200 epochs. The precision on the training set gets at 0.9615076.
- [notebook](https://colab.research.google.com/drive/1UqUE2r05cJ5m-fZEiveV1EuNS3jPrmJN?usp=sharing)
- I plan to train all tags (6300*20) with DAS6. And later compare the size of the model with data stored in a relational database like SQL.

- Some thoughts from the discussion with Petru:
    - It's hard to treat LLM really as a 'Database'. Because it might be difficult to implement even any of CRUD operations and make them stable.
    - Idea: Typo tolerant SQL (similar to fuzz search in a search engine) 
               Input a query with typo. LLM may accept it but SQL query can not.
	       To emulate a typo: insert 1 or 2 consecutive random chars into one tag(query)
    - Idea: Self-assessment like the self-retrieval papaer
        - Train another T5 model with randomized weight. Compare the TopK beam search results. Make use of both results to improve the performance.

**Comment by keonchennl** [comment]
- I found the Youtube Trending dataset on Kaggle has [an updated version](https://www.kaggle.com/datasets/rsrishav/youtube-trending-video-dataset?rvi=1&select=US_youtube_trending_data.csv). It has more data compared to [the old one](https://www.kaggle.com/datasets/datasnaek/youtube-new?rvi=1&select=USvideos.csv) Especially the USVideo set: old one has 6455 unique titles, and the new one has 48471.
- I switched to this udpated version of USVideo and use tags as query. This caused 340884 unique training samples.
- Training on DAS6 works! I setup the environment and is ready for training.

**Comment by keonchennl** [comment]
- If we don't filter the tags. one tag can map to multiple videos. If we train on this unfiltered data, can it generate multiple results (video_ids)?

**Comment by synctext** [comment]
- [Youtube trailers for 1000+ movies](https://www.kaggle.com/datasets/dineshvasired/movies-youtube-trailers-and-sentimentdinesh-dinesh)

**Comment by keonchennl** [comment]
- The results for the T5 tag experiment is better by encoding each video ID as a whole token. For 1000 and **10000** videos, it reaches 99.99% precision and recall.
- By manually checking the generated wrong I found the model actually performed better: The wrongly generated video id in fact are relevant videos because it contains the input tag! They should have been true positives but count as false positives because we only count it correct if the video id mapped exactly. If we use the new metric, the precision reaches 100%. 
- I wrapped up all experiment sections in the paper thanks to the feedback from @quintene  Here is the [Draft](https://github.com/Tribler/tribler/files/15391702/Thesis_Keon_2024.pdf)

**Comment by synctext** [comment]
- thesis results are now at master thesis level :racing_car: 
- solid step towards graduation!
- Green light form submitted :clap: :unicorn: :clap: 
- now focus on polishing **Table 1** into a graph
  - at least 7 data-points and a connecting dotted line.
  - Core of the thesis!
  - rough estimate of LLM semantic storage capacity for a fixed-epoch training budget.
- 1-week edit cycles with Quinten.

**Comment by keonchennl** [comment]
[Draft.pdf](https://github.com/user-attachments/files/15783664/Thesis_Keon_2024.4.pdf)
- Updated Table 1 with more datapoints (250 500 1000 2000 5000) and log-scale x-axis
- Polished Section Introduction, Problem statement and Related Work
- Meanwhile adjusted the title according to the content

**Comment by synctext** [comment]
- no peer-to-peer distributed system within introduction
- next step: final graduation form for finalisation of graduation date.
- Prior thesis title ward more broad and more understandable
- Using tags as queries experiment
  - clear that you use tags during inference
  - also mention explicitly if you use tags as training

**Comment by keonchennl** [comment]
-  Updated paper thanks to the feedback from @qstokkink   [Ver20240624.pdf](https://github.com/user-attachments/files/15961873/Thesis_Keon_2024.6.pdf)
    - Clarified assumptions
    - Rewrote system design
    - Reorganized Abstract, Introduction and Related Work sections
    - Polished wording
- Measured inference on my laptop (Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz + 1 GPU NVIDIA GeForce GTX 1650 Ti)
   - Average execution time per inference: 0.0520 seconds
   ~96 tokens per second (around 320.42% of Apple Foundation Model speed)
   - using python. No specific hardware optimization

**Comment by synctext** [comment]
- Nearly ready to defend :tada: 
- ```imbuing the docid space```, still has small items.
- Empty appendix
