### ISSUE TITLE
Option to send an error report when Tribler is stuck at shutdown

### ISSUE THREAD

**Issue by xoriole** [Tribler/tribler#7444]
Sometimes Tribler is stuck at shutdown which is not easy to reproduce. Currently, after a while, we show the users a button to force shutdown. In such a case, if we provide an option for the user to send us an error report, it will help us better understand the reason why Tribler was stuck.

![tribler-force-shutdown](https://github.com/Tribler/tribler/assets/1442867/0e8b91d7-7612-468e-aaa2-51efaac5bb84)

**Comment by synctext** [comment]
Very good idea. Libtorrent IO still seems to act out on Tribler. This would be great way to diagnose the 10-15 minute shutdown duration on a 6-years old Mac by User 0.

**Comment by drew2a** [comment]
@xoriole 

> In such a case, if we provide an option for the user to send us an error report.

How do you see the formation of the error report in this case? I'm asking because it is not obvious, and I want to know your view. If Tribler is stuck at shutdown, there would probably be no errors, just slow operations. Our FeedbackDialog method of sending errors assumes that you have an actual exception.
