### ISSUE TITLE
Tribler pre- V7.5.2 users are no longer in stats

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7573]
We lost all Tribler pre- V7.5.2 users. Or we stopped collecting stats on them or being able to connect to them.
Our [network crawler](https://dashboard.tribler.org/) indicates all our ```users <7.5.2``` are gone. What happened 3 or 4 Aug 2023?
 ![image](https://github.com/Tribler/tribler/assets/325224/61cd5155-eac9-4d9e-b9d2-773eaef2313e)
Because this is 303 users which sudenly disappeared, these are not normal user behavior issues. Something changed or got broken. Not a priority, but good to document what happened. Maximum 1-2 hours worth of our precious Dev Time.

**Comment by qstokkink** [comment]
Before 7.5.2 we had to guess what version users were running based on their reported community ids. This was an expensive operation.

Since #5524 (merged in 7.5.2), we have a stable URL for version detection and we now no longer have the guessing logic running. This is a much more lightweight operation. So the users are still there but we can't see them.

Unless we want to specifically see the old users, I reckon its acceptable to have these old users hidden and I'll close this issue.
