### ISSUE TITLE
Checkpoint information is shown on the Downloads Page just after Tribler is run

### ISSUE THREAD

**Issue by drew2a** [Tribler/tribler#7770]
**Describe the bug**
Instead of downloads, I see the checkpoint information on the Downloads Page just after Tribler is run. Some time later it turns to the normal downloads.

**To Reproduce**
1. Search for Ubuntu
2. Download any torrent with low seeders count
3. Close Tribler
4. Open Tribler
5. Go to the Downloads Page

**Expected behavior**
I expect to see the download but I see the checkpoint information instead.

**Screenshots**
<img width="845" alt="image" src="https://github.com/Tribler/tribler/assets/13798583/2765ad80-ba98-4a50-a55b-78ab2fc1f6eb">

**Desktop (please complete the following information):**

- OS: macOS
- Tribler's version: main `a25df64ad67e263fe84f65a0faa4753737bf914b`

**Comment by qstokkink** [comment]
This is actually not a bug but a feature and it has been designed like this:

https://github.com/Tribler/tribler/blob/8158747c914041ab55341dbb782c702bcf736ef6/src/tribler/gui/widgets/downloadspage.py#L186-L197

However, we've had a bug for years where the core would not answer any requests while the checkpoints were still being loaded. So, this feature remained hidden.

**Comment by drew2a** [comment]
@qstokkink, good to know. :) 

Perhaps we could fix the layout for it and leave it as it is? 

Although I liked the previous (buggy?) behavior, where a user sees downloads in the familiar layout, but with a "waiting for..." status.

**Comment by qstokkink** [comment]
The feature was implemented to fix #7032, which states the following:

> the user can wait until Tribler starts successfully, albeit with a "Loading" page showing for a very long time.

Apparently, the "waiting for..." or "loading" status was unacceptable to the original reporter (@kozlovsky) and having some form of progress shown was necessary.

Personally, I have no strong opinions on this issue. Both the previous resolution and the proposed resolution are fine by me.

**Comment by drew2a** [comment]
This behavior was introduced in

- https://github.com/Tribler/tribler/pull/7666

I've tested it with the following commits:

- https://github.com/Tribler/tribler/commit/d018d66c655bedb177efc2a17bde7dc1c536736b. Works correctly.
- https://github.com/Tribler/tribler/commit/f610c82ab5ba02004244131e0ebab8d621600c7d. Works incorrectly.

Related to (has a common root cause):
- #7768

**Comment by qstokkink** [comment]
@kozlovsky since you introduced this behavior in #7024, are you OK with reverting your changes?

**Comment by kozlovsky** [comment]
@qstokkink I'm investigating this

**Comment by kozlovsky** [comment]
The checkpoint counter was initially added to avoid user confusion when Tribler starts with an empty list of downloads. Some users were scared then that "all downloads have disappeared". After the recent updates in the main branch, the delay between the moments when Tribler started and when downloads appeared became even more extensive.

As it turns out, downloads are displayed with a delay because of a blocking call inside the first `DownloadManager.load_checkpoint` invocation. `DownloadManager.load_checkpoint` calls `DownloadManager.start_download`, which in turn calls `DownloadManager.start_handle`. Then, the entire `load_checkpoins` loop pauses until enough DHT peers are available before calling `ltsession.async_add_torrent` to start the actual downloading.

It is possible to fix the issue by splitting `DownloadManager.start_handle` into two parts, calling the second (delayed) part as a separate task. Then, all checkpoints can be restored without any significant delay.
