### ISSUE TITLE
per torrent ratio and up/down do not match

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#7817]
**Describe the bug**
per torrent ratio and up/down do not match

**To Reproduce**

1. download a torrent
2. restart part way through

**Current behavior**
total ratio is shown with session up / down

**Expected behavior**
total ratio should be shown with total up / down

**Screenshots**

![wut(1)](https://github.com/Tribler/tribler/assets/1793802/579bbf86-36f3-487d-bedf-e85a8cb1f031)

**Comment by qstokkink** [comment]
For debugging, a breakdown of these numbers:

What is shown:
https://github.com/Tribler/tribler/blob/4e25843a2252a33c0fb286b3b8bd4f2969a64757/src/tribler/gui/widgets/downloadsdetailstabwidget.py#L174-L178

Where it comes from:
https://github.com/Tribler/tribler/blob/b89ca5bd2d3b6afc0fc0128250719529e8688a31/src/tribler/core/components/libtorrent/restapi/downloads_endpoint.py#L331-L333

How it's implemented:
https://github.com/Tribler/tribler/blob/4fd1c8a20bc4825e00cbdb22980d669343ffc104/src/tribler/core/components/libtorrent/download_manager/download_state.py#L100-L114

The core of the inconsistency seems to be that the shown ratio is `all_time_upload / total_done` and the expected ratio (based on the reported "up" and "down") is `total_upload / total_download`.

**Comment by kozlovsky** [comment]
After some investigation, I need to say that the previous formula `all_time_upload / total_done` is close to the correct answer and is an expected way to calculate the `ratio`.

For each torrent session, we have:
* `total_upload`, `total_download` - the number of bytes downloaded and uploaded to all peers, accumulated, **this session only**. The session restarts when a torrent is paused and restarted again. When a torrent is paused, these counters are reset to 0.
* `total_payload_download,` `total_payload_upload` - the number of bytes sent and received this session, but only the actual payload data, ignoring any protocol overhead. When a torrent is paused, these counters are reset to 0.
* `all_time_upload` and `all_time_download` - are accumulated byte counters; they are saved in and restored from resume data to keep totals across sessions.
* `total_done` - the total number of bytes of the file(s) that we have. All this does not necessarily have to be downloaded during this session.

The `ratio` value is commonly considered as `uploaded` / `downloaded`, where the exact meaning of "uploaded" and "downloaded" can differ slightly depending on a specific corner case and a specific torrent client.

* When a user pauses and restarts a torrent several times, he still expects the ratio to be calculated over all session restarts, so `total_upload` and `total_download` are unsuitable.
* `all_time_upload` and `all_time_download` suits better, but we should not include protocol overhead and rejected blocks that failed integrity checks in the total download. Using `all_time_download` could potentially inflate the download portion of the ratio if some torrent pieces were downloaded multiple times due to errors or incomplete transfers. Therefore, `total_done` is the most suitable counter for the `ratio` calculation.

But **I agree that the calculated `ratio` does not match with the `up` /  `down` counters** because counters currently only display the data for the current session (after the torrent was unpaused). To fix it, we should also display the total number of uploaded/downloaded bytes.

So, the torrent statistics can be displayed as:
```
Ratio: 0.1, up: 1 MB (total 100 MB), down: 2 MB (total 1 GB)
```
This should remove user confusion, as the `ratio` is calculated for totals that will be displayed now.

There is a corner case that is not correctly handled by the current formula: when a user seeds a pre-downloaded torrent, and the `total_done` counter is `0`, the `ratio` is calculated as `0`. It should be ♾ or "MAX" instead because `0` has the opposite meaning for the ratio.

**Comment by Dmole** [comment]
I think it would make most sense to display just the all-time ratio/numbers but if both are to be shown then separate them like this:


`Ratio: 0.1, up: 100 MB, down: 1 GB (Session Ratio: 0.5, up: 1 MB, down: 2 MB)
`

**Comment by synctext** [comment]
All time ratio is defined as total from, say, 10 Tribler sessions. The original if report was (possibly) simply that all counters reset when restarting Tribler.
