### ISSUE TITLE
Blockchain Engineering - class of 2024 - Team Democracy-1: blockchain networking (b)

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#7913]
Project assignment for Delft University of Technology master course called "[blockchain engineering](https://github.com/Tribler/tribler/issues/7691)".
**Democracy-1: Blockchain networking**
- ~~Replay historical voting rounds on the live network. Emulate 10..50 identities from a single smartphone.~~
- ~~Understand and re-use existing [ready-to-go datasets](https://zenodo.org/records/10622438) with DAO votes.~~
- ~~Create transaction blocks within Trustchain in a custom IPv8 community using [Kotlin superapp](https://github.com/tribler/trustchain-superapp/)~~
- Share votes using a ledger-based gossip protocol
- Binary transfer of bulk votes using QUIC [or uTP](https://github.com/iiljkic/utp4j).
- The outcome of your entire project is a single number. Remember, running code is required for a passing grade 💥. Your focus is the amounts of blockchain-data bits you can transfer between two phones.
- ~~BONUS,~~ add [carrier-grade NAT](https://arxiv.org/pdf/2311.04658.pdf) puncturing

Background reading:
- The SIM-card experiment with [carrier-grade NAT](https://arxiv.org/pdf/2311.04658.pdf) puncturing. Real details: https://github.com/Tribler/tribler/issues/7258
- Read [about EVA protocol](https://repository.tudelft.nl/islandora/object/uuid%3Aa048eb7d-9c9b-4e59-84f0-9fc76a4d8ee5)!
- [TrustVault also uses binary transfer](https://repository.tudelft.nl/islandora/object/uuid:8a1d6933-5576-42a1-b7fa-18230cf33918/datastream/OBJ/download)

Upcoming sprint assignment
- fetch major code update for superapp modules and IPv8 sub-module
- understand existing code
- NAT puncturing testing, using the app feature. Try to get a receiving UDP packet!
- get a cmdline Java transfer going between 2 peers, with [uTP](https://github.com/iiljkic/utp4j).

**Comment by DeaLlazo** [comment]
- The first testing results for the first 2 lines of the table are below. The testing is done through the Wi-Fi at school with 1GB of data transfer:

1. Local 1 laptop, 2 Java cmdline processes | 65 MBbyte/sec

2. 2 laptops, 2 Java cmdline processes Wifi | 1 MBbyte/sec ()

**Comment by synctext** [comment]
- organised to work in 2 parts: puncturing and uTP transfer
- peer discovery then you can do uTP test transfer
- Lua script for uTP packet visibility in Wireshark :open_mouth: :open_mouth: :open_mouth:

**Comment by KolevVelyan** [comment]
### Made debug window for uTP.
<img src="https://github.com/Tribler/tribler/assets/56160005/66b07bab-b6d8-48de-9020-46df37f12f6b" alt="uTP debug screen" width="280" >
<img src="https://github.com/Tribler/tribler/assets/56160005/5c13b5ef-c48c-434b-a70c-03be6072c81f" alt="uTP debug screen with open dropdown menu" width="280" >

### Made `.lua` script for Wireshark to be able to recognise ipv8 packets for easier debugging
Source code: https://github.com/Elkozel/IPv8-Wireshark-Support

### Made `.lua` script for Wireshark to be able to recognise utp4j packets for easier debugging
Source code: https://github.com/KolevVelyan/utp4j-Wireshark-Support

**Comment by KolevVelyan** [comment]
### Link to forked repository where our changes can be seen: https://github.com/KolevVelyan/trustchain-superapp

**Comment by grimadas** [comment]
**This weeks progress:** 

- Fix puncturing on specific port on the person 
- UTP implemented between two devices 
- Problem with firewalls
- Client/Server investable: the sequence number is fixed, switched the server/client but the group.   
- Which port established the socket 

**For the next week:**
- Solving the problem with the firewall (any tips to do that? )
- Working on DAO votes and showing in the app

**Comment by KolevVelyan** [comment]
This week's progress:
- finished puncturing a specific port (that the sender will need to open)
- updated uTP repo to not use random sequence numbers
- successfully established uTP transfer b/w 2 emulators (but with disabled windows firewalls for specific IPs)
- updated debug screen to use the transfer and show new outputs
![image](https://github.com/Tribler/tribler/assets/56160005/579dc2b6-4a6d-48e8-b45e-42a857e0f516)

**Comment by synctext** [comment]
- making solid progress on understanding our whole technology stack
- Create an example IPv8 community with utp4j and use [endpoint-send-ipv8 to send a single UDP via endpoint override](https://github.com/Tribler/kotlin-ipv8/blob/476dc36d0a5208d4a6ef21d953e00e4a440046a4/ipv8/src/main/java/nl/tudelft/ipv8/messaging/udp/UdpEndpoint.kt#L50)

**Comment by KolevVelyan** [comment]
What we did this week:
- send and receiver are not blocking the UI thread no more :)
- fixed dropdown styling so now you can always see it
- implemented basic version of full network debugger 
-- page displays details about the user's peer
-- and a list [everyone is in "incoming" for now] for everyone in the community with status that changes (green->yellow->red) based on the last time we received a packet from them
-- also, added indicators for when receiving from or sending to another peer (see screenshot below)
-- peers get removed from list automatically when they disappear in the demo community
-- based the design and implementation on the old implementation (https://github.com/Tribler/app-to-app-communicator)
- going back to uTP debug screen:
-- removed "receive" button by attaching listeners that are triggered every time a send is made to a peer (still need to puncture initially but this will be removed later on as well)
-- made sender run on another thread so that it UI is non-blocking
-- made it so you cannot send while receiving or sending (since socket is used)
-- moved send and receive logic to a separate class so that it does not depend on the fragment it is used in
-- moved methods used by sender/receiver in superclass [code cleanup]
-- made peer list dropdown in a separate class so it can be reused easily [code cleanup]
-- in general code in the uTP debug fragment is much less as it is split in the corresponding files making it easy to understand

We are currently working on removing the puncture by going through ipv8s socket. We have made the serializer and deserializer for uTP packets on top of ipv8. Currently, we are looking into setting up the socket correctly.

Full network debugger screen:
<img src="https://github.com/Tribler/tribler/assets/56160005/86c22eb4-f9bf-4853-ab8b-273636b95b2a" width="280" >

**Comment by grimadas** [comment]
- Great progress: many nice QoL improvements 🎉 

For the next week: 
- Clarify "S", "R" in UI, or think of better status indicator
- Ipv8 keep-alive status and UTP alive status 
- Demo with apk and improved UI 
- Big goal: bypass the firewall by integrating with ipv8 socket.
- Remove puncture button
- Start working on documentation: Readme, modularising, improved readability of the code.

**Comment by KolevVelyan** [comment]
Progress this week:
- integrated UTP with ipv8. No need to use firewalls anymore. Works in 4G.
- custom ipv8 socket on top of current socket.
- integrated network debugger with UTP
- now peer is in incoming if we have received UTP data from them (green if < 10s;  yellow b/w 10 and 20s; red >20s)
- same for outgoing but for when we have sent them UTP data
- added info button about what the colors mean on the debugger
- some code clean up again
- NEW APK LINK: https://drive.google.com/file/d/1IxbA5m1eXBHUk-JXQfCKA1hofxzjtB1_/view?usp=sharing

Info screen:
![img1](https://github.com/Tribler/tribler/assets/56160005/b201fa64-616a-4493-aa9a-63c325127995)

**Comment by synctext** [comment]
- ```Sent all 1023 Kb of data in 0:3.810 (268.504 Kb/s)``` :tada: :tada: :tada: 
- Binary transfer operational! (yet not fully stable)

**Comment by KolevVelyan** [comment]
Progress this week:
- main screen:
  - removed the outgoing and incoming lists and merged them into one
  - reverted to the screen we had 2 weeks ago (with one list and peer details on top)
  - removed the blinking "S" and "R" indicators
- sending/receiving UTP:
  - made it so that when you click a peer the old screen pops up where you can send UTP with the same settings as before
  - when somebody sends you something popup automatically opens on top of any existing pop-ups (and closes any previously receiving popups that were not closed)
  - on both sending and receiving popups added a way to see the speed at which you receive/send with information such as total data received (which can be more than the actual file you are sending as packets get retransmitted if not acknowledged in time), speed of sending/receiving, the hight acknowledgement sent/received, the highest sequence number sent/received, total packets sent/received.
  - this updates during the transfer. you can also see how many packets (max SEQ number expected) are expected to be sent
  - caught an error where you could input numbers larger than an integer resulting in a crash
- changed custom IPV8 socket
  - fix some bugs including sending a big file, closing the connection sometimes resulted in a crash, and sometimes peer was not in list resulting in crash
  - made it so you can track each packet sent through it for the progress of a scan
- improved comment quality on all files

Still left to do:
- test thoroughly custom socket and UTP send/receive for crashes
- finalize code including comments and README
- add unit tests
- deal with premature finish of transfer
- some places we consider KB to be 1024 bytes but it should be 1000 (quick fix)
- test performance of new screens for many peers on screen
- test cancelling of scans of popups closing

Screenshots from this week:
1. Network Debugger screen
![img1_nd](https://github.com/Tribler/tribler/assets/56160005/c5c36103-d08e-41c9-a48f-d7c4523795ff)

2. Sending UTP popup
![img2_send](https://github.com/Tribler/tribler/assets/56160005/f3dc28be-2aa0-43ed-be5e-56a1e674f3fe)

3. Receiving UTP popup
![img3_receive](https://github.com/Tribler/tribler/assets/56160005/9dd73426-c4d0-4a6b-9e42-7df31fa5a393)

**Comment by grimadas** [comment]
For the final week: 
- Prepare the demo, make sure it goes smoothly. 
-  Hand in repository and application 
- What are the limitations of your protocol? How big of the file it can handle? What are the assumptions on the network (latency/bandwidth)  
- Going gray first when the peers are introduced and then it can  
- What are letters S, A, TP stand for? 
- Focus on tests, unit test would be nice, at least make a test cases (integration) for the corner cases that you mentioned

**Comment by KolevVelyan** [comment]
## Links
- Our repository of trustchain-superapp (and final code on _master_ branch): https://github.com/KolevVelyan/trustchain-superapp
- README: https://github.com/KolevVelyan/trustchain-superapp/blob/master/debug/src/main/java/nl/tudelft/trustchain/debug/README.md
- final apk: TODO
-  our fork of utp4j with minor changes: https://github.com/KolevVelyan/utp4j

## Final week progress
- added info button to explain S, A and TP flags
- popups now properly cancel transfer when closed
- added color grey for peers that are walkable but not in peer list , i.e., peers you know about but have not connected
- changed the MAX_CWND_INCREASE_PACKETS_PER_RTT  to 30 000 as suggested 3 weeks ago
- added comments everywhere where missing
- made extensive unit tests to test the UTPCommunication (Sender and Recevier) and the custom IPv8 socket (can be found in [_common_](https://github.com/KolevVelyan/trustchain-superapp/tree/master/common/src/test/java/nl/tudelft/trustchain/common) and [_debug_](https://github.com/KolevVelyan/trustchain-superapp/tree/master/debug/src/test/java/nl/tudelft/trustchain/debug))
- made [README](https://github.com/KolevVelyan/trustchain-superapp/blob/master/debug/src/main/java/nl/tudelft/trustchain/debug/README.md) which can be found in _debug_
- did some tests for transfer speed from which we found that on Wi-Fi we get around 1MB/s whereas on 4G we get around 0.1-0.2MB/s (they can be found in README)
- fixed several bugs which crashed the phone
- changed how the popups can be scrolled to be more intuitive
- updated printed statements to more properly reflect what is happening during transfer
- fixed bug where we did not account for the 31-byte IPv8 header so not the whole data was being sent
- handle premature finish of transfer (if not all expected data is sent/recevied then transfer is considered unsuccessful)

## Note
- UTP transfer still does not work great when on 5G because of the way puncturing works so we have not tested with doing transfers on 5G

**Comment by synctext** [comment]
- You got binary transfer to work at 1 MByte/sec 
- Bit of lag peer list and scroll problem
- documentation is solid, minor improvement point is deep code linkage and .GIF

**Comment by KolevVelyan** [comment]
## Gif of working debugger (2x speed)
<img src="https://github.com/Tribler/tribler/assets/56160005/451b5874-6526-4534-801f-f09a3f0ab121" width="280" />
