### ISSUE TITLE
Move File Storage issue

### ISSUE THREAD

**Issue by SmivvyUK** [Tribler/tribler#8028]
Ubuntu 22.04.4 LTS 64-bit
Tribler V7.14.0

Since updating from V7.13.2, the 'Move File Storage' feature no longer works. When selected, Tribler unceremoniously crashes to desktop with no error.

If the 'Explore Files' option is selected, the selected download folder is now opened in Firefox, and not in the File Explorer as previous versions used to do.

Any suggestions..?

**Comment by drew2a** [comment]
@SmivvyUK, thank you for your report. I've tried using the 'Move File Storage' feature on macOS, and it works as intended.

Could you provide more information? Is the download complete or not? Does the target directory exist? Also, could you provide log files (ensuring they do not contain sensitive information)?

**Comment by Pixel-FR** [comment]
Hi, 
I have the some problem : Tribler crashes when i want to 'Move File Storage', also with the option 'Export .torrent file', and Firefox is open when i select 'Explore Files'.
This problem is real for all files (directories and downloads completes). Tribler quits without any message.
The previous version of Tribler was working fine. I have upgraded Tribler from version 7.13.3 to 7.14.0 and my computer is running Ubuntu 22.04.4 LTS (64 bits).

**Comment by drew2a** [comment]
@Pixel-FR Thank you for this confirmation.

@xoriole Could the problem described above be related to the Python build issue you discovered in #8061?

**Comment by xoriole** [comment]
@drew2a The underlying issue could be the same. On the latest build, I'm not able to reproduce the issue.

@SmivvyUK @Pixel-FR It would be great if you could you try re-installing Tribler by downloading again.
https://www.tribler.org/download.html

 I have updated the installer file yesterday which should fix the issue. 
 If you still encounter this issue, please write back.

**Comment by Pixel-FR** [comment]
I have verified my Python build version : 3.10.12
I have also reinstalled Tribler and it works fine now. 
06/05/2024 : i downloaded a 'tribler 7.14.0 deb file' for 105 Mo. 
06/20/2024 : i downloaded a 'tribler 7.14.0 deb file' for 109 Mo. 
Same program, same version but something is different in 15 days ! 

Bug is gone ! I have more questions for others subjects. Thanks for you help.

**Comment by SmivvyUK** [comment]
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux..

Same as @Pixel-FR , Re-download shows differing file size.
Installed tribler_7.14.0_all.deb and tested..

Move Files now works as intended..
"Explore Files" still  opens Firefox and not 'Files' as it used to do.

We have progress..!
@xoriole Any thoughts on the "Explore Files" issue..?

**Comment by xoriole** [comment]
@Pixel-FR @SmivvyUK The new installer file is built using Python3.9 as the base python. Previous installer was built using Python 3.8. This can also be checked on Debug panel (you'll need to enable debug from the settings (top right gear icon)).

The tag and commit remain the same. The change was only the Python version.

About the issue of "Explore Files" opening on the browser, I have noted that myself as well and am investigating it.

**Comment by xoriole** [comment]
The original issue with move (and build issue) is resolved. However, on the explore issue, it is still unclear why it is opening the browser instead of the file explorer. Further investigation on it is stopped in favor of the new UI built using HTML tech removing the QT based GUI. The issue is likely related to how URI is handled, and this might be different for the new frontend. 

Therefore, I'm unassigning myself from this issue for now.
