### ISSUE TITLE
Undefined install for linux

### ISSUE THREAD

**Issue by lewishornsby** [Tribler/tribler#8257]
The install page for linux at https://www.tribler.org/linux.html reads...
wget 
sudo apt-get install ./undefined

**Comment by qstokkink** [comment]
Thanks for letting us know! It seems that I broke this last week (in [this commit](https://github.com/Tribler/tribler.github.com/commit/c17be103e24d667c8635a17e36e2110994058846)).

[Details] As a quick workaround to avoid `x64` pre-release users being pointed to `aarch64` I fixed ALL the `.deb` files to `x64`. However, the stable release doesn't have a `x64.deb`, only a `all.deb`. The installation instructions pull from stable [here](https://github.com/Tribler/tribler.github.com/blob/c17be103e24d667c8635a17e36e2110994058846/js/tribler.js#L140), which is `undefined` because there is no `x64.deb` in stable.
