### ISSUE TITLE
Consolidate REST error responses

### ISSUE THREAD

**Issue by qstokkink** [Tribler/tribler#8263]
We inconsistently use REST error responses.

2 instances:

```typescript
{
  error: {
    handled: boolean,
    message: string,
  }
}
```

3 instances:

```typescript
{
  error: {
    handled: boolean,
    code: string,
    message: string,
  }
}
```

52 instances:

```typescript
{
  error: string
}
```

This is bad because it causes error handling constructions like this:

https://github.com/Tribler/tribler/blob/6213050af39f9d074914e6007d8d5da8fac38c66/src/tribler/ui/src/dialogs/SaveAs.tsx#L156-L163

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated the REST error responses to consistently use the format with 'handled', 'code', and 'message' fields across all error instances in the provided files.

You can review changes in this commit: https://github.com/lattaai11/Tribler-tribler-8263/commit/440a511b5b6312e9dcb454013b836cfc0f4bb777.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the REST error response format to consistently use the most comprehensive structure across all error responses in the provided files. This includes updating the `return_handled_exception` function and various error responses in middleware and endpoints.

You can review changes in this commit: https://github.com/lattaai11/Tribler-tribler-8263/commit/cf004fe0b2feac08ff7a8cd07fd5cb3858875c5d.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated the error response format to consistently use {error: {handled: boolean, code: string, message: string}} across both files. This change improves consistency and provides more detailed error information.

You can review changes in this commit: https://github.com/lattaai11/Tribler-tribler-8263/commit/063ebbcc00be0cebed84b735b01746f78e54a93d.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the return_handled_exception function to use the consistent error response format.

You can review changes in this commit: https://github.com/lattaai11/Tribler-tribler-8263/commit/6701bebb6be2e9cfdd989a40e1effca4532fca9e.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by lattaai11** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated the error response format to consistently use the structure with 'handled', 'code', and 'message' fields across both files. This change improves consistency and provides more detailed error information.

You can review changes in this commit: https://github.com/lattaai11/Tribler-tribler-8263/commit/d35c8e033e5d80bc0de4b551419488838c2f6d4f.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by qstokkink** [comment]
@egbertbouman what do you think of cosolidating this to:

```typescript
{
  error: {
    handled: boolean,
    message: string,
  }
}
```

For the errors with a `code` we would port the `code` field by including it in the `message`. For the errors that currently only have an error message we would put them in a `{handled=True, message="previously the 'error' message"}`.

**Comment by egbertbouman** [comment]
Sounds good to me 👍

**Comment by qstokkink** [comment]
Thanks 🙏 I'll give this a go then.
