### ISSUE TITLE
Swarm age is misreported - 55 years ago

### ISSUE THREAD

**Issue by synctext** [Tribler/tribler#8288]
Search results screenshot. Query on Ubuntu 20.04 with latest V8.0.4 (well, "7.5.0.1" in the "Settings -> Versions" menu; consider that another bug :smiley:)
![image](https://github.com/user-attachments/assets/4ff458b3-f6a0-4be3-8e54-f2f90e7db4f3)

**Comment by qstokkink** [comment]
I believe this information is there due to a bug that was fixed many versions ago (@egbertbouman please correct me if I'm wrong). We could remove these entries, but then we would lose the torrent information just because the timestamp is not aesthetically pleasing. So, we opted to keep these.

I tested the 8.0.5 installer on both Mac and Ubuntu 24.04 and I cannot reproduce your odd version number:

![](https://github.com/user-attachments/assets/01ed8efb-eb84-4bd0-b3ed-fcdb97292f31)

Could you provide a screenshot of what this looks like for you?

**Comment by absolutep** [comment]
> these entries, but then we would lose the torrent information just because the timestamp is not aesthetically pleasing. So, we opted to keep these

I also discovered this exact same thing, but didn't list it as an issue.

I think this has something to do with libtorrent but in any case found these, you can have a read -

1] https://github.com/qbittorrent/qBittorrent/issues/18637
2] https://github.com/qbittorrent/qBittorrent/issues/21909

**Comment by egbertbouman** [comment]
Considering the underlying problem is already fixed. Let's fix this at the UI level, since the damage in the database is already done. We'll call epoch time "unknown".
