### ISSUE TITLE
[URGENT] Update Tribler Exit Node

### ISSUE THREAD

**Issue by absolutep** [Tribler/tribler#8301]
**Tribler Exit node seems to be running on libtorrent 0.1.0**

This was realesed more than 10 years ago.

Since, Anonymous seeding/leeching goes through this exit node, it is creating issues as newer torrent clients (99% of them) have updated to [newer libtorrent releases](https://github.com/arvidn/libtorrent/releases).

Especially, newer torrent clients based on libtorrent library itself like qBittorent have started rejecting older clients with new security features and what not.

Although, I am just guessing but doing this [might] solve _some_ of the issues related to seeding that Tribler faces _**even on non-anonymous mode**_.

In any case, please update Tribler exit node to latest version as soon as possible.

Thank You.

**Image** :- Tribler exit node at different hops length, **using antiquated libtorrent version**   

![tribler hop different](https://github.com/user-attachments/assets/c205f1fe-2e7d-4455-8603-75fd5ef1d21b)

**Comment by egbertbouman** [comment]
You're seeing this because libtorrent is running in anonymous mode, which sets client fingerprint to `-LT0100-`. You can see the `peer_fingerprint` in the UI if you have debug mode enabled: Debug -> Libtorrent -> Hops = 1.

Note that these fingerprints aren't actually coming from the exits themselves, instead it's coming from the Tribler client that's connected to the exit node.
