### ISSUE TITLE
Package the app for non-Debian based Linux

### ISSUE THREAD

**Issue by NonVideri** [Tribler/tribler#8318]
- The request is to add packaging formats for Linux distributions that aren't Debian based.
- Flatpaks and AppImages are distribution-agnostic, so they would do the trick.
- Alternatively, you could add other common formats like .rpm.

**Comment by qstokkink** [comment]
We* actually have a flatpak: `org.tribler.Tribler`. I tried to make an `AppImage` and `rpm` in the past, but these turned out to be too unstable (at the time, at least).

There is no `8.0` series release yet for flatpak, but `8.0.5` is in the works: https://github.com/flathub/org.tribler.Tribler/pull/20 Once that is released, I'll link it on our GitHub's `README` (perhaps it should also be on `tribler.org` 🤔). I'll keep this issue open as a reminder to do so.

_*I say "we", but this is actually maintained on voluntary basis by @overflw. You can buy him a coffee, if you like it._

**Comment by qstokkink** [comment]
The flathub `8.0.6` is available now! You can find it here: https://flathub.org/apps/org.tribler.Tribler
