### ISSUE TITLE
Failed change the anonymity of download!

### ISSUE THREAD

**Issue by teddyrogers** [Tribler/tribler#8319]
In Tribler 8.0.6, when changing the anonymity of a download I receive the error message shown in the image below, "Failed change the anonymity of download!". It does not matter if the hops being changed to is either 1, 2 or 3.

![image](https://github.com/user-attachments/assets/ef2aba5e-13c4-4e80-aa40-a1cb6f4453d4)

Refreshing the browser seems to indicate the number of hops has changed, even though the error message states otherwise.

If the number of hops has actually changed I do not know for sure, what is the best way to check?

**Comment by teddyrogers** [comment]
Having closed down Tribler and restarted, the Tribler page returns back to the hops it began with (before changing and getting the failed message).

**Comment by qstokkink** [comment]
Thanks for reporting! We'll try to get that fixed ASAP.

_[dev stuff]_ I think the following is going on. Due to a recent change, `start_handle` pushes a notification:

https://github.com/Tribler/tribler/blob/dee06a25f2ac06f2f65113c9eae8691a5a38c15b/src/tribler/core/libtorrent/download_manager/download_manager.py#L762

This is also how it happens in `get_metainfo`:

https://github.com/Tribler/tribler/blob/dee06a25f2ac06f2f65113c9eae8691a5a38c15b/src/tribler/core/libtorrent/download_manager/download_manager.py#L581

HOWEVER, the `get_trackers()` method returns a list of `bytes`, while a list of `str` is expected down the line in the notification handler. It is then fed into the database unchecked:

https://github.com/Tribler/tribler/blob/34993f057c08c51a43cfb918ad6a12ebf947eaf3/src/tribler/core/database/orm_bindings/torrent_metadata.py#L281

I'll try to reproduce this in a test. If I'm correct,  we've apparently been getting lucky the last year(s) with `get_metainfo`.

**Comment by qstokkink** [comment]
I thought this would be easy to reproduce, but so far I haven't been able to trigger this error. My earlier idea may be incorrect.

**Comment by teddyrogers** [comment]
@qstokkink is there a way to check/ verify in Tribler if the hop/s are actually connected and to where?

**Comment by teddyrogers** [comment]
@qstokkink thank you for the response and information.

Apologies, I should have explained better my question. If I want to check the hop/s and connections for each torrent how can I link the connections/ circuits to those torrents to make sure if 0, 1, 2 or 3 hops are displayed they really exist? Currently if I go into debug I don't know how to correlate this information to each torrent, made worse when there are multiple torrents active.

I know this is going slightly off topic (maybe a feature request to create), some of the debug information would be better displayed under each active torrent, when selected from the main list.

**Comment by qstokkink** [comment]
Aha, in that case I went overboard: just refreshing the web page (F5 or CTRL+F5) should be enough to force a resampling of the torrent state. Then, the displayed number of hops should definitely be correct.

**Comment by teddyrogers** [comment]
@qstokkink would it be possible to relocate or replicate some of the information from the debug menu to associate it to each respective torrent?

![image](https://github.com/user-attachments/assets/dc40489c-e392-4c76-9343-62ec8b31aac0)

**Comment by qstokkink** [comment]
We can do that and in the past, many years ago (Tribler 6.5.2 I believe), we had a network graph that showed all the circuits per download. I don't know (/can't remember) why this was removed. It's probably best to leave that to a separate issue though.

**Comment by teddyrogers** [comment]
Thank you for the reply, I'll raise a couple of feature request tickets.
