### ISSUE TITLE
Confusing Settings Default Values

### ISSUE THREAD

**Issue by teddyrogers** [Tribler/tribler#8328]
There are a few settings with "confusing" default values under "Settings" menu...

1) General -> Web server settings

The "Port" value shown here is "0". Should this be, "8085", as per the value described in Tribler FAQ or 65110?

2) Connection -> Bittorrent features

"Max connections per download" contains value "-1". Text underneath the value field states "0 = unlimited"

The last time I changed this value to "0" it seemed to stop/ break all downloads. What does value "-1" represent? 

3) Anonymity

Should this contain a reference stating this is to specify the default hop value including numbers 1 to 3 on the sliding scale?

**Comment by qstokkink** [comment]
Thanks for the suggestions! We can improve our GUI a bit. To give the answers:

> The "Port" value shown here is "0".

The port `0` is special to your operating system. It tells your operating system to claim whatever free port it has. You can also force Tribler to bind to a specific port, if you want to always use a stable port (for example if you want to use the REST API directly). We can add more info here.

> "Max connections per download" contains value "-1". Text underneath the value field states "0 = unlimited"

Indeed, this is wrong. The value `-1` is unlimited and `0` really means `0` connections. We'll have to correct this.

We can also add more information to the anonymity page to better explain the tradeoff between anonymization and download speed.

**Comment by qstokkink** [comment]
Thanks for the heads-up, I created an issue for the FAQ on our website repo: https://github.com/Tribler/tribler.github.com/issues/91

> Where can I find the most up-to-date documentation on all the settings and debug menu?

The settings should be self-explanatory in the GUI. If that is not the case, please let me know. We'll add more info.

We have some secret settings that are not supposed to be changed (because they can lead to start-up crashes or insecure setups etc.). The same goes for the debug tab: this is meant only for debuggers and developers. 

> Additionally are the "Network Explorer" and "Credit Mining" options available in Tribler 8?

The former has been dropped since Tribler 7 and the latter has been removed after its 4th (or 5th?) iteration (we've yet to get the credit mining to the point where it makes sense).

**Comment by teddyrogers** [comment]
Other than the issues raised above most of the settings appear straightforward enough.

It would be nice if there were more information available regarding the information shown in the Debug menu, to help understand and interpret this information.
