### ISSUE TITLE
Multitracker - Order of Processing

### ISSUE THREAD

**Issue by teddyrogers** [Tribler/tribler#8342]
In Tribler 8.x I have noticed for multi tracker torrents Tribler some times only lists one tracker (sometimes two) as, "Working", with the others listed as, "Not contacted yet", and, "Not working". As I am unable to find in Tribler, the actual tracker it has announced to, I assume the "Working" tracker is 'tracker1' in reference to the official tracker protocol?

Should Tribler have three "Working" trackers; two as 'tracker1', 'tracker2' and, 'backup' ?

As a suggestion for improvement it would be good to have an additional column (or marker) to list the (multi) tracker order.

Additionally should Tribler shuffle/ rotate the tracker list occasionally, for trackers which can trade peer information to help balance the load between trackers? This would also help when Tribler stalls on a download because a tracker has no peers connected to the torrent, Tribler could shuffle/ rotate to a tracker that has peers.

**Comment by teddyrogers** [comment]
> In Tribler 8.x I have noticed for multi tracker torrents Tribler some times only lists one tracker (sometimes two) as, "Working", with the others listed as, "Not contacted yet", and, "Not working". As I am unable to find in Tribler, the actual tracker it has announced to, I assume the "Working" tracker is 'tracker1' in reference to the official tracker protocol?
> 
> Should Tribler have three "Working" trackers; two as 'tracker1', 'tracker2' and, 'backup' ?

This may or may not be working, 100% of the time. I have tried a few more torrents (imported at the same time) of files that I know are known to the trackers. Some of the torrents are showing three, "Working", trackers with the others, "Not contacted yet" or, "Not working".

In one torrent a tracker is listed as, "Working", and in another torrent - the same tracker - is listed as, "Not working". I assume in this instance it could be that the exit node is blocked/ banned?

**Comment by qstokkink** [comment]
The official BitTorrent protocol dealing with trackers and their order is [BEP 12](https://www.bittorrent.org/beps/bep_0012.html). Essentially, there are two things going on. First, the "tier" and "order" of trackers is encoded in the torrent. This allows creators of torrents to specify complex tracker-visiting schemes (I don't think anybody really does this, though). So, your idea of tracker backup order already exists. Second, as soon as a working tracker is found, nothing else is checked. The idea of the BitTorrent protocol is that as soon as peers are found in a BitTorrent swarm, trackers should be avoided. The ultimate load balancing for trackers is no communication. Touching on the idea of "higher number of peers is better". I believe the idea behind the BitTorrent implementation is that only very few peers in a BitTorrent swarm are actively contributing to your download speed, the rest of the connections are useless overhead. In other words, "lower number of peers is better". I remember reading this somewhere, but I can't find the reference link anymore.

Because of some implementation details, we can't really distinguish "Not working" from "We already have peers so we didn't check this tracker". Both of these cases get labelled as "Not working". It CAN also be that an exit node's tracker request is blocked, but we have looked at this in the past and [it doesn't seem very common](https://github.com/Tribler/tribler/issues/3065#issuecomment-802329190).

We CAN break with BEP 12 and hammer trackers for more peers. I think this issue covers that: #8287 Of course, the questions are whether (a) we are then poisoning the BitTorrent network by overloading trackers and/or (b) shooting ourselves in the foot by introducing pointless peer connections that only slow down our downloads.

**Comment by teddyrogers** [comment]
> We CAN break with BEP 12 and hammer trackers for more peers. I think this issue covers that: #8287 Of course, the questions are whether (a) we are then poisoning the BitTorrent network by overloading trackers and/or (b) shooting ourselves in the foot by introducing pointless peer connections that only slow down our downloads.

I don't know enough about qBittorrent though I believe it to cycle through trackers to build a peer list.

If the concern is hammering the trackers consider at least one pass announcing to all trackers in the list? This way any peers that are missing on one (none working) tracker can potentially be found on another. I have seen Tribler stuck on, only one, "Working" tracker with zero peers not downloading or uploading anything whilst there are active peers on another tracker.

**Comment by qstokkink** [comment]
Agreed. I think there's a valid case to be made for a feature to overrule "working" trackers that report no peers. This should be covered by #8287. In order to keep our GitHub issues focused, I'll close this issue: if you have further feedback/insights on this topic, please post them in #8287
